<?
include("../class/layout.class");
include("../webedit/webedit.lib.php");
include '../include/phpexcel/Classes/PHPExcel.php';
include '../include/phpexcel/Classes/PHPExcel/Writer/Excel2007.php';

//include($_SERVER["DOCUMENT_ROOT"]."/class/sms.class");
//auth(9);

$db = new Database;
$mdb = new Database;
//$sms_design = new SMS;

if($status == "AC"){
	$page_name = "고객 신청완료 목록";
}else if($status == "TC"){
	$page_name = "관리자 접수완료 목록";
}else if($status == "IC"){
	$page_name = "출고완료 목록";
}else{
	$page_name = "접수취소 목록";
}

if ($FromYY == ""){
	$before10day = mktime(0, 0, 0, date("m")  , date("d")-20, date("Y"));

//	$sDate = date("Y/m/d");
	$sDate = date("Y/m/d", $before10day);
	$eDate = date("Y/m/d");

	$startDate = date("Ymd", $before10day);
	$endDate = date("Ymd");
}else{
	$sDate = $FromYY."/".$FromMM."/".$FromDD;
	$eDate = $ToYY."/".$ToMM."/".$ToDD;
	$startDate = $FromYY.$FromMM.$FromDD;
	$endDate = $ToYY.$ToMM.$ToDD;
	$birDate = $birYY.$birMM.$birDD;
}


	$max = 15; //페이지당 갯수

	if ($page == '')
	{
		$start = 0;
		$page  = 1;
	}
	else
	{
		$start = ($page - 1) * $max;
	}

	$where = " where di.di_ix != '' and di.group_ix = dg.group_ix ";
	//if(!$search_parent_group_ix){
	//	$search_parent_group_ix = $parent_group_ix;
	//}

	if($search_parent_group_ix != "" && $search_group_ix == ""){
		$where .= " and (dg.group_ix = '".$search_parent_group_ix."' or dg.parent_group_ix = '".$search_parent_group_ix."') ";
	}else if($search_parent_group_ix != "" && $search_group_ix != ""){
		$where .= " and dg.parent_group_ix = '".$search_parent_group_ix."' ";
	}

	if($search_group_ix != ""){
		$where .= " and dg.group_ix = '".$search_group_ix."' ";
	}

	if($mail_yn == "Y"){
		$where .= " and mail_yn =  '1' ";
	}else if($mail_yn == "N"){
		$where .= " and mail_yn =  '0' ";
	}

	if($sms_yn == "Y"){
		$where .= " and sms_yn =  '1' ";
	}else if($sms_yn == "N"){
		$where .= " and sms_yn =  '0' ";
	}

	if($delivery_type == "1"){
		$where .= " and delivery_type =  '1' ";
	}else if($delivery_type == "2"){
		$where .= " and delivery_type =  '2' ";
	}

	if($status){
		$where .= " and status =  '".$status."' ";
	}


	if($search_type != "" && $search_text != ""){
		$where .= " and $search_type LIKE  '%$search_text%' ";
	}

	$startDate = $FromYY.$FromMM.$FromDD;
	$endDate = $ToYY.$ToMM.$ToDD;

	if($startDate != "" && $endDate != ""){
		$where .= " and  MID(replace(di.regdate,'-',''),1,8) between  $startDate and $endDate ";
	}

	$vstartDate = $vFromYY.$vFromMM.$vFromDD;
	$vendDate = $vToYY.$vToMM.$vToDD;

	if($vstartDate != "" && $vendDate != ""){
		$where .= " and  MID(replace(regdate,'-',''),1,8) between  $vstartDate and $vendDate ";
	}

	// 전체 갯수 불러오는 부분
	$sql = "SELECT count(*) as total FROM delivery_info di , delivery_group dg $where ";
//	echo $sql;
	$db->query($sql);

	$db->fetch();
	$total = $db->dt[total];
	$str_page_bar = page_bar($total, $page,$max, "&max=$max&search_type=$search_type&search_text=$search_text&age=$age&status=$status&delivery_type=$delivery_type&FromYY=$FromYY&FromMM=$FromMM&FromDD=$FromDD&ToYY=$ToYY&ToMM=$ToMM&ToDD=$ToDD&vFromYY=$vFromYY&vFromMM=$vFromMM&vFromDD=$vFromDD&vToYY=$vToYY&vToMM=$vToMM&vToDD=$vToDD","view");





if($mode == "excel"){

//error_reporting(E_ALL);
PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

date_default_timezone_set('Asia/Seoul');

	$sql = "SELECT di.*, dg.group_name, dg.group_depth, dg.parent_group_ix , ddi.item_name, ddi.brand, ddi.price, ddi.amount
					FROM delivery_info di left join delivery_detail_info ddi on di.di_ix = ddi.di_ix, delivery_group dg  $where   ";
//	echo $sql;
//exit;
	$db->query($sql);

	$excel_datas = $db->fetchall();



$memberXL = new PHPExcel();

		// 속성 정의
	$memberXL->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("hanmipost.com")
								 ->setTitle("Application List")
								 ->setSubject("Application List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("hanmipost")
								 ->setCategory("hanmipost");

	// 데이터 등록
	$memberXL->getActiveSheet(0)->setCellValue('A' . 1, "번호");
	$memberXL->getActiveSheet(0)->setCellValue('B' . 1, "보내는이 이름");
	$memberXL->getActiveSheet(0)->setCellValue('C' . 1, "보내는이 전화");
	$memberXL->getActiveSheet(0)->setCellValue('D' . 1, "보내는이 주소");
	$memberXL->getActiveSheet(0)->setCellValue('E' . 1, "관리번호");
	$memberXL->getActiveSheet(0)->setCellValue('F' . 1, "받는이 이름(한글)");
	$memberXL->getActiveSheet(0)->setCellValue('G' . 1, "받는이 전화");
	$memberXL->getActiveSheet(0)->setCellValue('H' . 1, "받는이 휴대폰");
	$memberXL->getActiveSheet(0)->setCellValue('I' . 1, "받는이 우편번호");
	$memberXL->getActiveSheet(0)->setCellValue('J' . 1, "받는이 주소");
	$memberXL->getActiveSheet(0)->setCellValue('K' . 1, "받는이 상세주소");
	$memberXL->getActiveSheet(0)->setCellValue('L' . 1, "주민/사업자번호");
	$memberXL->getActiveSheet(0)->setCellValue('M' . 1, "배송메모");
	$memberXL->getActiveSheet(0)->setCellValue('N' . 1, "받는이구분");
	$memberXL->getActiveSheet(0)->setCellValue('O' . 1, "전자상거래");
	$memberXL->getActiveSheet(0)->setCellValue('P' . 1, "가로(cm)");
	$memberXL->getActiveSheet(0)->setCellValue('Q' . 1, "세로(cm)");
	$memberXL->getActiveSheet(0)->setCellValue('R' . 1, "높이(cm)");
	$memberXL->getActiveSheet(0)->setCellValue('S' . 1, "중량");
	$memberXL->getActiveSheet(0)->setCellValue('T' . 1, "중량단위");
	$memberXL->getActiveSheet(0)->setCellValue('U' . 1, "Box수량");
	$memberXL->getActiveSheet(0)->setCellValue('V' . 1, "상품명");
	$memberXL->getActiveSheet(0)->setCellValue('W' . 1, "브랜드");
	$memberXL->getActiveSheet(0)->setCellValue('X' . 1, "단가");
	$memberXL->getActiveSheet(0)->setCellValue('Y' . 1, "수량");


	//------ row 1 data ------
	for($i=0, $j=0;$i < count($excel_datas);$i++,$j++){
		//$db->fetch($i);

		$memberXL->getActiveSheet(0)->setCellValue('A' .($i + 2), ($i+1));
		if($excel_datas[$i][name_type] == "N"){
			$memberXL->getActiveSheet(0)->setCellValue('B' .($i + 2), $excel_datas[$i][shipper_first_name]." ".$excel_datas[$i][shipper_last_name]);
		}else{
			$memberXL->getActiveSheet(0)->setCellValue('B' .($i + 2), $excel_datas[$i][shipper_compnay_name]);
		}
		$memberXL->getActiveSheet(0)->setCellValue('C' .($i + 2), $excel_datas[$i][shipper_phone]);
		$memberXL->getActiveSheet(0)->setCellValue('D' .($i + 2), $excel_datas[$i][shipper_address1]." ".$excel_datas[$i][shipper_address2]);
		$memberXL->getActiveSheet(0)->setCellValue('E' .($i + 2), $excel_datas[$i][application_no]);
		$memberXL->getActiveSheet(0)->setCellValue('F' .($i + 2), $excel_datas[$i][addressee_name]);
		$memberXL->getActiveSheet(0)->setCellValue('G' .($i + 2), $excel_datas[$i][addressee_phone]);
		$memberXL->getActiveSheet(0)->setCellValue('H' .($i + 2), $excel_datas[$i][addressee_mobile]);
		$memberXL->getActiveSheet(0)->setCellValue('I' .($i + 2), $excel_datas[$i][addressee_zip]);
		$memberXL->getActiveSheet(0)->setCellValue('J' .($i + 2), $excel_datas[$i][addressee_address1]);
		$memberXL->getActiveSheet(0)->setCellValue('K' .($i + 2), $excel_datas[$i][addressee_address2]);
		$memberXL->getActiveSheet(0)->setCellValue('L' .($i + 2), $excel_datas[$i][addressee_certification_no]);
		$memberXL->getActiveSheet(0)->setCellValue('M' .($i + 2), $excel_datas[$i][order_memo]);
		$memberXL->getActiveSheet(0)->setCellValue('N' .($i + 2), ($excel_datas[$i][name_type] == "N" ? "1":"2"));
		$memberXL->getActiveSheet(0)->setCellValue('O' .($i + 2), $excel_datas[$i][delivery_type]);
		$memberXL->getActiveSheet(0)->setCellValue('P' .($i + 2), 10);
		$memberXL->getActiveSheet(0)->setCellValue('Q' .($i + 2), 10);
		$memberXL->getActiveSheet(0)->setCellValue('R' .($i + 2), 10);
		$memberXL->getActiveSheet(0)->setCellValue('S' .($i + 2), $excel_datas[$i][weight]);
		$memberXL->getActiveSheet(0)->setCellValue('T' .($i + 2), "2");
		$memberXL->getActiveSheet(0)->setCellValue('U' .($i + 2), "1");
		$memberXL->getActiveSheet(0)->setCellValue('V' .($i + 2), $excel_datas[$i][item_name]);
		$memberXL->getActiveSheet(0)->setCellValue('W' .($i + 2), $excel_datas[$i][brand]);
		$memberXL->getActiveSheet(0)->setCellValue('X' .($i + 2), $excel_datas[$i][price]);
		$memberXL->getActiveSheet(0)->setCellValue('Y' .($i + 2), $excel_datas[$i][amount]);




	}


	// 시트이름등록
	$memberXL->getActiveSheet()->setTitle('신청목록');

	// 첫번째 시트 선택
	$memberXL->setActiveSheetIndex(0);
	$memberXL->getActiveSheet()->getColumnDimension('A')->setWidth(5);
	$memberXL->getActiveSheet()->getColumnDimension('B')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('C')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('G')->setWidth(10);
	$memberXL->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('J')->setWidth(5);
	$memberXL->getActiveSheet()->getColumnDimension('K')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('L')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('M')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('N')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('O')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('P')->setWidth(10);
	$memberXL->getActiveSheet()->getColumnDimension('Q')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('R')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('S')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('T')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('U')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('V')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('W')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('X')->setAutoSize(10);
	$memberXL->getActiveSheet()->getColumnDimension('Y')->setAutoSize(10);

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="application_list.xls"');
	header('Cache-Control: max-age=0');


	$objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
	$objWriter->save('php://output');




exit;









header('Pragma: public');
header('Last-Modified: '.gmdate('D, d M Y H:i:s') . ' GMT');
header('Cache-Control: no-store, no-cache, must-revalidate');     // HTTP/1.1
header('Cache-Control: pre-check=0, post-check=0, max-age=0');    // HTTP/1.1
header('Content-Type: text/plain; charset=UTF-8');
header('Content-Transfer-Encoding: binary');
header('Content-Type: application/vnd.ms-excel;');                 // This should work for IE & Opera
header("Content-type: application/x-msexcel");                    // This should work for the rest
header('Content-Disposition: attachment; filename='.iconv("utf-8","CP949",$page_name).'.xls');

xlsBOF();

	xlsWriteLabel(0,0,"번호");
	xlsWriteLabel(0,1,"보내는이 이름");
	xlsWriteLabel(0,2,"보내는이 전화");
	xlsWriteLabel(0,3,"보내는이 주소");
	xlsWriteLabel(0,4,"관리번호");
	xlsWriteLabel(0,5,"받는이 이름(한글)");
	xlsWriteLabel(0,6,"받는이 전화");
	xlsWriteLabel(0,7,"받는이 휴대폰");
	xlsWriteLabel(0,8,"받는이 우편번호");
	xlsWriteLabel(0,9,"받는이 주소");
	xlsWriteLabel(0,10,"받는이 상세주소");

	xlsWriteLabel(0,11,"주민/사업자번호");
	xlsWriteLabel(0,12,"배송메모");
	xlsWriteLabel(0,13,"받는이구분");
	xlsWriteLabel(0,14,"전자상거래");
	xlsWriteLabel(0,15,"가로(cm)");
	xlsWriteLabel(0,16,"세로(cm)");
	xlsWriteLabel(0,17,"높이(cm)");
	xlsWriteLabel(0,18,"중량");
	xlsWriteLabel(0,19,"중량단위");
	xlsWriteLabel(0,20,"Box수량");
	xlsWriteLabel(0,21,"상품명");
	xlsWriteLabel(0,22,"브랜드");
	xlsWriteLabel(0,23,"단가");
	xlsWriteLabel(0,24,"수량");


	//------ row 1 data ------
	for($i=0, $j=0;$i < count($excel_datas);$i++,$j++){
		//$db->fetch($i);


		xlsWriteLabel(($j+1), 0, ($i+1));
		if($excel_datas[$i][name_type] == "N"){
			xlsWriteLabel(($j+1), 1, $excel_datas[$i][shipper_first_name]." ".$excel_datas[$i][shipper_last_name]);
		}else{
			xlsWriteLabel(($j+1), 1, $excel_datas[$i][shipper_compnay_name]."");
		}

		xlsWriteLabel(($j+1), 2, $excel_datas[$i][shipper_phone]);
		xlsWriteLabel(($j+1), 3, $excel_datas[$i][shipper_address1]." ".$excel_datas[$i][shipper_address2]);
		xlsWriteLabel(($j+1), 4, $excel_datas[$i][application_no]);

		xlsWriteLabel(($j+1), 5, $excel_datas[$i][addressee_name]);
		xlsWriteLabel(($j+1), 6, $excel_datas[$i][addressee_phone]);
		xlsWriteLabel(($j+1), 7, $excel_datas[$i][addressee_mobile]);
		xlsWriteLabel(($j+1), 8, $excel_datas[$i][addressee_zip]);
		xlsWriteLabel(($j+1), 9, $excel_datas[$i][addressee_address1]);
		xlsWriteLabel(($j+1), 10, $excel_datas[$i][addressee_address2]);
		xlsWriteNumber(($j+1), 11, $excel_datas[$i][addressee_certification_no]);
		xlsWriteNumber(($j+1), 12, $excel_datas[$i][order_memo]);
		xlsWriteNumber(($j+1), 13, ($excel_datas[$i][name_type] == "N" ? "1":"2"));
		xlsWriteNumber(($j+1), 14, $excel_datas[$i][delivery_type]);
		xlsWriteNumber(($j+1), 15, 10);
		xlsWriteNumber(($j+1), 16, 10);
		xlsWriteNumber(($j+1), 17, 10);
		xlsWriteNumber(($j+1), 18, "");
		xlsWriteNumber(($j+1), 19, "2");
		xlsWriteNumber(($j+1), 20, "1");
		xlsWriteLabel(($j+1), 21, $excel_datas[$i][item_name]);
		xlsWriteLabel(($j+1), 22, $excel_datas[$i][brand]);
		xlsWriteNumber(($j+1), 23, $excel_datas[$i][price]);
		xlsWriteNumber(($j+1), 24, $excel_datas[$i][amount]);

	}

	xlsEOF();
	exit;
}else{
	$sql = "SELECT di.*, dg.group_name, dg.group_depth, dg.parent_group_ix
			FROM delivery_info di , delivery_group dg  $where order by di.regdate desc LIMIT $start, $max";
	//echo $sql;

	$db->query($sql);
}






$Script = "
<script  id='dynamic'></script>
<script language='javascript'>

function loadCampaignGroup(sel,target) {
	//alert(target);
	var trigger = sel.options[sel.selectedIndex].value;
	var form = sel.form.name;
	//alert(target);
	var depth = sel.depth;
	//document.write('campaigngroup.load.php?form=' + form + '&trigger=' + trigger + '&target=' + target);
	dynamic.src = 'campaigngroup.load.php?form=' + form + '&trigger=' + trigger + '&target=' + target +'&depth=2';
	//document.location.href='campaigngroup.load.php?form=' + form + '&trigger=' + trigger + '&target=' + target +'&depth=2';

}


function ChangeRegistDate(frm){
	if(frm.regdate.checked){
		frm.FromYY.disabled = false;
		frm.FromMM.disabled = false;
		frm.FromDD.disabled = false;
		frm.ToYY.disabled = false;
		frm.ToMM.disabled = false;
		frm.ToDD.disabled = false;
	}else{
		frm.FromYY.disabled = true;
		frm.FromMM.disabled = true;
		frm.FromDD.disabled = true;
		frm.ToYY.disabled = true;
		frm.ToMM.disabled = true;
		frm.ToDD.disabled = true;
	}
}

function ChangeVisitDate(frm){
	if(frm.visitdate.checked){
		frm.vFromYY.disabled = false;
		frm.vFromMM.disabled = false;
		frm.vFromDD.disabled = false;
		frm.vToYY.disabled = false;
		frm.vToMM.disabled = false;
		frm.vToDD.disabled = false;
	}else{
		frm.vFromYY.disabled = true;
		frm.vFromMM.disabled = true;
		frm.vFromDD.disabled = true;
		frm.vToYY.disabled = true;
		frm.vToMM.disabled = true;
		frm.vToDD.disabled = true;
	}
}
function ChangeBirDate(frm){
	if(frm.bir.checked){
		frm.birYY.disabled = false;
		frm.birMM.disabled = false;
		frm.birDD.disabled = false;
	}else{
		frm.birYY.disabled = true;
		frm.birMM.disabled = true;
		frm.birDD.disabled = true;
	}
}

function init(){

	var frm = document.searchmember;
	onLoad('$sDate','$eDate');
	Init(document.list_frm);
	";

if($regdate != "1"){
$Script .= "
	frm.FromYY.disabled = true;
	frm.FromMM.disabled = true;
	frm.FromDD.disabled = true;
	frm.ToYY.disabled = true;
	frm.ToMM.disabled = true;
	frm.ToDD.disabled = true;";
}
/*
if($visitdate != "1"){
$Script .= "
	frm.vFromYY.disabled = true;
	frm.vFromMM.disabled = true;
	frm.vFromDD.disabled = true;
	frm.vToYY.disabled = true;
	frm.vToMM.disabled = true;
	frm.vToDD.disabled = true;	";
}
*/
$Script .= "
}

function BatchSubmit(frm){
	if(frm.search_searialize_value.length < 1){
		alert('적용대상중 [검색회원전체]는  검색후 사용 가능합니다. 확인후 다시 시도해주세요');
		return false;
	}

	if(frm.update_type.value == 1){
		if(frm.update_kind[0].checked){
			if(confirm('검색회원 전체의 택배그룹을 변경 하시겠습니까?')){return true;}else{return false;}
		}else if(frm.update_kind[1].checked){
			if(confirm('검색회원 접수상태를 변경 하시겠습니까?')){return true;}else{return false;}
		}
		/*
		}else if(frm.update_kind[1].checked){
			if(confirm('검색회원 전체의 메일링/SMS 그룹변경을 하시겠습니까?')){return true;}else{return false;}
		}else if(frm.update_kind[1].checked){
			if(confirm('검색회원 전체에게 SMS 발송을 하시겠습니까?')){return true;}else{return false;}
		}else if(frm.update_kind[2].checked){
			if(confirm('검색회원 전체에게 이메일발송을 하시겠습니까?')){return true;}else{return false;}
		}
		*/
	}else if(frm.update_type.value == 2){
		var di_ix_checked_bool = false;
		for(i=0;i < frm.di_ix.length;i++){
			if(frm.di_ix[i].checked){
				di_ix_checked_bool = true;
			}
			//	frm.di_ix[i].checked = false;
		}
		if(!di_ix_checked_bool){
			alert('선택된 수신자가 없습니다. 변경/발송 하시고자 하는 수신자를 선택하신 후 저장/보내기 버튼을 클릭해주세요');
			return false;
		}
	}

	if(frm.update_kind[0].checked){
		if(frm.parent_update_group_ix.value == ''){
			alert('변경하시고자 하는 그룹을 선택해주세요');
			frm.parent_update_group_ix.focus();
			return false;
		}

	}else if(frm.update_kind[1].checked){

	}else if(frm.update_kind[1].checked){
		if(frm.sms_text.value.length < 1){
			alert('SMS 발송 내역을 입력하신후 보내기 버튼을 클릭해주세요');
			frm.sms_text.focus();
			return false;
		}
	}else if(frm.update_kind[2].checked){

		if(frm.email_subject.value.length < 1){
			alert('이메일 제목을 입력해주세요');
			frm.email_subject.focus();
			return false;
		}

		frm.mail_content.value = iView.document.body.innerHTML;

		if(frm.mail_content.value.length < 1 || frm.mail_content.value == '<P>&nbsp;</P>'){
			alert('이메일 내용을 입력하신후 보내기 버튼을 클릭해주세요');
			//frm.mail_content.focus();
			return false;
		}

	}else if(frm.update_kind[2].checked){
		if(frm.hotcon_event_id.value.length < 1){
			alert('하트콘 이벤트 아이디를 입력해주세요');
			frm.hotcon_event_id.focus();
			return false;
		}

		if(frm.hotcon_pcode.value.length < 1){
			alert('하트콘 상품코드를 입력해주세요');
			frm.hotcon_pcode.focus();
			return false;
		}
	}

}

function ChangeUpdateForm(selected_id){
	var area = new Array('batch_update_sendemail','batch_update_status','batch_update_hotcon','batch_update_group','batch_update_sms');

	for(var i=0; i<area.length; ++i){
		if(area[i]==selected_id){
			document.getElementById(selected_id).style.display = 'block';
		}else{
			document.getElementById(area[i]).style.display = 'none';
		}
	}
}

function DeleteApplication(di_ix){
	if(confirm('해당 택배 접수 목록을 정말로 삭제하시겠습니까?')){
		document.frames['act'].location.href='application.act.php?act=delete&di_ix='+di_ix;
	}
}
</script>";

if($before_update_kind){
	$update_kind = $before_update_kind;
}

if(!$update_kind){
	$update_kind = "group";
}

$Contents = "


<table width='100%' cellspacing='0' cellspacing='0' border='0' align='center'>
  <tr>
    <td align='left' colspan=4 > ".GetTitleNavigation($page_name, "택배관리 > $page_name ")."</td>
  </tr>
  <tr>
	    <td align='left' colspan=4 style='padding-bottom:15px;'>
	    <div class='tab'>
			<table class='s_org_tab'>
			<tr>
				<td class='tab'>
					<table id='tab_01' ".($delivery_type == "" ? "class='on'":"")." >
					<tr>
						<th class='box_01'></th>
						<td class='box_02'  ><a href='?status=".$status."&delivery_type='>전체</a></td>
						<th class='box_03'></th>
					</tr>
					</table>
					<table id='tab_02' ".($delivery_type == "1" ? "class='on'":"")." >
					<tr>
						<th class='box_01'></th>
						<td class='box_02' ><a href='?status=".$status."&delivery_type=1'>일반택배</a></td>
						<th class='box_03'></th>
					</tr>
					</table>
					<table id='tab_02' ".($delivery_type == "2" ? "class='on'":"")." >
					<tr>
						<th class='box_01'></th>
						<td class='box_02' ><a href='?status=".$status."&delivery_type=2'>구매대행</a></td>
						<th class='box_03'></th>
					</tr>
					</table>
				</td>
				<td style='width:450px;text-align:right;vertical-align:bottom;padding:0 0 10 0'>

				</td>
			</tr>
			</table>
		</div>
	    </td>
	  </tr>
  <tr>
  	<td>";
$Contents .= "
<table class='box_shadow' cellspacing='0' cellpadding='0' style='width:100%;height:100%;' >
	<tr>
		<th class='box_01'></th>
		<td class='box_02'></td>
		<th class='box_03'></th>
	</tr>
	<tr>
		<th class='box_04'></th>
		<td class='box_05'  valign=top style=''>
 		<table width='100%' border='0' cellspacing='0' cellpadding='0' height='25' class='search_table_box'>
		<form name=searchmember method='get' style='display:inline;'><!--SubmitX(this);'-->
    <input type='hidden' name=act value='".$act."'>
    <input type='hidden' name=before_update_kind value='".$update_kind."'>";

$Contents .= "
		    <tr height=27>
		      <td class='search_box_title' align=center>주소록 그룹 </td>
		      <td class='search_box_item' align=left style='padding-left:5px;'>
		      ".getGroupInfoSelect('search_parent_group_ix', '1 차그룹',$search_parent_group_ix, $search_parent_group_ix, 1, " onChange=\"loadCampaignGroup(this,'search_group_ix')\" ")."
				  ".getGroupInfoSelect('search_group_ix', '2 차그룹',$search_parent_group_ix, $search_group_ix, 2)."
		      <!--".getFirstDIV($mdb, $search_parent_group_ix, 'search_parent_group_ix', "onChange=\"loadCampaignGroup(this,'search_group_ix')\"")."
		      <select name='search_group_ix' id='search_group_ix' >
					<option value=''>1차그룹을 먼저 선택해주세요</option>
					</select-->
		      </td>
		      <td class='search_box_title' align=center>조건검색 </td>
		      <td class='search_box_itme' align=left style='padding-left:5px;'>
		      <select name=search_type>
						<option value='application_no' ".CompareReturnValue("application_no",$search_type,"selected").">접수번호</option>
						<option value='shipper_name' ".CompareReturnValue("shipper_name",$search_type,"selected").">보내는사람</option>
						<option value='shipper_phone' ".CompareReturnValue("shipper_phone",$search_type,"selected").">보내는사람 연락처</option>
						<option value='shipper_mobile' ".CompareReturnValue("shipper_mobile",$search_type,"selected").">보내는사람 모바일</option>
						<!--option value='shipper_email' ".CompareReturnValue("shipper_email",$search_type,"selected").">보내는사람 이메일</option-->
						<optiongroup >=========================</optiongroup>
						<option value='addressee_name' ".CompareReturnValue("addressee_name",$search_type,"selected").">받는사람 이름</option>
						<option value='addressee_phone' ".CompareReturnValue("addressee_phone",$search_type,"selected").">받는사람 연락처</option>
		      </select>
		      <input type=text class='textbox' name='search_text' value='".$search_text."' style='width:50%;position:relative; top:-1px;' >
		      </td>
		    </tr>
		    <!--tr height=27>
		      <td bgcolor='#efefef' align=center>이메일 수신여부 </td>
		      <td align=left >
		      <input type=radio name='mail_yn' value='' id='mailsend_' ".CompareReturnValue("",$mail_yn,"checked")."><label for='mailsend_'>전체</label>
		      <input type=radio name='mail_yn' value='Y' id='mailsend_y'  ".CompareReturnValue("Y",$mail_yn,"checked")."><label for='mailsend_y'>수신회원만</label>
		      <input type=radio name='mail_yn' value='N' id='mailsend_n' ".CompareReturnValue("N",$mail_yn,"checked")."><label for='mailsend_n'>수신거부회원</label>
		      </td>
		       <td bgcolor='#efefef' align=center>SMS 수신여부 </td>
		      <td align=left >
		      <input type=radio name='sms_yn' value='' id='smssend_' ".CompareReturnValue("",$sms_yn,"checked")."><label for='smssend_'>전체</label>
		      <input type=radio name='sms_yn' value='Y' id='smssend_y'  ".CompareReturnValue("Y",$sms_yn,"checked")."><label for='smssend_y'>수신회원만</label>
		      <input type=radio name='sms_yn' value='N' id='smssend_n' ".CompareReturnValue("N",$sms_yn,"checked")."><label for='smssend_n'>수신거부회원</label>
		      </td>
		    </tr>
		    <tr hegiht=1><td colspan=4 class='dot-x'></td></tr-->
		    ";

$vdate = date("Ymd", time());
$today = date("Y/m/d", time());
$vyesterday = date("Y/m/d", time()-84600);
$voneweekago = date("Y/m/d", time()-84600*7);
$vtwoweekago = date("Y/m/d", time()-84600*14);
$vfourweekago = date("Y/m/d", time()-84600*28);
$vyesterday = date("Y/m/d",mktime(0,0,0,substr($vdate,4,2),substr($vdate,6,2),substr($vdate,0,4))-60*60*24);
$voneweekago = date("Y/m/d",mktime(0,0,0,substr($vdate,4,2),substr($vdate,6,2),substr($vdate,0,4))-60*60*24*7);
$v15ago = date("Y/m/d",mktime(0,0,0,substr($vdate,4,2),substr($vdate,6,2),substr($vdate,0,4))-60*60*24*15);
$vfourweekago = date("Y/m/d",mktime(0,0,0,substr($vdate,4,2),substr($vdate,6,2),substr($vdate,0,4))-60*60*24*28);
$vonemonthago = date("Y/m/d",mktime(0,0,0,substr($vdate,4,2)-1,substr($vdate,6,2)+1,substr($vdate,0,4)));
$v2monthago = date("Y/m/d",mktime(0,0,0,substr($vdate,4,2)-2,substr($vdate,6,2)+1,substr($vdate,0,4)));
$v3monthago = date("Y/m/d",mktime(0,0,0,substr($vdate,4,2)-3,substr($vdate,6,2)+1,substr($vdate,0,4)));

 $Contents .= "
		    <tr height=27>
		      <td class='search_box_title' align=center><label for='regdate'>등록일자</label><input type='checkbox' name='regdate' id='regdate' value='1' onclick='ChangeRegistDate(document.searchmember);' ".CompareReturnValue("1",$regdate,"checked")."></td>
		      <td class='search_box_item' align=left colspan=3 style='padding-left:5px;'>
		      	<table cellpadding=0 cellspacing=2 border=0 bgcolor=#ffffff>
				<tr>
					<TD width=220 nowrap><SELECT onchange=javascript:onChangeDate(this.form.FromYY,this.form.FromMM,this.form.FromDD) name=FromYY ></SELECT> 년 <SELECT onchange=javascript:onChangeDate(this.form.FromYY,this.form.FromMM,this.form.FromDD) name=FromMM></SELECT> 월 <SELECT name=FromDD></SELECT> 일 </TD>
					<TD width=20 align=center> ~ </TD>
					<TD width=220 nowrap><SELECT onchange=javascript:onChangeDate(this.form.ToYY,this.form.ToMM,this.form.ToDD) name=ToYY></SELECT> 년 <SELECT onchange=javascript:onChangeDate(this.form.ToYY,this.form.ToMM,this.form.ToDD) name=ToMM></SELECT> 월 <SELECT name=ToDD></SELECT> 일</TD>
					<TD>
						<a href=\"javascript:select_date('$voneweekago','$today',1);\"><img src='../image/b_btn_s_1week01.gif'></a>
						<a href=\"javascript:select_date('$v15ago','$today',1);\"><img src='../image/b_btn_s_15day01.gif'></a>
						<a href=\"javascript:select_date('$vonemonthago','$today',1);\"><img src='../image/b_btn_s_1month01.gif'></a>
						<a href=\"javascript:select_date('$v2monthago','$today',1);\"><img src='../image/b_btn_s_2month01.gif'></a>
						<a href=\"javascript:select_date('$v3monthago','$today',1);\"><img src='../image/b_btn_s_3month01.gif'></a>
					</TD>
				</tr>
			</table>
		      </td>
		    </tr>
		    <!--tr height=27>
		      <td bgcolor='#efefef' align=center><label for='visitdate'>등록일자</label><input type='checkbox' name='visitdate' id='visitdate' value='1' onclick='ChangeVisitDate(document.searchmember);' ".CompareReturnValue("1",$visitdate,"checked")."></td>
		      <td align=left colspan=3  style='padding-left:5px;'>
		      	<table cellpadding=0 cellspacing=2 border=0 bgcolor=#ffffff>
							<tr>
								<TD width=200 nowrap><SELECT onchange=javascript:onChangeDate(this.form.vFromYY,this.form.vFromMM,this.form.vFromDD) name=vFromYY ></SELECT> 년 <SELECT onchange=javascript:onChangeDate(this.form.vFromYY,this.form.vFromMM,this.form.vFromDD) name=vFromMM></SELECT> 월 <SELECT name=vFromDD></SELECT> 일 </TD>
								<TD width=20 align=center> ~ </TD>
								<TD width=200 nowrap><SELECT onchange=javascript:onChangeDate(this.form.vToYY,this.form.vToMM,this.form.vToDD) name=vToYY></SELECT> 년 <SELECT onchange=javascript:onChangeDate(this.form.vToYY,this.form.vToMM,this.form.vToDD) name=vToMM></SELECT> 월 <SELECT name=vToDD></SELECT> 일</TD>
								<TD>
									<a href=\"javascript:select_date('$voneweekago','$today',2);\"><img src='../image/b_btn_s_1week01.gif'></a>
									<a href=\"javascript:select_date('$v15ago','$today',2);\"><img src='../image/b_btn_s_15day01.gif'></a>
									<a href=\"javascript:select_date('$vonemonthago','$today',2);\"><img src='../image/b_btn_s_1month01.gif'></a>
									<a href=\"javascript:select_date('$v2monthago','$today',2);\"><img src='../image/b_btn_s_2month01.gif'></a>
									<a href=\"javascript:select_date('$v3monthago','$today',2);\"><img src='../image/b_btn_s_3month01.gif'></a>
								</TD>
							</tr>
						</table>
		      </td>
		    </tr>
		    <tr hegiht=1><td colspan=4 class='dot-x'></td></tr-->

		    </table>
		</td>
		<th class='box_06'></th>
	</tr>
	<tr>
		<th class='box_07'></th>
		<td class='box_08'></td>
		<th class='box_09'></th>
	</tr>
</table>			";

$Contents .= "
    </td>
  </tr>
	<tr height=50>
		<td style='padding:10 20 0 20' colspan=4 align=center><input type=image src='../image/bt_search.gif' align=absmiddle  > <!--a href=\"javascript:mybox.service('addressbook_add.php?code_ix=','10','450','600', 4, [], Prototype.emptyFunction, [], 'HOME > 택배관리 > 메일링/SMS대상추가');\">메일링/SMS 대상추가</a--></td>
	</tr>
	<tr height=25>
		<td style='padding:0 0 0 0' colspan=4 align=right>
		<a href='?mode=excel&".$QUERY_STRING."'><img src='../image/btn_excel_save.gif' border=0></a>
		</td>
	</tr>
</table></form>

<form name='list_frm' method='POST' onsubmit='return BatchSubmit(this);' action='application_list.act.php' target='act'><!--target='act'-->
<input type='hidden' name='di_ix[]' id='di_ix'>
<input type='hidden' name='search_searialize_value' value='".urlencode(serialize($_GET))."'>";

			$Contents .= "
			<div id='result_area'>
			<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' class='input_table_box'>
			  	<col width='5%' >
			    <col width='6%'>
				<col width='11%' >
				<col width='7%' >
			    <col width='8%'>
			    <col width='*' >
			    <col width='12%'>
			    <col width='8%' >
				<col width='12%' >";
			if($status == "TC"){
			$Contents .= "
			    <col width='8%' >";
			}
			$Contents .= "
				<col width='8%' >
			    <col width='10%'>
			  <tr height='28' bgcolor='#ffffff'>
			    <td align='center' class='s_td'><input type=checkbox name='all_fix' id='all_fix' onclick='fixAll(document.list_frm)'></td>
			    <td align='center' class='m_td'><font color='#000000'><b>그룹</b></font></td>
				<td align='center' class='m_td'><font color='#000000'><b>접수번호</b></font></td>
				<td align='center' class='m_td'><font color='#000000'><b>분류</b></font></td>
				<td align='center' class='m_td'><font color='#000000'><b>처리상태</b></font></td>
			    <td align='center' class='m_td'><font color='#000000' class=small nowrap><b>보내는이</b></font></td>
			    <td align='center' class='m_td'><font color='#000000' class=small><b>보내는이 연락처</b></font></td>
			    <!--td align='center' class='m_td'><font color='#000000'><b>이메일</b></font></td-->
			    <td align='center' class='m_td'><font color='#000000'><b>받는사람</b></font></td>
				<td align='center' class='m_td'><font color='#000000'><b>받는사람 연락처</b></font></td>";
			if($status == "TC"){
			$Contents .= "
			    <td align='center' class='m_td'><font color='#000000'><b>배송비</b></font></td>";
			}
			$Contents .= "
			    <td align='center' class='m_td'><font color='#000000'><b>등록일</b></font></td>
			    <td width='10%' align='center' class='e_td'><font color='#000000'><b>관리</b></font></td>
			  </tr>";



				for ($i = 0; $i < $db->total; $i++)
				{
					$db->fetch($i);

					$no = $total - ($page - 1) * $max - $i;
				/*
					if ($db->dt[mem_level] == "E")	{ $perm = "탈퇴회원"; }
					if ($db->dt[mem_level] == "M")	{ $perm = "일반회원"; }
					if ($db->dt[mem_level] == "B")	{ $perm = "입점업체"; }
					if ($db->dt[mem_level] == "C")	{ $perm = "특별회원"; }
				*/
					if($db->dt[group_depth] == 2){
						$mdb->query("SELECT group_name FROM delivery_group WHERE group_ix  = '".$db->dt[parent_group_ix]."' ");
						$mdb->fetch(0);
						$group_name = $mdb->dt[group_name]." > ".$db->dt[group_name];
					}else{
						$group_name = $db->dt[group_name];
					}
			if($db->dt[name_type] == "N"){
				$shipper_name = $db->dt[shipper_first_name]." ".$db->dt[shipper_last_name];
			}else{
				$shipper_name = $db->dt[shipper_compnay_name];
			}

			$Contents .= "
			  <tr height='28' onMouseOver=\"this.style.backgroundColor='#E8ECF1'; \" onMouseOut=\"this.style.backgroundColor=''\">
			    <td align='center' ><input type=checkbox name=di_ix[] id='di_ix' value='".$db->dt[di_ix]."'></td>
			    <td align='center'><span >".$group_name."</span></td>
				<td align='center' >".$db->dt[application_no]."</td>
				<td align='center' >".($db->dt[delivery_type] == "1" ? "구매대행":"일반택배")."</td>
				<td align='center' nowrap>";
				if($db->dt[status] == "AC"){
					$Contents .= "고객 신청완료";
				}else if($db->dt[status] == "TC"){
					$Contents .= "관리자 접수완료";
				}else if($db->dt[status] == "IC"){
					$Contents .= "출고완료";
				}else{
					$Contents .= "접수취소";
				}
				$Contents .= "
				</td>

			    <td align='center' ><a href='application_view.php?di_ix=".$db->dt[di_ix]."'><b>".$shipper_name."</b></a></td>
			    <td align='center' >".$db->dt[shipper_phone]."</td>
			    <!--td align='center' >".$db->dt[shipper_email]."</td-->
			    <td align='center' ><b>".$db->dt[addressee_name]."</b></td>
				<td align='center' ><b>".$db->dt[addressee_phone]."</b></td>";
			if($status == "TC"){
			$Contents .= "
				<td align='center' ><b>".$db->dt[delivery_fee]."</b></td>";
			}
			$Contents .= "
			    <td align='center' nowrap>".$db->dt[regdate]."</td>
			    <td align=center>
			    	<a href=\"javascript:PopSWindow('application.php?mmode=pop&di_ix=".$db->dt[di_ix]."',920,600,'member_info')\"><img src='../image/btc_modify.gif' border=0></a>
				    <!--a href=\"javascript:DeleteApplication('".$db->dt[di_ix]."')\"><img src='../image/btc_del.gif' border=0></a-->
				  </td>
			  </tr>
				<tr hegiht=1><td colspan=13 class='dot-x'></td></tr> ";

				}

			if (!$db->total){

			$Contents = $Contents."
			  <tr height=50 style='background:#ffffff'>
			    <td colspan='12' align='center'>등록된 데이타가 없습니다.</td>
			  </tr>";

			}

			$Contents .= "
			  <tr height='40' style='background:#ffffff'>
			    <td  colspan='12' align='right' >&nbsp;".$str_page_bar."&nbsp;</td>
			  </tr>
			</table>
			</div>";

$help_text = "
<div id='batch_update_group' ".($update_kind == "group" || $update_kind == ""  ? "style='display:block'":"style='display:none'")." >
<div style='padding:4 0 4 0'><img src='../images/dot_org.gif' align=absmiddle> <b> 그룹 일괄변경</b> <span class=small style='color:gray'>변경하시고자 하는 택배그룹을 선택후 저장 버튼을 클릭해주세요</span></div>
<table cellpadding=3 cellspacing=0 width=100% class='input_table_box'>
	<col width=170>
	<col width=*>
	<!--tr><td bgcolor='#efefef'> <b>지급액 / 차감액</b></td><td > <input type=text name='baymoney'  class=textbox value='' onkeydown='onlyNumber(this)' onkeyup='onlyNumber(this)'  style='width:150' > <span class='small blu'>사용의 경우 마니너스 금액으로 입력하세요 예) -1000</span></td></tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr-->
	<tr>
		<td class='input_box_title'>택배 관리그룹
			<input type='checkbox' name='mem_group_use' id='bir' value='1' onclick=\"if(this.checked){\$('parent_update_group_ix').disabled = false;$('update_group_ix').disabled = false;}else{\$('parent_update_group_ix').disabled = true;$('update_group_ix').disabled = true;}\">
		</td>
		<td class='input_box_item'>
		".getGroupInfoSelect('parent_update_group_ix', '1 차그룹',$parent_update_group_ix, $parent_update_group_ix, 1, " onChange=\"loadCampaignGroup(this,'update_group_ix')\" disabled ")."
		".getGroupInfoSelect('update_group_ix', '2 차그룹',$parent_update_group_ix, $update_group_ix, 2," disabled")."

		<!-- <span class=small style='color:gray'>회원그룹 변경에 따라 회원등급이 자동 변경됩니다.</span></td></tr> -->

</table>
<table cellpadding=3 cellspacing=0 width=100% style='border:0px solid silver;'>
	<!-- <tr height=30><td colspan=4 align=left><span class=small style='color:gray'>회원그룹 변경시 회원 등급이 자동으로 변경됩니다.</span></td></tr> -->
	<tr height=50><td colspan=4 align=center><input type=image src='../image/b_save.gif' border=0 style='cursor:hand;border:0px;' ></td></tr>
</table>
</div>
<div id='batch_update_sms' ".($update_kind == "sms" ? "style='display:block'":"style='display:none'")." >
<div style='padding:4 0 4 0'><img src='../images/dot_org.gif' align=absmiddle> <b>SMS 일괄발송</b> <span class=small style='color:gray'>검색/선택된 회원에게 SMS 를 발송합니다</span></div>
<table cellpadding=0 cellspacing=0>
	<tr>
		<td>
			<table class='box_shadow' style='width:132;height:120;' >
				<tr>
					<th class='box_01'></th>
					<td class='box_02'></td>
					<th class='box_03'></th>
				</tr>
				<tr>
					<th class='box_04'></th>
					<td class='box_05'  valign=top style='padding:5 7 5 7'>
						<table cellpadding=0 cellspacing=0><!--CheckSpecialChar(this);-->
						<tr><td align=left>mallstory sms </td></tr>
						<tr><td><textarea style='width:106;height:100;background-color:#efefef;border:1px solid #e6e6e6;padding:2px;overflow:hidden;' name='sms_text' onkeyup=\"fc_chk_byte(this,80, this.form.sms_text_count);\" ></textarea></td></tr>
						<tr><td height=20 align=right><input type=text name='sms_text_count' style='display:inline;border:0px;text-align:right' size=3 value=0> / 80 byte </td></tr>
						</table>

					</td>
					<th class='box_06'></th>
				</tr>
				<tr>
					<th class='box_07'></th>
					<td class='box_08'></td>
					<th class='box_09'></th>
				</tr>
			</table>
		</td>
	<!--/tr>
	<tr-->";
//$cominfo = getcominfo();

$help_text .= "
		<td valign=top style='padding:0 0 0 10'>
			<table cellpadding=0 cellspacing=0><input type=hidden name='sms_send_page' value='1'>
				<tr height=26><td align=left width=90 class=small>보내는사람 : </td><td><input type=text name='send_phone' class=textbox style='display:inline;' size=12 value='".$cominfo[com_phone]."'></td></tr>
				<tr height=22><td align=left class=small>SMS 잔여건수 : </td><td> 건 </td></tr>
				<tr height=22><td align=left class=small>발송수/발송대상 : </td><td><b id='sended_sms_cnt' class=blu>0</b> 건 / <b id='remainder_sms_cnt'>$total</a> 명</td></tr>
				<tr height=22>
						<td align=left class=small>발송수량(1회) : </td>
						<td>
						<select name=sms_max>
							<option value='5' >5</option>
							<option value='10'  >10</option>
							<option value='20' >20</option>
							<option value='50' >50</option>
							<option value='100' selected>100</option>
							<option value='200' >200</option>
							<option value='300' >300</option>
							<option value='400' >400</option>
							<option value='500' >500</option>
							<option value='1000' >1000</option>
						</select>
						</td>
				</tr>
				<tr height=22><td align=left class=small>일시정지 : </td><td><input type='checkbox' name='stop' id='sms_stop'><label for='sms_stop'>정지</label></td></tr>
				<tr height=50><td align=center colspan=2><input type=image src='../image/btn_send.gif' border=0> </td></tr>
			</table>
		</td>
	</tr>
</table>
</div>
<div id='batch_update_sendemail' ".($update_kind == "sendemail" ? "style='display:block'":"style='display:none'")." >
<div style='padding:4 0 4 0'><img src='../images/dot_org.gif' align=absmiddle> <b>email 일괄발송</b> <span class=small style='color:gray'>검색/선택된 회원에게 email 을 발송합니다.</span></div>
<table cellpadding=3 cellspacing=0 width=100% style='border:1px solid #e2e2e2;'>
	<col width=15%>
	<col width=35%>
	<col width=15%>
	<col width=35%>
	<tr><td bgcolor='#efefef'> <b>이메일 제목</b></td><td colspan=3> <input type=text name='email_subject'  class=textbox value=''  style='width:350' > <span class='small blu'></span></td></tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr>
	<tr><td bgcolor='#efefef'> <b>참조</b></td><td colspan=3> <input type=text name='mail_cc'  class=textbox value='' style='width:350' > <span class='small blu'>콤마(,) 구분으로 이메일을 입력해주세요</span></td></tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr>
	<tr height=22><input type=hidden name='email_send_page' value='1'>
		<td align=left bgcolor='#efefef'> <b>발송수/발송대상 </b> </td>
		<td><b id='sended_email_cnt' class=blu>0</b> 건 / <b id='remainder_email_cnt'>$total</a> 명</td>
		<td align=left bgcolor='#efefef'> <b>발송수량(1회) </b> </td>
		<td>
		<select name=email_max>
			<option value='5' >5</option>
			<option value='10'  >10</option>
			<option value='20' >20</option>
			<option value='50' >50</option>
			<option value='100' selected>100</option>
			<option value='200' >200</option>
			<option value='300' >300</option>
			<option value='400' >400</option>
			<option value='500' >500</option>
			<option value='1000' >1000</option>
		</select>
		</td>
	</tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr>
	<tr height=22><td align=left bgcolor='#efefef'> <b>일시정지 </b> </td><td><input type='checkbox' name='email_stop' id='email_stop'><label for='email_stop'>정지</label></td></tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr>
	<tr>
		<td colspan=4>".WebEdit()."<input type='hidden' name='mail_content' value=''></td>
	</tr>
</table>
<table cellpadding=5 cellspacing=1 width=100% >
	<tr bgcolor=#ffffff>
		<td colspan=2 align=right valign=top style='padding:0px;padding-right:20px;'>
		<a href='javascript:doToggleText();' onMouseOver=\"MM_swapImage('editImage15','','../webedit/image/bt_html_1.gif',1)\" onMouseOut='MM_swapImgRestore()'><img src='../webedit/image/bt_html.gif' name='editImage15' width='93' height='23' border='0' id='editImage15'></a>
    <a href='javascript:doToggleHtml();' onMouseOver=\"MM_swapImage('editImage16','','../webedit/image/bt_source_1.gif',1)\" onMouseOut='MM_swapImgRestore()'><img src='../webedit/image/bt_source.gif' name='editImage16' width='93' height='23' border='0' id='editImage16'></a>
		</td>
	</tr>
</table>
<table cellpadding=3 cellspacing=0 width=100% style='border:0px solid silver;'>
	<tr height=50><td colspan=4 align=center><input type=image src='../image/btn_send.gif' border=0 style='cursor:hand;border:0px;' ></td></tr>
</table>
</div>
<div id='batch_update_hotcon' ".($update_kind == "hotcon" ? "style='display:block'":"style='display:none'")." >
<div style='padding:4 0 4 0'><img src='../images/dot_org.gif'> <b>하트콘 일괄발송</b> <span class=small style='color:gray'>이벤트 코드와 하트콘 상품코드를 입력해주세요</span></div>
<table cellpadding=3 cellspacing=0 width=100% style='border:1px solid #e2e2e2;'>
	<col width=170>
	<col width=*>
	<tr><td bgcolor='#efefef'> <b>하트콘 이벤트코드</b></td><td > <input type=text name='hotcon_event_id'  class=textbox value='' onkeydown='onlyNumber(this)' onkeyup='onlyNumber(this)'  style='width:150' > <span class='small blu'>4자리 이벤트 코드를 입력해주세요</span></td></tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr>
	<tr>
		<td bgcolor='#efefef'> <b>하트콘 상품코드</b></td>
		<td > <input type=text name='hotcon_pcode'  class=textbox value='' style='width:250' > <span class='small blu'>10 자리 하트콘 상품 코드를 입력해주세요</span></td></tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr>
	<tr height=22>
		<td bgcolor='#efefef' align=left ><img src='../image/ico_dot.gif'> <b>발송수/발송대상 : </b><input type=hidden name='hotcon_send_page' value='1'></td>
		<td><b id='sended_hotcon_cnt' class=blu>0</b> 건 / <b id='remainder_hotcon_cnt'>$total</a> 명</td>
	</tr>
	<tr height=1><td colspan=4 class='dot-x'></td></tr>
	<tr height=22>
			<td align=left bgcolor='#efefef' ><img src='../image/ico_dot.gif'> <b>발송수량(1회) : </b></td>
			<td>
			<select name=hotcon_max>
				<option value='5' >5</option>
				<option value='10' >10</option>
				<option value='20' >20</option>
				<option value='50' >50</option>
				<option value='100' selected>100</option>
				<option value='200' >200</option>
				<option value='300' >300</option>
				<option value='400' >400</option>
				<option value='500' >500</option>
				<option value='1000' >1000</option>
			</select>
			</td>
	</tr>
	<tr height=22><td bgcolor='#efefef' align=left ><img src='../image/ico_dot.gif'> <b>일시정지 :</b> </td><td><input type='checkbox' name='stop' id='hotcon_stop'><label for='hotcon_stop'>정지</label></td></tr>
</table>
<table cellpadding=3 cellspacing=0 width=100% style='border:0px solid silver;'>
	<tr height=50>
	<td valign=top style='padding:0 0 0 10'>
			<table cellpadding=0 cellspacing=0>

			</table>
	<td colspan=4 align=center><input type=image src='../image/btn_send.gif' border=0 style='cursor:hand;border:0px;' ></td>
	</tr>
</table>
</div>
<div id='batch_update_status' ".($update_kind == "hotcon" ? "style='display:block'":"style='display:none'")." >
<div style='padding:4px 0 4px 0'><img src='../images/dot_org.gif'> <b>접수상태 일괄변경</b> <span class=small style='color:gray'>변경하시고자 하는 접수상태를 선택해주세요</span></div>
<table cellpadding=3 cellspacing=0 width=100% class='input_table_box'>
	<col width=170>
	<col width=*>
	<tr>
		<td class='input_box_title'> <b>접수상태</b></td>
		<td class='input_box_item'>
				<select name='change_status'>
					<option value='AC' >고객 신청완료</option>
					<option value='TC' >관리자 접수완료</option>
					<option value='IC' >출고완료</option>
					<option value='AD' >접수취소</option>
				</select>
		</td>
	</tr>

</table>
<table cellpadding=3 cellspacing=0 width=100% style='border:0px solid silver;'>
	<tr height=50>
	<td valign=top style='padding:0 0 0 10'>

	<td colspan=4 align=center><input type=image src='../image/b_save.gif' border=0 style='cursor:hand;border:0px;' ></td>
	</tr>
</table>
</div>
";

$select = "
<select name='update_type'>
					<option value='2'>선택한회원 전체에게</option>
					<option value='1'>검색한 회원 전체에게</option>
				</select>

				<input type='radio' name='update_kind' id='update_kind_group' value='group' ".CompareReturnValue("group",$update_kind,"checked")." onclick=\"ChangeUpdateForm('batch_update_group');\"><label for='update_kind_group' >택배 그룹 일괄변경</label>
				<!--input type='radio' name='update_kind' id='update_kind_sms' value='sms' ".CompareReturnValue("sms",$update_kind,"checked")." onclick=\"ChangeUpdateForm('batch_update_sms');\"><label for='update_kind_sms'>SMS 일괄발송</label>
				<input type='radio' name='update_kind' id='update_kind_sendemail' value='sendemail' ".CompareReturnValue("sendemail",$update_kind,"checked")." onclick=\"ChangeUpdateForm('batch_update_sendemail');\"><label for='update_kind_sendemail'>이메일 일괄발송</label>
				<input type='radio' name='update_kind' id='update_kind_hotcon' value='hotcon' ".CompareReturnValue("hotcon",$update_kind,"checked")." onclick=\"ChangeUpdateForm('batch_update_hotcon');\"><label for='update_kind_hotcon'>하트콘 일괄발송</label-->
				<input type='radio' name='update_kind' id='update_kind_status' value='status' ".CompareReturnValue("status",$update_kind,"checked")." onclick=\"ChangeUpdateForm('batch_update_status');\"><label for='update_kind_status'>접수상태 일괄변경</label>";

$Contents .= "".HelpBox($select, $help_text, "430")."</form>";


$Contents .= "
<form name='lyrstat'>
	<input type='hidden' name='opend' value=''>
</form>";




$P = new LayOut();
$P->addScript = "<script language='javascript' src='application.js'></script>\n<script language='JavaScript' src='../webedit/webedit.js'></script>\n<script language='javascript' src='../include/DateSelect.js'></script>\n".$Script;
$P->OnloadFunction = "init();";
$P->strLeftMenu = delivery_menu();
$P->Navigation = "배송대행서비스 > 택배관리 > 접수목록";
$P->title = "택배관리";
$P->strContents = $Contents;
echo $P->PrintLayOut();


function getGroupInfoSelect($obj_id, $obj_txt, $parent_group_ix, $selected, $depth=1, $property=""){
	$mdb = new Database;
	if($depth == 1){
		$sql = 	"SELECT dg.*
				FROM delivery_group dg
				where group_depth = '$depth'
				group by group_ix ";
	}else if($depth == 2){
		$sql = 	"SELECT dg.*
				FROM delivery_group dg
				where group_depth = '$depth' and parent_group_ix = '$parent_group_ix'
				group by group_ix ";
	}
	//echo $sql;
	$mdb->query($sql);

	$mstring = "<select name='$obj_id' id='$obj_id' $property>";
	$mstring .= "<option value=''>$obj_txt</option>";
	if($mdb->total){


		for($i=0;$i < $mdb->total;$i++){
			$mdb->fetch($i);
			if($mdb->dt[group_ix] == $selected){
				$mstring .= "<option value='".$mdb->dt[group_ix]."' selected>".$mdb->dt[group_name]."</option>";
			}else{
				$mstring .= "<option value='".$mdb->dt[group_ix]."'>".$mdb->dt[group_name]."</option>";
			}
		}

	}
	$mstring .= "</select>";

	return $mstring;
}

function getFirstDIV($mdb, $selected, $object_id='parent_group_ix', $depth=1, $property="disabled"){
	$mdb = new Database;

	$sql = 	"SELECT dg.*
			FROM delivery_group dg
			where group_depth = 1
			group by group_ix ";
	//echo $sql;
	$mdb->query($sql);

	$mstring = "<select name='$object_id' id='$object_id' $property>";
	$mstring .= "<option value=''>1차그룹</option>";
	if($mdb->total){


		for($i=0;$i < $mdb->total;$i++){
			$mdb->fetch($i);
			if($mdb->dt[group_ix] == $selected){
				$mstring .= "<option value='".$mdb->dt[group_ix]."' selected>".$mdb->dt[group_name]."</option>";
			}else{
				$mstring .= "<option value='".$mdb->dt[group_ix]."'>".$mdb->dt[group_name]."</option>";
			}
		}

	}
	$mstring .= "</select>";

	return $mstring;
}

/*

CREATE TABLE `mallstory_sms_group` (
  `sg_ix` int(8) NOT NULL AUTO_INCREMENT,
  `sg_name` varchar(50) DEFAULT NULL,
  `regdate` datetime DEFAULT NULL,
  PRIMARY KEY (`sg_ix`)
}

CREATE TABLE `delivery_info` (
  `di_ix` int(8) unsigned NOT NULL auto_increment,
  `com_div` varchar(20) default '',
  `div` varchar(30) default '',
  `url` varchar(255) default NULL,
  `page` int(8) default '0',
  `com_name` varchar(50) default NULL,
  `charger` varchar(50) default NULL,
  `phone` varchar(50) default NULL,
  `fax` varchar(20) default NULL,
  `mobile` varchar(20) default NULL,
  `email` varchar(50) default NULL,
  `homepage` varchar(50) default NULL,
  `com_address` varchar(50) default NULL,
  `mail_yn` enum('0','1') default '1',
  `marketer` varchar(100) default '',
  `memo` text,
  `regdate` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`di_ix`),
  KEY `regdate` (`regdate`)
) TYPE=MyISAM DEFAULT CHARSET=utf8


CREATE TABLE `mallstory_sms_address` (
  `sa_ix` int(8) NOT NULL AUTO_INCREMENT,
  `sg_ix` int(8) DEFAULT NULL,
  `sa_name` varchar(25) NOT NULL DEFAULT '0',
  `sa_mobile` varchar(15) DEFAULT '',
  `sa_sex` enum('M','F')  DEFAULT NULL,
  `sa_etc` varchar(255) DEFAULT NULL,
  `regdate` datetime DEFAULT NULL,
  PRIMARY KEY (`sa_ix`),
  KEY `regdate` (`regdate`),
) ENGINE=MyISAM  DEFAULT CHARSET=utf8

CREATE TABLE `mallstory_sms_history` (
  `sh_ix` int(8) NOT NULL AUTO_INCREMENT,
  `send_phone` varchar(50) DEFAULT NULL,
  `dest_mobile` varchar(15) DEFAULT '',
  `regdate` datetime DEFAULT NULL,
  PRIMARY KEY (`sg_ix`)
}
*/
?>



