<?php
/**
 * Created by PhpStorm.
 * User: moon
 * Date: 2019-11-26
 * Time: 오후 1:42
 */
include($_SERVER["DOCUMENT_ROOT"]."/admin/class/layout.class");
include '../include/phpexcel/Classes/PHPExcel.php';
set_time_limit(9999999999);
ini_set('memory_limit',-1);

$goods_basic_sample[] = array("code"=>"cid","title"=>"카테고리분류코드","desc"=>"","type"=>"","comment"=>"카테고리분류코드","validation"=>"true","sample"=>"");
$goods_basic_sample[] = array("code"=>"category_info","title"=>"카테고리분류","desc"=>"","type"=>"","comment"=>"카테고리분류","validation"=>"false","sample"=>"");
$goods_basic_sample[] = array("code"=>"this_category","title"=>"분류명(수정가능)","desc"=>"","type"=>"","comment"=>"분류명","validation"=>"false","sample"=>"");
$goods_basic_sample[] = array("code"=>"global_this_korean","title"=>"한글분류명(수정가능)","desc"=>"","type"=>"","comment"=>"한글분류명","validation"=>"false","sample"=>"");
$goods_basic_sample[] = array("code"=>"global_this_english","title"=>"영문분류명(수정가능)","desc"=>"","type"=>"","comment"=>"영문분류명","validation"=>"false","sample"=>"");




PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

date_default_timezone_set('Asia/Seoul');

$etc_excel = new PHPExcel();


if($act == 'get_category_code') {

// 속성 정의
    $etc_excel->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("Mallstory.com")
        ->setTitle("etc code List")
        ->setSubject("etc code List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("mallstory")
        ->setCategory("category code List");

    $etc_excel->setActiveSheetIndex(0);
    $etc_excel->getActiveSheet()->setTitle('카테고리');

    $ct_excel_info = array("카테고리코드(수정불가)", "카테고리분류(수정불가)", "분류명(수정가능)", "한글분류명(수정가능)", "영문분류명(수정가능)");
    $col = 'A';
    foreach ($ct_excel_info as $ci) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $ci);
//    $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setWidth(30);
        $col++;
    }

    $db->query("select cid,cname,global_cinfo from shop_category_info where cid not in ('000000000000000') order by cid");
    $db->fetch();
    $z = 2;

    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';

        $global_cinfo = json_decode($db->dt['global_cinfo'], true);


        $etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_TEXT);
        $etc_excel->getActiveSheet()->setCellValue($col . $z, " " . $db->dt[cid]);

        $col++;
        $ct_name = getCategoryInfo($db->dt[cid]);
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name);

        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt['cname']);

        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, urldecode($global_cinfo['cname']['korean']));

        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, urldecode($global_cinfo['cname']['english']));


        $z++;
    }

    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename=category_code.xls');
    header('Cache-Control: max-age=0');

    $etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
    $etc_excel->save('php://output');
}

if ($act == "new_excel_input") {    //엑셀정보 저장

    include("../include/lib/pclzip.lib.php");

    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    if ($excel_file_size > 0) {
        copy($excel_file, $_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/images/upfile/" . $excel_file_name);
    }

    $objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/images/upfile/" . $excel_file_name);

    $shift_num = 0;


    include("../logstory/class/sharedmemory.class");
    $shmop = new Shared("upload_category_data_" . $_SESSION["admininfo"]["charger_ix"]);
    $shmop->filepath = $_SERVER["DOCUMENT_ROOT"] . $_SESSION["admininfo"]["mall_data_root"] . "/_shared/";
    //echo $shmop->filepath;
    $shmop->SetFilePath();
    $upload_excel_data = $shmop->getObjectForKey("upload_category_data_" . $_SESSION["admininfo"]["charger_ix"]);

    $upload_excel_data = "";


    $col = 'A';



    foreach ($goods_basic_sample as $key => $value) {
        $upload_excel_data[session_id()][0][$value[code]] = $value[title];
        $col++;
    }

    $z = 0;

    // 데이터는 2줄부터 시작
    for ($rownum = 2; $rownum <= 30000; $rownum++) {


        if ($objPHPExcel->getActiveSheet()->getCell('A' . $rownum)->getValue() != "" || $objPHPExcel->getActiveSheet()->getCell('A' . $rownum)->getValue() == "0") {

            //continue;

            $col = 'A';
            foreach ($goods_basic_sample as $key => $value) {

                // PHPExcel_RichText
                if (is_object($objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue())) {
                    $objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell($col . $rownum));
                    $upload_excel_data[session_id()][$z + 1][$value[code]] = $objRichText->getPlainText();
                } else {
                    $upload_excel_data[session_id()][$z + 1][$value[code]] = $objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
                }
                $col++;
            }

            $upload_excel_data[session_id()][$z + 1][p_no] = $z;

        }
        $z++;
    }

    $shmop->setObjectForKey($upload_excel_data, "upload_category_data_" . $_SESSION["admininfo"]["charger_ix"]);
    if ($page_type == 'input') {
        echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./category_update_excel.php'</script>";
    } else {
        echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./category_update_excel.php'</script>";
    }
    exit;
}

if ($act == "single_goods_reg" && strlen($p_no) > 0) {


    include("../logstory/class/sharedmemory.class");

    $shmop = new Shared("upload_category_data_" . $_SESSION["admininfo"]["charger_ix"]);
    //	$shmop->clear();
    $shmop->filepath = $_SERVER["DOCUMENT_ROOT"] . $_SESSION["admininfo"]["mall_data_root"] . "/_shared/";
    $shmop->SetFilePath();
    $upload_excel_data = $shmop->getObjectForKey("upload_category_data_" . $_SESSION["admininfo"]["charger_ix"]);

    $select_excel_goods_infos = filter_by_value($upload_excel_data[session_id()], 'p_no', $p_no);

    foreach ($select_excel_goods_infos as $key => $value) {

        //이미지 등록 사용할 cid 획득
        $cid = trim($value['cid']);

        //상품코드가 존재하지 않을 경우 스킵
        if(empty($cid)){
            echo "<span class='red'>카테고리 분류코드는 필수 입니다. </span><br/>";
            continue;
        }

        $data_array = array();
        foreach ($value as $_key => $_value) {
            switch($_key){
                case 'this_category':
                    $data_array[$cid]['this_category'] = $_value;
                    break;
                case 'global_this_korean':
                    $data_array[$cid]['global_cinfo']['cname']['korean'] = urlencode($_value);
                    break;
                case 'global_this_english':
                    $data_array[$cid]['global_cinfo']['cname']['english'] = urlencode($_value);
                    break;
            }
        }
        foreach($data_array as $key=>$val){
            $global_cinfo = json_encode($val['global_cinfo']);
            $cname = $val['this_category'];
            $cid = $key;
            $sql = "update ".TBL_SHOP_CATEGORY_INFO." set
					global_cinfo = '$global_cinfo',
					cname = '$cname'					
				where 
					cid = '$cid'";
            $db->query($sql);

        }

//        $upload_excel_data[session_id()][$key][status] = "C";
//        $upload_excel_data[session_id()][$key][status_message] = "등록완료";
        echo "<span class='blue'>등록완료</span>";

    }

    $shmop->setObjectForKey($upload_excel_data, "upload_category_data_" . $_SESSION["admininfo"]["charger_ix"]);
    exit;
}

function getCategoryInfo($cid){
    $db = new Database;
    $db2 = new Database;
    if($cid) {
        $sql = "select * from shop_category_info where cid = '" . $cid . "'";
        $db->query($sql);
        $db->fetch();
        $depth = $db->dt[depth];
        $relation_cname = "";
        for ($i = 0; $i <= $depth; $i++) {
            $this_cid = substr(substr($cid, 0, ($i * 3 + 3)) . '000000000000', 0, 15);
            //echo "$i"."<br>";
            $sql = "select * from shop_category_info where cid = '" . $this_cid . "'";
            //echo nl2br($sql)."<br>";
            $db2->query($sql);
            $db2->fetch();
            $cname = $db2->dt[cname];

            if ($i == $depth) {
                $relation_cname .= $cname;
            } else {
                $relation_cname .= $cname . " > ";
            }

        }

        return $relation_cname;
    }
}