<?php
include("../class/layout.class");

$cid = $_GET['cid'];
$depth = $_GET['depth'];


if(empty($max)){
    $max = 10; //페이지당 갯수
}

if ($page == '')
{
    $start = 0;
    $page  = 1;
}
else
{
    $start = ($page - 1) * $max;
}


$sql = "select
            count(*) as cnt
        from
            shop_product as p 					
        left join 
            shop_product_relation as pr on p.id = pr.pid
        where
            pr.cid like '".substr($cid,0,3+(3*$depth))."%' 
        and p.is_delete = '0' ";

$db->query($sql);
$db->fetch();
$total = $db->dt['cnt'];

if($mode != 'excel') {
    $limit = "limit $start,$max";
}
$sql = "select 
          p.pname, p.state, p.add_info, p.pcode, p.id, p.sellprice, pr.cid , p.disp, pr.rid
        from 
          shop_product p
        left JOIN 
          shop_product_relation pr on p.id = pr.pid
        where 
          pr.cid like '".substr($cid,0,3+(3*$depth))."%' 
        and p.is_delete = '0'	
        order by p.regdate desc
        $limit
        ";
$db->query($sql);
$product_data = $db->fetchall();

if($mode == 'excel'){
    include '../include/phpexcel/Classes/PHPExcel.php';
    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    $memberXL = new PHPExcel();

    $memberXL->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("hanmipost.com")
        ->setTitle("Application List")
        ->setSubject("Application List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("hanmipost")
        ->setCategory("hanmipost");

    // 데이터 등록
    $memberXL->getActiveSheet(0)->setCellValue('A' . 1, "상품명");
    $memberXL->getActiveSheet(0)->setCellValue('B' . 1, "카테고리");
    $memberXL->getActiveSheet(0)->setCellValue('C' . 1, "노출여부");
    $memberXL->getActiveSheet(0)->setCellValue('D' . 1, "판매상태");
    $memberXL->getActiveSheet(0)->setCellValue('E' . 1, "색상명");
    $memberXL->getActiveSheet(0)->setCellValue('F' . 1, "상품코드");
    $memberXL->getActiveSheet(0)->setCellValue('G' . 1, "상품시스템코드");
    $memberXL->getActiveSheet(0)->setCellValue('H' . 1, "판매가");

    if(is_array($product_data)){
        foreach($product_data as $key=>$val){
            if($val['disp'] == '1'){
                $disp_text = "노출함";
            }else{
                $disp_text = "노출안함";
            }
            $memberXL->getActiveSheet(0)->setCellValue('A' .($key + 2), $val['pname']);
            $memberXL->getActiveSheet(0)->setCellValue('B' .($key + 2), getCategoryPathByAdmin($val['cid'], 4));
            $memberXL->getActiveSheet(0)->setCellValue('C' .($key + 2), $disp_text);
            $memberXL->getActiveSheet(0)->setCellValue('D' .($key + 2), $_SELL_STATUS[$val['state']]);
            $memberXL->getActiveSheet(0)->setCellValue('E' .($key + 2), $val['add_info']);
            $memberXL->getActiveSheet(0)->setCellValue('F' .($key + 2), $val['pcode']);
            $memberXL->getActiveSheet(0)->setCellValue('G' .($key + 2), $val['id']);
            $memberXL->getActiveSheet(0)->setCellValue('H' .($key + 2), $val['sellprice']);
        }
    }

    // 시트이름등록
    $memberXL->getActiveSheet()->setTitle('신청목록');

    // 첫번째 시트 선택
    $memberXL->setActiveSheetIndex(0);
    $memberXL->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);

    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="category_product_list.xls"');
    header('Cache-Control: max-age=0');


    $objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
    $objWriter->save('php://output');
    exit;
}


if($_SERVER["QUERY_STRING"] == "nset=$nset&page=$page"){
    $query_string = str_replace("nset=$nset&page=$page","",$_SERVER["QUERY_STRING"]) ;
}else{
    $query_string = str_replace("nset=$nset&page=$page&","","&".$_SERVER["QUERY_STRING"]) ;
}
$str_page_bar = page_bar($total, $page, $max, $query_string,"");

$list_item = "";
$deleteBool = false;

$addQaDir = "";
if($_SESSION['admin_config']['mall_domain'] == "0925admintest.barrelmade.co.kr"){
    $addQaDir = "/QA";
}

if(!empty($product_data)){
    foreach($product_data as $key=>$val){
        //$img_str = PrintImage($_SESSION['admin_config']['mall_data_root']."/images/product", $val['id'], "ms");
        $img_str = PrintImage($_SESSION['admin_config']['mall_data_root']."/images/addimgNew".$addQaDir, $val['id'], "slist");

        if($cid == $val['cid']){
            $deleteBool = true;
            $deleteButton = "<input type='button' value='매칭제거' onclick=\"deleteRelation('".$val['cid']."','".$val['id']."')\" >";
            $delectCheck = "";
        }else{
            $deleteButton = "-";
            $delectCheck = "disabled";
        }
        $list_item .= "
        <tr height=35 bgcolor=#ffffff align=center>
            <td class='list_box_td '> <input type='checkbox' class='listChk' name='rid[]' value='".$val['rid']."' $delectCheck/></td>
            <td class='input_box_item '>
                
                <table> 
                    <tr> 
                        <td rowspan='2'> 
                           <a href='../product/goods_input.php?id=".$val['id']."' target='_blank' > <img src='".$img_str."' width=50 height=50> </a>
                        </td>
                         <td>".getCategoryPathByAdmin($val['cid'], 4)."</td>
                    </tr>
                       
                        <td> 
                            ".$val['pname']."        
                        </td>
                    </tr>
                </table>                
            </td>
            <td class='list_box_td '> ".$_SELL_STATUS[$val['state']]."</td>
            <td class='list_box_td '> ".$val['add_info']."</td>
            <td class='list_box_td '> ".$val['pcode']."</td>
            <td class='list_box_td '> ".$val['id']."</td>
            <td class='list_box_td '> ".$val['sellprice']."</td>
            <td class='list_box_td '> ".$deleteButton."</td>
           
        </tr>
        ";
    }
}else{
    $list_item .= "
    <tr height=35 bgcolor=#ffffff align=center>
        <td class='list_box_td ' colspan='8'> 상품 내역이 없습니다. </td>
    </tr>
    ";
}
$deleteAllBtn = "";

$deleteAllBtn = "<input type='button' value='선택 매칭제거' onclick=\"deleteRelationAll('".$cid."','select')\" />";
$deleteAllBtn .= " <input type='button' value='전체 매칭제거' onclick=\"deleteRelationAll('".$cid."','all')\" />";

$Contents = "
<div style='float:right;'><a href='?mode=excel&".$QUERY_STRING."'><img src='../image/btn_excel_save.gif' border=0></a></div>
<table cellpadding=4 cellspacing=0 width=100% bgcolor=silver class='list_table_box'>
    <col width = '5%' />
    <col width = '*' />
    <col width = '10%' />
    <col width = '10%' />
    <col width = '10%' />
    <col width = '14%' />
    <col width = '10%' />
    <col width = '8%' />
    <tr align=center bgcolor=#efefef height=25>
        <td class='s_td' ><input type='checkbox' id='allCheck'/></td>
        <td class='s_td' >상품명</td>
        <td class='m_td' >판매상태</td>
        <td class='m_td' >색상명</td>   
        <td class='m_td' >상품코드</td>        
        <td class='m_td' >상품 시스템코드</td>
        <td class='m_td' >판매가</td>
        <td class='e_td' >관리</td>
    </tr>        
    ".$list_item."
</table>
<table width='100%'> 
    <tr> 
        <td align='left'>".$deleteAllBtn."</td>
        <td align=right>".$str_page_bar."</td>
    </tr>
</table>

";

$Script = "
<script> 
    function deleteRelation(cid,pid){
        if(cid && pid){
            if(confirm('카테고리 매칭을 해제 하시겠습니까?')){
                $.ajax({ 
                    type: 'POST', 
                    data: {'act': 'delete_relation', 'cid':cid, 'pid':pid},
                    url: './category_save.php',  
                    dataType: 'json', 
                    async: true, 
                    beforeSend: function(){ 
                        //alert(2)
                    },  
                    success: function(datas){ 
                        if(datas.success == true){
                            alert(datas.msg);
                            location.reload();                            
                        }else{
                            alert(datas.msg);
                        }
                    } 
                });
            }
        }
    }
    
    function deleteRelationAll(cid,type){
        if(cid){
            if(confirm('카테고리 매칭을 해제 하시겠습니까?')){
                var formData = new FormData();
                formData.append('act', 'delete_relation_all');
                formData.append('cid', cid);
                
                if(type=='all'){                   
		            formData.append('type', type);
                }else{
                    var lists = [];
                    $('input[name^=rid]:checked').each(function(){
                        lists.push($(this).val());
                    }); 
                    if(lists.length == 0){
                        alert('매칭 제거할 상품을 선택해 주세요.');
                        return false;
                    }                        
                    formData.append('lists[]', lists);
                }
                
                $.ajax({ 
                    type: 'POST', 
                    data: formData,
                    url: './category_save.php',  
                    dataType: 'json', 
                    contentType: false,
                    processData: false,
                    async: true, 
                    beforeSend: function(){ 
                        //alert(2)
                    },  
                    success: function(datas){ 
                        console.log(datas)
                        var sCnt = datas.s_cnt;
                        var fCnt = datas.f_cnt;
                            alert('매칭제거 성공:'+sCnt+'건 실패:'+fCnt+'건');
                            location.reload();
                        
                    } 
                });
            }
        }
    }
    
    $(document).ready(function(){
       $('#allCheck').on('click',function(){
          if($(this).is(':checked') == true){
              checkList(true);              
          }else{
              checkList(false);              
          }
       });
       
       $('.listChk').on('click',function(){
           var chkBool = true;
            $('.listChk').each(function(){
                var opt = $(this).prop('disabled');
                if(!opt){
                    if($(this).is(':checked') != true){
                        chkBool = false;
                    }
                }
            });  
            if(chkBool == true){
                $('#allCheck').attr('checked',true);
            }else{
                $('#allCheck').attr('checked',false);
            }            
       });
       
       function checkList(p){
           $('.listChk').each(function(){
               var opt = $(this).prop('disabled');
               if(!opt){
                   $(this).attr('checked',p);
               }
           });
           
       }
    });
</script>
";

$P = new ManagePopLayOut();
$P->addScript = $Script;
$P->Navigation = "카테고리 매칭 상품리스트";
$P->NaviTitle = "카테고리 매칭 상품리스트";
$P->strContents = $Contents;
echo $P->PrintLayOut();