<?
include($_SERVER["DOCUMENT_ROOT"]."/admin/class/layout.class");

$db = new Database;
$mdb = new Database;

$update_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"U");
$delete_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"D");
$create_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"C");
$excel_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E");

if($_COOKIE[product_notice_limit]){
	$max = $_COOKIE[product_notice_limit]; //페이지당 갯수
}else{
	$max = 15;
}

if ($page == '')
{
	$start = 0;
	$page  = 1;
}else{
	$start = ($page - 1) * $max;
}

if($page == '')
{
	$start = 0;
	$page  = 1;
}else{
	$start = ($page - 1) * $max;
}

if(count($status) > 0){
	$where .= " and (";
	$i = 1;
	foreach($status as $key => $value){
		if($i == count($status)){
			$where .= " pn.status = '".$value."'";
		}else{
			$where .= " pn.status = '".$value."' or ";
		}
	$i++;
	}
	$where .=")";
}
if(is_array($status)){
	if(in_array('W',$status)){
		$status_w = 'checked';
	}
	if(in_array('I',$status)){
		$status_i = 'checked';
	}
	if(in_array('C',$status)){
		$status_c = 'checked';
	}
}

if($regdate == '1'){
	if($sdate != "" && $edate !=""){
		$where .= " and date_format(pn.regdate,'%Y-%m-%d') between '".$sdate."' and '".$edate."'";
	}
}

$search_text = trim($search_text);

if($db->dbms_type == "oracle"){
	if($search_type != "" && $search_text != ""){
		$where .= " and $search_type LIKE  '%$search_text%' ";
	}
}else{
	if($search_type != "" && $search_text != ""){
		$where .= " and $search_type LIKE  '%$search_text%' ";
	}
}

if($md_code != ""){
	$where .= " and pn.md_code = '".$md_code."'";
}


if($_SESSION["admininfo"]["admin_level"] != '9'){
	$where .= " and pn.company_id = '".$admininfo[company_id]."'";
}else{
	if($company_id != ""){
		$where .= " and pn.company_id = '".$company_id."'";
	}
}

// 전체 갯수 불러오는 부분
$sql = "SELECT 
			* 
		FROM
			shop_product_notice as pn
		where
			type= 'P' $where";
$db->query($sql);
$db->fetch();
$total = $db->total;

$sql = "SELECT 
		pn.*,
		p.pname
		from
			shop_product_notice as pn
			left join shop_product as p on (pn.pid = p.id)
		where
			pn.type= 'P'
			$where
			order by regdate desc 
			limit $start, $max";
$db->query($sql);


$str_page_bar = page_bar($total, $page,$max, "&max=$max&update_kind=$update_kind&search_type=$search_type&search_text=$search_text&region=$region&gp_ix=$gp_ix&age=$age&birthday_yn=$birthday_yn&sex=$sex&mailsend_yn=$mailsend_yn&smssend_yn=$smssend_yn&mem_type=$mem_type&FromYY=$FromYY&FromMM=$FromMM&FromDD=$FromDD&ToYY=$ToYY&ToMM=$ToMM&ToDD=$ToDD&vFromYY=$vFromYY&vFromMM=$vFromMM&vFromDD=$vFromDD&vToYY=$vToYY&vToMM=$vToMM&vToDD=$vToDD&type=$type","view");//gp_level 을 사용하지 않아서 gp_ix 로 바꿈 kbk 13/02/19


if($mode == "excel"){

	$goods_infos = $db->fetchall();
	include("excel_out_columsinfo.php");
	$sql = "select conf_val from inventory_config where charger_ix='".$admininfo[charger_ix]."' and conf_name='qna_".$type."' ";
	$db->query($sql);
	$db->fetch();
	$stock_report_excel = $db->dt[conf_val];

	$sql = "select conf_val from inventory_config where charger_ix='".$admininfo[charger_ix]."' and conf_name='qna_edit_".$type."' ";
	$db->query($sql);
	$db->fetch();
	$stock_report_excel_checked = $db->dt[conf_val];

	$check_colums = unserialize(stripslashes($stock_report_excel_checked));

	$columsinfo = $colums;

	include '../include/phpexcel/Classes/PHPExcel.php';
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$inventory_excel = new PHPExcel();

	// 속성 정의
	$inventory_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("accounts plan price List")
								 ->setSubject("accounts plan price List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("accounts plan price List");
	$col = 'A';
	foreach($check_colums as $key => $value){
		$inventory_excel->getActiveSheet(0)->setCellValue($col . "1", $columsinfo[$value][title]);
		$col++;
	}

	$before_pid = "";
	
	for ($i = 0; $i < count($goods_infos); $i++)
	{
		$j="A";
		foreach($check_colums as $key => $value){

			if($key == "complete_date"){
				$value_str = $goods_infos[$i][complete_date];
			}else if($key == "regdate"){
				$value_str = $goods_infos[$i][regdate];
			}else if($key == "code"){
				$value_str = $goods_infos[$i][fs_code];
			}else if($key == "md_code"){
				$value_str = $goods_infos[$i][f_md_code];
			}else if($key == "gp_name"){

				$sql = "select
						sg.gp_name
					from
						common_member_detail as cmd
						left join shop_groupinfo as sg on (cmd.gp_ix = sg.gp_ix)
					where
						cmd.code = '".$user_code."'";

				$mdb->query($sql);
				$mdb->fetch();
				$value_str = $mdb->dt[gp_name];
			}else if($key == "md_name"){

				$sql = "select
							AES_DECRYPT(UNHEX(name),'".$db->ase_encrypt_key."') as name
						from
							common_member_detail
							
						where
							code = '".$goods_infos[$i][fs_md_code]."'";

				$mdb->query($sql);
				$mdb->fetch();
				$value_str = $mdb->dt[name];
			}else if($key == "status"){

				switch($goods_infos[$i][status]){
					case 'W':
						$value_str = "문의요청";
					break;
					case 'I':
						$value_str = "처리중";
					break;
					case 'C':
						$value_str = "처리완료";
					break;
				}

			}else{
				$value_str = $goods_infos[$i][$value];//$db1->dt[$value];
			}

			$inventory_excel->getActiveSheet()->setCellValue($j . ($z + 2), $value_str);
			$j++;

		}
		$z++;
	}
	// 첫번째 시트 선택
	$inventory_excel->setActiveSheetIndex(0);

	// 너비조정
	$col = 'A';
	foreach($check_colums as $key => $value){
		$inventory_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="cscenter'.$info_type.'.xls"');
	header('Cache-Control: max-age=0');

	$objWriter = PHPExcel_IOFactory::createWriter($inventory_excel, 'Excel5');
	$objWriter->save('php://output');

	exit;
}


$Script = "
<script language='javascript'>

function view_go()
{
	var sort = document.view.sort[document.view.sort.selectedIndex].value;

	location.href = 'member.php?view='+sort;
}

function ChangeRegistDate(frm){
	if(frm.regdate.checked){
		frm.FromYY.disabled = false;
		frm.FromMM.disabled = false;
		frm.FromDD.disabled = false;
		frm.ToYY.disabled = false;
		frm.ToMM.disabled = false;
		frm.ToDD.disabled = false;
	}else{
		frm.FromYY.disabled = true;
		frm.FromMM.disabled = true;
		frm.FromDD.disabled = true;
		frm.ToYY.disabled = true;
		frm.ToMM.disabled = true;
		frm.ToDD.disabled = true;
	}
}

function ChangeVisitDate(frm){
	if(frm.visitdate.checked){
		frm.vFromYY.disabled = false;
		frm.vFromMM.disabled = false;
		frm.vFromDD.disabled = false;
		frm.vToYY.disabled = false;
		frm.vToMM.disabled = false;
		frm.vToDD.disabled = false;
	}else{
		frm.vFromYY.disabled = true;
		frm.vFromMM.disabled = true;
		frm.vFromDD.disabled = true;
		frm.vToYY.disabled = true;
		frm.vToMM.disabled = true;
		frm.vToDD.disabled = true;
	}
}
function ChangeBirDate(frm){
	if(frm.bir.checked){
		frm.birYY.disabled = false;
		frm.birMM.disabled = false;
		frm.birDD.disabled = false;
	}else{
		frm.birYY.disabled = true;
		frm.birMM.disabled = true;
		frm.birDD.disabled = true;
	}
}

function clearAll(frm){
		for(i=0;i < frm.code.length;i++){
				frm.code[i].checked = false;
		}
}

function checkAll(frm){
       	for(i=0;i < frm.code.length;i++){
				frm.code[i].checked = true;
		}
}

function fixAll(frm){
	if (!frm.all_fix.checked){
		clearAll(frm);
		frm.all_fix.checked = false;
			
	}else{
		checkAll(frm);
		frm.all_fix.checked = true;
	}
	//input_check_num();
}

function ProductQnaDelete(pn_ix){
	if(confirm(language_data['product_qna.php']['A'][language])){
	//'제품문의를  정말로 삭제하시겠습니까? '
		window.frames['act'].location.href='../product/product_notice.act.php?act=detail_delete&pn_ix='+pn_ix
		//document.getElementById('iframe_act').src='product_qna.act.php?act=detail_delete&pn_ix='+pn_ix;
	}
}



$(document).ready(function (){
	$('#max').change(function(){
		var value= $(this).val();
		$.cookie('product_notice_limit', value, {expires:1,domain:document.domain, path:'/', secure:0});

		document.location.reload();
		
	});

});

function reloadView(){

	if($('#distinct').attr('checked') == true || $('#distinct').attr('checked') == 'checked'){		
		$.cookie('distinct', '1', {expires:1,domain:document.domain, path:'/', secure:0});
	}else{		
		$.cookie('distinct', '0', {expires:1,domain:document.domain, path:'/', secure:0});
	}
	
	document.location.reload();

}


function ChangeUpdateForm(selected_id){
	var area = new Array('batch_update_reserve','batch_update_group','batch_update_sms','batch_update_coupon','batch_update_sendemail');

	for(var i=0; i<area.length; ++i){
		if(area[i]==selected_id){
			document.getElementById(selected_id).style.display = 'block';
			$.cookie('member_update_kind', selected_id.replace('batch_update_',''), {expires:1,domain:document.domain, path:'/', secure:0});
		}else{
			document.getElementById(area[i]).style.display = 'none';
		}
	}
}

	$(document).ready(function() {
		$('select#email_subject_select').change(function(){
			if($(this).val() != ''){
				$.ajax({
					type: 'GET',
					data: {'act': 'mail_info', 'mail_ix': $(this).val()},
					url: '../campaign/mail.act.php',
					dataType: 'json',
					async: true,
					beforeSend: function(){

					},
					success: function(mail_info){
						document.getElementById('iView').contentWindow.document.body.innerHTML = mail_info.mail_text;
						$('#email_subject_text').val(mail_info.mail_title);
						//alert(mail_info);
						//$('#row_'+wl_ix).slideRow('up',500);
					}
				});
			}
		});

		$('#state').change(function() {

			var value = $(this).val();

			if(value == '2'){
				$('#use_state1').css('display','none');
				$('#use_state2').css('display','');

				$('#use_state1').attr('disabled',true);
				$('#use_state2').attr('disabled',false);
			}else{
				$('#use_state1').css('display','');
				$('#use_state2').css('display','none');

				$('#use_state1').attr('disabled',false);
				$('#use_state2').attr('disabled',true);
			}
		});
	});

	function BatchSubmit(frm){

		if(frm.update_type.value == 1 && frm.search_searialize_value.length < 1){
			alert(language_data['member_batch.php']['A'][language]);//'적용대상중 [검색회원전체]는  검색후 사용 가능합니다. 확인후 다시 시도해주세요'
			return false;
		}

	}

	function input_check_num() {
		var sms_cnt=document.getElementById('remainder_sms_cnt');
		var email_cnt=document.getElementById('remainder_email_cnt');
		var frm=document.list_frm;
		if(frm.update_type.value==2) {
			var code_checked_num = 0;
			for(i=1;i < frm.code.length;i++){
				if(frm.code[i].checked){
					code_checked_num++;
				}
			}
			sms_cnt.innerHTML=code_checked_num;
			email_cnt.innerHTML=code_checked_num;
		}
	}

		function LoadEmail(email_type){
		if(email_type == 'new'){
			//$('#email_subject_text').css('display','inline');
			$('#email_select_area').css('display','none');
		}else if(email_type == 'box'){
			//$('#email_subject_text').css('display','none');
			$('#email_select_area').css('display','inline');
		}
	}

</script>";

$Contents = "
<table width='100%' border='0' align='center'>
<tr>
	<td align='left' colspan=6 > ".GetTitleNavigation("문의요청하기", $title)."</td>
</tr>
<tr>
	<td>";

$Contents .= "
	<table class='box_shadow' style='width:100%;' cellpadding='0' cellspacing='0' border='0'>
	<tr>
		<th class='box_01'></th>
		<td class='box_02'></td>
		<th class='box_03'></th>
	</tr>
	<tr>
		<th class='box_04'></th>
		<td class='box_05'  valign=top style='padding:5px 0px 5px 0px'>
 			<table width='100%' border='0' cellspacing='0' cellpadding='0' height='25' class='search_table_box'>
			<form name=searchmember method='get'>
			<col width='18%'>
			<col width='*'>
			<tr height=27>
				<td class='search_box_title'> 처리상태 </td>
				<td class='search_box_item' colspan='3'>
					<input type='checkbox' name='status[W]' value='W' id='status_w' ".$status_w."><label for='status_w'>문의요청</label>&nbsp;
					<input type='checkbox' name='status[I]' value='I' id='status_i' ".$status_i."><label for='status_i'>처리중</label>&nbsp;
					<input type='checkbox' name='status[C]' value='C' id='status_c' ".$status_c."><label for='status_c'>처리완료</label>
				</td>
			</tr>";

	$Contents .= "
		
			<tr height=27>
				<td class='search_box_title' >담당 MD</td>
				<td class='search_box_item'>
				".MDSelect($md_code, "md_code", "md_ix")."
				<input type='hidden' name='md_mem_ix' value=''>
				</td>
				<td class='search_box_title' >셀러업체</td>
				<td class='search_box_item'>
				".companyAuthList($company_id , "validation=false title='셀러업체' ")."
				</td>
			</tr>
			<tr height=27>
				<td class='search_box_title' ><label for='regdate'>기간 작성일</label>
					<input type='checkbox' name='regdate' id='regdate' value='1' onclick='ChangeRegistDate(document.searchmember);' ".CompareReturnValue("1",$regdate,"checked").">
				</td>
				<td class='search_box_item' colspan=3>
				".search_date('sdate','edate',$sdate,$edate)."
				</td>
			</tr>
			<tr height=27>
				<td class='search_box_title' >조건검색 </td>
				<td class='search_box_item' colspan='3'>
					<table cellpadding=0 cellspacing=0 width=100%>
						<col width='80'>
						<col width='*'>
						<tr>
							<td>
							<select name=search_type>
									<option value='fs.name' ".CompareReturnValue("fs.name",$search_type,"selected").">문의자명</option>
									<option value='fs.id' ".CompareReturnValue("fs.id",$search_type,"selected").">문의자ID</option>
									<option value='ccd.com_name' ".CompareReturnValue("ccd.com_name",$search_type,"selected").">셀러명</option>
							</select>
							</td>
							<td>
								<input type=text name='search_text' class='textbox' value='".$search_text."' style='width:200px;font-size:12px;padding:1px;' >
							</td>
						</tr>
					</table>
				</td>
			</tr>
			</table>
		</td>
		<th class='box_06'></th>
	</tr>
	<tr>
		<th class='box_07'></th>
		<td class='box_08'></td>
		<th class='box_09'></th>
	</tr>
	</table>
	</td>
</tr>
<tr height=50>
	<td style='padding:10px 20px 0 20px' colspan=4 align=center><input type=image src='../images/".$admininfo["language"]."/bt_search.gif' align=absmiddle  ></td>
</tr>
</table>
<br>
</form>";

$Contents .= "
<form name='list_frm' method='POST' onsubmit='return BatchSubmit(this);' action='product_notice.act.php'  target='act'>
<input type='hidden' name='code[]' id='code'>
<input type='hidden' name='act' value='info_delete'>
<table width='100%' border='0' cellpadding='0' cellspacing='0' align='left' >
<col width='80'>

<col width='*'>
<col width='100'>
<tr height=30 >
	<td>	
		전체 : ".$total." 개
	</td>
	<td align='left'>
		<img src='../images/icon/alarm_danger.gif'> 문의요청 &nbsp;&nbsp;&nbsp;
		<img src='../images/icon/1106_02.gif'> 처리중 &nbsp;&nbsp;&nbsp;
		<img src='../images/icon/alarm_safe.gif'> 처리완료
	</td>
	<td align=right>
	";

$Contents .= "
	</td>
	<td align=right>
	목록수 : <select name='max' id='max'>
				<option value='5' ".($_COOKIE[product_notice_limit] == '5'?'selected':'').">5</option>
				<option value='10' ".($_COOKIE[product_notice_limit] == '10'?'selected':'').">10</option>
				<option value='20' ".($_COOKIE[product_notice_limit] == '20'?'selected':'').">20</option>
				<option value='30' ".($_COOKIE[product_notice_limit] == '30'?'selected':'').">30</option>
				<option value='50' ".($_COOKIE[product_notice_limit] == '50'?'selected':'').">50</option>
				<option value='100' ".($_COOKIE[product_notice_limit] == '100'?'selected':'').">100</option>
			</select>
	</td>
</tr>
</table>
<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' class='list_table_box'>
	<col width='2%'>
	<col width='4%'>
	<col width='4%'> 
	<col width='11%'> 
	<col width='*'>
	<col width='7%'>
	<col width='10%'>
	<col width='7%'>
	<col width='7%'>
	<col width='11%'>
	<col width='7%'>
	<col width='7%'>

	<tr height='40' bgcolor='#ffffff'>
		<td align='center' class=s_td><input type=checkbox name='all_fix' id='all_fix' onclick='fixAll(document.list_frm)'></td>
		<td align='center' class='m_td'><font color='#000000'><b>알림</b></font></td>
		<td align='center' class='m_td'><font color='#000000'><b>순번</b></font></td>
		<td align='center' class='m_td'><font color='#000000'><b>작성일</b></font></td>
		<td align='center' class='m_td small' nowrap><font color='#000000'><b>제목</b></font></td>

		<td align='center' class='m_td small' nowrap><font color='#000000'><b>시스템코드</font></td>

		<td align='center' class='m_td small' nowrap><font color='#000000'><b>셀러명</font></td>
		<td align='center' class='m_td small' nowrap><font color='#000000'><b>문의자 명<br>ID</b></font></td>
		<td align='center' class=m_td><font color='#000000'><b>담당 MD</b></font></td>

		<td align='center' class=m_td><font color='#000000'><b>처리상태<br>처리완료일</b></font></td>
		<td align='center' class=m_td><font color='#000000'><b>계시글확인</b></font></td>
		<td align='center' class=e_td><font color='#000000'><b>관리</b></font></td>
	</tr>";

if($db->total == 0){
	$Contents .="
	<tr height=50>
		<td colspan='12' align='center'>등록된 데이타가 없습니다.</td>
	</tr>";

}else{
	for ($i = 0; $i < $db->total; $i++)
	{
		$db->fetch($i);
		$complete_date = $db->dt[complete_date];
		$regdate = $db->dt[regdate];
		$user_code = $db->dt[code];
		$md_code = $db->dt[md_code];

		$no = $total - ($page - 1) * $max - $i;

		switch($db->dt[status]){
			case 'W':
				$image = "<img src='../images/icon/alarm_danger.gif'>";
			break;
			case 'I':
				$image = "<img src='../images/icon/1106_02.gif'>";
			break;
			case 'C':
				$image = "<img src='../images/icon/alarm_safe.gif'>";
			break;
		}

		switch($db->dt[status]){
			case 'W':
				$status = '<font color=red><b>문의요청</b></font>';
			break;
			case 'I':
				$status = '<font color="blue"><b>처리중</b></font>';
			break;
			case 'C':
				$status = ' 처리완료';
			break;
		}

		switch($db->dt[check_yn]){
			case 'Y':
				$check_yn = '<font color=red><b>확인</b></font>';
			break;
			case 'N':
				$check_yn = '<font color="blue"><b>미확인</b></font>';
			break;
		}

		$Contents .="
		<tr height='45' onMouseOver=\"this.style.backgroundColor='#E8ECF1'; \" onMouseOut=\"this.style.backgroundColor=''\">
			<td class='list_box_td'><input type=checkbox name=pn_ix[] id='code' value='".$db->dt[pn_ix]."' onClick='input_check_num()'></td>
			<td class='list_box_td' >".$image."</td>
			<td class='list_box_td' >".$no."</td>
			<td class='list_box_td' >".$regdate."</td>
			<td class='list_box_td point' style='text-align:left;padding:0px 5px;line-height:150%;' >
				".$db->dt[title]."<br>
				<span style='font-weight:normal'>".$db->dt[pname]."</span>
			</td>
			<td class='list_box_td' style='line-height:150%;'>".$db->dt[pid]."</td>
			<td class='list_box_td' style='line-height:150%;'>".$db->dt[com_name]."<br>".$db->dt[seller_id]."</td>
			<td class='list_box_td' style='line-height:150%;'>".$db->dt[name]."<br>".$db->dt[id]."</td>

			<td class='list_box_td ' nowrap>".$db->dt[md_name]."</td>
			 
			<td class='list_box_td' >".$status."<br>".($complete_date == '0000-00-00 00:00:00'?'-':$complete_date)."</td>
			<td class='list_box_td' > ".$check_yn."</td>

			<td class='list_box_td ctr' style='padding:5px;'>
				<table border='0' cellpadding='0' cellspacing='0' align='center'>
				<tr>
				<td>";
				if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"C")){
					$Contents.="<a href=\"javascript:PoPWindow('product_notice.php?mmode=pop&pn_ix=".$db->dt[pn_ix]."&type=$type&pid=".$db->dt[pid]."&act=update',900,700,'product_notice');\"><img  src='../images/".$admininfo["language"]."/btn_reply.gif' border=0></a>";
				}else{
					$Contents.="<a href=\"".$auth_update_msg."\"><img  src='../images/".$admininfo["language"]."/btn_reply.gif' border=0></a>";
				}
	$Contents.="&nbsp;</td>";
	$Contents.="<td>";
				if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"D")){
					$Contents.="
					<a href=JavaScript:ProductQnaDelete('".$db->dt[pn_ix]."')><img  src='../images/".$admininfo["language"]."/btc_del.gif' border=0></a>";
				}else{
					$Contents.="
					<a href=\"".$auth_delete_msg."\"><img  src='../images/".$admininfo["language"]."/btc_del.gif' border=0></a>";
				}
		$Contents.="&nbsp;</td>";

	$Contents.="
				</tr>
				</table>";


$Contents .= "
			</td>
		</tr>";
	}
}

$Contents .= "
</table>

<table width=100% border='0'>
<tr>
	<td align='left'>
	<input type='hidden' name='act' value='info_delete' />
	<input type='image' src='../images/icon/btn_select_del.gif' value='선택삭제' id='' name='' style='border:0 none;margin-top:15px;' />
	</td>
	<td align='right'>";

	$Contents .= "
	</td>
</tr>
</table>

<table width=100% border='0'>
<tr>
	<!--<td align='left'><input type='checkbox' value='' id='check_member_list'> 선택수정 히스토리 <input type='button' value='삭제'>-->
	<td align='right'>".$str_page_bar."</td>
</tr>
</table>";

/*
$help_text = "
<table cellpadding=0 cellspacing=0 class='small' >
	<col width=8>
	<col width=*>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >회원에게 SMS 또는 메일을 보내실려면 보내고자 하는 회원을 선택하신후 '선택회원 SMS 보내기' 버튼을 클릭하신후 메일을 보내실수 있습니다</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >회원정보를 백업하기 위해서는 회원정보 검색후 엑셀로 저장 버튼을 클릭하시면 됩니다</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >검색기능을 통해서 조건에 맞는 회원을 빠르게 검색하실수 있습니다</td></tr>
</table>
";*/


if($admininfo[mall_type] == "H"){
	$Contents .= "".HelpBox($help_text, 520)."</form>";
}else{
	$Contents .= "".HelpBox($help_text, 750)."</form>";
}

$Contents .= "
<form name='lyrstat'>
	<input type='hidden' name='opend' value=''>
</form>";

$P = new LayOut;
$P->addScript = "$Script";
$P->strLeftMenu = product_menu();
$P->OnloadFunction = "";
$P->Navigation = "상품관리 > 상품수정알림게시판";
$P->title = "상품수정알림게시판";
$P->strContents = $Contents;
$P->PrintLayOut();


?>



