<?php
	include($_SERVER["DOCUMENT_ROOT"]."/admin/class/layout.class");
	include("../lib/imageResize.lib.php");
	include '../include/phpexcel/Classes/PHPExcel.php';
	include('goods_mandatory_info.lib.php');
	include("../product/product_input_excel.lib.php");


	$removestring = array("\n", "\t");


	if($admininfo[company_id] == ""){
		echo "<script language='javascript' src='../_language/language.php'></script><script language='javascript'>alert(language_data['common']['C'][language]);location.href='../'</script>";
		//'관리자 로그인후 사용하실수 있습니다.'
		exit;
	}

	$db = new MySQL;
	//$db2 = new MySQL;
	$image_db = new MySQL;


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 카테고리 브랜드 코드 엑셀 다운로드
/// 작성 : 홍진영 ( 2013.05.03 )
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if($_GET["act"] == "ect_code_down"){

	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$etc_excel = new PHPExcel();

	// 속성 정의
	$etc_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("etc code List")
								 ->setSubject("etc code List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("etc code List");

	$b_excel_info = array ("브랜드명","브랜드코드");
	$col = 'A';
	foreach($b_excel_info as $bi){
		$etc_excel->getActiveSheet(0)->setCellValue($col . "1", $bi);
		$etc_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}

	$ct_excel_info = array ("대분류","중분류","소분류","카테고리코드");
	$col = 'H';
	foreach($ct_excel_info as $ci){
		$etc_excel->getActiveSheet(0)->setCellValue($col . "1", $ci);
		$etc_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}







	$db->query("select b_ix,brand_name from shop_brand where disp='1' order by brand_name");
	$db->fetch();

	$z = 2;

	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet(1)->setCellValue($col . $z , $db->dt[brand_name]);
		$col++;
		$etc_excel->getActiveSheet(1)->setCellValue($col . $z , $db->dt[b_ix]);
		$z++;
	}

	//$db->query("select cid,FUNC_GET_CATE_NAME_BY_CID(cid) as ct_name from shop_ct_info where depth='2' order by cid");
	$db->query("select cid from shop_category_info order by cid");
	$db->fetch();
	$z = 2;

	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'H';
		//$ct_name=explode('>',$db->dt[ct_name]);
		$ct_name=explode('>',getCategoryPathByAdmin($db->dt[cid], 4));
		$etc_excel->getActiveSheet(0)->setCellValue($col . $z , $ct_name[0]);
		$col++;
		$etc_excel->getActiveSheet(0)->setCellValue($col . $z , $ct_name[1]);
		$col++;
		$etc_excel->getActiveSheet(0)->setCellValue($col . $z , $ct_name[2]);
		$col++;
		$etc_excel->getActiveSheet(0)->setCellValue($col . $z , $db->dt[cid]);
		$z++;
	}

	$etc_excel->getActiveSheet(0)->setTitle('브랜드 & 카테고리');
	$etc_excel->setActiveSheetIndex(0);

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename=category_brnad_code_v1.xls');
	header('Cache-Control: max-age=0');

	$etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
	$etc_excel->save('php://output');
}


//print_r($_POST);
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 샘플 엑셀 다운로드
/// 작성 : 신훈식 ( 2013.04.29 )
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if($_POST["act"] == "sample_excel_down"){



	if(substr($mandatory_type_1,0,1)=='0')	$mandatory_type_1 = substr($_POST["mandatory_type_1"],1,1);
	if(!$_POST["mandatory_type_2"])			$mandatory_type_2 = $_POST["mandatory_type_2"];
	else									$mandatory_type_2 = '1';
	if(!$_POST["mandatory_type_3"])			$mandatory_type_3 = $_POST["mandatory_type_3"];
	else									$mandatory_type_3 = '1';

	//$selected_mandatory_info = $goods_mandatory_info[$_POST["mandatory_type_1"]][$_POST["mandatory_type_2"]][$_POST["mandatory_type_3"]];
	$selected_mandatory_info = $goods_mandatory_info[$mandatory_type_1][$mandatory_type_2][$mandatory_type_3];

	$sample_excel_info = array_merge($goods_basic_sample,$selected_mandatory_info);
	//echo "aaa".intval($_POST["mandatory_type_1"]);
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$sample_excel = new PHPExcel();

	// 속성 정의
	$sample_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("accounts plan price List")
								 ->setSubject("accounts plan price List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("accounts plan price List");
	$col = 'A';

	foreach($sample_excel_info as $key => $value){

		if($value[validation]=='true'){
			$sample_excel->getActiveSheet(0)->getStyle($col . "1")->getFont()->getColor()->setARGB("FFFF0000");
		}

		if($value[code]=="mandatory_type"){
			$mandatory_type = $_POST["mandatory_type_1"].$mandatory_type_2.$mandatory_type_3;
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $mandatory_type);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}elseif($value[code]=="category"){
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $value[sample]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getStyle($col . "2")->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}elseif($value[code]=="admin"){
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $admininfo[company_id]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}elseif($value[code]=="product_type"){
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $product_type);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}else{
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $value[sample]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}
	}

	$sample_excel->getActiveSheet(0)->getStyle('A' . "4")->getFont()->getColor()->setARGB("FFFF0000");
	$sample_excel->getActiveSheet(0)->setCellValue('A' . "4",'빨간색 글씨로 되어있는 항목은 필수 입니다. !!');



	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="sample_excel.xls"');
	header('Cache-Control: max-age=0');

	$objWriter = PHPExcel_IOFactory::createWriter($sample_excel, 'Excel5');
	$objWriter->save('php://output');
	exit;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 상품등록
/// 작성 : 신훈식 ( 2013.04.29 )
/// 내용 : 엑셀 업로드된 데이타를 shared memory 에 저장후 한개씩 처리해서 결과를 반영해 나가는 구조로 바꾼다.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if($act == "new_excel_input"){

	include("../include/lib/pclzip.lib.php");

	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');


		if ($excel_file_size > 0){
			copy($excel_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);
		}

		if ($goods_img_file_size > 0){
			copy($goods_img_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".$goods_img_file_name);

			//PclZip 객체를 생성합니다.
			//$객체 = new PclZip("생성할 압축파일 이름");
			$zipfile = new PclZip($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".$goods_img_file_name);
			//zip파일에 압축할 파일이나 디렉토리의 경로를 지정하여 압축을 실행합니다.
			//$객체->create("파일이나 디렉토리 경로");
			//echo $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".str_replace(".zip","",$goods_img_file_name);
			//$create = $zipfile->create($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".str_replace(".zip","",$goods_img_file_name));

			$extract = $zipfile->extract(PCLZIP_OPT_PATH, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".str_replace(".zip","",$goods_img_file_name)); 
			//exit;

		}

		$objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);

		$shift_num = 0;

		// 데이터는 3줄부터 시작, 1, 2줄은 제목+코드명

		$rownum = 2;


		//$columnVar = $objPHPExcel->setActiveSheetIndex(0)->getCell('A' . ($rownum))->getValue();

		include("../logstory/class/sharedmemory.class");
		$shmop = new Shared("upload_excel_data");
		$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/_shared/";
		//echo $shmop->filepath;
		$shmop->SetFilePath();
		$upload_excel_data = $shmop->getObjectForKey("upload_excel_data");

		$col = 'A';
		for($i=0;$i < count($goods_basic_sample)-1;$i++){
			$col++;
		}

		$mandatory_type=$objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
		//$goods_basic_sample
		$selected_mandatory_info = $goods_mandatory_info[substr($mandatory_type,0,1)][substr($mandatory_type,1,1)][substr($mandatory_type,2,1)];

		if(is_array($selected_mandatory_info)){
			$sample_excel_info = array_merge($goods_basic_sample,$selected_mandatory_info);
		}else{
			$sample_excel_info = $goods_basic_sample;
		}

		$col = 'A';

		foreach($sample_excel_info as $key => $value){
			$upload_excel_data[session_id()][$rownum-2][$value[code]] = $value[title];//$objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();

			$col++;
		}




		$z=0;

		while (($objPHPExcel->getActiveSheet()->getCell('C' . $rownum)->getValue() != "") && ($i < 11000)) {
			//$pcode = $objPHPExcel->getActiveSheet()->getCell('A' . $rownum)->getValue();
			$col = 'A';
			foreach($sample_excel_info as $key => $value){
				$upload_excel_data[session_id()][$rownum-1][$value[code]] = $objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();

				$col++;
			}

			$upload_excel_data[session_id()][$rownum-1][p_no] = $z;

			$z++;
			$rownum++;
		}


		//print_r($upload_excel_data);
		//exit;


		//$upload_excel_data[md5($_SERVER["REMOTE_ADDR"])] = array('ipaddr' => $_SERVER["REMOTE_ADDR"], 'user_id' => $this->USERID,  'user_code' => $this->UCODE, 'page_id' => $page_id, 'before_visit_date' => date("Y-m-d H:i:s",$this->BEFORE_LAST_CON_TIME), 'recent_visit_date' => date("Y-m-d H:i:s"));
		/*
		if(count($upload_excel_data) > 100){
			foreach ($upload_excel_data as $key => $row) {
				if((time()- strtotime($row['recent_visit_date'])) > 600){
			  	unset($upload_excel_data[$key]);
			  }
			}
		}
		*/

		$shmop->setObjectForKey($upload_excel_data, "upload_excel_data") ;
		echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./product_input_excel.php?up_mode=new_upload'</script>";
}


if($act == "single_goods_reg"){

	include("../logstory/class/sharedmemory.class");
	//auth(8);
	$shmop = new Shared("upload_excel_data");
	//	$shmop->clear();
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$_SESSION["admininfo"]["mall_data_root"]."/_shared/";
	$shmop->SetFilePath();
	$upload_excel_data = $shmop->getObjectForKey("upload_excel_data");

	//$db->query("SELECT * FROM ".TBL_SHOP_PRODUCT." where pcode = '".$pcode."' ");
	

	$act = "insert";


	$select_excel_goods_infos = filter_by_value($upload_excel_data[session_id()], 'p_no', $p_no);

	//print_r($select_excel_goods_infos);
	foreach($select_excel_goods_infos as $key => $value){

		$insert_yn=true;

		foreach($value as $_key => $_value){
			if($_key=='mandatory_type'){
				$$_key = $_value;
			}
			//echo $_key."=".$_value."<br>";
		}

		if($mandatory_type){
			$mandatory_type_1 = substr($mandatory_type,0,1);
			$mandatory_type_2 = substr($mandatory_type,1,1);
			$mandatory_type_3 = substr($mandatory_type,2,1);

			$selected_mandatory_info = $goods_mandatory_info[$mandatory_type_1][$mandatory_type_2][$mandatory_type_3];

			$i=0;
			//상품고시
			foreach($value as $_key => $_value){
				if($_key!='mandatory_type'){
					$$_key = $_value;
				}

				foreach($selected_mandatory_info as $__key => $__value){
					if($_key ==$__value[code]){
						$mandatory_info[$i][code]=$__value[code];
						$mandatory_info[$i][pmi_title]=$__value[title];
						$mandatory_info[$i][pmi_desc]=$_value;
						$i++;
					}
				}
			}
		}else{
			$insert_yn=false;
			$result_massage = "<span class='red'>상품고시분류타입이 없습니다.</span>";
		}




		if(!$product_type && $product_type!='0'){
			$insert_yn=false;
			$result_massage = "<span class='red'>상품구분이 없습니다.</span>";
		}

		if(!$admin){
			$insert_yn=false;
			$result_massage = "<span class='red'>입점업체 코드가 없습니다.</span>";
		}

		if(!$category){
			$insert_yn=false;
			$result_massage = "<span class='red'>카테고리가 없습니다.</span>";
		}else{
			$cid=$category;
			unset($category);
			$category[0]=$cid;
		}
		//$result_massage = $category."--";

		if(!$pname){
			$insert_yn=false;
			$result_massage = "<span class='red'>제품명이 없습니다.</span>";
		}

		if(!$orgin){
			$insert_yn=false;
			$result_massage = "<span class='red'>원산지가 없습니다.</span>";
		}

		if(!$brand){
			$insert_yn=false;
			$result_massage = "<span class='red'>브랜드가 없습니다.</span>";
		}

		if(!$company){
			$insert_yn=false;
			$result_massage = "<span class='red'>제조사가 없습니다.</span>";
		}

		if(!$delivery_date){
			$insert_yn=false;
			$result_massage = "<span class='red'>출고기간이 없습니다.</span>";
		}

		if($product_type==1 || $product_type==2){
			if(!$local_pirce){
				$insert_yn=false;
				$result_massage = "<span class='red'>상품현지가가 없습니다.</span>";
			}

			if(!$exchange_rate){
				$insert_yn=false;
				$result_massage = "<span class='red'>환율이 없습니다.</span>";
			}
		}
	
		$db->query("SELECT * FROM ".TBL_COMMON_SELLER_DELIVERY." where company_id = '".$admin."' ");
		$db->fetch();
		$commission = $db->dt[commission];
		$coprice = $sellprice*(100-$commission)/100;
		
		if(!$coprice){
			$insert_yn=false;
			$result_massage = "<span class='red'>(정상)매입가가 없습니다.</span>";
		}

		if(!$listprice){
			$insert_yn=false;
			$result_massage = "<span class='red'>(정상)판매가가 없습니다.</span>";
		}

		if(!$option_name){
			$insert_yn=false;
			$result_massage = "<span class='red'>옵션명이 없습니다.</span>";
		}else{
			$options[0][option_name]=$option_name;
		}

	
		//옵션
		if($options_div){

			$option_div = explode(',',$options_div);
			$i=0;
			foreach($option_div as $div){
				$div_array=explode('|',$div);
				$options[0][details][$i][option_div] = $div_array[0];
				$i++;
			}

		}else{
			$insert_yn=false;
			$result_massage = "<span class='red'>옵션구분값이 없습니다.</span>";
		}

		///////DEFAULT///////
		if(!empty($local_pirce)&&!empty($local_tax)){
			$local_tax_rate = ($local_tax / $local_pirce)*100;
		}else{
			$local_tax_rate =0;
		}

		$orgin_price = $local_pirce + $local_distribution_pirce + $local_tax;
		$duty =  (( $orgin_price * $exchange_rate ) + $air_shipping ) * $duty_rate / 100;
		$surtax = (( $orgin_price * $exchange_rate ) + $air_shipping ) + ($duty * 0.1);
		$total_duty = $duty + $surtax;

		$commission = round(100 - ($coprice/$listprice * 100));

		if($product_type==1 || $product_type==2){
			$sellcommission = round(100 - ($coprice /$sellprice * 100));
		}else{
			$sellcommission = round(100 - ($sellcoprice /$sellprice * 100));
		}

		if(strlen($mandatory_type_1) < 2)		$mandatory_type_1 = '0'.$mandatory_type_1;

		$state = "6";//등록신청중
		$disp = "0";//노출안함

		if(strlen($category[0]) < 15)		$category[0] = str_repeat('0',15-strlen($category[0])).$category[0];
		$basic = $category[0];
		$options[0]["option_use"]=1;
		$options[0]["option_kind"]='s';
		$options[0]["type"]=9;
		$bs_act="1";
		$delivery_policy="1";
		$one_commissio="Y";
		///////DEFAULT///////

		if($insert_yn){
			if($upload_excel_data[session_id()][$key][status]!='C'){
				include "goods_input.act.php";

				//이미지
				if($mainimg){
					if ($mainimg != "") {
						Batch_Images_Processing($mainimg, $pid);
					}
				}

				$upload_excel_data[session_id()][$key][status] = "C";
				$upload_excel_data[session_id()][$key][status_message] = "등록완료";
				echo "<span class='blue'>등록완료</span>";
			}else{
				echo "<span class='blue'>PASS</span>";
			}
		}else{
			echo $result_massage;
		}
	}

	$shmop->setObjectForKey($upload_excel_data, "upload_excel_data") ;

}

if ($act == "excel_input"){

	//error_reporting(E_ALL);
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');


	session_start();


		//post 값으로 넘어온값 저장
		$post_company_id = $company_id ;
		$post_brand = $brand ;

		if ($excel_file_size > 0){
			copy($excel_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);
		}

		$objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);

		$shift_num = 0;

		// 데이터는 3줄부터 시작, 1, 2줄은 제목+코드명

		$rownum = 3;


		$columnVar = $objPHPExcel->setActiveSheetIndex(0)->getCell('A' . ($rownum))->getValue();


		while (($objPHPExcel->getActiveSheet()->getCell('C' . $rownum)->getValue() != "") && ($i < 11000)) {
			//////////////////////////// 데이터를 가져옴 //////////////////////////////////
			$pcode = $objPHPExcel->getActiveSheet()->getCell('A' . $rownum)->getValue();
			$admin = $objPHPExcel->getActiveSheet()->getCell('B' . $rownum)->getValue();
			$pname = $objPHPExcel->getActiveSheet()->getCell('C' . $rownum)->getValue();
			$paper_pname = $objPHPExcel->getActiveSheet()->getCell('D' . $rownum)->getValue();
			$brand_name = $objPHPExcel->getActiveSheet()->getCell('E' . $rownum)->getValue();
			$brand = $objPHPExcel->getActiveSheet()->getCell('F' . $rownum)->getValue();
			$company = $objPHPExcel->getActiveSheet()->getCell('G' . $rownum)->getValue();
			//$make_country = $objPHPExcel->getActiveSheet()->getCell('G' . $rownum)->getValue();
			$shotinfo = $objPHPExcel->getActiveSheet()->getCell('H' . $rownum)->getValue();
			$search_keyword = $objPHPExcel->getActiveSheet()->getCell('I' . $rownum)->getValue();
			$category_str = $objPHPExcel->getActiveSheet()->getCell('J' . $rownum)->getValue();
			$basicinfo = $objPHPExcel->getActiveSheet()->getCell('K' . $rownum)->getValue();
			$delivery_company = $objPHPExcel->getActiveSheet()->getCell('L' . $rownum)->getValue();
			$delivery_price1 = $objPHPExcel->getActiveSheet()->getCell('M' . $rownum)->getValue();
			$delivery_price2 = $objPHPExcel->getActiveSheet()->getCell('N' . $rownum)->getValue();
			$delivery_product_policy = $objPHPExcel->getActiveSheet()->getCell('O' . $rownum)->getValue();
			$option_name1 = $objPHPExcel->getActiveSheet()->getCell('P' . $rownum)->getValue();
			$option_item1 = $objPHPExcel->getActiveSheet()->getCell('Q' . $rownum)->getValue();
			$option_name2 = $objPHPExcel->getActiveSheet()->getCell('R' . $rownum)->getValue();
			$option_item2 = $objPHPExcel->getActiveSheet()->getCell('S' . $rownum)->getValue();
			$option_name3 = $objPHPExcel->getActiveSheet()->getCell('T' . $rownum)->getValue();
			$option_item3 = $objPHPExcel->getActiveSheet()->getCell('U' . $rownum)->getValue();

			$coprice = $objPHPExcel->getActiveSheet()->getCell('V' . $rownum)->getValue();
			$wholesale_price = $objPHPExcel->getActiveSheet()->getCell('W' . $rownum)->getValue();
			$listprice = $objPHPExcel->getActiveSheet()->getCell('X' . $rownum)->getValue();
			$sellprice = $objPHPExcel->getActiveSheet()->getCell('Y' . $rownum)->getValue();
if($_SERVER["HTTP_HOST"] == "academyprice.s2.mallstory.com"){
			$ap_price = $objPHPExcel->getActiveSheet()->getCell('Z' . $rownum)->getValue();
			$stock = $objPHPExcel->getActiveSheet()->getCell('AA' . $rownum)->getValue();
			$safestock = $objPHPExcel->getActiveSheet()->getCell('AB' . $rownum)->getValue();
			$surtax_yorn = $objPHPExcel->getActiveSheet()->getCell('AC' . $rownum)->getValue();
			$reserve_yn = $objPHPExcel->getActiveSheet()->getCell('AD' . $rownum)->getValue();
			$reserve = $objPHPExcel->getActiveSheet()->getCell('AE' . $rownum)->getValue();
			$imagePath = $objPHPExcel->getActiveSheet()->getCell('AF' . $rownum)->getValue();
			$DownLoadimagePath = $objPHPExcel->getActiveSheet()->getCell('AG' . $rownum)->getValue();
			$DownLoadDescimagePath = $objPHPExcel->getActiveSheet()->getCell('AH' . $rownum)->getValue();
}else{
			$stock = $objPHPExcel->getActiveSheet()->getCell('Z' . $rownum)->getValue();
			$safestock = $objPHPExcel->getActiveSheet()->getCell('AA' . $rownum)->getValue();
			$surtax_yorn = $objPHPExcel->getActiveSheet()->getCell('AB' . $rownum)->getValue();
			$reserve_yn = $objPHPExcel->getActiveSheet()->getCell('AC' . $rownum)->getValue();
			$reserve = $objPHPExcel->getActiveSheet()->getCell('AD' . $rownum)->getValue();
			$imagePath = $objPHPExcel->getActiveSheet()->getCell('AE' . $rownum)->getValue();
			$DownLoadimagePath = $objPHPExcel->getActiveSheet()->getCell('AF' . $rownum)->getValue();
			$DownLoadDescimagePath = $objPHPExcel->getActiveSheet()->getCell('AG' . $rownum)->getValue();
}
			$pimage = $imagePath;
			//$pimage = $objPHPExcel->getActiveSheet()->getCell('AF' . $rownum)->getValue();
			//////////////////////////// 케이스별로 값을 세팅함. //////////////////////////////////
			// pname 이 존재 하지 않으면 값을 세팅 안한다는 말씀.

			$pcode =trim($pcode);
			$admin = trim($admin);
			$pname = str_replace("'","\\'",trim($pname));
			$paper_pname = str_replace("'","\\'",trim($paper_pname));
			$brand_name = str_replace("'","\\'",trim($brand_name));
			$brand = str_replace("'","\\'",trim($brand));
			//$pimage = iconv('CP949','UTF-8',$data->sheets[0]['cells'][$i][6+$shift_num]);
			$company = str_replace("'","\\'",trim($company));
			$shotinfo = str_replace("'","\\'",trim($shotinfo));
			$search_keyword = trim($search_keyword);
			$category_str = trim($category_str);
			$basicinfo = trim($basicinfo);
			$delivery_company = "WE";//trim($delivery_company);
			$delivery_price1 = trim($delivery_price1);
			$delivery_price2 = trim($delivery_price2);
			$delivery_product_policy = trim($delivery_product_policy);
			$option_name1 = trim($option_name1);
			$option_item1 = trim($option_item1);
			$option_name2 = trim($option_name2);
			$option_item2 = trim($option_item2);
			$option_name3 = trim($option_name3);
			$option_item3 = trim($option_item3);


			$coprice = trim($coprice);
			$listprice = trim($listprice);
			$sellprice = trim($sellprice);
			$ap_price = trim($ap_price);

			$stock = trim($stock);
			$safestock = trim($safestock);
			$surtax_yorn = trim($surtax_yorn);
			$reserve_yn = trim($reserve_yn);
			$reserve = trim($reserve);
			$pimage = trim($pimage);

			if($pname){
				/*
				switch ($surtax_yorn)
				{
					case "면세":
						$surtax_yorn = "Y";
						break;
					case "과세":
					case "면세아님":
						$surtax_yorn = "N";
						break;
					default:
						$surtax_yorn = "";
						break;
				}
				*/
				switch ($delivery_company)
				{
					case "본사배송":
						$delivery_company = "WE";
						break;
					case "업체배송":
						$delivery_company = "MI";
						break;
					default:
						$delivery_company = "WE";
						break;
				}

				if($delivery_price1 || $delivery_price2){
					switch ($delivery_product_policy)
					{
						case "무료배송":
							$delivery_product_policy = "3";
							$delivery_price = $delivery_price2;
							break;
						case "유료배송":
							$delivery_product_policy = "1";
							$delivery_price = $delivery_price1;
							break;

					}
					$delivery_policy = "2";
				} else {
					$delivery_policy = "1";
				}

				switch ($delivery_method)
				{
					case "택배":
						$delivery_method = "1";
						break;
					case "소포/등기":
						$delivery_method = "2";
						break;
					case "퀵서비스":
						$delivery_method = "3";
						break;
					case "화물배달":
						$delivery_method = "4";
						break;
					case "일반우편":
						$delivery_method = "5";
						break;
					case "방문수령/직접배송":
						$delivery_method = "6";
						break;
					default:
						$delivery_method = "";
						break;
				}

				switch ($pack_method)
				{
					case "일반포장":
						$pack_method = "A";
						break;
					case "냉장포장":
						$pack_method = "B";
						break;
					case "냉동포장":
						$pack_method = "C";
						break;
					default:
						$pack_method = "";
						break;

				}

				/////////////////////////////////////////////////////////////////////
				//                              트랜잭션 시작
				/////////////////////////////////////////////////////////////////////
				//$result = true; // 쿼리 성공여부를 나타내는 boolean

				//$result = $db->query("SET AUTOCOMMIT=0");
				//$result = $db->query("BEGIN");

				// 업데이트에 조건절이 없음????
				//$db->query("update ".TBL_SHOP_PRODUCT." set vieworder = vieworder + 1  ");
				//$db->fetch();

				$db->query("SELECT max(vieworder)+1 as max_vieworder FROM ".TBL_SHOP_PRODUCT." ");
				$db->fetch();
				$vieworder = $db->dt[max_vieworder];

				//$vieworder = 1;

				if($post_company_id !=""){ //선택한 입점업체를 우선적으로
					$admin = $post_company_id;
				}

				if($admininfo[admin_level] == 9){ // 레벨 9는 운영자
					$state = "1";
					$disp = "0";
					if($mode == "copy"){
						if($admin == "") {
							$company_id = $admininfo[company_id]; // 세션에 있는 정보
						} else {
							$company_id = $admin;
						}
					}else{
						//$company_id = $admininfo[company_id]; // 세션에 있는 정보
						if($admin == "") {//mode 값이 넘어오지 않음 kbk 12/04/23
							$company_id = $admininfo[company_id]; // 세션에 있는 정보
						} else {
							$company_id = $admin;
						}
					}
				}else{
					$state = "6";
					$disp = "0";
					$company_id = $admininfo[company_id]; // 입점업체 본인이 등록하는 경우
				}

				if($post_brand !=""){ //선택한 브랜드를 우선적으로
					$brand = $post_brand;
				}

				if($brand_name != ""){
					$brand_name = $brand_name;
				}else{
					$sql = "select brand_name from shop_brand where b_ix = '$brand'";
					$db->query($sql);
					$db->fetch();
					$brand_name = $db->dt[brand_name];
				}

				/*if($cid){
					$reg_category = "Y";
				}else{
					$reg_category = "N";
				}*/
				$reg_category = "N";

				//if(!$stock)  $stock = "9999";
				//if(!$safestock)  $safestock = "5";  jk 수정 입력안했을때 왜 강제로 값을 넣는지 알 수 없슴

				if($stock){//재고 값이 있을때 간편재고 사용함 상태로 변경 JK 130328
					$stock_use_yn = "Q";
				}else{
					$stock_use_yn = "N";
				}

				/*if(trim($admin) == "") {
					$admin = "3444fde7c7d641abc19d5a26f35a12cc";
				}*/
				if($_SERVER["HTTP_HOST"] == "academyprice.s2.mallstory.com"){
				$sql = "INSERT INTO ".TBL_SHOP_PRODUCT." (id,  pname, paper_pname, pcode, brand,brand_name, company, shotinfo,   listprice,sellprice,ap_price,  coprice,
						reserve_yn, reserve,  basicinfo,   state, disp, movie,
						vieworder, admin,stock,stock_use_yn,safestock,search_keyword,reg_category,
						surtax_yorn, delivery_policy, delivery_product_policy, delivery_price,
						one_commission,commission,etc2, regdate,
						 delivery_company, product_type, sns_btn,regdate_desc)
						values('', '".strip_tags($pname)."', '".strip_tags($paper_pname)."', '$pcode', '$brand','$brand_name','$company', '$shotinfo', '$listprice','$sellprice','$ap_price', '$coprice','$reserve_yn', '$reserve',  '$basicinfo',
						  $state, 1, '$movie', '$vieworder', '$company_id',
						'$stock','$stock_use_yn','$safestock','$search_keyword','$reg_category',
						'$surtax_yorn', '$delivery_policy', '$delivery_product_policy', '$delivery_price',
						'N','$commission','$etc2',NOW(),
						'$delivery_company', '0', 'N;',unix_timestamp(NOW())*-1) ";//one_commission 값을 입력받지 않음 그래서 기본으로 N 값 등록되게 함 kbk 12/06/14
				}else{
				$sql = "INSERT INTO ".TBL_SHOP_PRODUCT." (id,  pname, paper_pname, pcode, brand,brand_name, company, shotinfo,   listprice,sellprice,  coprice,
						reserve_yn, reserve,  basicinfo,   state, disp, movie,
						vieworder, admin,stock,stock_use_yn,safestock,search_keyword,reg_category,
						surtax_yorn, delivery_policy, delivery_product_policy, delivery_price,
						one_commission,commission,etc2, regdate,
						 delivery_company, product_type, sns_btn,regdate_desc)
						values('', '".strip_tags($pname)."', '".strip_tags($paper_pname)."', '$pcode', '$brand','$brand_name','$company', '$shotinfo', '$listprice','$sellprice', '$coprice','$reserve_yn', '$reserve',  '$basicinfo',
						  $state, 1, '$movie', '$vieworder', '$company_id',
						'$stock','$stock_use_yn','$safestock','$search_keyword','$reg_category',
						'$surtax_yorn', '$delivery_policy', '$delivery_product_policy', '$delivery_price',
						'N','$commission','$etc2',NOW(),
						'$delivery_company', '0', 'N;',unix_timestamp(NOW())*-1) ";//one_commission 값을 입력받지 않음 그래서 기본으로 N 값 등록되게 함 kbk 12/06/14
				}
				$sql = str_replace($removestring, " ", $sql);
				$db->sequences = "SHOP_GOODS_SEQ";

				$db->query($sql);
				error_log("aaa  " . $sql);

				if($db->dbms_type == "oracle"){
					$pid = $db->last_insert_id;
				}else{
					$db->query("SELECT id FROM ".TBL_SHOP_PRODUCT." WHERE id=LAST_INSERT_ID()");
					$db->fetch();
					$pid = $db->dt[id];
				}

				//if($pimage != ""){
				//	ExcelImageCopy($pimage, $pid);
				//}
                //상품 상세이미지 복사 안하도록 주석처리(문대리님 요청) 12.07.03 bgh
				//$basicinfo = basicinfoCopy($basicinfo, $pid);

				$db->query("UPDATE ".TBL_SHOP_PRODUCT." SET basicinfo = '$basicinfo' WHERE id='$pid'");

				if($option_name1 != ""){
					$db->sequences = "SHOP_GOODS_OPTIONS_SEQ";
					$db->query("insert into ".TBL_SHOP_PRODUCT_OPTIONS."(opn_ix,pid,option_name,option_kind,option_use,regdate) values('','$pid','$option_name1','s','1',NOW())	  ");

					if($db->dbms_type == "oracle"){
						$opn_ix = $db->last_insert_id;
					}else{
						$db->query("SELECT opn_ix FROM ".TBL_SHOP_PRODUCT_OPTIONS." WHERE opn_ix=LAST_INSERT_ID()");
						$db->fetch();
						$opn_ix = $db->dt[opn_ix];
					}
					$option_item1 = str_replace("'","",$option_item1);
					$option_item1s = explode(",",$option_item1);

					for($j=0;$j<count($option_item1s);$j++){
						$sql = "INSERT INTO ".TBL_SHOP_PRODUCT_OPTIONS_DETAIL." (id, pid, opn_ix, option_div,option_price,option_etc1) ";
						$sql = $sql." values ('','$pid','$opn_ix','".trim($option_item1s[$j])."','','') ";
						$db->sequences = "SHOP_GOODS_OPTIONS_DT_SEQ";
						$db->query($sql);
					}
				}

				if($option_name2 != ""){
					$db->sequences = "SHOP_GOODS_OPTIONS_SEQ";
					$db->query("insert into ".TBL_SHOP_PRODUCT_OPTIONS."(opn_ix,pid,option_name,option_kind,option_use,regdate) values('','$pid','$option_name2','s','1',NOW())	  ");

					if($db->dbms_type == "oracle"){
						$opn_ix = $db->last_insert_id;
					}else{
						$db->query("SELECT opn_ix FROM ".TBL_SHOP_PRODUCT_OPTIONS." WHERE opn_ix=LAST_INSERT_ID()");
						$db->fetch();
						$opn_ix = $db->dt[opn_ix];
					}
					$option_item2 = str_replace("'","",$option_item2);
					$option_item2s = explode(",",$option_item2);

					for($j=0;$j<count($option_item2s);$j++){
						$sql = "INSERT INTO ".TBL_SHOP_PRODUCT_OPTIONS_DETAIL." (id, pid, opn_ix, option_div,option_price,option_etc1) ";
						$sql = $sql." values ('','$pid','$opn_ix','".trim($option_item2s[$j])."','','') ";
						$db->sequences = "SHOP_GOODS_OPTIONS_DT_SEQ";
						$db->query($sql);
					}
				}

				if($option_name3 != ""){
					$db->sequences = "SHOP_GOODS_OPTIONS_SEQ";
					$db->query("insert into ".TBL_SHOP_PRODUCT_OPTIONS."(opn_ix,pid,option_name,option_kind,option_use,regdate) values('','$pid','$option_name3','s','1',NOW())	  ");

					if($db->dbms_type == "oracle"){
						$opn_ix = $db->last_insert_id;
					}else{
						$db->query("SELECT opn_ix FROM ".TBL_SHOP_PRODUCT_OPTIONS." WHERE opn_ix=LAST_INSERT_ID()");
						$db->fetch();
						$opn_ix = $db->dt[opn_ix];
					}

					$option_item3 = str_replace("'","",$option_item3);
					$option_item3s = explode(",",$option_item3);

					for($j=0;$j<count($option_item3s);$j++){
						$sql = "INSERT INTO ".TBL_SHOP_PRODUCT_OPTIONS_DETAIL." (id, pid, opn_ix, option_div,option_price,option_etc1) ";
						$sql = $sql." values ('','$pid','$opn_ix','".trim($option_item3s[$j])."','','') ";
						$db->sequences = "SHOP_GOODS_OPTIONS_DT_SEQ";
						$db->query($sql);
					}
				}

				$category = split(">",$category_str);

				if($category[0] != ""){
					$sql = "SELECT cname, cid FROM ".TBL_SHOP_CATEGORY_INFO." WHERE cname = '".trim($category[0])."' ";
					$db->query($sql);
					$db->fetch();
					if($db->total){
						$cid = $db->dt[cid];
						$parent_cid = $db->dt[cid];
					}else{
						$cid = $_POST["cid"];
					}
					//$reg_category = "Y";
					if($category[1]){
						$sql = "SELECT cname, cid FROM ".TBL_SHOP_CATEGORY_INFO." WHERE cname = '".trim($category[1])."' and cid LIKE '".substr($parent_cid,0,3)."%' ";
						$db->query($sql);
						$db->fetch();
						if($db->total){
							$cid = $db->dt[cid];
							$parent_cid = $db->dt[cid];
						}
						if($category[2]){
							$sql = "SELECT cname, cid FROM ".TBL_SHOP_CATEGORY_INFO." WHERE cname = '".trim($category[2])."' and cid LIKE '".substr($parent_cid,0,6)."%' ";
							$db->query($sql);
							$db->fetch();
							if($db->total){
								$cid = $db->dt[cid];
								$parent_cid = $db->dt[cid];
							}
							if($category[3]){
								$sql = "SELECT cname, cid FROM ".TBL_SHOP_CATEGORY_INFO." WHERE cname = '".trim($category[3])."' and cid LIKE '".substr($parent_cid,0,9)."%' ";
								$db->query($sql);
								$db->fetch();
								if($db->total){
									$cid = $db->dt[cid];
								}
							}
						}
					}
				} else	{
					$cid = $_POST["cid"];
				}

				if($cid != ""){
					$db->sequences = "SHOP_GOODS_LINK_SEQ";
					$db->query("insert into ".TBL_SHOP_PRODUCT_RELATION." (rid, cid, pid ,disp ,basic, insert_yn, regdate) values ('','$cid', '$pid','1','1','Y',NOW())");
					$db->query("UPDATE ".TBL_SHOP_PRODUCT." SET reg_category='Y' WHERE id='".$pid."' ");
				}

				/////////////////////////////////
				if ($pimage != "") {
					Batch_Images_Processing($pimage, $pid);
				}

				$basedir = $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/product/";
				$targetDirectory = $basedir . UploadDirText($basedir, $pid, 'Y') . '/';

				/////////////////////////////////
				if ($DownLoadimagePath != "" || $DownLoadDescimagePath != ""){
					$path = $targetDirectory."/download/";

					if(!is_dir($path)){
						mkdir($path, 0777);
						chmod($path,0777);
					}

					$path = $targetDirectory."/download/".md5("FORBIZ".$pid)."/";

					if(!is_dir($path)){
						mkdir($path, 0777);
						chmod($path,0777);
					}
				}


				if ($DownLoadimagePath != "")
				{
					$download_image_name = returnFileName($DownLoadimagePath);
					//echo $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/BatchUploadImages/".$DownLoadimagePath."<br><br>";
					//echo $targetDirectory."/download/".md5("FORBIZ".$pid)."/".$download_image_name."<br><br>";

					copy($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/BatchUploadImages/".$DownLoadimagePath, $targetDirectory."/download/".md5("FORBIZ".$pid)."/".$download_image_name);
					unlink($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/BatchUploadImages/".$DownLoadimagePath);
					$download_img_update = " , download_img = '".$download_image_name."' ";
				}

				if ($DownLoadDescimagePath != "")
				{
					$download_desc_name = returnFileName($DownLoadDescimagePath);
					copy($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/BatchUploadImages/".$DownLoadDescimagePath, $targetDirectory."/download/".md5("FORBIZ".$pid)."/".$download_desc_name);
					unlink($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/BatchUploadImages/".$DownLoadDescimagePath);
					$download_desc_update = " , download_desc = '".$download_desc_name."' ";
				}
				$db->query("UPDATE ".TBL_SHOP_PRODUCT." SET editdate=NOW() $download_img_update $download_desc_update WHERE id='".$pid."' ");

				$rownum++;
			}
		}

		// 다 쓴 파일 삭제
		if (file_exists($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name)){
			unlink($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);
		}
		//set_time_limit(300);
		//ini_set('memory_limit', '128M');
		echo "<script language='javascript' src='../js/message.js.php'></script><script>show_alert('상품등록이 완료되었습니다.');document.location.href='./product_input_excel.php?cid=$cid&depth=$depth&view=innerview'</script>";

}



	function Batch_Images_Processing($xlImageFileName, $bpid)
	{
		global $admin_config;

			syslog(LOG_INFO, '$admin_config[mall_data_root]\r\n');

			$uploadDirectory = UploadDirText($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/product", $bpid, 'Y');
			$sourceDirectory = $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/BatchUploadImages/";
			$sourceImageFileFullPath = $sourceDirectory . $xlImageFileName;

			ExcelImageCopy($sourceImageFileFullPath, $bpid);
	}


	function basicinfoCopy($basicinfo, $INSERT_PRODUCT_ID){
		global $admin_config, $DOCUMENT_ROOT, $HTTP_HOST;
		$data_text_convert = $basicinfo;
		$data_text_convert = str_replace("\\","",$data_text_convert);
		$data_text_convert = str_replace("<img","<IMG",$data_text_convert);

		preg_match_all("|<IMG .*src=\"(.*)\".*>|U",$data_text_convert,$out, PREG_PATTERN_ORDER);

		$path = $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product_detail/".$INSERT_PRODUCT_ID."/";

		if(substr_count($data_text_convert,"<IMG") > 0){
			if(!is_dir($path)){
				mkdir($path, 0777);
				chmod($path,0777);
			}else{
				chmod($path,0777);
			}
		}

		for($i=0;$i < count($out);$i++){
			for($j=0;$j < count($out[$i]);$j++){

				$img = returnImagePath($out[$i][$j]);
				$img = ClearText($img);
				try{
					if($img){
						if(substr_count($img,$admin_config[mall_data_root]."/images/product_detail/$INSERT_PRODUCT_ID/") == 0){// 이미지 URL 이 이벤트 관련 폴더에 있지 않으면 ...
							if(substr_count($img,"$HTTP_HOST")>0){
								$local_img_path = str_replace("http://$HTTP_HOST",$_SERVER["DOCUMENT_ROOT"]."",$img);

								copy($local_img_path,$_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product_detail/$INSERT_PRODUCT_ID/".returnFileName($img));
								if(substr_count($img,$admin_config[mall_data_root]."/images/upfile/") > 0){
									unlink($local_img_path);
								}

								$basicinfo = str_replace($img,$admin_config[mall_data_root]."/images/product_detail/$INSERT_PRODUCT_ID/".returnFileName($img),$basicinfo);	 // 업로드된 파일들이 URL 에 관계 없이 보일수 있도록 URL 을  / 로 치환
							}else{
								if(substr_count($img,$DOCUMENT_ROOT)){
									if(copy($DOCUMENT_ROOT.$img,$_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product_detail/$INSERT_PRODUCT_ID/".returnFileName($DOCUMENT_ROOT.$img))){
										$basicinfo = str_replace($img,$admin_config[mall_data_root]."/images/product_detail/$INSERT_PRODUCT_ID/".returnFileName($img),$basicinfo);	 // 업로드된 파일들이 URL 에 관계 없이 보일수 있도록 URL 을  / 로 치환
									}
								}else{

									if(copy($img,$_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product_detail/$INSERT_PRODUCT_ID/".returnFileName($img))){
										$basicinfo = str_replace($img,$admin_config[mall_data_root]."/images/product_detail/$INSERT_PRODUCT_ID/".returnFileName($img),$basicinfo);	 // 업로드된 파일들이 URL 에 관계 없이 보일수 있도록 URL 을  / 로 치환
									}
								}
							}
						}
					}

				}catch(Exception $e){
				    // 에러처리 구문
				    //exit($e->getMessage());
				}

			}
		}

		$basicinfo = str_replace("http://$HTTP_HOST","",$basicinfo);

		return $basicinfo;
	}


	function ExcelImageCopy($image_path, $pid){
		global $admin_config, $DOCUMENT_ROOT,$image_db;

		$basedir = $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product/";
		$targetDirectory = $basedir . UploadDirText($basedir, $pid, 'Y') . '/';

		if(!file_exists($image_path)) {
			return ;
		}
		$image_info = getimagesize ($image_path);
		$image_type = substr($image_info['mime'],-3);

		//echo($image_path);
		//define_syslog_variables();
		//openlog("phplog", LOG_PID , LOG_LOCAL0);

		$image_db->query("select width,height from shop_image_resizeinfo order by idx");//kbk 11/12/15
		$image_info2 = $image_db->fetchall();
		$basic_img_src = $targetDirectory . "/basic_".$pid.".gif";
		copy($image_path, $basic_img_src);

		if(file_exists($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/watermark/watermark.png")) {
			require_once "../lib/class.upload.php";


			$s_water_handle = new Upload($targetDirectory."/basic_".$pid.".gif");
			$s_water_result = WaterMarkProcess2($s_water_handle, $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/", $targetDirectory);

			$basic_img_src = $targetDirectory."/basic_watermark_".$pid.".gif";
			copy($targetDirectory."/watermark/basic_".$pid.".gif",$basic_img_src);
			chmod($targetDirectory."/basic_".$pid.".gif", 0777);
			//@copy($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/watermark".$uploaddir."/basic_".$pid.".gif",$_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/product".$uploaddir."/basic_".$pid.".gif");
			//@chmod($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/product".$uploaddir."/basic_".$pid.".gif", 0777);

			//echo $basic_img_src;
			//exit;
			$image_type = "gif"; // 워터마크 처리후 마임타입이 gif로 바뀐다.
		}

		switch ($image_type) {
			case "gif":
			case "GIF":
				MirrorGif($basic_img_src, $targetDirectory . "/b_".$pid.".gif", MIRROR_NONE);
				resize_gif($targetDirectory . "/b_".$pid.".gif",$image_info2[0][0],$image_info2[0][1]);

				MirrorGif($basic_img_src, $targetDirectory . "/m_".$pid.".gif", MIRROR_NONE);
				resize_gif($targetDirectory . "/m_".$pid.".gif",$image_info2[1][0],$image_info2[1][1]);

				MirrorGif($basic_img_src, $targetDirectory . "/ms_".$pid.".gif", MIRROR_NONE);
				resize_gif($targetDirectory . "/ms_".$pid.".gif",$image_info2[2][0],$image_info2[2][1]);

				MirrorGif($basic_img_src, $targetDirectory ."/s_".$pid.".gif", MIRROR_NONE);
				resize_gif($targetDirectory . "/s_".$pid.".gif",$image_info2[3][0],$image_info2[3][1]);

				MirrorGif($basic_img_src, $targetDirectory . "/c_".$pid.".gif", MIRROR_NONE);
				resize_gif($targetDirectory . "/c_".$pid.".gif",$image_info2[4][0],$image_info2[4][1]);
				break;


			default:
				//copy($image_path, $basic_img_src);

				Mirror($basic_img_src, $targetDirectory . "/b_".$pid.".gif", MIRROR_NONE);
				resize_jpg($targetDirectory . "/b_".$pid.".gif",$image_info2[0][0],$image_info2[0][1]);

				Mirror($basic_img_src, $targetDirectory . "/m_".$pid.".gif", MIRROR_NONE);
				resize_jpg($targetDirectory . "/m_".$pid.".gif",$image_info2[1][0],$image_info2[1][1]);

				Mirror($basic_img_src, $targetDirectory . "/ms_".$pid.".gif", MIRROR_NONE);
				resize_jpg($targetDirectory . "/ms_".$pid.".gif",$image_info2[2][0],$image_info2[2][1]);

				Mirror($basic_img_src, $targetDirectory ."/s_".$pid.".gif", MIRROR_NONE);
				resize_jpg($targetDirectory . "/s_".$pid.".gif",$image_info2[3][0],$image_info2[3][1]);

				Mirror($basic_img_src, $targetDirectory . "/c_".$pid.".gif", MIRROR_NONE);
				resize_jpg($targetDirectory . "/c_".$pid.".gif",$image_info2[4][0],$image_info2[4][1]);
				break;
		}
		if (is_file($image_path)) {
			@unlink($image_path);
		}
		syslog(LOG_INFO, 'END\r\n');
	}

/*
	// removes a directory and everything within it
	function rmdirr($target,$verbose=false)
	{
		$exceptions=array('.','..');
		if (!$sourcedir=@opendir($target))
		{
		   if ($verbose)
		       echo '<strong>Couldn&#146;t open '.$target."</strong><br />\n";
		   return false;
		}
		while(false!==($sibling=readdir($sourcedir)))
		{
		   if(!in_array($sibling,$exceptions))
		   {
		       $object=str_replace('//','/',$target.'/'.$sibling);
		       if($verbose)
		           echo 'Processing: <strong>'.$object."</strong><br />\n";
		       if(is_dir($object))
		           rmdirr($object);
		       if(is_file($object))
		       {
		           $result=@unlink($object);
		           if ($verbose&&$result)
		               echo "File has been removed<br />\n";
		           if ($verbose&&(!$result))
		               echo "<strong>Couldn&#146;t remove file</strong>";
		       }
		   }
		}
		closedir($sourcedir);
		if($result=@rmdir($target))
		{
		   if ($verbose)
		       echo "Target directory has been removed<br />\n";
		   return true;
		}
		if ($verbose)
		   echo "<strong>Couldn&#146;t remove target directory</strong>";

		return false;
	}


	function ClearText($str)
	{
		return str_replace(">","",$str);
	}


	function returnFileName($filestr){
		$strfile = split("/",$filestr);

		return str_replace("%20","",$strfile[count($strfile)-1]);
		//return count($strfile);

	}

	function returnImagePath($str){
		$IMG = split(" ",$str);

		for($i=0;$i<count($IMG);$i++){
			//echo substr_count($IMG[$i],"src");
				if(substr_count($IMG[$i],"src=") > 0){
					$mstring = str_replace("src=","",$IMG[$i]);
					return str_replace("\"","",$mstring);
				}
		}
	}

	function imageExists($image,$dir) {

	    $i=1; $probeer=$image;

	    while(file_exists($dir.$probeer)) {
	        $punt=strrpos($image,".");
	        if(substr($image,($punt-3),1)!==("[") && substr($image,($punt-1),1)!==("]")) {
	            $probeer=substr($image,0,$punt)."[".$i."]".
	            substr($image,($punt),strlen($image)-$punt);
	        } else {
	            $probeer=substr($image,0,($punt-3))."[".$i."]".
	            substr($image,($punt),strlen($image)-$punt);
	        }
	        $i++;
	    }
	    return $probeer;
	}
*/
?>