<?
if($regdate == ""){		//기본설정 시간
    $before10day = mktime(0, 0, 0, date("m")  , date("d")-20, date("Y"));
//	$sDate = date("Y/m/d");
    $sDate = date("Y-m-d", $before10day);
    $eDate = date("Y-m-d");


}else{
    $sDate = $sdate;
    $eDate = $edate;

}

if($mode != ""){
    if($mode == 'excel_search'){
        $info_type = 'excel_search';
    }else{
        $info_type = 'search';
    }
}

if($is_sell_date == '1') {
    $sell_startdate = $search_sell_priod_sdate . " " . $search_sell_priod_sdate_h . ":" . $search_sell_priod_sdate_i . ":" . $search_sell_priod_sdate_s;
    $sell_enddate = $search_sell_priod_edate . " " . $search_sell_priod_edate_h . ":" . $search_sell_priod_edate_i . ":" . $search_sell_priod_edate_s;
}
if(is_array($product_type)) {				//상품구분을 select 에서 checkbox 로 바꿈 kbk 13/08/05
    $add_search_product_type_query="";
    $product_type_cnt=count($product_type);
    for($i=0;$i<$product_type_cnt;$i++) {
        $add_search_product_type_query.="&product_type[]=".$product_type[$i];
    }
}else{
    $add_search_product_type_query="&product_type=$product_type";
}

if($_SERVER[QUERY_STRING] == "nset=$nset&page=$page"){
    $query_string = str_replace("nset=$nset&page=$page","",$_SERVER[QUERY_STRING]) ;
}else{
    $query_string = str_replace("nset=$nset&page=$page&","","&".$_SERVER[QUERY_STRING]) ;
}
$str_page_bar = page_bar($total, $page, $max,  $query_string, "");

if($mode == 'excel'){		//상품리스트 엑셀 다운로드 2014-07-15 이학봉

    $goods_info = $slave_db->fetchall();
    include '../include/phpexcel/Classes/PHPExcel.php';

    if($admininfo[admin_level] == '9'){
        $excel_type = 'company';
    }else{
        $excel_type = 'seller';
    }
    $excel_file_name = "batch_products_update_excel_".$excel_type.".xls";

    $objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"]."/admin/product/".$excel_file_name);

    $etc_excel = new PHPExcel();

///////////////////
    // 속성 정의
    $etc_excel->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("Mallstory.com")
        ->setTitle("etc code List")
        ->setSubject("etc code List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("mallstory")
        ->setCategory("etc code List");

    $etc_excel->setActiveSheetIndex(0);
    $etc_excel->getActiveSheet()->setTitle('대량상품수정');

    $z = 6;
    for($i=0;$i<count($goods_info);$i++){

        //$db->fetch($i);

        $col = 'A';

        $objPHPExcel->getActiveSheet()->setCellValue('A' . $z , "");
        $objPHPExcel->getActiveSheet()->getStyle('B' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );
        $objPHPExcel->getActiveSheet()->setCellValue('B' . $z , " ".$goods_info[$i][id]);	//상품시스템키
        $objPHPExcel->getActiveSheet()->setCellValue('C' . $z , $goods_info[$i][product_type]);	//상품구분
        $objPHPExcel->getActiveSheet()->getStyle('D' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );
        $objPHPExcel->getActiveSheet()->setCellValue('D' . $z , " ".$goods_info[$i][cid]);		//카테고리
        $objPHPExcel->getActiveSheet()->setCellValue('E' . $z , $goods_info[$i][pname]);		//상품명

        $objPHPExcel->getActiveSheet()->setCellValue('F' . $z , $goods_info[$i][gid]);		//상품코드(품목코드)
        $objPHPExcel->getActiveSheet()->setCellValue('G' . $z , $goods_info[$i][paper_pname]);	//매입상품명
        $objPHPExcel->getActiveSheet()->setCellValue('H' . $z , $goods_info[$i][barcode]);		//바코드
        $objPHPExcel->getActiveSheet()->setCellValue('I' . $z , $goods_info[$i][shotinfo]);		//상품간략소개
        $objPHPExcel->getActiveSheet()->setCellValue('J' . $z , $goods_info[$i][trade_admin]);	//매입업체

        $sql = "select og_ix from common_origin where origin_name = '".$goods_info[$i][origin]."'";
        $slave_db->query($sql);
        $slave_db->fetch();
        $objPHPExcel->getActiveSheet()->setCellValue('K' . $z , $slave_db->dt[og_ix]);				//원산지코드
        $objPHPExcel->getActiveSheet()->setCellValue('L' . $z , $goods_info[$i][c_ix]);			//제조사코드
        $objPHPExcel->getActiveSheet()->setCellValue('M' . $z , $goods_info[$i][brand]);		//브랜드코드
        $objPHPExcel->getActiveSheet()->setCellValue('N' . $z , $goods_info[$i][surtax_yorn]);	//면세여부
        $objPHPExcel->getActiveSheet()->setCellValue('O' . $z , $goods_info[$i][state]);		//판매상태
        $objPHPExcel->getActiveSheet()->setCellValue('P' . $z , $goods_info[$i][disp]);			//노출여부
        $objPHPExcel->getActiveSheet()->setCellValue('Q' . $z , $goods_info[$i][product_weight]);		//무게
        $objPHPExcel->getActiveSheet()->setCellValue('R' . $z , $goods_info[$i][is_sell_date]);			//판매기간사용여부
        $sell_priod_sdate = explode(" ",$goods_info[$i][sell_priod_sdate]);
        $sell_priod_edate = explode(" ",$goods_info[$i][sell_priod_edate]);
        $objPHPExcel->getActiveSheet()->setCellValue('S' . $z , str_replace("-","",$sell_priod_sdate[0])."-".str_replace("-","",$sell_priod_edate[0]));				//판매기간설정
        $objPHPExcel->getActiveSheet()->setCellValue('T' . $z , $goods_info[$i][delivery_coupon_yn]);			//배송쿠폰사용여부
        $objPHPExcel->getActiveSheet()->setCellValue('U' . $z , $goods_info[$i][coupon_use_yn]);				//상품쿠폰사용여부
        $objPHPExcel->getActiveSheet()->setCellValue('V' . $z , $goods_info[$i][search_keyword]);				//검색키워드
        $objPHPExcel->getActiveSheet()->setCellValue('W' . $z , $goods_info[$i][stock_use_yn]);					//재고관리사용여부

        $objPHPExcel->getActiveSheet()->setCellValue('X' . $z , $goods_info[$i][safestock]);				//안전재고
        $objPHPExcel->getActiveSheet()->setCellValue('Y' . $z , $goods_info[$i][stock]);					//실재고

        $objPHPExcel->getActiveSheet()->setCellValue('Z' . $z , $goods_info[$i][movie]);				//동영상 URL
        $objPHPExcel->getActiveSheet()->setCellValue('AA' . $z , $goods_info[$i][make_date]);			//제조일자
        $objPHPExcel->getActiveSheet()->setCellValue('AB' . $z , $goods_info[$i][expiry_date]);			//유효일
        $objPHPExcel->getActiveSheet()->setCellValue('AC' . $z , $goods_info[$i][is_adult]);				//19금상품
        $objPHPExcel->getActiveSheet()->setCellValue('AD' . $z , $goods_info[$i][coprice]);				//공급가
        $objPHPExcel->getActiveSheet()->setCellValue('AE' . $z , $goods_info[$i][wholesale_price]);				//도매판매가
        $objPHPExcel->getActiveSheet()->setCellValue('AF' . $z , $goods_info[$i][wholesale_sellprice]);			//도매할인가
        $objPHPExcel->getActiveSheet()->setCellValue('AG' . $z , $goods_info[$i][listprice]);					//소매판매가
        $objPHPExcel->getActiveSheet()->setCellValue('AH' . $z , $goods_info[$i][sellprice]);					//소매할인가
        $objPHPExcel->getActiveSheet()->setCellValue('AI' . $z , $goods_info[$i][allow_basic_cnt]);			//기본시작수량
        $objPHPExcel->getActiveSheet()->setCellValue('AJ' . $z , $goods_info[$i][allow_max_cnt]);			//최대판매수량
        $objPHPExcel->getActiveSheet()->setCellValue('AK' . $z , $goods_info[$i][wholesale_allow_byoneperson_cnt]);				//ID당구매수량
        $objPHPExcel->getActiveSheet()->setCellValue('AL' . $z , $goods_info[$i][allow_order_type]);		//한정판매사용여부
        $objPHPExcel->getActiveSheet()->setCellValue('AM' . $z , $goods_info[$i][allow_order_cnt_byonesell]);			//한정판매 수량
        $objPHPExcel->getActiveSheet()->setCellValue('AN' . $z , $goods_info[$i][delivery_type]);			//배송타입
        $objPHPExcel->getActiveSheet()->setCellValue('AO' . $z , $goods_info[$i][one_commission]);					//개별수수료사용여부
        $objPHPExcel->getActiveSheet()->setCellValue('AP' . $z , $goods_info[$i][account_type]);				//정산방식
        $objPHPExcel->getActiveSheet()->setCellValue('AQ' . $z , getProductCategoryRate($goods_info[$i][id],$goods_info[$i][cid],'W')."|".getProductCategoryRate($goods_info[$i][id],$goods_info[$i][cid],'R'));		//수수료

        $sql = "select * from shop_product_displayinfo where pid = '".$goods_info[$i][id]."' and dp_use = '1' order by dp_ix asc ";
        $slave_db->query($sql);
        $display_options = $slave_db->fetchall();
        for($j=0;$j<count($display_options);$j++){

            if($j != count($display_options) -1){
                $display_enter = "^\n";
            }
            $display_option .= $display_options[$j][dp_title]."|".$display_options[$j][dp_desc]."|".$display_options[$j][dp_etc_desc].$display_enter;
            $dp_ix .= $display_options[$j][dp_ix].$display_enter;

            $display_enter = '';
        }
        $objPHPExcel->getActiveSheet()->getStyle('AR' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );
        $objPHPExcel->getActiveSheet()->setCellValue('AR' . $z , " ".$dp_ix);			//디스플레이옵션 키
        $objPHPExcel->getActiveSheet()->setCellValue('AS' . $z , $display_option);			//디스플레이옵션

        $sql = "select * from shop_product_viralinfo where pid = '".$goods_info[$i][id]."' and vi_use='1' order by vi_ix asc ";
        $slave_db->query($sql);
        $virals = $slave_db->fetchall();
        for($j=0;$j<count($virals);$j++){
            if($j != count($virals) -1){
                $virals_enter = "^\n";
            }
            $virals_text .= $virals[$j][viral_name]."|".$virals[$j][viral_url]."|".$virals[$j][viral_desc].$virals_enter;
            $vi_ix .= $virals[$j][vi_ix].$virals_enter;
            $virals_enter = '';
        }
        $objPHPExcel->getActiveSheet()->getStyle('AT' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );
        $objPHPExcel->getActiveSheet()->setCellValue('AT' . $z , " ".$vi_ix);	//바이럴등록키
        $objPHPExcel->getActiveSheet()->setCellValue('AU' . $z , $virals_text);	//바이럴등록키

        $mandatory_type = explode("|",$goods_info[$i][mandatory_type]);
        $objPHPExcel->getActiveSheet()->setCellValue('AV' . $z , $mandatory_type[0]);		//상품고시유형

        $sql = "select * from shop_product_mandatory_info where pid = '".$goods_info[$i][id]."' order by pmi_ix ASC";
        $slave_db->query($sql);
        $mandatory_array = $slave_db->fetchall();
        for($j=0;$j<count($mandatory_array);$j++){
            if($j != count($mandatory_array) -1){
                $mandatory_enter = "^\n";
            }
            $pmi_code = explode("|",$mandatory_array[$j][pmi_code]);
            $mandatory .= $pmi_code[1]."|".$mandatory_array[$j][pmi_desc].$mandatory_enter;
            $pmi_ix .= $mandatory_array[$j][pmi_ix].$mandatory_enter;

            $mandatory_enter = '';
        }
        $objPHPExcel->getActiveSheet()->setCellValue('AW' . $z , $mandatory);	//상품고시 정보
        $objPHPExcel->getActiveSheet()->setCellValue('AX' . $z , $pmi_ix);		//상품고시정보킥값
        $objPHPExcel->getActiveSheet()->setCellValue('AY' . $z , $goods_info[$i][m_basicinfo]);		//모바일상세설명
        $objPHPExcel->getActiveSheet()->setCellValue('AZ' . $z , $goods_info[$i][basicinfo]);		//웹상품상세설명
        $objPHPExcel->getActiveSheet()->setCellValue('BA' . $z , '');								//상품이미지

        $sql = "select
					po.*,
					pod.*,
					gu.gid
				from 
					shop_product_options as po 
					inner join shop_product_options_detail as pod on (po.opn_ix = pod.opn_ix)
					left join inventory_goods_unit as gu on (pod.option_code = gu.gu_ix)
				where
					po.pid = '".$goods_info[$i][id]."'
					and po.option_kind = 'b'";
        $slave_db->query($sql);
        $options_info = $slave_db->fetchall();

        for($j=0;$j<count($options_info);$j++){

            if($j != count($options_info) -1){
                $option_enter = "|";
            }

            $option_div .= $options_info[$j][option_div].$option_enter;						//옵션구분
            $option_coprice .= $options_info[$j][option_coprice].$option_enter;				//옵션공급가
            $option_wholesale_listprice .= $options_info[$j][option_wholesale_listprice].$option_enter;				//옵션도매판매가
            $option_wholesale_price .= $options_info[$j][option_wholesale_price].$option_enter;				//옵션도매할인가

            $option_listprice .= $options_info[$j][option_listprice].$option_enter;				//옵션소매판매가
            $option_price .= $options_info[$j][option_price].$option_enter;						//옵션소매할인가

            $option_stock .= $options_info[$j][option_stock].$option_enter;						//실재고
            $option_safestock .= $options_info[$j][option_safestock].$option_enter;				//안전재고

            $option_code .= $options_info[$j][gid].$option_enter;					//옵션 품목코드
            $option_barcode .= $options_info[$j][option_barcode].$option_enter;				//옵션 바코드

            $option_enter = '';
        }

        $objPHPExcel->getActiveSheet()->setCellValue('BB' . $z , $options_info[0][option_name]);			//가격재고관리 옵션명
        $objPHPExcel->getActiveSheet()->setCellValue('BC' . $z , $options_info[0][opn_ix]);			//옵션 키값
        $objPHPExcel->getActiveSheet()->setCellValue('BD' . $z , $option_div);			//옵션구분
        $objPHPExcel->getActiveSheet()->setCellValue('BE' . $z , $option_coprice);			//옵션공급가
        $objPHPExcel->getActiveSheet()->setCellValue('BF' . $z , $option_wholesale_listprice);			//옵션도매판매가
        $objPHPExcel->getActiveSheet()->setCellValue('BG' . $z , $option_wholesale_price);			//옵션도매할인가
        $objPHPExcel->getActiveSheet()->setCellValue('BH' . $z , $option_listprice);			//옵션소매판매가
        $objPHPExcel->getActiveSheet()->setCellValue('BI' . $z , $option_price);			//옵션소매할인가
        $objPHPExcel->getActiveSheet()->setCellValue('BJ' . $z , $option_stock);			//실재고
        $objPHPExcel->getActiveSheet()->setCellValue('BK' . $z , $option_safestock);			//안전재고

        $objPHPExcel->getActiveSheet()->setCellValue('BL' . $z , $option_code);			//옵션(품목코드)
        $objPHPExcel->getActiveSheet()->setCellValue('BM' . $z , $option_barcode);			//옵션(바코드)

        //$objPHPExcel->getActiveSheet()->setCellValue('BH' . $z , 'Y');			//지식쇼핑사용유무
        //$objPHPExcel->getActiveSheet()->setCellValue('BI' . $z , 'Y');			//다음쇼핑하우 사용유무

        $z++;

        $option_div = '';
        $option_coprice = '';
        $option_wholesale_listprice = '';
        $option_wholesale_price = '';
        $option_listprice = '';
        $option_price = '';
        $option_stock = '';
        $option_safestock = '';
        $option_code = '';
        $option_barcode = '';

        $dp_ix = '';
        $display_option = '';

        $vi_ix = '';
        $virals_text = '';

        $pmi_ix = '';
        $mandatory = '';

    }

/////////////////////

    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename=batch_products_update_excel.xls');
    header('Cache-Control: max-age=0');

    $objPHPExcel = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
    $objPHPExcel->save('php://output');

    exit;

}

$slave_db->query("select idx from shop_icon where disp = '1' order by idx");
if($slave_db->total){
    $icon_list = $slave_db->fetchall();
}

if($page_type == "shortage_results_product_list"){
    $Contents .= "	
	<table border=0 cellpadding=0 cellspacing=0 width='100%'>
	<tr>
		<td valign=top align='right'>
			<input type='button' value='실적부족상품 리스트 노출 설정' style='cursor:pointer;' onclick=\"PoPWindow('./shortage_results_setup.php?company_id=".$admininfo[company_id]."',500,380,'sendsms')\">
		</td>
	</tr>
	</table>
	";
}

$Contents .="
	<table border=0 cellpadding=0 cellspacing=0 width='100%'>
	<tr>
		<td align='left' colspan=4> ".GetTitleNavigation("상품리스트", "상품관리 > 상품리스트")."</td>
	</tr>
	<tr>
		<td align='left' colspan=4 style='padding-bottom:15px;'>
			<div class='tab'>
			<table class='s_org_tab'>
			<tr>
				<td class='tab'>
					<table id='tab_01' ".($info_type == "search" || $info_type == "" ? "class='on' ":"").">
					<tr>
						<th class='box_01'></th>
						<td class='box_02'><a href='?info_type=search&up_mode=$up_mode'>카테고리별 상품목록</a></td>
						<th class='box_03'></th>
					</tr>
					</table>
					<table id='tab_02' ".($info_type == "excel_search"? "class='on' ":"").">
					<tr>
						<th class='box_01'></th>
						<td class='box_02'><a href='?info_type=excel_search&up_mode=$up_mode'><img src='../images/icon/excel_icon.gif' border='0'>엑셀일괄 검색</a></td>
						<th class='box_03'></th><!--onclick=\"ShowSearchDiv('excel')\"-->
					</tr>
					</table>
				</td>
				<td class='btn'>
				</td>
			</tr>
			</table>
		</div>
		</td>
	</tr>
	</table>";


$Contents .= "	
	<form name='search_form' id='search_form' method='get' action='".$HTTP_URL."' onsubmit='return CheckFormValue(this);' enctype='multipart/form-data'>
	<!--input type='hidden' name='view' value='innerview'-->
	<table border=0 cellpadding=0 cellspacing=0 width='100%'>
	<input type='hidden' name='mode' value='search'>
	<input type='hidden' name='up_mode' value='$up_mode'>
	<input type='hidden' name='cid2' value='$cid2'>
	<input type='hidden' name='depth' value='$depth'>
	<input type='hidden' name='sprice' value='0' />
	<input type='hidden' name='eprice' value='1000000' />
	<input type='hidden' name='info' value='$info' />
	<tr>
		<td colspan=2>
			<table class='box_shadow' style='width:100%;' cellpadding='0' cellspacing='0' border='0'><!---mbox04-->
				<tr>
					<th class='box_01'></th>
					<td class='box_02'></td>
					<th class='box_03'></th>
				</tr>
				<tr>
					<th class='box_04'></th>
					<td class='box_05 align=center' style='padding:0px'>";
if($info_type == "search" || $info_type == ""){
    $Contents .=	"
						<div id='search_text_div'>
						<input type='hidden' name='mode' value='search'>
						<table cellpadding=0 cellspacing=1 border=0 width=100% align='center' class='search_table_box'>
							<col width=18%>
							<col width=32%>
							<col width=18%>
							<col width=32%>";
    if($_SESSION["admin_config"][front_multiview] == "Y"){
        $Contents .= "
	<tr>
		<td class='search_box_title' > 프론트 전시 구분</td>
		<td class='search_box_item' colspan=3>".GetDisplayDivision($mall_ix, "select")." </td>
	</tr>";
    }
    $Contents .= "";

    if($page_type != "gift_list"){
        $Contents .=	"		<!--
							<tr>
								<td class='search_box_title' > 선택된 카테고리  </td>
								<td class='search_box_item' colspan=3>  <b id='select_category_path1'>".($search_text == "" ? getCategoryPathByAdmin($cid2, $depth)."(".$total."개)":"<b style='color:red'>'$search_text'</b> 로 검색된 결과 입니다.")."</b></div>  </td>
							</tr>-->
							<tr>
								<td class='input_box_title'>
									<div style='float:left;padding-top:5px;'><b>카테고리선택</b></div>
									<div style='float:left;padding-left:20px;'>
										<img src='../images/icon/search_icon.gif' value='검색' onclick=\"PoPWindow('../product/search_category.php?group_code=',800,600,'add_brand_category')\" style='cursor:pointer;'>
									</div>
								</td>
								<td class='input_box_item' colspan=3 >
									<div id='selected_category_6' style='padding:10px;overflow-y:scroll;max-height:100px;'>
									<table width='98%' cellpadding='0' cellspacing='0' id='objMd'>
									<colgroup>
										<col width='*'>
										<col width='600'>
									</colgroup>
									<tbody>";
        if(count($cid) > 0){

            for($k=0;$k<count($cid);$k++){

                $re_cid = $cid[$k];
                $sql = "select * from shop_category_info where cid = '".$re_cid."'";
                $slave_db->query($sql);
                $slave_db->fetch();
                $depth = $slave_db->dt[depth];

                for($i=0;$i<=$depth;$i++){
                    $this_cid = substr(substr($re_cid, 0,($i*3+3)).'000000000000',0,15);
                    $sql = "select * from shop_category_info where cid = '".$this_cid."'";
                    $slave_db->query($sql);
                    $slave_db->fetch();
                    $cname = $slave_db->dt[cname];
                    $relation_cname[$k] .= $cname." > ";
                }

                $Contents .= "	<tr style='height:26px;' id='row_".$re_cid."'>
													<td>
													<input type='hidden' name='cid[]' id='cid_".$re_cid."' value='".$re_cid."'>".$relation_cname[$k]."</td><td><a href='javascript:void(0)' onclick=\"cid_del('".$re_cid."')\"><img src='../images/korea/btc_del.gif' border='0'></a>
													</td>
												</tr>";
            }
        }
        $Contents .= "
										</tbody>
										</table>
									</div>
								</td>
							</tr>";
    }

    if($page_type != 'gift_list'){

        if($admininfo[mall_type] != "F" && $admininfo[admin_level] == 9){

            $Contents .=	"<tr>
							<td class='search_box_title' >상품구분</td>
							<td class='search_box_item' colspan='3'>
								<table cellpadding=0 cellspacing=0 border='0' width='100%'  align='left'>
								<col width=60>
								<col width=60>
								<col width=130>
								<col width=130>
								<col width=90>
								<!--col width=80--> 
								<tr>
									<td>
									<input type='checkbox' name='product_type[]' id='product_type_0' value='0' title='일반상품' ".(is_array($product_type)?in_array('0',$product_type)?'checked':'':'')."/>
									<label for='product_type_0'>일반</label> 
									</td>
									<td>
									<input type='checkbox' name='product_type[]' id='product_type_99' value='99' title='세트상품' " . (is_array($product_type) ? in_array('99', $product_type) ? 'checked' : '' : '') . "/>
									<label for='product_type_99'>세트</label>
									</td>
									
									 <td></td>
                                <td></td>
                                <td></td>
                                ";
            $Contents .="
								</tr>
								</table>
							</td>
						</tr>";
        }

        if($page_type == "" && $page_type != "gift_list"  && $page_type != "update_state"){
            $Contents .=	"	<tr>
								<td class='search_box_title' >판매상태</td>
								<td class='search_box_item' colspan='3'>
									<table cellpadding=0 cellspacing=0 border='0'  align='left'>";

            $Contents .=	"
									<col width=70>
									<col width=80>
									<col width=90>";

            $Contents .=	"		<col width=80> 
									<col width=90>
									<col width=110>
									
									
									<tr>";


            $Contents .=	"
										<td>
										<input type='checkbox' name='state[]' id='search_state_1' value='1' title='판매중' ".(is_array($state)?in_array('1',$state)?'checked':'':'')."/>
										<label for='search_state_1'> 판매중 </label> 
										</td>
										<td>
										<input type='checkbox' name='state[]' id='search_state_0' value='0' title='일시품절' ".(is_array($state)?in_array('0',$state)?'checked':'':'')."/>
										<label for='search_state_0'> 일시품절 </label> 
										</td>
										<td>
										<input type='checkbox' name='state[]' id='search_state_2' value='2' title='판매중지' ".(is_array($state)?in_array('2',$state)?'checked':'':'')."/>
										<label for='search_state_2'> 판매중지</label>
										</td>
										<td>
										<input type='checkbox' name='state[]' id='search_state_8' value='8' title='승인거부' ".(is_array($state)?in_array('8',$state)?'checked':'':'')."/> 
										<label for='search_state_8'> 승인거부 </label>
										</td>";

            if($admininfo[admin_level] == '9'){


                $Contents .=	"			<td>
										<input type='checkbox' name='state[]' id='search_state_6' value='6' title='승인대기' ".(is_array($state)?in_array('6',$state)?'checked':'':'')."/> 
										<label for='search_state_6'> 승인대기 </label>
										</td>

										<td>
										<input type='checkbox' name='state[]' id='search_state_7' value='7' title='수정대기상품' ".(is_array($state)?in_array('7',$state)?'checked':'':'')."/> 
										<label for='search_state_7'> 수정대기상품 </label>
										</td>";


                $Contents .=	"	
										
										";

                $Contents .=	"	
										<td>
										<input type='checkbox' name='state[]' id='search_state_9' value='9' title='판매금지' ".(is_array($state)?in_array('9',$state)?'checked':'':'')."/> 
										<label for='search_state_9'> 판매금지 </label>
										</td>
										";

                $Contents .=	"	
										<td>
										<input type='checkbox' name='state[]' id='search_state_4' value='4' title='판매예정' ".(is_array($state)?in_array('4',$state)?'checked':'':'')."/> 
										<label for='search_state_4'> 판매예정 </label>
										</td>
										";

                $Contents .=	"	
										<td>
										<input type='checkbox' name='state[]' id='search_state_5' value='5' title='판매종료' ".(is_array($state)?in_array('5',$state)?'checked':'':'')."/> 
										<label for='search_state_5'> 판매종료 </label>
										</td>
										";

            }
            $Contents .=	"
									</tr>
									</table>
								</td>
							</tr>
							<tr> 
							    <td class='search_box_title' >재고상태</td>
								<td class='search_box_item' colspan='3'>
									<label><input type='checkbox' name='stock_status' value='1' ".($stock_status==1?'checked':'')."/> 재고품절</label>
                                </td>
							</tr>
							";
        }
        if($page_type != "update_price"  && $page_type != "update_delivery_policy" && $page_type != "update_basic_info"){

            $Contents .=	"
							<tr>
								<td class='search_box_title' > 할인상품 </td>
								<td class='search_box_item' colspan='3'>
									<table cellpadding=0 cellspacing=0 border='0'   align='left'>
									<col width=90>
									<col width=80>
									<col width=90>
									<tr>
										<td>
										<input type='checkbox' name='sale_rate[]' id='sale_rate_1' value='1' title='즉시할인' ".(is_array($sale_rate)?in_array('1',$sale_rate)?'checked':'':'')."/>
										<label for='sale_rate_1'> 즉시할인 </label> 
										</td>
										<!--
										<td>
										<input type='checkbox' name='sale_rate[]' id='sale_rate_2' value='2' title='기획할인' ".(is_array($sale_rate)?in_array('2',$sale_rate)?'checked':'':'')."/>
										<label for='sale_rate_2'> 기획할인 </label> 
										</td>
										<td>
										<input type='checkbox' name='sale_rate[]' id='sale_rate_3' value='3' title='특별할인' ".(is_array($sale_rate)?in_array('3',$sale_rate)?'checked':'':'')."/>
										<label for='sale_rate_3'> 특별할인 </label> 
										</td>-->
										<td></td>
									</tr>
									</table>
								</td>
								<!--
								<td class='search_box_title'>개별수수료 사용여부</td>
								<td class='search_box_item'>
									<table cellpadding=0 cellspacing=0 border='0'  align='left'>
									<col width=60>
									<col width=100>
									<tr>
										<td>
											<input type='checkbox' name='one_commission[]' id='one_commission_y' value='Y' title='사용' ".(is_array($one_commission)?in_array('Y',$one_commission)?'checked':'':'')."/><label for='one_commission_y'> 사용 </label> 
										</td>
										<td>
											<input type='checkbox' name='one_commission[]' id='one_commission_n' value='N' title='미사용' ".(is_array($one_commission)?in_array('N',$one_commission)?'checked':'':'')."/><label for='one_commission_n'> 미사용 </label> 
										</td>
										
										<td></td>
									</tr>
									</table>
								</td>
								-->
							</tr>";
        }
    }

    if($page_type != "company_wating_product_list" && $page_type != "update_price" && $page_type != "update_delivery_policy"  && $page_type != "update_basic_info" && $admininfo[admin_level] == '9'){
        $Contents .=	"
							<tr>
								<td class='search_box_title' > 재고관리 </td>
								<td class='search_box_item'>
								<table cellpadding=0 cellspacing=0 border='0'  align='left'>
									<col width=120>
									<col width=110>
									<col width=120>
									<tr>
									    <!--
										<td>
										<input type='checkbox' name='stock_use_yn[]' id='stock_use_yn_n' value='N' title='사용안함' ".(is_array($stock_use_yn)?in_array('N',$stock_use_yn)?'checked':'':'')."/>
										<label for='stock_use_yn_n'> 사용안함 </label> 
										</td>
										<td>
										<input type='checkbox' name='stock_use_yn[]' id='stock_use_yn_q' value='Q' title='빠른재고 사용' ".(is_array($stock_use_yn)?in_array('Q',$stock_use_yn)?'checked':'':'')."/>
										<label for='stock_use_yn_q'> 빠른재고 사용 </label>
										</td>
										-->
										<td>
										<input type='checkbox' name='stock_use_yn[]' id='stock_use_yn_y' value='Y' title='WMS재고 사용' ".(is_array($stock_use_yn)?in_array('Y',$stock_use_yn)?'checked':'':'')."/>
										<label for='stock_use_yn_y'> WMS재고 사용 </label>
										</td>
										<td></td>
									</tr>
									</table>
								</td>
								<td class='search_box_title'>면세여부</td>
								<td class='search_box_item'>
									<table cellpadding=0 cellspacing=0 border='0'  align='left'>
									<col width=60>
									<col width=100>
									<tr>
										<td>
											<input type='checkbox' name='surtax_yorn[]' id='surtax_yorn_n' value='N' title='과세' ".(is_array($surtax_yorn)?in_array('N',$surtax_yorn)?'checked':'':'')."/><label for='surtax_yorn_n'> 과세 </label> 
										</td>
										<td>
											<input type='checkbox' name='surtax_yorn[]' id='surtax_yorn_y' value='Y' title='면세' ".(is_array($surtax_yorn)?in_array('Y',$surtax_yorn)?'checked':'':'')."/><label for='surtax_yorn_y'> 면세 </label> 
										</td>
										
										<td></td>
									</tr>
									</table>
								</td>
							</tr>";
    }else{
        $Contents .=	"
							<tr>
								<td class='search_box_title'>면세여부</td>
								<td class='search_box_item'>
									<table cellpadding=0 cellspacing=0 border='0'  align='left'>
									<col width=60>
									<col width=100>
									<tr>
										<td>
											<input type='checkbox' name='surtax_yorn[]' id='surtax_yorn_n' value='N' title='과세' ".(is_array($surtax_yorn)?in_array('N',$surtax_yorn)?'checked':'':'')."/><label for='surtax_yorn_n'> 과세 </label> 
										</td>
										<td>
											<input type='checkbox' name='surtax_yorn[]' id='surtax_yorn_y' value='Y' title='면세' ".(is_array($surtax_yorn)?in_array('Y',$surtax_yorn)?'checked':'':'')."/><label for='surtax_yorn_y'> 면세 </label> 
										</td>
										
										<td></td>
									</tr>
									</table>
								</td>
								<td class='search_box_title'>배송비설정</td>
								<td class='search_box_item'>
									<table cellpadding=0 cellspacing=0 border='0'  align='left'>
									<col width=100>
									<col width=100>
									<tr>
										<td>
											<input type='checkbox' name='delivery_policy[]' id='delivery_policy_1' value='1' title='기본설정' ".(is_array($delivery_policy)?in_array('1',$delivery_policy)?'checked':'':'')."/><label for='delivery_policy_1'> 기본설정 </label> 
										</td>
										<td>
											<input type='checkbox' name='delivery_policy[]' id='delivery_policy_2' value='2' title='개별설정' ".(is_array($delivery_policy)?in_array('2',$delivery_policy)?'checked':'':'')."/><label for='delivery_policy_2'> 개별설정 </label> 
										</td>
										
										<td></td>
									</tr>
									</table>
								</td>
							</tr>";
    }

    if($admininfo[admin_level] == '9'){
        $Contents .=	"	
							<tr>
								<td class='search_box_title'>노출여부</td>
								<td class='search_box_item'>
									<table cellpadding=0 cellspacing=0 border='0'  align='left'>
									<col width=60>
									<col width=100>
									<tr>
										<td>
											<input type='checkbox' name='disp[]' id='disp_1' value='1' title='노출' ".(is_array($disp)?in_array('1',$disp)?'checked':'':'')."/><label for='disp_1'> 노출 </label> 
										</td>
										<td>
											<input type='checkbox' name='disp[]' id='disp_0' value='0' title='미노출' ".(is_array($disp)?in_array('0',$disp)?'checked':'':'')."/><label for='disp_0'> 미노출 </label> 
										</td>
										<td></td>
									</tr>
									</table>
								</td>
								<td class='search_box_title'>브랜드</td>
								<td class='search_box_item'>
								".BrandListSelect($b_ix, $cid)."
								</td>
							</tr>
							<tr>
								<td class='search_box_title'>모바일상품 사용여부</td>
								<td class='search_box_item' colspan='3'>
									<table cellpadding=0 cellspacing=0 border='0'  align='left'>
									<col width=60>
									<col width=100>
									<col width=60>
									<tr>
										<td>
											<input type='radio' name='is_mobile_use' value='A' id='is_mobile_use_a' ".($is_mobile_use == "A" || $is_mobile_use == "" ? "checked":"")." > 
											<label for='is_mobile_use_a'> 전체</label>
										</td>
										<td>
											<input type='radio' name='is_mobile_use' value='M' id='is_mobile_use_m' ".($is_mobile_use == "M" ? "checked":"")." > 
											<label for='is_mobile_use_m'> 모바일 </label> 
										</td>
										<td>
											<input type='radio' name='is_mobile_use' value='W' id='is_mobile_use_w' ".($is_mobile_use == "W" ? "checked":"")." > 
											<label for='is_mobile_use_w'> 웹 </label>
										</td>
									</tr>
									</table>
								</td>
								<!--
								<td class='search_box_title'>재고품절상품</td>
								<td class='search_box_item'>
									
									<input type='checkbox' name='stock_soldout' id='stock_soldout' value='1' ".($stock_soldout == "1" ? "checked":"")."> <label for='stock_soldout'>실재고</label>
									<input type='checkbox' name='option_stock_soldout' id='option_stock_soldout' value='1' ".($option_stock_soldout == "1" ? "checked":"")."> <label for='option_stock_soldout'>옵션재고</label>
									<input type='checkbox' name='available_stock_soldout' id='available_stock_soldout' value='1' ".($available_stock_soldout == "1" ? "checked":"")."> <label for='available_stock_soldout'>가용재고</label>
								</td>
								-->
							</tr>";
    }

    if($admininfo[admin_level]=='9' && false){
		if($page_type == "update_delivery_policy"){
			$seller_validation = "validation='true'";
		}else{
			$seller_validation = "validation='false'";
		}

        $Contents .=	"
							<tr>
								<td class='search_box_title'>셀러업체</td>
								<td class='search_box_item'>
									".companyAuthList($company_id , $seller_validation." title='셀러업체' ")."
								</td>
								<td class='search_box_title' >배송타입</td>
								<td class='search_box_item' >
									<table cellpadding=0 cellspacing=0 border='0' align='left'>
									<col width=80>
									<col width=100>
									<tr>
										<td>
											<input type='checkbox' name='delivery_type[]' id='delivery_type_1' value='1' title='통합배송' ".(is_array($delivery_type)?in_array('1',$delivery_type)?'checked':'':'')."/><label for='delivery_type_1'> 통합배송 </label> 
										</td>
										<td>
											<input type='checkbox' name='delivery_type[]' id='delivery_type_2' value='2' title='입점업체배송' ".(is_array($delivery_type)?in_array('2',$delivery_type)?'checked':'':'')."/><label for='delivery_type_2'> 입점업체배송 </label> 
										</td>
										<td></td>
									</tr>
									</table>
								</td>
							</tr>";
    }

    $Contents .=	"
							<tr height=27>
								<td class='search_box_title'><label for='regdate'>등록일자</label>
								<input type='checkbox' name='regdate' id='regdate' value='1' onclick='ChangeRegistDate(document.search_form);' ".CompareReturnValue("1",$regdate,"checked")."></td>
								<td class='search_box_item' colspan=3 >
								<div style='float:left;padding-top:5px;'>
									<select name='search_date_type' id='search_date_type'>
									<option value='1' ".CompareReturnValue("1",$search_date_type,'selected')."> 상품등록일</option>
									<option value='2' ".CompareReturnValue("2",$search_date_type,'selected')."> 상품수정일</option>
									</select>
								</div>
								<div style='float:left; padding-left:10px;'>
									".search_date('sdate','edate',$sDate,$eDate)."
								</div>
								</td>
							</tr>";

    if($page_type == 'update_sell_priod_date'){
        $Contents .=	"
							<tr height=27>
								<td class='search_box_title'><label for='regdate'>상품판매일</label>
								<td class='search_box_item' colspan=3 >
								<table cellpadding='0' cellspacing='2' border='0' bgcolor=#ffffff width=100%>
									<col width='130'>
									<col width='*'>
									<tr>
										<td>
											<input type='radio' name='is_sell_date' value='0' id='is_sell_date_0' ".($is_sell_date == "0" ? "checked":"")."> <label for='is_sell_date_0'>미적용</label>
											<input type='radio' name='is_sell_date' value='1' id='is_sell_date_1' ".($is_sell_date == "1" ? "checked":"")."> <label for='is_sell_date_1'>적용</label>
										<TD nowrap>
											".search_date('search_sell_priod_sdate','search_sell_priod_edate',$sell_startdate,$sell_enddate,'Y')."
										</TD>

									</tr>
								</table>
								</td>
							</tr>";
    }

    if($admininfo[admin_level]=='9'){
        $Contents .=	"
							<tr>
								<td class='search_box_title'> 담당MD </td>
								<td class='search_box_item' colspan='3'>
									".MDSelect($md_code)."
								</td>
								<!--
								<td class='search_box_title' > 상품관리구분 </td>
								<td class='search_box_item' >
									<input type='checkbox' name='com_type[]' id='com_type_a' value='A' title='본사 상품' ".(is_array($com_type)?in_array('A',$com_type)?'checked':'':'')."/>
									<label for='com_type_a'> 본사 상품 </label> 
									<input type='checkbox' name='com_type[]' id='com_type_s' value='S' title='셀러 상품' ".(is_array($com_type)?in_array('S',$com_type)?'checked':'':'')."/>
									<label for='com_type_s'> 셀러 상품 </label> 
								</td>
								-->
							</tr>";
    }
    /*
    $Contents .=	"
							<tr>								 
								<td class='search_box_title' > 이미지 정보 </td>
								<td class='search_box_item' >
									<input type='checkbox' name='etc9[]' id='etc9_1' value='1' title='정사각형' ".(is_array($etc9)?in_array('1',$etc9)?'checked':'':'')."/>
									<label for='etc9_1'> 정사각형 </label> 
									<input type='checkbox' name='etc9[]' id='etc9_2' value='2' title='직사각형' ".(is_array($etc9)?in_array('2',$etc9)?'checked':'':'')."/>
									<label for='etc9_2'> 직사각형</label> 
									<input type='checkbox' name='etc9[]' id='etc9_9' value='9' title='이미지없음' ".(is_array($etc9)?in_array('9',$etc9)?'checked':'':'')."/>
									<label for='etc9_9'> 이미지없음</label> 
								</td>
								<td class='search_box_title' > 서비스 분류</td>
								<td class='search_box_item' >
								<div style='float:left;margin-right:5px;'><input type=checkbox name='soho' id='soho'  value='1' ".($soho ? "checked":"")."><label for='soho'>트렌드</label></div>
								<div style='float:left;margin-right:5px;'><input type=checkbox name='designer' id='designer'  value='1'  ".($designer ? "checked":"")."><label for='designer'>디자이너</label></div>
								<div style='float:left;margin-right:5px;'><input type=checkbox name='mirrorpick' id='mirrorpick'  value='1'  ".($mirrorpick ? "checked":"")."><label for='mirrorpick'>미러픽</label></div>
								</td>
							</tr>";
*/
    if($page_type == "update_wish"){
        $Contents .=	"
							<tr>
								<td class='search_box_title'> 관련상품 </td>
								<td class='search_box_item' colspan='3'>
									<input type='checkbox' name='relation_product_check' id='relation_product_check' value='1' ".($relation_product_check == '1'?"checked":"")."> 
									<label for='relation_product_check'>관련상품 미설정상품</label>
								</td>
							</tr>";
    }

    $Contents .=	"
							<tr>
								<td class='search_box_title'>  검색어
								<span style='padding-left:2px' class='helpcloud' help_width='220' help_height='30' help_html='검색하시고자 하는 값을 ,(콤마) 구분으로 넣어서 검색 하실 수 있습니다'><img src='/admin/images/icon_q.gif' align=absmiddle/></span>
								
								<input type='checkbox' name='mult_search_use' id='mult_search_use' value='1' ".($mult_search_use == '1'?'checked':'')." title='다중검색 체크'> 
								<label for='mult_search_use'>(다중검색 체크)</label>
								</td>
								<td class='search_box_item' colspan='3'>
									<table cellpadding=0 cellspacing=0 border='0'>
									<tr>
										<td valign='top'>
											<div style='padding-top:5px;'>
											<select name='search_type' id='search_type'  style=\"font-size:12px;\">
											<option value='p.pname' ".CompareReturnValue("p.pname",$search_type).">상품명</option>
											<option value='p.pcode' ".CompareReturnValue("p.pcode",$search_type).">상품코드</option>
											<option value='p.id' ".CompareReturnValue("p.id",$search_type).">상품시스템코드</option>
											<option value='p.barcode' ".CompareReturnValue("p.barcode",$search_type).">바코드</option>
											<option value='p.admin_memo' ".CompareReturnValue("p.admin_memo",$search_type).">관리메모</option>
											<!--<option value='pod.option_code' ".CompareReturnValue("pod.option_code",$search_type).">옵션코드</option>
											<option value='ccd.com_name' ".CompareReturnValue("ccd.com_name",$search_type).">셀러명</option>
											<option value='p.brand_name' ".CompareReturnValue("p.brand_name",$search_type).">브랜드명</option>-->
											</select>
											</div>
										</td>
										<td style='padding:5px;'>
											<div id='search_text_input_div'>
												<input id=search_texts class='textbox1' value='".$search_text."' autocomplete='off' clickbool='false' style='WIDTH: 210px; height:18px; COLOR: #736357; BACKGROUND-COLOR: #ffffff' name=search_text validation=false  title='검색어'>
											</div>
											<div id='search_text_area_div' style='display:none;'>
												<textarea name='search_text' id='search_text_area' class='tline textbox' style='padding:0px;height:90px;width:150px;' disabled>".$search_text."</textarea>
												<label><input type='radio' name='search_in_out' value='I' ".CompareReturnValue("I",$search_in_out,'checked')." checked />포함</label>
												<label><input type='radio' name='search_in_out' value='O' ".CompareReturnValue("O",$search_in_out,'checked')."/>불포함</label>
											</div>
										</td>
										<td>
											<div>
												<span class='small blu' > 
												    * 다중 검색은 다중 아이디로 검색 지원이 가능합니다. 구분값은 ',' 혹은 'Enter'로 사용 가능합니다. <br /> 
												    * 상품시스템 코드를 기준으로 약 150건의 다중 검색이 가능하며 검색어 길이에 따라 +- 처리 될 수 있습니다.
												</span>
											</div>
										</td>
									</tr>
									</table>
								</td>
							</tr>
						";


    $Contents .=	"
							</table>
							
						</div>";
}else{

    $Contents .=	"
						<div id='search_excel_div' style='display:;'>
						<input type='hidden' name='mode' value='excel_search'>
						<table cellpadding=0 cellspacing=0 border=0 width=100% align='center' class='search_table_box'>
							<col width=17%>
							<col width=33%>
							<col width=17%>
							<col width=33%>
							<tr height=27>
								<td class='search_box_title'><label for='regdate'>등록일자</label><input type='checkbox' name='regdate' id='regdate' value='1' onclick='ChangeRegistDate(document.search_form);' ".CompareReturnValue("1",$regdate,"checked")."></td>
								<td class='search_box_item' colspan=3 >
								<div style='float:left;padding-top:5px;'>
									<select name='search_date_type' id='search_date_type'>
									<option value='1' ".CompareReturnValue("1",$search_date_type,'selected')."> 상품등록일</option>
									<option value='2' ".CompareReturnValue("2",$search_date_type,'selected')."> 상품수정일</option>
									</select>
								</div>
								<div style='float:left; padding-left:10px;'>
									".search_date('sdate','edate',$sDate,$eDate)."
								</div>
								</td>
							</tr>
							<tr>
								<td class='search_box_title' >  검색어(엑셀파일)  </td>
								<td class='search_box_item' colspan='3'>
									<table cellpadding=0 cellspacing=0 border='0'>
									<tr>
										<td valign='top'>
											<div style='padding-top:5px;'>
											<select name='search_type' id='search_type_excel'  style=\"font-size:12px;\">
												<option value='p.pname' ".CompareReturnValue("p.pname",$search_type).">상품명</option>
												<option value='p.pcode' ".CompareReturnValue("p.pcode",$search_type).">상품코드</option>
												<option value='p.id' ".CompareReturnValue("p.id",$search_type).">상품시스템코드</option>
												<option value='pod.option_code' ".CompareReturnValue("pod.option_code",$search_type).">옵션코드</option>
												<option value='ccd.com_name' ".CompareReturnValue("ccd.com_name",$search_type).">셀러명</option>
												<option value='b.brand_name' ".CompareReturnValue("brand_name",$search_type).">브랜드명</option>
											</select>
											</div>
										</td>
										<td style='padding:5px;'>
											<input type='file' class='textbox' name='search_excel_file' id='search_excel_file' style='height:22px;width:90%' validation=false title='엑셀일괄 검색 파일'>
										</td>
									</tr>
									</table>
								</td>
							</tr>
						</table>
						
						</div>";
}

$Contents .=	"
					</td>
					<th class='box_06'></th>
				</tr>
				<tr>
					<th class='box_07'></th>
					<td class='box_08'></td>
					<th class='box_09'></th>
				</tr>
			</table>
		</td>
	</tr>
	</table>

	<table border=0 cellpadding=0 cellspacing=0 width='100%'>
	<tr>
		<td height='50' colspan=2 align=center style='padding:10px 0px'>
			<input type=image src='../images/".$admininfo["language"]."/bt_search.gif' border=0 align=absmiddle> <!--btn_inquiry.gif-->
		</td>
		<!-- 이걸 왜 넣엇는지요 ... 
		<td style='vertical-align:top;'>
			<div style='text-align:right;padding:10px 0px 10px 10px;'>
			목록수 : <select name='max' id='max'>
				<option value='5' ".($_COOKIE[product_update_limit] == '5'?'selected':'').">5</option>
				<option value='10' ".($_COOKIE[product_update_limit] == '10'?'selected':'').">10</option>
				<option value='20' ".($_COOKIE[product_update_limit] == '20'?'selected':'').">20</option>
				<option value='30' ".($_COOKIE[product_update_limit] == '30'?'selected':'').">30</option>
				<option value='50' ".($_COOKIE[product_update_limit] == '50'?'selected':'').">50</option>
				<option value='100' ".($_COOKIE[product_update_limit] == '100'?'selected':'').">100</option>
				<option value='500' ".($_COOKIE[product_update_limit] == '500'?'selected':'').">500</option>
				<option value='1000' ".($_COOKIE[product_update_limit] == '1000'?'selected':'').">1000</option>
			</select>
			</div>
		</td>-->
	</tr>
	</table>
	</form>";

$Script .= "
	<!--script Language='JavaScript' src='../product/product_list.js'></script>
	<script language='javascript' src='/admin/js/jquery.form.js'></script>
	<script language='javascript' src='/admin/js/jquery.form.min.js'></script-->
	<script language='javascript'>

	$(function () { 
		$('#search_type_excel').change(function (){
			var value= $(this).val();
			$('#listfrom_search_type').val(value);	//엑셀일괄 검색은 POST 로 검색되기 때문에 검색어가 먹히지 않아서 listfrom 에 해다 값들을 입력했음 2014-04-16 이학봉
		});
	});

	

	</script>";

?>