<?
// 대량 상품수정 실행파일 2014-07-02 이학봉
include("../class/layout.class");
include '../include/phpexcel/Classes/PHPExcel.php';

if($admininfo[company_id] == ""){
	//echo "<script language='javascript' src='../_language/language.php'></script><script language='javascript'>alert(language_data['common']['C'][language]);location.href='/admin/admin.php'</script>";
    //'관리자 로그인후 사용하실수 있습니다.'
	//exit;
}

if($search_searialize_value){
	$unserialize_search_value = unserialize(urldecode($search_searialize_value));
	extract($unserialize_search_value);
}

$db = new Database;
$db2 = new Database;

//search 조건	시작
include ('../product/product_query_search.php');
// search 조건	끝

/*선택한 회원이나 , 전체 검색한 회원은 같기에 위에서 한번만 선언한다. 2014-04-16 이학봉*/
if($update_type == '2'){		//선택한 상품
	if(is_array($select_pid)){
		$where.=" AND p.id IN ('".implode("','",$select_pid)."')";
	}
}

if($admininfo[admin_level] != '9'){
	$where .= " and p.admin ='".$admininfo[company_id]."' ";
}

if($act == 'excel_down'){
	ini_set('memory_limit','2048M');
	set_time_limit(9999999);

	if($info_type == ""){	//다운받을 엑셀 약식값이 없을경우 본사양식으로 다운 2014-07-25 이학봉
		$info_type = 'company';
	}

	if($update_type == '2'){

		if(is_array($cpid)){
		
		$excel_down_where .=" AND p.id IN ('".implode("','",$cpid)."') ORDER BY p.id DESC ";

		$sql = "SELECT 
					HIGH_PRIORITY p.id,
					p.*,
					r.cid,
					csd.charge_code,
					(select gu.gid from inventory_goods_unit as gu where gu.gu_ix = p.pcode ) as gid,
					 p.bimg, p.mimg, p.msimg, p.simg, p.cimg,p.allow_order_type
					 ,pg.pname as english_pname
					 ,pg.add_info as english_add_info
				FROM
					shop_product p
					force index(regdate_desc) 
					left join shop_product_relation r on (p.id = r.pid and r.basic = '1')
					inner join common_company_detail ccd on (p.admin = ccd.company_id)
					left join common_seller_detail csd on (ccd.company_id = csd.company_id)
					left join shop_product_global pg on (p.id = pg.id)
				where 
					1
					and p.is_delete = '0'
					and p.regdate_desc < 0 
					and p.id is NOT NULL AND p.product_type NOT IN ('4','5','6','21','31')
					$excel_down_where";
		}else{
			echo "<script language='javascript'>alert('다운받을 상품정보가 없습니다.');</script>";
		}

	}

}else{

	$sql = "SELECT 
				HIGH_PRIORITY p.id,
				p.*,
				csd.charge_code,
				(select gu.gid from inventory_goods_unit as gu where gu.gu_ix = p.pcode ) as gid,
				p.bimg, p.mimg, p.msimg, p.simg, p.cimg,p.allow_order_type
			FROM
				shop_product p
				force index(regdate_desc) 
				inner join common_company_detail ccd on (p.admin = ccd.company_id)
				left join common_seller_detail csd on (ccd.company_id = csd.company_id)
				
			where
				1
				and p.is_delete = '0'
				and p.regdate_desc < 0 
				and p.id is NOT NULL AND p.product_type NOT IN ('4','5','6','21','31')
				$where";

}

	$db->query($sql);
	$goods_info = $db->fetchall();

//if($info_type == 'company'){		//운영자용
	$info_type = 'company';
	$excel_file_name = "batch_products_update_excel_new_".$info_type.".xls";

	$objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"]."/admin/product/".$excel_file_name);

	$etc_excel = new PHPExcel();


///////////////////
	// 속성 정의
	$etc_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("etc code List")
								 ->setSubject("etc code List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("etc code List");

	$etc_excel->setActiveSheetIndex(0);
	$etc_excel->getActiveSheet()->setTitle('�뷮��ǰ����');

	$z = 7;

	for($i=0;$i<count($goods_info);$i++){

		$db->fetch($i);

		$col = 'A';


        $sql = "select * from shop_product_global where id = '".$goods_info[$i]['id']."'";
        $db2->query($sql);
        $global_info = $db2->fetch();

		//html 코드 변환 처리
        $goods_info[$i][pname] = htmlspecialchars_decode($goods_info[$i][pname],ENT_QUOTES);
        $goods_info[$i][english_pname] = htmlspecialchars_decode($global_info[pname],ENT_QUOTES);
        $goods_info[$i][basicinfo] = htmlspecialchars_decode($goods_info[$i][basicinfo],ENT_QUOTES);
        $goods_info[$i][m_basicinfo] = htmlspecialchars_decode($goods_info[$i][m_basicinfo],ENT_QUOTES);
        $goods_info[$i][english_add_info] = htmlspecialchars_decode($global_info[add_info],ENT_QUOTES);

		$objPHPExcel->getActiveSheet()->setCellValue('A' . $z , "");
		$objPHPExcel->getActiveSheet()->getStyle('B' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );
		$objPHPExcel->getActiveSheet()->setCellValue('B' . $z , " ".$goods_info[$i][id]);	//��ǰ�ý���Ű
		$objPHPExcel->getActiveSheet()->setCellValue('C' . $z , $goods_info[$i][product_type]);	//��ǰ����
		$objPHPExcel->getActiveSheet()->getStyle('D' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );	//ī�װ�

		//����ī�װ� �߰� 2014-08-09 ���к�
		$sql = "select cid from shop_product_relation where pid = '".$goods_info[$i][id]."' order by basic ASC";
		$db->query($sql);
		$category_array = $db->fetchall();
		for($j=0;$j<count($category_array);$j++){
			if($j != count($category_array) -1){
				$category_enter = "|";
			}

			$cid_text .= $category_array[$j][cid].$category_enter;

			$category_enter = "";
		}

		$objPHPExcel->getActiveSheet()->setCellValue('D' . $z , " ".$cid_text);		//ī�װ� ( | ���а� ù��° ī�װ��� �⺻ī�װ�)

		//MD_id
		$sql = "select id from common_user where id = '".$goods_info[$i][md_code]."'";
		$db->query($sql);
		$db->fetch();
		$md_id = $db->dt[id];
		$objPHPExcel->getActiveSheet()->setCellValue('E' . $z , $goods_info[$i][md_id]);		//MD_���̵�

		$objPHPExcel->getActiveSheet()->setCellValue('F' . $z , $goods_info[$i][pname]);		//��ǰ��

        /*
		if($goods_info[$i][stock_use_yn] == 'Y'){
			$pcode = $goods_info[$i][gid];
		}else{
			$pcode = $goods_info[$i][pcode];
		}
		*/

        $pcode = $goods_info[$i][pcode];

		$objPHPExcel->getActiveSheet()->getStyle('G' . $z)->getFont()->setColor(new PHPExcel_Style_Color('FF000000'));
		$objPHPExcel->getActiveSheet()->getStyle('H' . $z)->getFont()->setColor(new PHPExcel_Style_Color('FF000000'));
		$objPHPExcel->getActiveSheet()->getStyle('I' . $z)->getFont()->setColor(new PHPExcel_Style_Color('FF000000'));
		$objPHPExcel->getActiveSheet()->getStyle('J' . $z)->getFont()->setColor(new PHPExcel_Style_Color('FF000000'));
		$objPHPExcel->getActiveSheet()->setCellValue('G' . $z , $goods_info[$i][english_pname]);		//������ǰ��
        $objPHPExcel->getActiveSheet()->setCellValue('H' . $z , $goods_info[$i][add_info]);		//�߰�����
        $objPHPExcel->getActiveSheet()->setCellValue('I' . $z , $goods_info[$i][english_add_info]);		//�߰�����
		$objPHPExcel->getActiveSheet()->setCellValue('J' . $z , $pcode);		//��ǰ�ڵ�(ǰ���ڵ�)
		$objPHPExcel->getActiveSheet()->setCellValue('K' . $z , $goods_info[$i][paper_pname]);	//���Ի�ǰ��
		$objPHPExcel->getActiveSheet()->setCellValue('L' . $z , $goods_info[$i][barcode]);		//���ڵ�
		$objPHPExcel->getActiveSheet()->setCellValue('M' . $z , $goods_info[$i][shotinfo]);		//��ǰ�����Ұ�
		$objPHPExcel->getActiveSheet()->setCellValue('N' . $z , $goods_info[$i][trade_admin]);	//���Ծ�ü

		$sql = "select og_ix from common_origin where origin_name = '".$goods_info[$i][origin]."'";
		$db->query($sql);
		$db->fetch();
		$objPHPExcel->getActiveSheet()->setCellValue('O' . $z , $db->dt[og_ix]);				//�������ڵ�
		$objPHPExcel->getActiveSheet()->setCellValue('P' . $z , $goods_info[$i][company]);			//�������ڵ�(�ؽ�Ʈ������ ���� 2014-08-10)

		$objPHPExcel->getActiveSheet()->setCellValue('Q' . $z , $goods_info[$i][brand]);		//�귣���ڵ�
		$objPHPExcel->getActiveSheet()->setCellValue('R' . $z , $goods_info[$i][surtax_yorn]);	//�鼼����
		$objPHPExcel->getActiveSheet()->setCellValue('S' . $z , $goods_info[$i][state]);		//�ǸŻ���
		$objPHPExcel->getActiveSheet()->setCellValue('T' . $z , $goods_info[$i][disp]);			//���⿩��
		$objPHPExcel->getActiveSheet()->setCellValue('U' . $z , $goods_info[$i][product_weight]);		//����
		$objPHPExcel->getActiveSheet()->setCellValue('V' . $z , $goods_info[$i][is_sell_date]);			//�ǸűⰣ��뿩��
		$sell_priod_sdate = explode(" ",$goods_info[$i][sell_priod_sdate]);
		$sell_priod_edate = explode(" ",$goods_info[$i][sell_priod_edate]);
		$objPHPExcel->getActiveSheet()->setCellValue('W' . $z , str_replace("-","",$sell_priod_sdate[0])."-".str_replace("-","",$sell_priod_edate[0]));				//�ǸűⰣ����
		$objPHPExcel->getActiveSheet()->setCellValue('X' . $z , $goods_info[$i][delivery_coupon_yn]);			//���������뿩��
		$objPHPExcel->getActiveSheet()->setCellValue('Y' . $z , $goods_info[$i][coupon_use_yn]);				//��ǰ������뿩��
		$objPHPExcel->getActiveSheet()->setCellValue('Z' . $z , $goods_info[$i][search_keyword]);				//�˻�Ű����
		$objPHPExcel->getActiveSheet()->setCellValue('AA' . $z , $goods_info[$i][stock_use_yn]);					//��������뿩��

		$objPHPExcel->getActiveSheet()->setCellValue('AB' . $z , $goods_info[$i][safestock]);				//�������
		$objPHPExcel->getActiveSheet()->setCellValue('AC' . $z , $goods_info[$i][stock]);					//�����

		$objPHPExcel->getActiveSheet()->setCellValue('AD' . $z , $goods_info[$i][movie]);				//������ URL
		$objPHPExcel->getActiveSheet()->setCellValue('AE' . $z , $goods_info[$i][make_date]);			//��������
		$objPHPExcel->getActiveSheet()->setCellValue('AF' . $z , $goods_info[$i][expiry_date]);			//��ȿ��

		if($goods_info[$i][is_adult] == ""){
			$is_adult = '0';
		}else{
			$is_adult = $goods_info[$i][is_adult];
		}
		$objPHPExcel->getActiveSheet()->setCellValue('AG' . $z , $is_adult);				//19�ݻ�ǰ
		$objPHPExcel->getActiveSheet()->setCellValue('AH' . $z , $goods_info[$i][coprice]);				//���ް�
		$objPHPExcel->getActiveSheet()->setCellValue('AI' . $z , $goods_info[$i][wholesale_price]);				//�����ǸŰ�
		$objPHPExcel->getActiveSheet()->setCellValue('AJ' . $z , $goods_info[$i][wholesale_sellprice]);			//�������ΰ�
		$objPHPExcel->getActiveSheet()->setCellValue('AK' . $z , $goods_info[$i][listprice]);					//�Ҹ��ǸŰ�
		$objPHPExcel->getActiveSheet()->setCellValue('AL' . $z , $goods_info[$i][sellprice]);					//�Ҹ����ΰ�
		$objPHPExcel->getActiveSheet()->setCellValue('AM' . $z , $goods_info[$i][premiumprice]);			//�����̾���

		$objPHPExcel->getActiveSheet()->setCellValue('AN' . $z , $goods_info[$i][allow_basic_cnt]);			//�⺻���ۼ���
		$objPHPExcel->getActiveSheet()->setCellValue('AO' . $z , $goods_info[$i][allow_max_cnt]);			//�ִ��Ǹż���
		$objPHPExcel->getActiveSheet()->setCellValue('AP' . $z , $goods_info[$i][wholesale_allow_byoneperson_cnt]);				//ID�籸�ż���
		$objPHPExcel->getActiveSheet()->setCellValue('AQ' . $z , $goods_info[$i][allow_order_type]);		//�����ǸŻ�뿩��
		$objPHPExcel->getActiveSheet()->setCellValue('AR' . $z , $goods_info[$i][allow_order_cnt_byonesell]);			//�����Ǹ� ����
		$objPHPExcel->getActiveSheet()->setCellValue('AS' . $z , $goods_info[$i][delivery_type]);			//���Ÿ��
		$objPHPExcel->getActiveSheet()->setCellValue('AT' . $z , $goods_info[$i][one_commission]);					//�����������뿩��
		$objPHPExcel->getActiveSheet()->setCellValue('AU' . $z , $goods_info[$i][account_type]);				//������
		$objPHPExcel->getActiveSheet()->setCellValue('AV' . $z , ($goods_info[$i][one_commission] == 'N'?getProductCategoryRate($goods_info[$i][id],$goods_info[$i][cid],'W')."|".getProductCategoryRate($goods_info[$i][id],$goods_info[$i][cid],'R'):$goods_info[$i][wholesale_commission]."|".$goods_info[$i][commission]));		//������

		$sql = "select * from shop_product_displayinfo where pid = '".$goods_info[$i][id]."' and dp_use = '1' order by dp_ix asc ";
		$db->query($sql);
		$display_options = $db->fetchall();
		for($j=0;$j<count($display_options);$j++){

			if($j != count($display_options) -1){
				$display_enter = "^\n";
			}
			$display_option .= $display_options[$j][dp_title]."|".$display_options[$j][dp_desc]."|".$display_options[$j][dp_etc_desc].$display_enter;
			$dp_ix .= $display_options[$j][dp_ix].$display_enter;

			$display_enter = '';
		}
		$objPHPExcel->getActiveSheet()->getStyle('AW' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT ); //���÷��̿ɼ�Ű
		$objPHPExcel->getActiveSheet()->setCellValue('AW' . $z , " ".$dp_ix);			//���÷��̿ɼ� Ű
		$objPHPExcel->getActiveSheet()->setCellValue('AX' . $z , $display_option);			//���÷��̿ɼ�

		$sql = "select * from shop_product_viralinfo where pid = '".$goods_info[$i][id]."' and vi_use='1' order by vi_ix asc ";
		$db->query($sql);
		$virals = $db->fetchall();
		for($j=0;$j<count($virals);$j++){
			if($j != count($virals) -1){
				$virals_enter = "^\n";
			}
			$virals_text .= $virals[$j][viral_name]."|".$virals[$j][viral_url]."|".$virals[$j][viral_desc].$virals_enter;
			$vi_ix .= $virals[$j][vi_ix].$virals_enter;
			$virals_enter = '';
		}
		$objPHPExcel->getActiveSheet()->getStyle('AY' . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );
		$objPHPExcel->getActiveSheet()->setCellValue('AY' . $z , " ".$vi_ix);	//���̷����Ű
		$objPHPExcel->getActiveSheet()->setCellValue('AZ' . $z , $virals_text);	//���̷���ϳ���

		$mandatory_type = explode("|",$goods_info[$i][mandatory_type]);
		$objPHPExcel->getActiveSheet()->setCellValue('BA' . $z , $mandatory_type[0]);		//��ǰ�������

		$sql = "select * from shop_product_mandatory_info where pid = '".$goods_info[$i][id]."' order by pmi_ix ASC";
		$db->query($sql);
		$mandatory_array = $db->fetchall();
		for($j=0;$j<count($mandatory_array);$j++){
			if($j != count($mandatory_array) -1){
				$mandatory_enter = "^";
			}
			$pmi_code = explode("|",$mandatory_array[$j][pmi_code]);
			$mandatory .= $pmi_code[1]."|".$mandatory_array[$j][pmi_desc].$mandatory_enter;
			$pmi_ix .= $mandatory_array[$j][pmi_ix].$mandatory_enter;

			$mandatory_enter = '';
		}

		$objPHPExcel->getActiveSheet()->setCellValue('BB' . $z , $mandatory);	//��ǰ��� ����
		$objPHPExcel->getActiveSheet()->setCellValue('BC' . $z , $pmi_ix);		//��ǰ�������ű��


        $mandatory_type_global = explode("|",$goods_info[$i][mandatory_type_global]);
        $objPHPExcel->getActiveSheet()->setCellValue('BD' . $z , $mandatory_type_global[0]);

        $sql = "select * from shop_product_mandatory_info_global where pid = '".$goods_info[$i][id]."' order by pmi_ix ASC";
        $db->query($sql);
        $mandatory_array_global = $db->fetchall();
        for($j=0;$j<count($mandatory_array_global);$j++){
            if($j != count($mandatory_array_global) -1){
                $mandatory_enter_global = "^";
            }
            $pmi_code_global = explode("|",$mandatory_array_global[$j][pmi_code]);
            $mandatory_global .= $pmi_code_global[1]."|".$mandatory_array_global[$j][pmi_desc].$mandatory_enter_global;
            $pmi_ix_global .= $mandatory_array_global[$j][pmi_ix].$mandatory_enter_global;

            $mandatory_enter_global = '';
        }

        $objPHPExcel->getActiveSheet()->setCellValue('BE' . $z , $mandatory_global);
        $objPHPExcel->getActiveSheet()->setCellValue('BF' . $z , $pmi_ix_global);



		$objPHPExcel->getActiveSheet()->setCellValue('BG' . $z , $goods_info[$i][m_basicinfo]);		//����ϻ󼼼���
		$objPHPExcel->getActiveSheet()->setCellValue('BH' . $z , $goods_info[$i][basicinfo]);		//����ǰ�󼼼���
		$objPHPExcel->getActiveSheet()->setCellValue('BI' . $z , '');								//��ǰ�̹���


		$sql = "select
					po.*
				from 
					shop_product_options as po 
				where
					po.pid = '".$goods_info[$i][id]."'
					and po.option_kind in ('c1','c2','i1','i2')
					order by po.opn_ix ASC";
		$db2->query($sql);
		$basic_options_info = $db2->fetchall();

		for($j=0;$j<count($basic_options_info);$j++){

			if($j != count($basic_options_info) -1){
				//$basic_option_div = "|";
				$basic_option_enter = "^";
			}

			$basic_opn_ix .= $basic_options_info[$j][opn_ix].$basic_option_enter;						//�ɼ�Ű
			$basic_option_name .= $basic_options_info[$j][option_name].$basic_option_enter;				//�ɼǸ�
			$basic_option_use .= $basic_options_info[$j][option_use].$basic_option_enter;				//�ɼǻ�뿩��
			$basic_option_kind .= $basic_options_info[$j][option_kind].$basic_option_enter;				//�ɼ�����

			$sql = "select
					*
					from
						shop_product_options_detail
					where
						pid = '".$goods_info[$i][id]."'
						and opn_ix = '".$basic_options_info[$j][opn_ix]."'
						order by id ASC";
			$db2->query($sql);
			$basic_option_detail = $db2->fetchall();

			for($k=0;$k<count($basic_option_detail);$k++){
				if($k != count($basic_option_detail) -1){
					$detail_option_enter = "|";
					//$detail_option_enter = "^";
				}else{
					$detail_option_enter = "^";
				}
				$basic_opd_ix .= $basic_option_detail[$k][id].$detail_option_enter;		//�ɼǱ��� Ű
				$basic_option_soldout .= $basic_option_detail[$k][option_soldout].$detail_option_enter;		//�ɼ�ǰ������
				$basic_option_div .= $basic_option_detail[$k][option_div].$detail_option_enter;		//�ɼǱ���
				$basic_option_price .= $basic_option_detail[$k][option_price].$detail_option_enter;		//�ɼǰ���

				$detail_option_enter = '';
			}

			$basic_option_enter = '';
		}

		$objPHPExcel->getActiveSheet()->setCellValue('BJ' . $z , $basic_opn_ix);				//�⺻�ɼ�(�ɼ�Ű)
		$objPHPExcel->getActiveSheet()->setCellValue('BK' . $z , $basic_option_name);				//�⺻�ɼ�(�ɼǸ�)
		$objPHPExcel->getActiveSheet()->setCellValue('BL' . $z , $basic_option_use);				//�⺻�ɼ�(�ɼǻ�뿩��)
		$objPHPExcel->getActiveSheet()->setCellValue('BM' . $z , $basic_option_kind);			//�⺻�ɼ�(�ɼ�����)

		$objPHPExcel->getActiveSheet()->setCellValue('BN' . $z , $basic_option_soldout);			//�⺻�ɼ�(ǰ������)
		$objPHPExcel->getActiveSheet()->setCellValue('BO' . $z , $basic_option_div);			//�⺻�ɼ�(�⺻�ɼǱ���)
		$objPHPExcel->getActiveSheet()->setCellValue('BP' . $z , $basic_option_price);			//�⺻�ɼ�(�߰�����)
		$objPHPExcel->getActiveSheet()->setCellValue('BQ' . $z , $basic_opd_ix);			//�⺻�ɼ�(�ɼǱ���Ű)

		$sql = "select
					po.*,
					pod.*,
					gu.gid
				from 
					shop_product_options as po 
					inner join shop_product_options_detail as pod on (po.opn_ix = pod.opn_ix)
					left join inventory_goods_unit as gu on (pod.option_code = gu.gu_ix)
				where
					po.pid = '".$goods_info[$i][id]."'
					and po.option_kind = 'b'
					order by pod.id ASC";
		$db2->query($sql);
		$options_info = $db2->fetchall();

		for($j=0;$j<count($options_info);$j++){
			if($j != count($options_info) -1){
				$option_enter = "|";
			}

			$option_div .= $options_info[$j][option_div].$option_enter;						//�ɼǱ���
			$option_coprice .= $options_info[$j][option_coprice].$option_enter;				//�ɼǰ��ް�
			$option_wholesale_listprice .= $options_info[$j][option_wholesale_listprice].$option_enter;				//�ɼǵ����ǸŰ�
			$option_wholesale_price .= $options_info[$j][option_wholesale_price].$option_enter;				//�ɼǵ������ΰ�

			$option_listprice .= $options_info[$j][option_listprice].$option_enter;				//�ɼǼҸ��ǸŰ�
			$option_price .= $options_info[$j][option_price].$option_enter;						//�ɼǼҸ����ΰ�

			$option_stock .= $options_info[$j][option_stock].$option_enter;						//�����
			$option_safestock .= $options_info[$j][option_safestock].$option_enter;				//�������

			if($goods_info[$i][stock_use_yn] == 'Y'){
				$option_code .= $options_info[$j][gid].$option_enter;					//�ɼ� ǰ���ڵ�
			}else{
				$option_code .= $options_info[$j][option_code].$option_enter;					//�ɼ� ǰ���ڵ�
			}

			$option_barcode .= $options_info[$j][option_barcode].$option_enter;				//�ɼ� ���ڵ�
			$option_soldout .= $options_info[$j][option_soldout].$option_enter;				//�ɼ� ǰ������

			$option_enter = '';
		}

		$objPHPExcel->getActiveSheet()->setCellValue('BR' . $z , $options_info[0][opn_ix]);			//���������� �ɼ�Ű
		$objPHPExcel->getActiveSheet()->setCellValue('BS' . $z , $options_info[0][option_name]);			//���������� �ɼǸ�
		$objPHPExcel->getActiveSheet()->setCellValue('BT' . $z , $option_div);			//�ɼǱ���
		$objPHPExcel->getActiveSheet()->setCellValue('BU' . $z , $option_coprice);			//�ɼǰ��ް�
		$objPHPExcel->getActiveSheet()->setCellValue('BV' . $z , $option_wholesale_listprice);			//�ɼǵ����ǸŰ�
		$objPHPExcel->getActiveSheet()->setCellValue('BW' . $z , $option_wholesale_price);			//�ɼǵ������ΰ�
		$objPHPExcel->getActiveSheet()->setCellValue('BX' . $z , $option_listprice);			//�ɼǼҸ��ǸŰ�
		$objPHPExcel->getActiveSheet()->setCellValue('BY' . $z , $option_price);			//�ɼǼҸ����ΰ�
		$objPHPExcel->getActiveSheet()->setCellValue('BZ' . $z , $option_stock);			//�����

		$objPHPExcel->getActiveSheet()->setCellValue('CA' . $z , $option_soldout);			//�ɼ�(ǰ������)
		$objPHPExcel->getActiveSheet()->setCellValue('CB' . $z , $option_safestock);			//�������

		$objPHPExcel->getActiveSheet()->setCellValue('CD' . $z , $option_code);			//�ɼ�(ǰ���ڵ�)
		$objPHPExcel->getActiveSheet()->setCellValue('CE' . $z , $option_barcode);			//�ɼ�(���ڵ�)

		$objPHPExcel->getActiveSheet()->setCellValue('CF' . $z , 'Y');			//���ļ��λ������
		$objPHPExcel->getActiveSheet()->setCellValue('CG' . $z , 'Y');			//���������Ͽ� �������
        $objPHPExcel->getActiveSheet()->setCellValue('CH' . $z , $goods_info[$i]['preface']);
        $objPHPExcel->getActiveSheet()->setCellValue('CI' . $z , $global_info['preface']);
        $objPHPExcel->getActiveSheet()->setCellValue('CJ' . $z , $goods_info[$i]['regdate']);

        $z++;

		//�⺻�ɼǰ���
		$basic_opn_ix = '';
		$basic_option_name = '';
		$basic_option_use = '';
		$basic_option_kind = '';

		$basic_option_soldout = '';
		$basic_option_div = '';
		$basic_option_price = '';
		$basic_opd_ix = '';

		//�������ɼǰ���
		$option_div = '';
		$option_coprice = '';
		$option_wholesale_listprice = '';
		$option_wholesale_price = '';
		$option_listprice = '';
		$option_price = '';
		$option_stock = '';
		$option_safestock = '';
		$option_code = '';
		$option_barcode = '';
		$option_soldout = '';
		
		$dp_ix = '';
		$display_option = '';

		$vi_ix = '';
		$virals_text = '';

        $pmi_ix = '';
        $mandatory = '';
        $pmi_ix_global = '';
        $mandatory_global = '';
		$cid_text = '';
		
	}

/////////////////////

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename=batch_products_update_excel.xls');
	header('Cache-Control: max-age=0');

	$objPHPExcel = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
	$objPHPExcel->save('php://output');

?>