<?php
include($_SERVER["DOCUMENT_ROOT"] . "/admin/class/layout.class");
include("../lib/imageResize.lib.php");
include '../include/phpexcel/Classes/PHPExcel.php';
include('goods_mandatory_info.lib.php');
include("../product/product_input_excel.lib.php");

unset($goods_mandatory_info); //DB에서 불러오기에 기존 데이타 삭제 2014-04-01 이학봉

//Excel upload Memory Limit
set_time_limit(9999999999);
ini_set('memory_limit', -1);
//

$removestring = array("\n", "\t");

if ($admininfo[company_id] == "") {
    echo "<script language='javascript' src='../_language/language.php'></script><script language='javascript'>alert(language_data['common']['C'][language]);location.href='../'</script>";
    //'관리자 로그인후 사용하실수 있습니다.'
    exit;
}

$db = new Database;
$image_db = new Database;

//상품고시 정부 DB에서 불러와서 배열로 마추기 2014-04-01 이학봉
$sql = "select
			*
			from
				shop_mandatory_info as mi 
				inner join shop_mandatory_detail as md on (mi.mi_ix = md.mi_ix)
			where
				is_use = '1'
				order by md.seq ASC";
$db->query($sql);
$data_array = $db->fetchall();

for ($i = 0; $i < count($data_array); $i++) {
    $goods_mandatory_info[$data_array[$i][mi_code]][$data_array[$i][mid_code]][$i][code] = $data_array[$i][detail_code];
    $goods_mandatory_info[$data_array[$i][mi_code]][$data_array[$i][mid_code]][$i][title] = $data_array[$i][mid_title];
    $goods_mandatory_info[$data_array[$i][mi_code]][$data_array[$i][mid_code]][$i][desc] = $data_array[$i][mid_desc];
    $goods_mandatory_info[$data_array[$i][mi_code]][$data_array[$i][mid_code]][$i][comment] = $data_array[$i][mid_comment];
    $goods_mandatory_info[$data_array[$i][mi_code]][$data_array[$i][mid_code]][$i][validation] = 'true';
    $goods_mandatory_info[$data_array[$i][mi_code]][$data_array[$i][mid_code]][$i][sample] = '';
}

//상품고시 정부 DB에서 불러와서 배열로 마추기 2014-04-01 이학봉

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 카테고리 브랜드 코드 엑셀 다운로드
/// 작성 : 홍진영 ( 2013.05.03 )
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if ($_GET["act"] == "ect_code_down") {

    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    $etc_excel = new PHPExcel();

    // 속성 정의
    $etc_excel->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("Mallstory.com")
        ->setTitle("etc code List")
        ->setSubject("etc code List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("mallstory")
        ->setCategory("etc code List");

    $etc_excel->setActiveSheetIndex(0);
    $etc_excel->getActiveSheet()->setTitle('카테고리');

    $ct_excel_info = array("대분류", "중분류", "소분류", "카테고리코드", "");
    $col = 'A';
    foreach ($ct_excel_info as $ci) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $ci);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $col++;
    }

    $db->query("select cid from shop_category_info order by cid");
    $db->fetch();
    $z = 2;

    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';
        //$ct_name=explode('>',$db->dt[ct_name]);
        $ct_name = explode('>', getCategoryPathByAdmin($db->dt[cid], 4));
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name[0]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name[1]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name[2]);
        $col++;
        $etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_TEXT);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, " " . $db->dt[cid]);
        $col++;
        //$etc_excel->getActiveSheet()->getStyle($col . $z)->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
        $etc_excel->getActiveSheet()->setCellValue($col . $z, (substr($db->dt[cid], 0, 3) == '010' ? '업체 사용금지' : ''));

        $z++;
    }

    $etc_excel->createSheet();
    $etc_excel->setActiveSheetIndex(1);
    $etc_excel->getActiveSheet()->setTitle('MD');

    $md_excel_info = array("MD명", "MD이메일", "MD코드");
    $col = 'A';

    foreach ($md_excel_info as $md) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $md);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $col++;
    }

    $sql = "SELECT  cu.code, cu.id, AES_DECRYPT(UNHEX(cmd.name),'" . $db->ase_encrypt_key . "') as name,  
				AES_DECRYPT(UNHEX(cmd.mail),'" . $db->ase_encrypt_key . "') as mail,
				AES_DECRYPT(UNHEX(cmd.pcs),'" . $db->ase_encrypt_key . "') as pcs
				FROM " . TBL_COMMON_USER . " cu inner join " . TBL_COMMON_MEMBER_DETAIL . " cmd on cu.code = cmd.code
				where cu.mem_div = 'MD'
				order by  name asc ";
    $db->query($sql);

    $z = 2;
    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[name]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[mail]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[code]);
        $z++;
    }

    $etc_excel->createSheet();
    $etc_excel->setActiveSheetIndex(2);
    $etc_excel->getActiveSheet()->setTitle('브랜드');

    $b_excel_info = array("브랜드명", "브랜드코드");
    $col = 'A';

    foreach ($b_excel_info as $bi) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $bi);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $col++;
    }

    $db->query("select b_ix,brand_name from shop_brand where disp='1' order by brand_name");
    $db->fetch();

    $z = 2;
    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[brand_name]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[b_ix]);
        $z++;
    }


    $etc_excel->createSheet();
    $etc_excel->setActiveSheetIndex(3);
    $etc_excel->getActiveSheet()->setTitle('제조사');

    $c_excel_info = array("제조사명", "제조사코드");
    $col = 'A';

    foreach ($c_excel_info as $c) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $c);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $col++;
    }

    $db->query("select c_ix,company_name from shop_company where disp='1' order by company_name");
    $db->fetch();

    $z = 2;
    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[company_name]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[c_ix]);
        $z++;
    }

    $etc_excel->createSheet();
    $etc_excel->setActiveSheetIndex(4);
    $etc_excel->getActiveSheet()->setTitle('원산지');

    $o_excel_info = array("원산지명", "원산지코드");
    $col = 'A';

    foreach ($o_excel_info as $oi) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $oi);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $col++;
    }

    $db->query("select og_ix,origin_name from common_origin where disp='1' ");
    $db->fetch();

    $z = 2;
    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[origin_name]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[og_ix]);
        $z++;
    }


    $etc_excel->createSheet();
    $etc_excel->setActiveSheetIndex(5);
    $etc_excel->getActiveSheet()->setTitle('표준카테고리');

    $ct_excel_info = array("대분류", "중분류", "소분류", "세분류", "카테고리코드");
    $col = 'A';
    foreach ($ct_excel_info as $ci) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $ci);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $col++;
    }

    $db->query("select cid from standard_category_info order by cid");
    $db->fetch();
    $z = 2;

    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';
        //$ct_name=explode('>',$db->dt[ct_name]);
        $ct_name = explode('>', getStandardCategoryPathByAdmin($db->dt[cid], 4));
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name[0]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name[1]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name[2]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $ct_name[3]);
        $col++;
        $etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_TEXT);
        $etc_excel->getActiveSheet()->setCellValue($col . $z, " " . $db->dt[cid]);
        $col++;
        //$etc_excel->getActiveSheet()->getStyle($col . $z)->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
        $etc_excel->getActiveSheet()->setCellValue($col . $z, (substr($db->dt[cid], 0, 3) == '010' ? '업체 사용금지' : ''));

        $z++;
    }


    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename=etc_code_v1.xls');
    header('Cache-Control: max-age=0');

    $etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
    $etc_excel->save('php://output');
}


//print_r($_POST);
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 샘플 엑셀 다운로드
/// 작성 : 신훈식 ( 2013.04.29 )
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if ($_POST["act"] == "sample_excel_down") {

    $selected_mandatory_info = $goods_mandatory_info[$mandatory_type_1][$mandatory_type_2];    //DB저장후 2차배열까지만 사용 2014-04-01 이학봉

    $tmp_sample_excel_info = array_merge($goods_basic_sample, $selected_mandatory_info);

    $sample_excel_info = array_merge($tmp_sample_excel_info, $goods_options_sample);

    //echo "aaa".intval($_POST["mandatory_type_1"]);
    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    $sample_excel = new PHPExcel();

    // 속성 정의
    $sample_excel->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("Mallstory.com")
        ->setTitle("accounts plan price List")
        ->setSubject("accounts plan price List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("mallstory")
        ->setCategory("accounts plan price List");
    $col = 'A';

    foreach ($sample_excel_info as $key => $value) {

        if ($value[validation] == 'true') {
            $sample_excel->getActiveSheet(0)->getStyle($col . "1")->getFont()->getColor()->setARGB("FFFF0000");
        }

        if ($value[code] == "mandatory_type") {
            //$mandatory_type = $_POST["mandatory_type_1"].$mandatory_type_2.$mandatory_type_3;
            $mandatory_type = $_POST["mandatory_type_1"] . $mandatory_type_2;    //2차배열까지만 2014-04-01 이학봉
            $sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "2", " " . $mandatory_type);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
            $sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
            $col++;
        } elseif ($value[code] == "category") {
            $sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "2", $value[sample]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
            $sample_excel->getActiveSheet(0)->getStyle($col . "2")->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER);
            $sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
            $col++;
        } elseif ($value[code] == "admin") {
            $sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "2", $admininfo[company_id]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
            $sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
            $col++;
        } elseif ($value[code] == "product_type") {
            $sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "2", $product_type);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
            $sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
            $col++;
        } else {
            $sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "2", $value[sample]);
            $sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
            $sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
            $col++;
        }
    }

    $sample_excel->getActiveSheet(0)->getStyle('A' . "4")->getFont()->getColor()->setARGB("FFFF0000");
    $sample_excel->getActiveSheet(0)->setCellValue('A' . "4", '빨간색 글씨로 되어있는 항목은 필수 입니다. !!');


    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="sample_excel.xls"');
    header('Cache-Control: max-age=0');

    $objWriter = PHPExcel_IOFactory::createWriter($sample_excel, 'Excel5');
    $objWriter->save('php://output');
    exit;

}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 상품등록
/// 작성 : 신훈식 ( 2013.04.29 )
/// 내용 : 엑셀 업로드된 데이타를 shared memory 에 저장후 한개씩 처리해서 결과를 반영해 나가는 구조로 바꾼다.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

if ($act == "new_excel_input") {    //대량상품등록 엑셀정보 저장

    include("../include/lib/pclzip.lib.php");

    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    if ($excel_file_size > 0) {
        copy($excel_file, $_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/images/upfile/" . $excel_file_name);
    }

    if ($goods_img_file_size > 0) {
        copy($goods_img_file, $_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/BatchUploadImages/" . $goods_img_file_name);

        //PclZip 객체를 생성합니다.
        //$객체 = new PclZip("생성할 압축파일 이름");
        $zipfile = new PclZip($_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/BatchUploadImages/" . $goods_img_file_name);

        $extract = $zipfile->extract(PCLZIP_OPT_PATH, $_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/BatchUploadImages/" . str_replace(".zip", "", $goods_img_file_name));

    }

    $objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/images/upfile/" . $excel_file_name);

    $shift_num = 0;

    //$rownum = 6;

    //$columnVar = $objPHPExcel->setActiveSheetIndex(0)->getCell('A' . ($rownum))->getValue();

    include("../logstory/class/sharedmemory.class");
    $shmop = new Shared("upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);
    $shmop->filepath = $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/_shared/";
    //echo $shmop->filepath;
    $shmop->SetFilePath();
    $upload_excel_data = $shmop->getObjectForKey("upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);

    $upload_excel_data = "";

    /*
    $col = 'A';
    for($i=0;$i < count($goods_basic_sample)-1;$i++){
        $col++;
    }
    */

    $col = 'A';

    foreach ($goods_basic_sample as $key => $value) {
        $upload_excel_data[session_id()][0][$value[code]] = $value[title];//$objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
        $col++;
    }

    $z = 0;
    //while (($objPHPExcel->getActiveSheet()->getCell('B' . $rownum)->getValue() != "") && ($rownum < 500)) {

    // 데이터는 3줄부터 시작, 1, 2줄은 제목+코드명
    //for($rownum=7;$rownum<=30000;$rownum++){
    for ($rownum = 6; $rownum <= 30000; $rownum++) {

        $pcode = $objPHPExcel->getActiveSheet()->getCell('I' . $rownum)->getValue();

        if ($objPHPExcel->getActiveSheet()->getCell('B' . $rownum)->getValue() != "" || $objPHPExcel->getActiveSheet()->getCell('B' . $rownum)->getValue() == "0") {

            //continue;

            $col = 'A';
            foreach ($goods_basic_sample as $key => $value) {

                // PHPExcel_RichText
                if (is_object($objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue())) {
                    $objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell($col . $rownum));
                    $upload_excel_data[session_id()][$z + 1][$value[code]] = $objRichText->getPlainText();
                } else {
                    $upload_excel_data[session_id()][$z + 1][$value[code]] = $objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
                }
                $col++;
            }

            $upload_excel_data[session_id()][$z + 1][p_no] = $z;
            $upload_excel_data[session_id()][$z + 1][company_id] = $company_id;
            $upload_excel_data[session_id()][$z + 1][mall_ix] = $company_id;

            $upload_excel_data[session_id()][$z + 1][goods_img_file] = $goods_img_file_name;

        }
        $z++;
        //$rownum++;
    }

    $shmop->setObjectForKey($upload_excel_data, "upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);
    if ($page_type == 'input') {
        echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./product_input_excel.php?up_mode=new_upload'</script>";
    } else {
        echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./product_update_excel.php?up_mode=new_upload'</script>";
    }
    exit;
}


if ($act == "single_goods_reg" && strlen($p_no) > 0) {        //메모리에 저장된 대량상품등록 정보로 상품추가 부분 2014-06-18 이학봉


    //대량수정일경우 체크된 버튼 처리 시작 2014-08-16 이학봉

    if ($page_type == 'update') {
        $check_array = $_REQUEST[check_data];
        if (is_array($check_array) && count($check_array)) {

            for ($i = 0; $i < count($check_array); $i++) {
                $check_infos[$check_array[$i][name]] = $check_array[$i][value];
            }

        } else {
            //체크버튼이 없을경우 처리하지 않음
            $insert_yn = false;
            //$result_massage .= "<span class='red'>상품시스템코드 체크는 필수 입니다. </span><br/>";
            return false;
        }
    }

    include("../logstory/class/sharedmemory.class");

    $shmop = new Shared("upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);
    //	$shmop->clear();
    $shmop->filepath = $_SERVER["DOCUMENT_ROOT"] . $_SESSION["admininfo"]["mall_data_root"] . "/_shared/";
    $shmop->SetFilePath();
    $upload_excel_data = $shmop->getObjectForKey("upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);

    $select_excel_goods_infos = filter_by_value($upload_excel_data[session_id()], 'p_no', $p_no);

    foreach ($select_excel_goods_infos as $key => $value) {
        /*
        if($key < 5){	//5번짜 라인부터 상품등록 하게끔 설정 2014-06-24 이학봉
            continue;
        }
        */

        $insert_yn = true;
        $result_massage = "";

        foreach ($value as $_key => $_value) {
            if ($_key == 'mandatory_type' || $_key == 'mandatory_type_global') {
                $$_key = trim($_value);
            }

            //필수값 체크!!!
            foreach ($goods_basic_sample as $basic_sample) {
                if ($basic_sample[code] == $_key) {
                    if ($basic_sample[validation] == "true" && $_value == "" && $_value != "0" && $_key != "product_type") {
                        $insert_yn = false;
                        $result_massage .= "<span class='red'>" . $basic_sample[title] . " " . $_value . " 이(가) 없습니다.</span><br/>";
                    }
                }
            }
        }

        foreach ($value as $_key => $_value) {
            if ($_key != 'mandatory_type' && $_key != 'mandatory_type_global') {
                $$_key = trim(str_replace("'", "&#39;", $_value));
            }
        }
        if ($_SESSION['admininfo']['charger_id'] == 'forbiz' || $_SERVER[REMOTE_ADDR] == '221.151.188.11') {
            if ($company_id == "") {        //포비즈 전용 엑셀에 입점업체 키값이 잇을경우 입점업체로 등록됨. 2014-07-07 이학봉
                $company_id = $admin;
            }
        }

        $gid = $pcode;


        if (($_SESSION['admininfo']['charger_id'] == 'forbiz' || $_SERVER[REMOTE_ADDR] == '221.151.188.11') && false) {    //외부 아이피 : 221.151.188.11 내부 아이피 : 192.168.0.1

            $sql = "select id from shop_product where pname = '" . $pname . "' and  admin = '" . $company_id . "' and pcode = '" . $pcode . "'";
            $db->query($sql);
            $db->fetch();

            if ($db->total > 0) {
                echo "<span class='blue'>이미 등록(동일 상품명)</span>";
                $upload_excel_data[session_id()][$key][status] = "C";
                $upload_excel_data[session_id()][$key][status_message] = "등록완료";
                continue;
            }
        }

        //상품구분
        if (empty($product_type)) {    //상품구분이 없을경우를 위함
            $product_type = '0';
        }

        //필터정보
        $filter_info_array = explode("|", $filter_info);

        for ($i = 0; $i < count($filter_info_array); $i++) {
            $filter_code = $filter_info_array[$i];

            $sql = "SELECT idx, filter_type FROM shop_product_filter WHERE filter_code = '" . $filter_code . "'";
            $db->query($sql);
            $db->fetch();
            $filter_info_array_filter_type = $db->dt[filter_type];
            $filter_info_array_idx = $db->dt[idx];
            $product_filter[$filter_info_array_filter_type][] = $filter_info_array_idx;
        }

        //선택값 체크 시작 2014-07-21 이학봉
        //1. 상품타입
        $product_type_array = array('0', '5', '12');

        if (!in_array($product_type, $product_type_array)) {
            $insert_yn = false;
            $result_massage .= "<span class='red'>상품구분값이 정상적이지 않습니다.</span><br/>";
        }

        if ($product_type == '5') {
            $product_type = '12';
        }

        //2. 면세여부
        $surtax_yorn_array = array('Y', 'N');
        if (!in_array($surtax_yorn, $surtax_yorn_array)) {
            $insert_yn = false;
            $result_massage .= "<span class='red'>면세구분값이 정상적이지 않습니다.</span><br/>";
        }

        //3. 판매상태
        $state_array = array('0', '1', '2', '6', '7', '8', '9');
        if (!in_array($state, $state_array)) {
            $insert_yn = false;
            $result_massage .= "<span class='red'>판매상태값이 정상적이지 않습니다.</span><br/>";
        }

        //5. 노출여부
        $disp_array = array('1', '0');
        if (!in_array($disp, $disp_array)) {
            $insert_yn = false;
            $result_massage .= "<span class='red'>노출여부값이 정상적이지 않습니다.</span><br/>";
        }

        //6. 판매기간사용여부
        $is_sell_date_array = array('1', '0');
        if (!in_array($is_sell_date, $is_sell_date_array)) {
            $insert_yn = false;
            $result_massage .= "<span class='red'>판매기간 사용여부값이 정상적이지 않습니다.</span><br/>";
        }

        //7. 배송쿠폰사용여부
        /*
		$delivery_coupon_yn_array = array('Y','N');
		if(!in_array($delivery_coupon_yn,$delivery_coupon_yn_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>배송쿠폰 사용여부값이 정상적이지 않습니다.</span><br/>";
		}
		*/

        //8. 상품쿠폰사용여부
        $coupon_use_yn_array = "Y";
        /*$coupon_use_yn_array = array('Y', 'N');
        if (!in_array($coupon_use_yn, $coupon_use_yn_array)) {
            $insert_yn = false;
            $result_massage .= "<span class='red'>상품쿠폰 사용여부값이 정상적이지 않습니다.</span><br/>";
        }*/

        //10. 재고관리 사용여부
        /*
		$stock_use_yn_array = array('N','Q','Y');
		if(!in_array($stock_use_yn,$stock_use_yn_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>재고관리 사용여부값이 정상적이지 않습니다.</span><br/>";
		}
		*/

        //11. 19금 사용여부
        /*
		$is_adult_array = array('1','0');
		if(!in_array($is_adult,$is_adult_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>19금 사용여부값이 정상적이지 않습니다.</span><br/>";
		}
		*/

        //13. 배송타입선택
        /*
		$delivery_type_array = array('1','2');
		if(!in_array($delivery_type,$delivery_type_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>배송타입선택 값이 정상적이지 않습니다.</span><br/>";
		}
        */

        if ($admininfo[admin_level] == '9') {    //본사등록시에만 체크
            //12. 한정판매 사용여부
            /*
            $allow_order_type_array = array('1','0');
            if(!in_array($allow_order_type,$allow_order_type_array)){
                $insert_yn=false;
                $result_massage .= "<span class='red'>한정판매 사용여부값이 정상적이지 않습니다.</span><br/>";
            }
            */

            //13. 개별수수료 사용여부
            /*
            $one_commission_array = array('Y','N');
            if(!in_array($one_commission,$one_commission_array)){
                $insert_yn=false;
                $result_massage .= "<span class='red'>개별수수료 사용여부값이 정상적이지 않습니다.</span><br/>";
            }
            */

            if ($one_commission == "Y") {
                //14. 정산방식
                $account_type_array = array('1', '2', '3');
                if (!in_array($account_type, $account_type_array)) {
                    $insert_yn = false;
                    $result_massage .= "<span class='red'>정산방식값이 정상적이지 않습니다.</span><br/>";
                }
            }

        } else {    //셀러담당자일경우 기본값으로 입력
            $allow_order_type = '0';        //한정수량판매 사용여부 (사용안함)
            $allow_order_cnt_byonesell = '0';    //한정판매수량
            $account_type = '1';            //정산방식 (판매가정산)
            $one_commission = 'N';            //개별수수료 사용여부 (사용안함)
            $coupon_use_yn = 'Y';
            $delivery_coupon_yn = 'Y';        //
            $delivery_type = '2';            //배송타입 : 입점업체배송
        }

        //체크 완료 2014-07-21 이학봉


        //카테고리
        //카테고리 엑셀수정시 # 일경우 수정하지 않음 2014-08-09 확인일자
        if ($category != "#") {
            /*
            $basic = $category;	//카테고리는 기본카테고리로 저장됨 2014-06-18 이학봉
            if(strlen($category) == '15'){
                $display_category[0]=$category;
            }*/

            //다중카테고리 입력가능하게 처리 2014-08-09 이학봉
            $category_array = explode("|", trim($category));
            if (count($category_array) > 0) {
                $basic = $category_array[0];    //첫번째 카테고리를 기본으로 지정함 2014-08-09 이학봉
                $display_category = $category_array;
            }
        }

        //판매상태
        if ($admininfo[admin_level] != 9) {        //셀러업체일경우에는 등록신청중으로 등록됨 2014-06-18 이학봉
            $state = "6";//등록신청중
        }

        //MD코드
        $db->query("select * from common_user where id = '" . $md_id . "' and mem_type='A' and mem_div='MD' ");
        $db->fetch();
        $md_code = $db->dt[code];

        //원산지
        $db->query("select * from common_origin where og_ix = '" . $og_ix . "'");
        $db->fetch();
        $origin = $db->dt[origin_name];

        if($mall_ix == ""){
            $mall_ix = "20bd04dac38084b2bafdd6d78cd596b1";
        }

        //제조사
        //제조사는 텍스트로 입력하게끔 변경 2014-08-09 이학봉
        /*
        if($company_code!=""){
            $db->query("SELECT company_name FROM shop_company where c_ix = '".$company_code."' ");
            $db->fetch();
            $company=$db->dt[company_name];
        }
        $c_ix = $company_code;
        */

        $company = $company;        //제조사

        //브랜드는 $brand 로 넘기면됨

        //판매기간 설정
        if ($sell_priod_date != "") {
            $sell_priod_date_array = explode("-", $sell_priod_date);
            $sell_priod_sdate = substr($sell_priod_date_array[0], 0, 4) . "-" . substr($sell_priod_date_array[0], 4, 2) . "-" . substr($sell_priod_date_array[0], 6, 2);
            $sell_priod_edate = substr($sell_priod_date_array[1], 0, 4) . "-" . substr($sell_priod_date_array[1], 4, 2) . "-" . substr($sell_priod_date_array[1], 6, 2);
        }

        //$is_mobile_use = 'W';	//모바일 상품 사용유무는 엑셀일괄등록시 웹용으로 기본 세팅됨 2014-08-13 이학봉
        $is_mobile_use = 'A';

        //기본시작수량
        $wholesale_allow_basic_cnt = $allow_basic_cnt;    //도매기본시작수량
        $allow_basic_cnt = $allow_basic_cnt; //소매기본시작수량

        //최대판매수량
        $wholesale_allow_max_cnt = $allow_max_cnt;        //도매최대판매수량
        $allow_max_cnt = $allow_max_cnt;                //소매최대판매수량

        //ID당 구매수량
        $wholesale_allow_byoneperson_cnt = $wholesale_allow_byoneperson_cnt;    //도매ID당 구매수량
        $allow_byoneperson_cnt = $wholesale_allow_byoneperson_cnt;                //소매ID당 구매수량

        //상품개별정책 사용유무 및 배송정책 템플리 키값 설정
        if ($page_type == 'input') {    //배송정책은 대량등록시에만 적용됨 2014-08-04
            $delivery_policy = '1';        //기본사용안함으로 설정 2014-06-18 이학봉
            $sql = "select * from shop_delivery_template where company_id = '" . $company_id . "' and is_basic_template = '1'";
            $db->query($sql);
            $delivery_array = $db->fetchall();
            for ($i = 0; $i < count($delivery_array); $i++) {
                $dt_ix[$delivery_array[$i][product_sell_type]][1][template_check] = '1';
                $dt_ix[$delivery_array[$i][product_sell_type]][1][dt_ix] = $delivery_array[$i][dt_ix];
            }
        }

        //수수료 설정
        if ($commission != "") {
            $commission_array = explode("|", $commission);
            $commission = $commission_array[1];
            $wholesale_commission = $commission_array[0];
        }

        //한정판매수량
        if ($allow_order_type == '0') {
            $allow_order_cnt_byonesell = '0';
        }

        //판매기간이 빈값일경우
        if ($is_sell_date == "") {
            $is_sell_date = '0';
        }

        //상품오프라인 코드 (WMS사용시 아래부분에서 다시 gu_ix 로 값을 구해서 넘김) 2014-07-07 이학봉
        $pcode = $gid;

        //디스플레이 옵션
        if ($display_option != "") {
            $display_options_array = explode("^", $display_option);
            $display_options = "";
            for ($i = 0; $i < count($display_options_array); $i++) {
                $detail_array = explode("|", $display_options_array[$i]);
                $display_options[$i][dp_use] = '1';
                $display_options[$i][dp_title] = trim($detail_array[0]);
                $display_options[$i][dp_desc] = trim($detail_array[1]);
                $display_options[$i][dp_etc_desc] = trim($detail_array[2]);
            }
        }


        //바이럴등록
        if ($virals != "") {
            $virals_array = explode("^", $virals);
            $virals = "";
            for ($i = 0; $i < count($virals_array); $i++) {
                $virals_detail_array = explode("|", $virals_array[$i]);
                $virals[$i][vi_use] = '1';
                $virals[$i][viral_name] = trim($virals_detail_array[0]);
                $virals[$i][viral_url] = trim($virals_detail_array[1]);
                $virals[$i][viral_desc] = trim($virals_detail_array[2]);
            }
        }

        //상품고시정보
        $mandatory_type_1 = trim($mandatory_type);    //고시정보유형
        $mandatory_type_2 = '1';    //고시정보유형

        if ($mandatory_info != "") {
            $mandatory_use = 'Y';
            $mandatory_info_array = explode("^", $mandatory_info);
            $pmi_ix_array = explode("^", $pmi_ix);
            $mandatory_info = "";
            for ($i = 0; $i < count($mandatory_info_array); $i++) {
                $mandatory_detail_array = explode("|", $mandatory_info_array[$i]);
                $sql = "select * from shop_mandatory_detail where mi_ix = '" . $mandatory_type . "' and detail_code = '" . trim($mandatory_detail_array[0]) . "'";

                $db->query($sql);
                $db->fetch();

                $mandatory_info[$i][pmi_ix] = trim($pmi_ix_array[$i]);
                $mandatory_info[$i][pmi_code] = trim($mandatory_type) . "|" . trim($mandatory_detail_array[0]);
                $mandatory_info[$i][pmi_title] = trim(str_replace("'", "&#39;", $db->dt[mid_title]));
                $mandatory_info[$i][pmi_desc] = trim(str_replace("'", "&#39;", $mandatory_detail_array[1]));
                //trim(str_replace("'","&#39;",$_value));
            }
        }

        //상품고시정보(영문)
        $mandatory_type_1_global = trim($mandatory_type_global);    //고시정보유형
        $mandatory_type_2_global = '1';    //고시정보유형

        if ($mandatory_info_global != "") {
            $mandatory_use_global = 'Y';
            $mandatory_info_array_global = explode("^", $mandatory_info_global);
            $pmi_ix_array_global = explode("^", $pmi_ix_global);
            $mandatory_info_global = "";
            for ($i = 0; $i < count($mandatory_info_array_global); $i++) {
                $mandatory_detail_array_global = explode("|", $mandatory_info_array_global[$i]);
                $sql = "select * from shop_mandatory_detail where mi_ix = '" . $mandatory_type_global . "' and detail_code = '" . trim($mandatory_detail_array_global[0]) . "'";

                $db->query($sql);
                $db->fetch();

                $mandatory_info_global[$i][pmi_ix] = trim($pmi_ix_array_global[$i]);
                $mandatory_info_global[$i][pmi_code] = trim($mandatory_type_global) . "|" . trim($mandatory_detail_array_global[0]);
                $mandatory_info_global[$i][pmi_title] = trim(str_replace("'", "&#39;", $db->dt[mid_title]));
                $mandatory_info_global[$i][pmi_desc] = trim(str_replace("'", "&#39;", $mandatory_detail_array_global[1]));
                //trim(str_replace("'","&#39;",$_value));
            }
        }

        //상품기본옵션 추가 2014-08-09 이학봉
        if ($basic_option_name != "") {    //옵션명으로 구분

            $basic_option_name_array = explode("^", trim($basic_option_name));    //옵션명
            $basic_option_kind_array = explode("^", trim($basic_option_kind));    //옵션종류

            $basic_opd_ix_array = explode("^", trim($basic_opd_ix));    //옵션구분키
            $basic_option_div_array = explode("^", trim($basic_option_div));    //옵션구분
            $basic_option_soldout_array = explode("^", trim($basic_option_soldout));    //품절여부
            $basic_option_price_array = explode("^", trim($basic_option_price));    //옵션가격

            if ($page_type == 'update') {
                $basic_opn_ix_array = explode("^", $basic_opn_ix);    //기본옵션키
                $basic_option_use_array = explode("^", $basic_option_use);    //옵션사용여부
            }

            for ($i = 0; $i < count($basic_option_name_array); $i++) {
                if ($page_type == 'input') {
                    $options[$i][option_use] = '1';                                //옵션_사영여부
                } else {
                    $options[$i][opn_ix] = $basic_opn_ix_array[$i];                                //옵션키
                    $options[$i][option_use] = $basic_option_use_array[$i];                                //옵션_사영여부
                }
                $options[$i][option_name] = $basic_option_name_array[$i];    //옵션명
                $options[$i][option_type] = '1';                            //수량별
                $options[$i][option_kind] = $basic_option_kind_array[$i];    //옵션종류

                $basic_opd_ix_detail = explode("|", trim($basic_opd_ix_array[$i]));    //옵션당_구분키값
                $basic_option_div_detail = explode("|", trim($basic_option_div_array[$i]));    //옵션당_옵션구분
                $basic_option_soldout_detail = explode("|", trim($basic_option_soldout_array[$i]));    //옵션당_품절여부
                $basic_option_price_detail = explode("|", trim($basic_option_price_array[$i]));    //옵션당_옵션가격

                for ($j = 0; $j < count($basic_option_div_detail); $j++) {
                    if ($page_type == 'input') {    //상품등록시 빈값
                        $options[$i][details][$j][opd_ix] = '';    //옵션구분키 (상품수정시 필요)
                    } else {
                        $options[$i][details][$j][opd_ix] = $basic_opd_ix_detail[$i];    //옵션구분키 (상품수정시 필요)
                    }
                    $options[$i][details][$j][option_soldout] = $basic_option_soldout_detail[$j];    //품절여부
                    //$options[$i][details][$j][option_div] = $basic_option_div_detail[$j];    //옵션구분
                    $options[$i][details][$j][price] = $basic_option_price_detail[$j];    //옵션가격
                }
            }

        }

        //가격재고관리 옵션
        /*	가격재고관리 옵션 기본설정값
        option_kind = b
        use_option_type = non_set_option
        option_type = 9
        */
        $product_options_use = false;

        $use_option_type = 'non_set_option';
        if ($stock_options_code != "") {
            $stock_use_yn = "Y";
        }
        if ($stock_use_yn == "Y" && $stock_options_code != "") {    //WMS사용할경우 가격재고관리 옵션

            $stock_options_code_array = explode("|", $stock_options_code);
            $option_div_array = explode("|", $option_div);
            $english_option_div_array = explode("|", $english_option_div);
            $stock_options_listprice_array = explode("|", $stock_options_listprice);
            $stock_options_sellprice_array = explode("|", $stock_options_sellprice);
            $english_stock_options_listprice_array = explode("|", $english_stock_options_listprice);
            $english_stock_options_sellprice_array = explode("|", $english_stock_options_sellprice);

            if(empty($english_option_div)){
                $english_option_div_array = $option_div_array;
            }

            $stock_options[0][option_use] = '1';    //옵션사용여부
            $stock_options[0][option_type] = 'c';
            $stock_options[0][option_kind] = 'b';
            $stock_options[0][opn_ix] = $opn_ix;
            $stock_options[0][option_name] = $option_name;
            $stock_options[0][english_option_name] = $english_option_name;

            for ($i = 0; $i < count($stock_options_code_array); $i++) {
                $option_pcode = $stock_options_code_array[$i];

                $option_div_result = $option_div_array[$i];
                $stock_options_listprice_result = $stock_options_listprice_array[$i];
                $stock_options_sellprice_result = $stock_options_sellprice_array[$i];

                if(empty($stock_options_listprice_result)){
                    $stock_options_listprice_result = $listprice;
                }
                if(empty($stock_options_sellprice_result)){
                    $stock_options_sellprice_result = $sellprice;
                }

                $english_option_div_result = $english_option_div_array[$i];
                $english_stock_options_listprice_result = $english_stock_options_listprice_array[$i];
                $english_stock_options_sellprice_result = $english_stock_options_sellprice_array[$i];

                $sql = "select 
							gu.*,
							g.gname,
							(select 
								ifnull(sum(ps.stock),0) as option_stock
							from
								inventory_product_stockinfo as ps 
								inner join inventory_place_info as pi on (ps.pi_ix = pi.pi_ix and pi.online_place_yn = 'Y')
							where
								ps.gid = gu.gid 
								and ps.unit = gu.unit
                and ps.ps_ix='1') as option_stock,
							(select ifnull(sum(gs.safestock),0) as safestock  from inventory_goods_safestock as gs where gs.gu_ix = gu.gu_ix and gs.company_id = g.admin) as total_safestock
						from
							inventory_goods_unit as gu 
							inner join inventory_goods as g on (gu.gid = g.gid and gu.unit = g.basic_unit)
						where
							g.gid = '" . $option_pcode . "'";

                $db->query($sql);
                $db->fetch();

                $stock_options[0][details][$i][option_div] = $option_div_result;
                $stock_options[0][details][$i][option_color] = $option_div_result;
                //$stock_options[0][details][$i][option_div] = $db->dt[gname];
                //$stock_options[0][details][$i][option_color] = $db->dt[gname];
                $stock_options[0][details][$i][coprice] = $coprice;
                //$stock_options[0][details][$i][coprice] = $db->dt[buying_price];
                $stock_options[0][details][$i][wholesale_listprice] = $db->dt[wholesale_price];
                $stock_options[0][details][$i][wholesale_price] = $db->dt[wholesale_price];
                $stock_options[0][details][$i][listprice] = $stock_options_listprice_result;
                $stock_options[0][details][$i][sellprice] = $stock_options_sellprice_result;
                //$stock_options[0][details][$i][listprice] = $db->dt[listprice];
                //$stock_options[0][details][$i][sellprice] = $db->dt[sellprice];
                $stock_options[0][details][$i][sell_ing_cnt] = '';
                $stock_options[0][details][$i][stock] = $db->dt[option_stock];
                $stock_options[0][details][$i][safestock] = $db->dt[total_safestock];
                $stock_options[0][details][$i][code] = $db->dt[gu_ix];
                $stock_options[0][details][$i][gid] = $db->dt[gid];
                $stock_options[0][details][$i][barcode] = $db->dt[barcode];
                $stock_options[0][details][$i][soldout] = $db->dt[soldout];
                $stock_options[0][details][$i][english_option_color] = $english_option_div_result;
                $stock_options[0][details][$i][english_option_div] = $english_option_div_result;
                $stock_options[0][details][$i][english_coprice] = $english_coprice;
                $stock_options[0][details][$i][english_listprice] = $english_stock_options_listprice_result;
                $stock_options[0][details][$i][english_sellprice] = $english_stock_options_sellprice_result;

                $option_stock += $db->dt[option_stock];    //총 합산재고수량
                $option_safestock += $db->dt[total_safestock];    //총 합산 안전재고 수량

            }

            $product_options_use = true;    //재고관리와 가격재고관리 옵션을 사용할경우 shop_product.pcode 는 빈값으로 처리해야함
        }

        //재고관리 사용시 상품금액정보
        if ($stock_use_yn == "Y" && $pcode != "") {

            $sql = "select 
						g.*,
						gu.*,
						gu.barcode as p_barcode,
						(select 
							ifnull(sum(ps.stock),0) as total_stock
						from
							inventory_product_stockinfo as ps 
							inner join inventory_place_info as pi on (ps.pi_ix = pi.pi_ix and pi.online_place_yn = 'Y')
						where
							ps.gid = gu.gid 
							and ps.unit = gu.unit) as total_stock,
						(select ifnull(sum(gs.safestock),0) as safestock  from inventory_goods_safestock as gs where gs.gu_ix = gu.gu_ix and gs.company_id = g.admin) as total_safestock
					from
						inventory_goods_unit as gu 
						inner join inventory_goods as g on (gu.gid = g.gid and gu.unit = g.basic_unit)
					where
						g.gid = '" . $pcode . "'";

            $db->query($sql);
            $db->fetch();

            if ($db->total) {

                $coprice = $db->dt[buying_price];
                $wholesale_price = $db->dt[wholesale_price];
                $wholesale_sellprice = $db->dt[wholesale_price];
                $listprice = $db->dt[sellprice];
                $sellprice = $db->dt[sellprice];
                $safestock = $db->dt[total_safestock];
                $stock = $db->dt[total_stock];
                $available_stock = $db->dt[total_safestock];

                $pcode = $db->dt[gu_ix];            //품목시스템코드
                $paper_pname = $db->dt[gname];        //매입상품명
                $barcode = $db->dt[p_barcode];        //바코드

                $og_ix = $db->dt[og_ix];            //원산지
                $c_ix = $db->dt[c_ix];                //제조사
                $brand = $db->dt[b_ix];                //브랜드
                $trade_admin = $db->dt[ci_ix];        //주매입처
                if ($db->dt[surtax_div] == '1') {
                    $surtax_yorn = 'N';                //과세(부과세포함)
                } else {
                    $surtax_yorn = 'Y';                //면세(면세율적용)
                }

                $product_weight = $db->dt[weight];    //weight (기본단위무게)

                //원산지
                if ($og_ix != "") {
                    $db->query("select * from common_origin where og_ix = '" . $og_ix . "'");
                    $db->fetch();
                    $origin = $db->dt[origin_name];
                }

                //제조사
                if ($c_ix != "") {
                    $db->query("SELECT company_name FROM shop_company where c_ix = '" . $company_code . "' ");
                    $db->fetch();
                    $company = $db->dt[company_name];
                }

            }

        }

        if ($stock_use_yn == "Y" && $stock_options_code != "") {
            $safestock = $option_safestock;
            $stock = $option_stock;
        } else {
            $safestock = $safestock;
            $stock = $stock;
        }

        //셀러업체 배송정책 업데이트용
        //if($company_id == '' && $page_type == 'update'){	//대량상품수정일 경우 입점업체 지정안하면 상품의 입점업체 키값으로 수정 2014-07-01 이학봉

        if (false) {    //상품대량수정시 배송정책은 업데이트 할 필요 없음
            $sql = "select admin,md_code from shop_product where id = '" . $id . "'";
            $db->query($sql);
            $db->fetch();
            $company_id = $db->dt[admin];
            $md_code = $db->dt[md_code];

            $sql = "select * from shop_product_delivery where pid = '" . $id . "'";
            $db->query($sql);
            $delivery_array = $db->fetchall();

            if (count($delivery_array) > 0) {
                for ($i = 0; $i < count($delivery_array); $i++) {
                    $dt_ix[$delivery_array[$i][is_wholesale]][$delivery_array[$i][delivery_div]][template_check] = '1';
                    $dt_ix[$delivery_array[$i][is_wholesale]][$delivery_array[$i][delivery_div]][dt_ix] = $delivery_array[$i][dt_ix];
                }
            }
        }

        //이미지 자동복사
        //chk_allimg = '1';
        ///$chk_mimg = '1';
        //$chk_msimg = '1';
        //$chk_simg = '1';
        //$chk_cimg = '1';

        /*
        //예외처리
        $basicinfo = str_replace("''", "", $basicinfo);
        $basicinfo = str_replace("'", "&#39;", $basicinfo);
        $basicinfo = str_replace('"', "&quot;", $basicinfo);
        $basicinfo = strip_tags($basicinfo, "<img><table><th><col><colgroup><tbody><tr><td><div><a><ul><li><dl><dt><p><h><font><strong><br><span>");    //2014-07-27 edit 태그 예외처리 이학봉

        $m_basicinfo = str_replace("''", "", $m_basicinfo);
        $m_basicinfo = str_replace("'", "&#39;", $m_basicinfo);
        $m_basicinfo = str_replace('"', "&quot;", $m_basicinfo);
        $m_basicinfo = strip_tags($m_basicinfo, "<img><table><th><col><colgroup><tbody><tr><td><div><a><ul><li><dl><dt><p><h><font><strong><br><span>");    //2014-07-27 edit 태그 예외처리 이학봉
        */

        $goods_desc_copy = "1";
        $bs_act = "1";
        $one_commissio = "N";

        /*
        if ($product_options_use == true) {        //재고관리와 가격재고관리 옵션을 사용할경우 shop_product.pcode 는 빈값으로 처리해야함 2014-08-11 이학봉
            $pcode = '';
        }
        */

        if ($page_type == 'input') {
            $act = "insert";
        } else {
            $act = "update";
        }

        ///////DEFAULT///////
        if ($insert_yn) {
            if ($upload_excel_data[session_id()][$key][status] != 'C') {

                if ($page_type == 'input') {
                    include "goods_input.act.php";
                } else {
                    include "goods_update_excel.act.php";
                }

                if ($page_type == 'input') {

                    if ($mainimg != "") {
                        $mainimg_array = explode("|", trim($mainimg));

                        $time = date('YmdHis', time());

                        for ($i = 0; $i < count($mainimg_array); $i++) {
                            Batch_Images_Processing('mainNew', $mainimg_array[$i], $pid, $goods_img_file, $i, $time);
                        }
                    }

                    /*if ($mainimg != '#') {
                        if ($mainimg != "") {
                            Batch_Images_Processing('main', $mainimg, $pid, $goods_img_file);
                        }
                    }

                    if ($addimg != "") {
                        $addimg_array = explode("|", trim($addimg));

                        for ($i = 0; $i < count($addimg_array); $i++) {
                            Batch_Images_Processing('add', $addimg_array[$i], $pid, $goods_img_file);
                        }
                    }

                    if ($listimg != "") {
                        Batch_Images_Processing('list', $listimg, $pid, $goods_img_file);
                    }

                    if ($pattern_image != "") {
                        Batch_Images_Processing('filter', $pattern_image, $pid, $goods_img_file);
                    }

                    if ($basicinfo != '#') {
                        //$basicinfo = basicinfoCopy($basicinfo, $id);
                        $db->query("update shop_product set basicinfo='" . $basicinfo . "' where id='" . $pid . "' ");
                    }

                    if ($m_basicinfo != '#') {
                        //$m_basicinfo = basicinfoCopy($m_basicinfo, $id);
                        $db->query("update shop_product set m_basicinfo='" . $m_basicinfo . "' where id='" . $pid . "' ");
                    }*/

                    if ($option_div != '#') {
                        $option_div_array = explode("|", $option_div);
                        $english_option_div_array = explode("|", $english_option_div);
                        if(empty($english_option_div)){
                            $english_option_div_array = $option_div_array;
                        }
                        for ($i = 0; $i < count($option_div_array); $i++) {
                            $db->query("update shop_product_options_detail set option_div='" . $option_div_array[$i] . "', option_color='" . $option_div_array[$i] . "' where pid='" . $pid . "' and set_group_seq='" . $i . "' ");
                            $db->query("update shop_product_options_detail_global set option_div='" . $english_option_div_array[$i] . "', option_color='" . $english_option_div_array[$i] . "' where pid='" . $pid . "' and set_group_seq='" . $i . "' ");
                        }
                    }

                } else {

                    //이미지
                    if ($check_infos[update_check_mainimg] == '1') {    //이미지
                        if ($mainimg != '#') {
                            if ($mainimg != "") {
                                Batch_Images_Processing('main', $mainimg, $id, $goods_img_file);
                            }
                        }
                    }

                    if ($check_infos[update_check_basicinfo] == '1') {    //상세이미지

                        if ($basicinfo != '#') {
                            $basicinfo = basicinfoCopy($basicinfo, $id);
                            $db->query("update shop_product set basicinfo='" . $basicinfo . "' where id='" . $id . "' ");

                        }
                    }

                    if ($check_infos[update_check_m_basicinfo] == '1') {    //모바일 상세이미지
                        if ($m_basicinfo != '#') {
                            $m_basicinfo = basicinfoCopy($m_basicinfo, $id);
                            $db->query("update shop_product set m_basicinfo='" . $m_basicinfo . "' where id='" . $id . "' ");
                        }
                    }
                }

                $upload_excel_data[session_id()][$key][status] = "C";
                $upload_excel_data[session_id()][$key][status_message] = "등록완료";
                echo "<span class='blue'>등록완료</span>";
            } else {
                echo "<span class='blue'>PASS</span>";
            }
        } else {
            echo $result_massage;
        }
    }

    $shmop->setObjectForKey($upload_excel_data, "upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);
    exit;
}

if ($act == "bad_goods_info_excel") {
    include("../logstory/class/sharedmemory.class");
    $shmop = new Shared("upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);
    $shmop->filepath = $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/_shared/";
    //echo $shmop->filepath;
    $shmop->SetFilePath();
    $upload_excel_data = $shmop->getObjectForKey("upload_excel_data_" . $_SESSION["admininfo"]["charger_ix"]);

    $title_info = array();
    $bad_info_excel_data = array();

    foreach ($upload_excel_data[session_id()] as $key => $val) {
        if ($key == 0) {
            $title_info = $val;
        } elseif ($val[status] != "C") {
            array_push($bad_info_excel_data, $val);
        }
    }

    if (count($bad_info_excel_data) > 0) {

        PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

        date_default_timezone_set('Asia/Seoul');

        $etc_excel = new PHPExcel();

        // 속성 정의
        $etc_excel->getProperties()->setCreator("포비즈 코리아")
            ->setLastModifiedBy("Mallstory.com")
            ->setTitle("etc code List")
            ->setSubject("etc code List")
            ->setDescription("generated by forbiz korea")
            ->setKeywords("mallstory")
            ->setCategory("etc code List");

        $etc_excel->setActiveSheetIndex(0);
        $etc_excel->getActiveSheet()->setTitle('등록실패상품');

        $col = 'A';
        foreach ($title_info as $key => $val) {

            $etc_excel->getActiveSheet()->setCellValue($col . "1", $val);
            $etc_excel->getActiveSheet()->mergeCells($col . "1:" . $col . "5");
            //$etc_excel->getActiveSheet()->getColumnDimension($col . "5")->setAutoSize(true);
            $col++;
        }


        for ($i = 0, $z = 6; $i < count($bad_info_excel_data); $i++, $z++) {
            $col = 'A';

            foreach ($title_info as $key => $val) {
                if ($key == "category") {
                    $etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_TEXT);
                    $etc_excel->getActiveSheet()->setCellValue($col . $z, " " . $bad_info_excel_data[$i][$key]);
                } else {
                    $etc_excel->getActiveSheet()->setCellValue($col . $z, $bad_info_excel_data[$i][$key]);
                }

                $col++;
            }
        }

        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename=bad_goods_info_excel.xls');
        header('Cache-Control: max-age=0');

        $etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
        $etc_excel->save('php://output');
    } else {
        if ($page_type == 'input') {
            echo "<script type='text/javascript'>
		<!--
			alert('등록 실패한 상품이 없습니다.');
			location.href='./product_input_excel.php?up_mode=new_upload';
			
		//-->
		</script>";
        } else {
            echo "<script type='text/javascript'>
		<!--
			alert('등록 실패한 상품이 없습니다.');
			location.href='./product_update_excel.php?up_mode=new_upload';
			
		//-->
		</script>";
        }
    }
    exit;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시정보 다운로드
/// 작성 : 이학봉 ( 2014-06-18 )
/// 내용 : 상품정보고시를 DB구조대로 저장
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if ($act == "mandatory_down") {

    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    $etc_excel = new PHPExcel();

    // 속성 정의
    $etc_excel->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("Mallstory.com")
        ->setTitle("etc code List")
        ->setSubject("etc code List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("mallstory")
        ->setCategory("etc code List");

    $etc_excel->setActiveSheetIndex(0);
    $etc_excel->getActiveSheet()->setTitle('상품정보고시');


    $ct_excel_info = array("상품고시명", "코드", "상세코드", "상품정보 고시명", "설명");
    $col = 'A';
    foreach ($ct_excel_info as $ci) {
        $etc_excel->getActiveSheet()->setCellValue($col . "1", $ci);
        $etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
        $col++;
    }

    $sql = "select 
				mi.mandatory_name,
				md.*
			from 
				shop_mandatory_info as mi 
				inner join shop_mandatory_detail as md on (mi.mi_ix = md.mi_ix)
			where
				mi.is_use = '1'
				order by mi_ix ASC,detail_code ASC";
    $db->query($sql);
    $db->fetch();
    $z = 2;

    for ($i = 0; $i < $db->total; $i++) {
        $db->fetch($i);
        $col = 'A';
        //$ct_name=explode('>',$db->dt[ct_name]);
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[mandatory_name]);
        $col++;
        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[mi_ix]);
        $col++;

        $etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_TEXT);
        $etc_excel->getActiveSheet()->setCellValue($col . $z, " " . $db->dt[detail_code]);
        $col++;

        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[mid_title]);
        $col++;

        $etc_excel->getActiveSheet()->setCellValue($col . $z, $db->dt[mid_comment]);
        $z++;
    }
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename=etc_code_v1.xls');
    header('Cache-Control: max-age=0');

    $etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
    $etc_excel->save('php://output');
    exit;
}


function Batch_Images_Processing($process_type, $xlImageFileName, $bpid, $goods_img_file = '', $num, $time = '')
{
    global $admin_config;

    //syslog(LOG_INFO, '$admin_config[mall_data_root]\r\n');

    //$uploadDirectory = UploadDirText($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/product", $bpid, 'Y');
    $sourceDirectory = $_SERVER["DOCUMENT_ROOT"] . $admin_config["mall_data_root"] . "/BatchUploadImages/";

    if ($goods_img_file != "") {
        $goods_img_file_array = explode(".", $goods_img_file);
        $zip_directory = $goods_img_file_array[0] . "/";
    }

    if (substr($xlImageFileName, 0, 5) == "http:") {
        $sourceImageFileFullPath = $xlImageFileName;
    } else {
        if (@substr_count($xlImageFileName, $zip_directory) > 0) {
            $sourceImageFileFullPath = $sourceDirectory . $xlImageFileName;
        } else {
            $sourceImageFileFullPath = $sourceDirectory . $zip_directory . $xlImageFileName;
        }
    }

    if ($process_type == 'main') {
        ExcelImageCopy($sourceImageFileFullPath, $bpid);
    } else if ($process_type == 'list') {
        if (substr($sourceImageFileFullPath, 0, 5) != "http:") {
            if (file_exists($sourceImageFileFullPath)) {
                ExcelListImageCopy($sourceImageFileFullPath, $bpid);
            }
        }
    } else if ($process_type == 'filter') {
        if (substr($sourceImageFileFullPath, 0, 5) != "http:") {
            if (file_exists($sourceImageFileFullPath)) {
                ExcelFilterImageCopy($sourceImageFileFullPath, $bpid);
            }
        }
    } else if ($process_type == 'mainNew') {
        ExcelImageCopyNew($sourceImageFileFullPath, $bpid, $num, $time);
    } else {
        if (substr($sourceImageFileFullPath, 0, 5) != "http:") {
            if (file_exists($sourceImageFileFullPath)) {
                ExcelAddImageCopy($sourceImageFileFullPath, $bpid);
            }
        }
    }
}

function basicinfoCopy($basicinfo, $INSERT_PRODUCT_ID)
{
    global $admin_config, $DOCUMENT_ROOT, $HTTP_HOST;

    //아카마이 ftp 파일 업로드
    $akamaiFtpUploadFiles = array();

    $data_text_convert = $basicinfo;
    $data_text_convert = str_replace("\\", "", $data_text_convert);
    $data_text_convert = str_replace("<img", "<IMG", $data_text_convert);
    $data_text_convert = str_replace("&quot;", '"', $data_text_convert);

    preg_match_all("|<IMG .*src=\"(.*)\".*>|U", $data_text_convert, $out, PREG_PATTERN_ORDER);

    $uploaddir = UploadDirText($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/product", $INSERT_PRODUCT_ID, 'Y');
    $path = $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/";

    if (substr_count($data_text_convert, "<IMG") > 0) {
        if (!is_dir($path)) {
            mkdir($path, 0777);
            chmod($path, 0777);
        } else {
            chmod($path, 0777);
        }
    }

    for ($i = 0; $i < count($out); $i++) {
        for ($j = 0; $j < count($out[$i]); $j++) {

            $img = returnImagePath($out[$i][$j]);
            $img = ClearText($img);

            try {
                if ($img) {
                    if (substr_count($img, $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/") == 0) {// 이미지 URL 이 이벤트 관련 폴더에 있지 않으면 ...

                        if (substr_count($img, $_SERVER["HTTP_HOST"]) > 0) {
                            $local_img_path = str_replace("http://" . $_SERVER["HTTP_HOST"], $_SERVER["DOCUMENT_ROOT"], $img);

                            @copy($local_img_path, $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/" . returnFileName($img));

                            if (substr_count($img, $admin_config[mall_data_root] . "/BatchUploadImages/") > 0) {
                                //unlink($local_img_path);
                            }

                            $akamaiFtpUploadFiles[] = returnFileName($img);

                            $basicinfo = str_replace($img, $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/" . returnFileName($img), $basicinfo);     // 업로드된 파일들이 URL 에 관계 없이 보일수 있도록 URL 을  / 로 치환
                        } else {
                            if (substr_count($img, $DOCUMENT_ROOT)) {
                                //$img = $DOCUMENT_ROOT.$img;
                                if (@copy($DOCUMENT_ROOT . $img, $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/" . returnFileName($DOCUMENT_ROOT . $img))) {
                                    $basicinfo = str_replace($img, $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/" . returnFileName($img), $basicinfo);     // 업로드된 파일들이 URL 에 관계 없이 보일수 있도록 URL 을  / 로 치환

                                    $akamaiFtpUploadFiles[] = returnFileName($img);
                                }
                            } else {

                                $local_img_path = str_replace("http://" . $_SERVER["HTTP_HOST"], $_SERVER["DOCUMENT_ROOT"], $img);

                                if (substr_count($local_img_path, $_SERVER["DOCUMENT_ROOT"]) == 0) {
                                    $local_img_path = $_SERVER["DOCUMENT_ROOT"] . $local_img_path;
                                }

                                if (@copy($local_img_path, $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/" . returnFileName($img))) {
                                    $basicinfo = str_replace($img, $admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail/" . returnFileName($img), $basicinfo);     // 업로드된 파일들이 URL 에 관계 없이 보일수 있도록 URL 을  / 로 치환

                                    if (substr_count($local_img_path, $admin_config[mall_data_root] . "/BatchUploadImages/") > 0) {
                                        //unlink($local_img_path);
                                    }

                                    $akamaiFtpUploadFiles[] = returnFileName($img);
                                }
                            }
                            //echo ":::".$img."<br>";
                        }
                    }
                }

            } catch (Exception $e) {
                // 에러처리 구문
                //exit($e->getMessage());
            }
        }
    }

    akamaiFtpUpload($admin_config[mall_data_root] . "/images/product" . $uploaddir . "/product_detail", $akamaiFtpUploadFiles);

    $basicinfo = str_replace("http://$HTTP_HOST", "", $basicinfo);

    return $basicinfo;
}

/**
 * 이미지 체크
 * @param $image_url
 * @return boolean
 */
function checkImageExist($image_url)
{

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $image_url);
    // 다운로드 하지 않음
    curl_setopt($ch, CURLOPT_NOBODY, 1);
    curl_setopt($ch, CURLOPT_FAILONERROR, 1);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    if (curl_exec($ch) !== FALSE) {
        return TRUE;
    } else {
        return FALSE;
    }
}

function ExcelImageCopyNew($image_path, $pid, $num, $time)
{
    global $admin_config, $DOCUMENT_ROOT, $image_db;

    $addQaDir = "";
    if($_SESSION['admin_config']['mall_domain'] == "0925admintest.barrelmade.co.kr"){
        $addQaDir = "/QA";
    }

    $uploaddir		= UploadDirText($_SESSION["admin_config"]["mall_data_root"] . "/images/productNew".$addQaDir, $pid, 'Y');
    $adduploaddir	= UploadDirText($_SESSION["admin_config"]["mall_data_root"] . "/images/addimgNew".$addQaDir, $pid, 'Y');

    $basicDir		= $_SESSION["admin_config"]["mall_data_root"] . "/images/productNew".$addQaDir.$uploaddir;
	//$backUpBasicDir = $_SESSION["admin_config"]["mall_data_root"] . "/images/productNew/".$_SESSION['admininfo']['charger_id']."/productNew";

	$addDir			= $_SESSION["admin_config"]["mall_data_root"] . "/images/addimgNew".$addQaDir.$adduploaddir;
	//$backUpAddDir	= $_SESSION["admin_config"]["mall_data_root"] . "/images/productNew/".$_SESSION['admininfo']['charger_id']."/addimgNew";

	if(!is_dir($basicDir)){
        mkdir($basicDir);
        chmod($basicDir,0777);
    }

	if(!is_dir($addDir)){
        mkdir($addDir);
        chmod($addDir,0777);
    }

	//$postCount = 0;

    $image_type = substr($image_path, -3);

    $image_info = getimagesize($image_path);

    if ($image_info[0] > $image_info[1]) {
        $image_resize_type = "W";
    } else {
        $image_resize_type = "H";
    }

    // 원본이미지
    copy($image_path, $basicDir."/basic_".$pid."_".$time."_".$num.".gif");

    $image_db->query("select width,height from shop_image_resizeinfo order by idx");//kbk 11/12/15
    $image_info2 = $image_db->fetchall();

    // 리스트이미지
    if ($image_type == "png" || $image_type == "PNG" || $image_type == "jpg" || $image_type == "JPG" || $image_type == "jpeg" || $image_type == "JPEG") {
        MirrorPNG($image_path, $addDir."/list_".$pid."_".$time."_".$num.".gif", MIRROR_NONE);
        resize_png($addDir."/list_".$pid."_".$time."_".$num.".gif", $image_info2[0][width], $image_info2[0][height], $image_resize_type);
    }else{
        copy($image_path, $addDir."/list_".$pid."_".$time."_".$num.".gif");
        resize_jpg($addDir."/list_".$pid."_".$time."_".$num.".gif", $image_info2[0][width], $image_info2[0][height], $image_resize_type);
    }

    // 오버이미지
    if ($image_type == "png" || $image_type == "PNG" || $image_type == "jpg" || $image_type == "JPG" || $image_type == "jpeg" || $image_type == "JPEG") {
        MirrorPNG($image_path, $addDir."/over_".$pid."_".$time."_".$num.".gif", MIRROR_NONE);
        resize_png($addDir."/over_".$pid."_".$time."_".$num.".gif", $image_info2[1][width], $image_info2[1][height], $image_resize_type);
    }else{
        copy($image_path, $addDir."/over_".$pid."_".$time."_".$num.".gif");
        resize_jpg($addDir."/over_".$pid."_".$time."_".$num.".gif", $image_info2[1][width], $image_info2[1][height], $image_resize_type);
    }

    // 이미지작은
    if ($image_type == "png" || $image_type == "PNG" || $image_type == "jpg" || $image_type == "JPG" || $image_type == "jpeg" || $image_type == "JPEG") {
        MirrorPNG($image_path, $addDir."/slist_".$pid."_".$time."_".$num.".gif", MIRROR_NONE);
        resize_png($addDir."/slist_".$pid."_".$time."_".$num.".gif", $image_info2[2][width], $image_info2[2][height], $image_resize_type);
    }else{
        copy($image_path, $addDir."/slist_".$pid."_".$time."_".$num.".gif");
        resize_jpg($addDir."/slist_".$pid."_".$time."_".$num.".gif", $image_info2[2][width], $image_info2[2][height], $image_resize_type);
    }

    // 썸네일이미지
    if ($image_type == "png" || $image_type == "PNG" || $image_type == "jpg" || $image_type == "JPG" || $image_type == "jpeg" || $image_type == "JPEG") {
        MirrorPNG($image_path, $addDir."/nail_".$pid."_".$time."_".$num.".gif", MIRROR_NONE);
        resize_png($addDir."/nail_".$pid."_".$time."_".$num.".gif", $image_info2[3][width], $image_info2[3][height], $image_resize_type);
    }else{
        copy($image_path, $addDir."/nail_".$pid."_".$time."_".$num.".gif");
        resize_jpg($addDir."/nail_".$pid."_".$time."_".$num.".gif", $image_info2[3][width], $image_info2[3][height], $image_resize_type);
    }

    // 패턴이미지
    if ($image_type == "png" || $image_type == "PNG" || $image_type == "jpg" || $image_type == "JPG" || $image_type == "jpeg" || $image_type == "JPEG") {
        MirrorPNG($image_path, $addDir."/patt_".$pid."_".$time."_".$num.".gif", MIRROR_NONE);
        resize_png($addDir."/patt_".$pid."_".$time."_".$num.".gif", $image_info2[4][width], $image_info2[4][height], $image_resize_type);
    }else{
        copy($image_path, $addDir."/patt_".$pid."_".$time."_".$num.".gif");
        resize_jpg($addDir."/patt_".$pid."_".$time."_".$num.".gif", $image_info2[4][width], $image_info2[4][height], $image_resize_type);
    }

    if (file_exists($image_path)) {
        unlink($image_path);
    }
}


function ExcelImageCopy($image_path, $pid)
{
    global $admin_config, $DOCUMENT_ROOT, $image_db;

    $basedir = $_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/images/product/";
    $uploaddir = UploadDirText($basedir, $pid, 'Y');
    $targetDirectory = $basedir . UploadDirText($basedir, $pid, 'Y') . '/';

    if (substr($image_path, 0, 5) != "http:") {
        if (!file_exists($image_path)) {
            return;
        }
    } else {
        if (!checkImageExist($image_path)) {
            return;
        }
    }

    $image_info = getimagesize($image_path);
    $image_type = substr($image_info['mime'], -3);


    $image_db->query("select width,height from shop_image_resizeinfo order by idx");//kbk 11/12/15
    $image_info2 = $image_db->fetchall();
    $basic_img_src = $targetDirectory . "/basic_" . $pid . ".gif";

    copy($image_path, $basic_img_src);

    if (file_exists($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/watermark/watermark.png")) {
        require_once "../lib/class.upload.php";

        $s_water_handle = new Upload($targetDirectory . "/basic_" . $pid . ".gif");
        $s_water_result = WaterMarkProcess2($s_water_handle, $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/", $targetDirectory);

        $basic_img_src = $targetDirectory . "/basic_watermark_" . $pid . ".gif";
        copy($targetDirectory . "/watermark/basic_" . $pid . ".gif", $basic_img_src);
        chmod($targetDirectory . "/basic_" . $pid . ".gif", 0777);

        $image_type = "gif"; // 워터마크 처리후 마임타입이 gif로 바뀐다.
    }


    switch ($image_type) {
        case "gif":
        case "GIF":

            MirrorGif($basic_img_src, $targetDirectory . "/b_" . $pid . ".gif", MIRROR_NONE);
            resize_gif($targetDirectory . "/b_" . $pid . ".gif", $image_info2[0]['width'], $image_info2[0]['height']);

            MirrorGif($basic_img_src, $targetDirectory . "/m_" . $pid . ".gif", MIRROR_NONE);
            resize_gif($targetDirectory . "/m_" . $pid . ".gif", $image_info2[1]['width'], $image_info2[1]['height']);

            MirrorGif($basic_img_src, $targetDirectory . "/ms_" . $pid . ".gif", MIRROR_NONE);
            resize_gif($targetDirectory . "/ms_" . $pid . ".gif", $image_info2[2]['width'], $image_info2[2]['height']);

            MirrorGif($basic_img_src, $targetDirectory . "/s_" . $pid . ".gif", MIRROR_NONE);
            resize_gif($targetDirectory . "/s_" . $pid . ".gif", $image_info2[3]['width'], $image_info2[3]['height']);

            MirrorGif($basic_img_src, $targetDirectory . "/c_" . $pid . ".gif", MIRROR_NONE);
            resize_gif($targetDirectory . "/c_" . $pid . ".gif", $image_info2[4]['width'], $image_info2[4]['height']);

            break;


        default:
            //copy($image_path, $basic_img_src);

            Mirror($basic_img_src, $targetDirectory . "/b_" . $pid . ".gif", MIRROR_NONE);
            resize_jpg($targetDirectory . "/b_" . $pid . ".gif", $image_info2[0]['width'], $image_info2[0]['height']);

            Mirror($basic_img_src, $targetDirectory . "/m_" . $pid . ".gif", MIRROR_NONE);
            resize_jpg($targetDirectory . "/m_" . $pid . ".gif", $image_info2[1]['width'], $image_info2[1]['height']);

            Mirror($basic_img_src, $targetDirectory . "/ms_" . $pid . ".gif", MIRROR_NONE);
            resize_jpg($targetDirectory . "/ms_" . $pid . ".gif", $image_info2[2]['width'], $image_info2[2]['height']);

            Mirror($basic_img_src, $targetDirectory . "/s_" . $pid . ".gif", MIRROR_NONE);
            resize_jpg($targetDirectory . "/s_" . $pid . ".gif", $image_info2[3]['width'], $image_info2[3]['height']);

            Mirror($basic_img_src, $targetDirectory . "/c_" . $pid . ".gif", MIRROR_NONE);
            resize_jpg($targetDirectory . "/c_" . $pid . ".gif", $image_info2[4]['width'], $image_info2[4]['height']);
            break;
    }
    if (is_file($image_path)) {
        //@unlink($image_path);
    }

    //아카마이 ftp 파일 업로드
    $akamaiFtpUploadFiles = array();
    $akamaiFtpUploadFiles[] = "basic_" . $pid . ".gif";
    $akamaiFtpUploadFiles[] = "b_" . $pid . ".gif";
    $akamaiFtpUploadFiles[] = "m_" . $pid . ".gif";
    $akamaiFtpUploadFiles[] = "ms_" . $pid . ".gif";
    $akamaiFtpUploadFiles[] = "s_" . $pid . ".gif";
    $akamaiFtpUploadFiles[] = "c_" . $pid . ".gif";
    akamaiFtpUpload($admin_config[mall_data_root] . "/images/product" . $uploaddir, $akamaiFtpUploadFiles);
    //syslog(LOG_INFO, 'END\r\n');
}

function ExcelListImageCopy($image_path, $pid)
{
    global $admin_config, $DOCUMENT_ROOT, $image_db;

    $basedir = $_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/images/product/";
    $uploaddir = UploadDirText($basedir, $pid, 'Y');
    $targetDirectory = $basedir . UploadDirText($basedir, $pid, 'Y') . '/';

    if (substr($image_path, 0, 5) != "http:") {
        if (!file_exists($image_path)) {
            return;
        }
    } else {
        if (!checkImageExist($image_path)) {
            return;
        }
    }

    $image_info = getimagesize($image_path);
    $image_type = substr($image_info['mime'], -3);

    $image_db->query("select width,height from shop_image_resizeinfo where idx=3 order by idx");//kbk 11/12/15
    $image_info2 = $image_db->fetchall();
    $basic_img_src = $targetDirectory . "/ms_" . $pid . ".gif";

    copy($image_path, $basic_img_src);

    switch ($image_type) {
        case "gif":
        case "GIF":

            MirrorGif($basic_img_src, $targetDirectory . "/ms_" . $pid . ".gif", MIRROR_NONE);
            resize_gif($targetDirectory . "/ms_" . $pid . ".gif", $image_info2[0]['width'], $image_info2[0]['height']);

            break;


        default:

            Mirror($basic_img_src, $targetDirectory . "/ms_" . $pid . ".gif", MIRROR_NONE);
            resize_jpg($targetDirectory . "/ms_" . $pid . ".gif", $image_info2[0]['width'], $image_info2[0]['height']);

            break;
    }
}

function ExcelFilterImageCopy($image_path, $pid)
{
    global $admin_config, $DOCUMENT_ROOT, $image_db;

    $basedir = $_SERVER["DOCUMENT_ROOT"] . "" . $admin_config[mall_data_root] . "/images/product/";
    $uploaddir = UploadDirText($basedir, $pid, 'Y');
    $targetDirectory = $basedir . UploadDirText($basedir, $pid, 'Y') . '/';

    if (substr($image_path, 0, 5) != "http:") {
        if (!file_exists($image_path)) {
            return;
        }
    } else {
        if (!checkImageExist($image_path)) {
            return;
        }
    }

    $image_info = getimagesize($image_path);
    $image_type = substr($image_info['mime'], -3);

    //$image_db->query("select width,height from shop_image_resizeinfo where idx=2 order by idx");//kbk 11/12/15
    //$image_info2 = $image_db->fetchall();
    $basic_img_src = $targetDirectory . "/filter_" . $pid . ".gif";

    copy($image_path, $basic_img_src);
}

function ExcelAddImageCopy($image_path, $pid)
{

    global $admin_config, $DOCUMENT_ROOT, $image_db;

    $adb = new Database;

    $adduploaddir = UploadDirText($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg", $pid, 'Y');

    $sql = "INSERT INTO " . TBL_SHOP_ADDIMAGE . " (id, pid, deepzoom, regdate) values('', '$pid','0',  NOW()) ";
    $adb->sequences = "SHOP_ADDIMAGE_SEQ";
    $adb->query($sql);

    $adb->query("SELECT id FROM " . TBL_SHOP_ADDIMAGE . " WHERE id=LAST_INSERT_ID()");
    $adb->fetch();
    $ad_ix = $adb->dt[id];

    if (substr($image_path, 0, 5) != "http:") {
        if (!file_exists($image_path)) {
            return;
        }
    }

    $image_info = getimagesize($image_path);
    $image_type = substr($image_info['mime'], -3);


    $image_db->query("select width,height from shop_image_resizeinfo order by idx");//kbk 11/12/15
    $image_info2 = $image_db->fetchall();

    switch ($image_type) {
        case "gif":
        case "GIF":

            copy($image_path, $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/basic_" . $ad_ix . "_add.gif");
            MirrorGif($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/basic_" . $ad_ix . "_add.gif", $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", MIRROR_NONE);
            resize_gif($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", $image_info2[0][width], $image_info2[0][height], $image_resize_type);

            MirrorGif($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/m_" . $ad_ix . "_add.gif", MIRROR_NONE);
            resize_gif($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/m_" . $ad_ix . "_add.gif", $image_info2[1][width], $image_info2[1][height], $image_resize_type);

            MirrorGif($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/c_" . $ad_ix . "_add.gif", MIRROR_NONE);
            resize_gif($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/c_" . $ad_ix . "_add.gif", $image_info2[4][width], $image_info2[4][height], $image_resize_type);

            break;


        default:

            copy($image_path, $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/basic_" . $ad_ix . "_add.gif");
            Mirror($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/basic_" . $ad_ix . "_add.gif", $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", MIRROR_NONE);
            resize_jpg($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", $image_info2[0][width], $image_info2[0][height], $image_resize_type);

            Mirror($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/m_" . $ad_ix . "_add.gif", MIRROR_NONE);
            resize_jpg($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/m_" . $ad_ix . "_add.gif", $image_info2[1][width], $image_info2[1][height], $image_resize_type);

            Mirror($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/b_" . $ad_ix . "_add.gif", $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/c_" . $ad_ix . "_add.gif", MIRROR_NONE);
            resize_jpg($_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/images/addimg" . $adduploaddir . "/c_" . $ad_ix . "_add.gif", $image_info2[4][width], $image_info2[4][height], $image_resize_type);

            break;
    }
    if (is_file($image_path)) {
        //@unlink($image_path);
    }

    //아카마이 ftp 파일 업로드
    $akamaiFtpUploadFiles = array();
    $akamaiFtpUploadFiles[] = "basic_" . $ad_ix . "_add.gif";
    $akamaiFtpUploadFiles[] = "b_" . $ad_ix . "_add.gif";
    $akamaiFtpUploadFiles[] = "m_" . $ad_ix . "_add.gif";
    $akamaiFtpUploadFiles[] = "c_" . $ad_ix . "_add.gif";
    akamaiFtpUpload($admin_config[mall_data_root] . "/images/addimg" . $adduploaddir, $akamaiFtpUploadFiles);
    //syslog(LOG_INFO, 'END\r\n');
}

?>
