<?php
/**
 * Created by PhpStorm.
 * User: FB_sc
 * Date: 2019-04-25
 * Time: 오후 5:05
 */
include("../class/layout.class");
include '../include/phpexcel/Classes/PHPExcel.php';


ini_set('memory_limit','2048M');
set_time_limit(9999999);

PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

date_default_timezone_set('Asia/Seoul');

$db = new Database;
$EXL = new PHPExcel();

$EXL->getProperties()->setCreator("포비즈 코리아")
    ->setLastModifiedBy("Mallstory.com")
    ->setTitle("keyword List")
    ->setSubject("keyword List")
    ->setDescription("generated by forbiz korea")
    ->setKeywords("mallstory")
    ->setCategory("keyword List");

$EXL->getActiveSheet()->setTitle('키워드 리스트');
$EXL->setActiveSheetIndex(0);

$sql = "SELECT * FROM shop_search_keyword order by searchcnt desc";
$db->query($sql);
$keywords = $db->fetchall();
$keywords_total = $db->total;


if($keywords_total > 0){

    $title = Array(
        '0' => '번호',
        '1' => '코드',
        '2' => '키워드',
        '3' => '전체',
        '4' => '웹',
        '5' => '모바일',
        '6' => '분류',
        '7' => '사용유무',
        '8' => '등록일자'
    );

    for($i=0,$col='A'; $i<count($title); $i++,$col++){
        $EXL->getActiveSheet()->setCellValue($col."1", $title[$i]);
    }

    $rownum = 2;
    for($i=0; $i<$keywords_total; $i++){
        $keyword = $keywords[$i];
        $recommend = '인기검색어';
        $disp = '사용';
        $col='A';

        if($keyword['disp'] == '0'){
            $disp = '사용안함';
        }

        $EXL->getActiveSheet()->setCellValue($col++.$rownum, ($i+1));
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $keyword['k_ix']);
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $keyword['keyword']);
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $keyword['searchcnt']);
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $keyword['searchcnt_web']);
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $keyword['searchcnt_mobile']);
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $recommend);
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $disp);
        $EXL->getActiveSheet()->setCellValue($col++.$rownum, $keyword['regdate']);

        if(($i+1) == $keywords_total) $EXL->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);

        $rownum++;
    }

    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="keyword_list_'.date("Ymd").'.xls"');
    header('Cache-Control: max-age=0');

    $objWriter = PHPExcel_IOFactory::createWriter($EXL, 'Excel5');
    $objWriter->save('php://output');
}else {
    echo "<script>alert('키워드가 존재하지 않습니다.');location.href='/promotion/keyword_list.php';</script>";
}
