<?

	include("../class/layout.class");
	include '../include/phpexcel/Classes/PHPExcel.php';

	//error_reporting(E_ALL);
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$db = new Database;
	$mdb = new Database;
	$ig_db = new Database;

	if ($admininfo[mall_type] == "O"){
		if($db->dbms_type == "oracle"){
			$where = " where cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F','S') ";
		}else{
			$where = " where cu.code != '' and cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F','S') ";
		}
	}else{
		if($db->dbms_type == "oracle"){
			$where = " where cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F') ";
		}else{
			$where = " where cu.code != '' and cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F') ";
		}
	}

    if($page_type=="member_vip_list"){
        $where .= " and cmd.level_ix  in ('4','5','6')";
    }else if($page_type=="member_black_list"){
        $where .= " and cmd.level_ix in ('7','8','9')  ";
    }

	if($region != ""){
		$where .= " and addr1 LIKE  '%".$region."%' ";
	}

	if($gp_level != ""){
		$where .= " and mg.gp_level = '".$gp_level."' ";
	}

	if($gp_ix != ""){
		$where .= " and mg.gp_ix = '".$gp_ix."' ";
	}


	$birthday = $birYY.$birMM.$birDD;
	$birthday2 = substr($birYY,2,2).$birMM.$birDD;

	if($sex == "M" || $sex == "W"){
		$where .= " and sex_div =  '$sex' ";
	}

	if($mailsend_yn != "A" && $mailsend_yn != ""){
		$where .= " and info =  '$mailsend_yn' ";
	}

	if($smssend_yn != "A" && $smssend_yn != ""){
		$where .= " and sms =  '$smssend_yn' ";
	}

	if($db->dbms_type == "oracle"){
		if($search_type != "" && $search_text != ""){
			if($search_type == "name" || $search_type == "mail" || $search_type == "pcs" || $search_type == "tel" ){
				$where .= " and AES_DECRYPT($search_type,'".$db->ase_encrypt_key."') LIKE  '%$search_text%' ";
			}else{
				$where .= " and $search_type LIKE  '%$search_text%' ";
			}
		}
	}else{
		if($search_type != "" && $search_text != ""){
			if($search_type == "name" || $search_type == "mail" || $search_type == "pcs" || $search_type == "tel" ){
				$where .= " and AES_DECRYPT(UNHEX($search_type),'".$db->ase_encrypt_key."') LIKE  '%$search_text%' ";
			}else{
				$where .= " and $search_type LIKE  '%$search_text%' ";
			}
		}
	}

	$startDate = $FromYY.$FromMM.$FromDD;
	$endDate = $ToYY.$ToMM.$ToDD;

	if($startDate != "" && $endDate != ""){
		$where .= " and  MID(replace(cu.date,'-',''),1,8) between  $startDate and $endDate ";
	}

	$vstartDate = $vFromYY.$vFromMM.$vFromDD;
	$vendDate = $vToYY.$vToMM.$vToDD;

	if($vstartDate != "" && $vendDate != ""){
		$where .= " and  MID(replace(cu.last,'-',''),1,8) between  $vstartDate and $vendDate ";
	}

	if($db->dbms_type == "oracle"){
		$sql = "select cmd.code, cu.id, AES_DECRYPT(cmd.name,'".$db->ase_encrypt_key."') as name, AES_DECRYPT(cmd.mail,'".$db->ase_encrypt_key."') as mail,
			cu.visit, date_format(cmd.date_,'%Y.%m.%d') as regdate, mg.gp_name,  last, AES_DECRYPT(cmd.pcs,'".$db->ase_encrypt_key."') as pcs,
			AES_DECRYPT(UNHEX(cmd.zip),'".$db->ase_encrypt_key."') as zip,AES_DECRYPT(UNHEX(cmd.addr1),'".$db->ase_encrypt_key."') as addr1,AES_DECRYPT(UNHEX(cmd.addr2),'".$db->ase_encrypt_key."') as addr2
			from common_user cu, common_member_detail cmd , ".TBL_SHOP_GROUPINFO." mg $where  ORDER BY cmd.date_ DESC "; //kbk
	}else{
		$sql = "select cmd.code, cu.id, AES_DECRYPT(UNHEX(cmd.name),'".$db->ase_encrypt_key."') as name, AES_DECRYPT(UNHEX(cmd.mail),'".$db->ase_encrypt_key."') as mail,
			cu.visit, date_format(cmd.date,'%Y.%m.%d') as regdate, mg.gp_name,  UNIX_TIMESTAMP(last) AS last, AES_DECRYPT(UNHEX(cmd.pcs),'".$db->ase_encrypt_key."') as pcs,
			AES_DECRYPT(UNHEX(cmd.zip),'".$db->ase_encrypt_key."') as zip,AES_DECRYPT(UNHEX(cmd.addr1),'".$db->ase_encrypt_key."') as addr1,AES_DECRYPT(UNHEX(cmd.addr2),'".$db->ase_encrypt_key."') as addr2
			from common_user cu, common_member_detail cmd , ".TBL_SHOP_GROUPINFO." mg $where  ORDER BY cmd.date DESC "; //kbk
	}
	//echo $sql;
	$db->query($sql);

	$memberXL = new PHPExcel();

	// 속성 정의
	$memberXL->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("Member List")
								 ->setSubject("Member List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("Member List");

	// 데이터 등록
	$memberXL->getActiveSheet(0)->setCellValue('A' . 1, "번호");
	$memberXL->getActiveSheet(0)->setCellValue('B' . 1, "그룹");
	$memberXL->getActiveSheet(0)->setCellValue('C' . 1, "이름");
	$memberXL->getActiveSheet(0)->setCellValue('D' . 1, "아이디");
	$memberXL->getActiveSheet(0)->setCellValue('E' . 1, "이메일");
	$memberXL->getActiveSheet(0)->setCellValue('F' . 1, "등록일");
	$memberXL->getActiveSheet(0)->setCellValue('G' . 1, "로긴수");
	$memberXL->getActiveSheet(0)->setCellValue('H' . 1, "적립금");
	$memberXL->getActiveSheet(0)->setCellValue('I' . 1, "핸드폰");
	$memberXL->getActiveSheet(0)->setCellValue('J' . 1, "우편번호");
	$memberXL->getActiveSheet(0)->setCellValue('K' . 1, "주소");


	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);

		if($db->dbms_type == "oracle"){
			$mdb->query("SELECT sum(if(state='1',reserve,-reserve)) as reserve_sum FROM ".TBL_SHOP_RESERVE." WHERE uid_ = '".$db->dt[code]."' and state in (1,2)");
		}else{
			$mdb->query("SELECT sum(if(state='1',reserve,-reserve)) as reserve_sum FROM ".TBL_SHOP_RESERVE." WHERE uid = '".$db->dt[code]."' and state in (1,2)");
		}
		$mdb->fetch(0);

		$memberXL->getActiveSheet()->setCellValue('A' . ($i + 2), ($i + 1));
		$memberXL->getActiveSheet()->setCellValue('B' . ($i + 2), $db->dt[gp_name]);
		$memberXL->getActiveSheet()->setCellValue('C' . ($i + 2), wel_masking_seLen($db->dt[name], 1, 1));
		$memberXL->getActiveSheet()->setCellValue('D' . ($i + 2), $db->dt[id]);
		$memberXL->getActiveSheet()->setCellValue('E' . ($i + 2), wel_masking("E",$db->dt[mail]));
		$memberXL->getActiveSheet()->setCellValue('F' . ($i + 2), $db->dt[regdate]);
		$memberXL->getActiveSheet()->setCellValue('G' . ($i + 2), $db->dt[visit]);
		$memberXL->getActiveSheet()->setCellValue('H' . ($i + 2), ($mdb->dt[reserve_sum] == "" ? "-":$mdb->dt[reserve_sum]));
		$memberXL->getActiveSheet()->setCellValue('I' . ($i + 2), wel_masking("P",$db->dt[pcs]));
		$memberXL->getActiveSheet()->setCellValue('J' . ($i + 2), $db->dt[zip]);
		$memberXL->getActiveSheet()->setCellValue('K' . ($i + 2), $db->dt[addr1]." ".$db->dt[addr2]);
	}

	// 시트이름등록
	$memberXL->getActiveSheet()->setTitle('회원');

	// 첫번째 시트 선택
	$memberXL->setActiveSheetIndex(0);
	$memberXL->getActiveSheet()->getColumnDimension('A')->setWidth(5);
	$memberXL->getActiveSheet()->getColumnDimension('B')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('C')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('G')->setWidth(10);
	$memberXL->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);

	//header('Content-Type: application/vnd.ms-excel');
	//header('Content-Disposition: attachment;filename="members.xls"');
	//header('Cache-Control: max-age=0');

	//$objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
	//$objWriter->save('php://output');





		//	wel_ 엑셀 다운로드 히스토리 저장
			$ig_excel_dn_history_SQL = "
				INSERT INTO
					ig_excel_dn_history
				SET
					code = '".$admininfo[charger_ix]."',
					ip = '". $_SERVER['REMOTE_ADDR']."',
					dn_type = 'member_black_list',
					dn_reason = '".addslashes($irs)."',
					dn_text = '".addslashes($QUERY_STRING)."',
					regDt = '".date("Y-m-d H:i:s")."'
			";
			$ig_db->query($ig_excel_dn_history_SQL);
		//	//wel_ 엑셀 다운로드 히스토리 저장



	//	ig 엑셀 파일 zip 파일로 생성 후 패스워드 걸기	방법2
		$download_filename = 'member_list_'.$info_type.date("YmdHis").'.zip'; 
		$igExcel_file = '../excelDn/member_list_'.$info_type.'.xls'; 

		$objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
		$objWriter->save($igExcel_file);


		$ig_dnFile_full = '../excelDn/'.$download_filename;

			if(trim($ipw) == "") {
				$ig_pw = "barrel";
			} else {
				$ig_pw = $ipw;
			}


			shell_exec('zip -P '.$ig_pw.' -r ../excelDn/'.$download_filename.' '.$igExcel_file);

					header('Content-type: application/octet-stream');
					header('Content-Disposition: attachment; filename="' . $download_filename . '"'); // 저장될 파일 이름
					header('Content-Transfer-Encoding: binary');
					header('Content-length: ' . filesize($ig_dnFile_full));
					header('Expires: 0');
					header("Pragma: public");

					ob_clean();
					flush();
					readfile($ig_dnFile_full);


				unlink($igExcel_file);
				unlink($ig_dnFile_full);
	//	//ig 엑셀 파일 zip 파일로 생성 후 패스워드 걸기	방법2



	exit;
?>