<?
include("../class/layout.class");
//auth(9);

$db = new Database;
$mdb = new Database;
$ig_db = new Database;

$update_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"U");
$delete_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"D");
$create_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"C");
$excel_auth = checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E");



if($_COOKIE[member_max_limit]){
	$max = $_COOKIE[member_max_limit]; //페이지당 갯수
}else{
	$max = 50;
}

if($mode == "search" || $mode == "excel"){
	include "member_query_all.php";
}

if($mode == "excel"){

	//echo $sql;
	//exit;


		//	wel_ 엑셀 다운로드 히스토리 저장
			$ig_excel_dn_history_SQL = "
				INSERT INTO
					ig_excel_dn_history
				SET
					code = '".$admininfo[charger_ix]."',
					ip = '". $_SERVER['REMOTE_ADDR']."',
					dn_type = 'member',
					dn_reason = '".addslashes($irs)."',
					dn_text = '".addslashes($QUERY_STRING)."',
					regDt = '".date("Y-m-d H:i:s")."'
			";
			$ig_db->query($ig_excel_dn_history_SQL);
		//	//wel_ 엑셀 다운로드 히스토리 저장



	$goods_infos = $db->fetchall("object");

	$info_type = "member";
	include("excel_out_columsinfo.php");
	$sql = "select conf_val from inventory_config where charger_ix='".$admininfo[charger_ix]."' and conf_name='member_list_".$info_type."' ";
	$db->query($sql);
	$db->fetch();
	$stock_report_excel = $db->dt[conf_val];

	$sql = "select conf_val from inventory_config where charger_ix='".$admininfo[charger_ix]."' and conf_name='check_member_list_".$info_type."' ";
	$db->query($sql);
	$db->fetch();
	$stock_report_excel_checked = $db->dt[conf_val];

	$check_colums = unserialize(stripslashes($stock_report_excel_checked));
	
	if(empty($check_colums)){
		echo "<script>alert('다운받을 엑셀 항목이 설정되어 있지 않습니다. 엑셀 설정 후 다시 시도 바랍니다.')</script>";
		echo "<script>window.history.back()</script>";
		exit;
	}

	$columsinfo = $colums;

	include '../include/phpexcel/Classes/PHPExcel.php';
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$inventory_excel = new PHPExcel();

	// 속성 정의
	$inventory_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("accounts plan price List")
								 ->setSubject("accounts plan price List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("accounts plan price List");
	$col = 'A';
	foreach($check_colums as $key => $value){
		$inventory_excel->getActiveSheet(0)->setCellValue($col . "1", $columsinfo[$value][title]);
		$col++;
	}

	$before_pid = "";

	for ($i = 0; $i < count($goods_infos); $i++)
	{
		$j="A";
		foreach($check_colums as $key => $value){
			if($key == "authorized"){
				switch($goods_infos[$i][authorized]){
					case "Y":
						$value_str = "승인";
						break;
					case "N":
						$value_str = "승인대기";
						break;
					case "X":
						$value_str = "승인거부";
						break;
					default:
						$value_str = "알수없음";
						break;
				}
			}else if($key == "mem_type"){

				switch($goods_infos[$i][mem_type]){
					case "M":
						$value_str = "일반회원";
						break;
					case "C":
						$value_str = "기업".($db->dt[com_name] != "" ? "(".$db->dt[com_name].")":"");
						break;
					case "A":
						$value_str = "직원(관리자)";
						break;
				}

			}else if($key == "mem_div"){
				switch($goods_infos[$i][mem_div]){
					case "MD":
					$value_str = "MD담당자";
					break;
					case "S":
					$value_str = "셀러";
					break;
					case "D":
					$value_str = "기타";
					break;
				}
			}else if($key == "nationality"){
				switch($goods_infos[$i][nationality]){
					case "I":
					$value_str = "국내";
					break;
					case "O":
					$value_str = "해외";
					break;
				}
			}else if($key == "name"){
				if($goods_infos[$i][loginType] == 'K') {
					$value_str = '*******';
				} else {
					$value_str = wel_masking_seLen($goods_infos[$i][$value], 1, 1);
				}
			}else if($key == "pcs"){
				$value_str = wel_masking("P",$goods_infos[$i][$value]);
			//}else if($key == "mail"){
			//	$value_str = wel_masking("E",$goods_infos[$i][$value]);
			}else{
				$value_str = $goods_infos[$i][$value];//$db1->dt[$value];
			}

			$inventory_excel->getActiveSheet()->setCellValue($j . ($z + 2), $value_str);
			$j++;

			unset($history_text);
		}
		$z++;
	}
	// 첫번째 시트 선택
	$inventory_excel->setActiveSheetIndex(0);

	// 너비조정
	$col = 'A';
	foreach($check_colums as $key => $value){
		$inventory_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}



	//header('Content-Type: application/vnd.ms-excel');
	//header('Content-Disposition: attachment;filename="member_list_'.$info_type.'.xls"');
	//header('Cache-Control: max-age=0');

	//$objWriter = PHPExcel_IOFactory::createWriter($inventory_excel, 'Excel5');
	//$objWriter->save('php://output');




	//	ig 엑셀 파일 zip 파일로 생성 후 패스워드 걸기	방법2
		$download_filename = 'member_list_'.$info_type.date("YmdHis").'.zip'; 
		$igExcel_file = '../excelDn/member_list_'.$info_type.'.xlsx'; 

		$objWriter = PHPExcel_IOFactory::createWriter($inventory_excel, 'Excel2007');
		$objWriter->save($igExcel_file);


		$ig_dnFile_full = '../excelDn/'.$download_filename;

			if(trim($ipw) == "") {
				$ig_pw = "barrel";
			} else {
				$ig_pw = $ipw;
			}


			shell_exec('zip -P '.$ig_pw.' -r ../excelDn/'.$download_filename.' '.$igExcel_file);

					header('Content-type: application/octet-stream');
					header('Content-Disposition: attachment; filename="' . $download_filename . '"'); // 저장될 파일 이름
					header('Content-Transfer-Encoding: binary');
					header('Content-length: ' . filesize($ig_dnFile_full));
					header('Expires: 0');
					header("Pragma: public");

					ob_clean();
					flush();
					readfile($ig_dnFile_full);


				unlink($igExcel_file);
				unlink($ig_dnFile_full);
	//	//ig 엑셀 파일 zip 파일로 생성 후 패스워드 걸기	방법2





	/*
	//	ig 엑셀 파일 zip 파일로 생성 후 패스워드 걸기	방법1

		//	echo $ipw; //	파일 비밀번호
		$objWriter = PHPExcel_IOFactory::createWriter($inventory_excel, 'Excel5');
		$excel_file_tmp = tempnam("../excelDn/", 'member_list_'.$info_type);
		$objWriter->save($excel_file_tmp);


			//$ig_zip_file_tmp = tempnam("../excelDn/", 'member_list_'.$info_type);
			$ig_zip = new ZipArchive();


			$download_filename = 'member_list_'.$info_type.date("YmdHis").'.zip'; 

			$ig_file = '../excelDn/'.$download_filename; // 저장할 파일명


			//$ig_req = $ig_zip->open($ig_zip_file_tmp, ZipArchive::OVERWRITE);
			$ig_req = $ig_zip->open($ig_file, ZipArchive::OVERWRITE);





			if ($ig_req === true) { 

				// 파일을 만들면서 내용을 넣는다. 
				$ig_zip->addFile($excel_file_tmp, 'member_list_'.$info_type.'_val.xls');
				$ig_zip->close();

						//shell_exec('zip -P 1234 -r ../excelDn/ig_test.zip '.$ig_file);
						//system('echo "1234" | zipcloak '.$ig_file);
						//shell_exec('zip -P 1234 '.$ig_file.' '.$ig_file);

					$N_file = $ig_file; // 파일의 전체 경로
					$N_file_name = $download_filename; // 저장될 파일 이름

					header('Content-type: application/octet-stream');
					header('Content-Disposition: attachment; filename="' . $N_file_name . '"');
					header('Content-Transfer-Encoding: binary');
					header('Content-length: ' . filesize($ig_file));
					header('Expires: 0');
					header("Pragma: public");

					ob_clean();
					flush();
					readfile($N_file);


				unlink($ig_file);
				unlink($excel_file_tmp);

			}
			else {
				echo "failed errno: ". $ig_req ." ";
	//	//ig 엑셀 파일 zip 파일로 생성 후 패스워드 걸기
	*/






	exit;
}


$Script = "
<script language='javascript'>

function view_go()
{
	var sort = document.view.sort[document.view.sort.selectedIndex].value;
	location.href = 'member.php?view='+sort;
}

function ChangeRegistDate(frm){
	if(frm.regdate.checked){
		$('input[name=cmd_sdate]').attr('disabled',false);
		$('input[name=cmd_edate]').attr('disabled',false);

	}else{
		$('input[name=cmd_sdate]').attr('disabled',true);
		$('input[name=cmd_edate]').attr('disabled',true);
	}
}

function ChangeVisitDate(frm){
	if(frm.visitdate.checked){
		$('input[name=slast]').attr('disabled',false);
		$('input[name=elast]').attr('disabled',false);
	}else{
		$('input[name=slast]').attr('disabled',true);
		$('input[name=elast]').attr('disabled',true);
	}
}

function init(){

	var frm = document.searchmember;
	onLoad('$sDate','$eDate','$sDate2','$eDate2','$sDate3');";

$Script .= "
}


function deleteMemberInfo(act, code){
	if(confirm('해당회원 정보를 정말로 삭제하시겠습니까? \\n 삭제시 관련된 모든 정보가 삭제됩니다.')){
		window.frames['iframe_act'].location.href= 'member.act.php?act='+act+'&code='+code;
	}
}

$(document).ready(function (){

	$('#max').change(function(){
		var value= $(this).val();
		$.cookie('member_max_limit', value, {expires:1,domain:document.domain, path:'/', secure:0});
		document.location.reload();
		
	});

});


</script>";

$Contents = "
<script language='javascript' src='member.js?page=$page&ctgr=$ctgr&view=$view&qstr=".rawurlencode($qstr)."'></script>
<table width='100%' border='0' align='center'>
<tr>
	<td align='left' colspan=6 > ".GetTitleNavigation("전체회원관리", "회원관리 > 전체회원관리 ")."</td>
</tr>
<tr>
	<td>
	<table width='100%' cellpadding=0 cellspacing=0 border='0' >
	<col width='15%' />
	<col width='35%' />
	<col width='15%' />
	<col width='35%' />
	<tr>
	    <td align='left' colspan=4> ".GetTitleNavigation("$menu_name", "본사관리 > $menu_name")."</td>
	</tr>
	<tr>
	    <td align='left' colspan=4 style='padding-bottom:20px;'>
	    <div class='tab'>
			<table class='s_org_tab'>
			<col width='550px'>
			<col width='*'>
			<tr>
				<td class='tab'>
					<table id='tab_01' ".(($info_type == "member" || $info_type == "") ? "class='on' ":"").">
					<tr>
						<th class='box_01'></th>
						<td class='box_02'  ><a href='?info_type=member'>전체회원리스트</a> <span style='padding-left:2px' class='helpcloud' help_width='410' help_height='70' help_html='사업자 정보를 작성하여 등록한 후에 해당 사업자에 관리자화면 로그인 정보를 발급해 줄 수 있습니다.<br />사업자 정보 추가 후 [목록관리] - [사용자 추가]를 통해 관리자에 계정을 발급해 주시기 바랍니다.'><img src='/admin/images/icon_q.gif' /></span></td>
						<th class='box_03'></th>
					</tr>
					</table>";
/*
$Contents .= "
					<table id='tab_02' ".($info_type == "basic_member" ? "class='on' ":"").">
					<tr>
						<th class='box_01'></th>
						<td class='box_02' >";

							$Contents .= "<a href='basic_member.php?info_type=basic_member'>회원가입/매출기초분석</a>";

						$Contents .= "
						</td>
						<th class='box_03'></th>
					</tr>
					</table>";
*/
$Contents .= "
					<!--
					<table id='tab_03' ".($info_type == "cust_member" ? "class='on' ":"").">
					<tr>
						<th class='box_01'></th>
						<td class='box_02' >";

							$Contents .= "<a href='cust_member.php?info_type=cust_member'>회원별상세매출분석</a>";

						$Contents .= "

						</td>
						<th class='box_03'></th>
					</tr>
					</table>
					-->
				</td>
				<td style='text-align:right;vertical-align:bottom;padding:0 0 10px 0'>

				</td>
			</tr>
			</table>
		</div>
		</td>
	</tr>
	</table>";

$Contents .= "
	<table class='box_shadow' style='width:100%;' cellpadding='0' cellspacing='0' border='0'>
		<tr>
			<th class='box_01'></th>
			<td class='box_02'></td>
			<th class='box_03'></th>
		</tr>
		<tr>
			<th class='box_04'></th>
			<td class='box_05'  valign=top style='padding:5px 0px 5px 0px'>
			<table width='100%' border='0' cellspacing='0' cellpadding='0' height='25' class='search_table_box'>
			<form name=searchmember method='get'><!--SubmitX(this);'-->
				<input type='hidden' name=mc_ix value='".$mc_ix."'>
				<input type='hidden' name=mode value='search'>
				<col width='18%'>
				<col width='32%'>
				<col width='18%'>
				<col width='32%'>";
					if($_SESSION["admin_config"][front_multiview] == "Y"){
					$Contents .= "
					<tr>
						<td class='search_box_title' > 글로벌 회원 구분</td>
						<td class='search_box_item' colspan=3>".GetDisplayDivision($mall_ix, "select")." </td>
					</tr>";
					}
$Contents .= "
					<tr height=27>
						<td class='search_box_title' >조건검색 
						<input type='checkbox' name='mult_search_use' id='mult_search_use' value='1' ".($mult_search_use == '1'?'checked':'')." title='다중검색 체크'> 
						<label for='mult_search_use'>(다중검색 체크)</label>
						</td>
						<td class='search_box_item'>
							<table cellpadding=0 cellspacing=0 width=100%>
								<col width='80'>
								<col width='*'>
								<tr>
									<td>
									<select name=search_type>
											<option value='cmd.pcs' ".CompareReturnValue("cmd.pcs",$search_type,"selected").">휴대전화</option>
											<option value='cmd.name' ".CompareReturnValue("cmd.name",$search_type,"selected").">고객명</option>
											<option value='cu.id' ".CompareReturnValue("cu.id",$search_type,"selected").">아이디</option>
											<option value='cmd.tel' ".CompareReturnValue("cmd.tel",$search_type,"selected").">전화번호</option>
											<option value='ccd.com_name' ".CompareReturnValue("ccd.com_name",$search_type,"selected").">회사명</option>
											<option value='ccd.com_phone' ".CompareReturnValue("ccd.com_phone",$search_type,"selected").">회사전화</option>
											<option value='ccd.com_fax' ".CompareReturnValue("ccd.com_fax",$search_type,"selected").">회사팩스</option>
											<option value='cmd.mail' ".CompareReturnValue("cmd.mail",$search_type,"selected").">이메일</option>
											<option value='cmd.addr1' ".CompareReturnValue("cmd.addr1",$search_type,"selected").">주소</option>
									</select>
									</td>
									<td>
										<div id='search_text_input_div'>
											<input type=text name='search_text' class='textbox' value='".$search_text."' style='width:70%;font-size:12px;padding:1px;' >
										</div>
										<div id='search_text_area_div' style='display:none;'>
											<textarea name='search_text' id='search_text_area' class='tline textbox' style='padding:0px;height:90px;width:150px;' disabled>".$search_text."</textarea>
											<div style='color:blue;'>*다중 검색의 경우 약 150건의 데이터를 검색 하실 수 있습니다.(문자열 길이에 따라 +- 오차가 있습니다.)</div>
										</div>
										
									</td>
								</tr>
							</table>
						</td>
						<td class='search_box_title' >회원그룹 </td>
						<td class='search_box_item' >
						".makeGroupSelectBox($mdb,"gp_ix",$gp_ix)."
						</td>
					</tr>
					<tr height=27>
					<!--
						<td class='search_box_title' >국내/해외 </td>
						<td class='search_box_item' >
						<input type=radio name='nationality' value=''  id='nationality_'  ".CompareReturnValue("",$nationality,"checked")." checked><label for='nationality_'>전체</label>
						<input type=radio name='nationality' value='I' id='nationality_I' ".CompareReturnValue("I",$nationality,"checked")."><label for='nationality_I'>국내회원</label>
						<input type=radio name='nationality' value='O' id='nationality_O' ".CompareReturnValue("O",$nationality,"checked")."><label for='nationality_O'>해외회원</label>
						<input type=radio name='nationality' value='D' id='nationality_D' ".CompareReturnValue("D",$nationality,"checked")."><label for='nationality_D'>기타회원</label>
						</td>
						-->
						<td class='search_box_title' >회원구분 </td>
						<td class='search_box_item' colspan='3'>
						<input type=radio name='mem_type' value=''  id='mem_type_'  ".CompareReturnValue("",$mem_type,"checked")." checked><label for='mem_type_'>전체</label>
						<input type=radio name='mem_type' value='M' id='mem_type_m' ".CompareReturnValue("M",$mem_type,"checked")."><label for='mem_type_m'>일반회원</label>
						<input type=radio name='mem_type' value='C' id='mem_type_c' ".CompareReturnValue("C",$mem_type,"checked")."><label for='mem_type_c'>사업자회원</label>
						<!--input type=radio name='mem_type' value='A' id='mem_type_a' ".CompareReturnValue("A",$mem_type,"checked")."><label for='mem_type_a'>직원(관리자)</label-->
						</td>
					</tr>
					<tr  height=27>
						<td class='search_box_title'  >지역선택</td>
						<td class='search_box_item'>
							<select name='region' style='width:100px;font-size:12px;'>
								<option value=''>지역 선택</option>
								<option value='서울'  ".CompareReturnValue("서울",$region,"selected").">서울</option>
								<option value='충북'  ".CompareReturnValue("충북",$region,"selected").">충북</option>
								<option value='충남'  ".CompareReturnValue("충남",$region,"selected").">충남</option>
								<option value='전북'  ".CompareReturnValue("전북",$region,"selected").">전북</option>
								<option value='제주'  ".CompareReturnValue("제주",$region,"selected").">제주</option>
								<option value='전남'  ".CompareReturnValue("전남",$region,"selected").">전남</option>
								<option value='경북'  ".CompareReturnValue("경북",$region,"selected").">경북</option>
								<option value='경남'  ".CompareReturnValue("경남",$region,"selected").">경남</option>
								<option value='경기'  ".CompareReturnValue("경기",$region,"selected").">경기</option>
								<option value='부산'  ".CompareReturnValue("부산",$region,"selected").">부산</option>
								<option value='대구'  ".CompareReturnValue("대구",$region,"selected").">대구</option>
								<option value='인천'  ".CompareReturnValue("인천",$region,"selected").">인천</option>
								<option value='광주'  ".CompareReturnValue("광주",$region,"selected").">광주</option>
								<option value='대전'  ".CompareReturnValue("대전",$region,"selected").">대전</option>
								<option value='울산'  ".CompareReturnValue("울산",$region,"selected").">울산</option>
								<option value='강원'  ".CompareReturnValue("강원",$region,"selected").">강원</option>
								</select>
						</td>
						<td class='search_box_title' >회원타입 </td>
						<td class='search_box_item' >
							<input type=radio name='mem_div' value='' id='mem_div_'  ".CompareReturnValue("",$mem_div,"checked")." checked><label for='mem_div_'>전체</label>
							<input type=radio name='mem_div' value='S' id='mem_div_s'  ".CompareReturnValue("S",$mem_div,"checked")."><label for='mem_div_s'>셀러</label>
							<input type=radio name='mem_div' value='MD' id='mem_div_md' ".CompareReturnValue("MD",$mem_div,"checked")."><label for='mem_div_md'>MD담당자</label>
							<input type=radio name='mem_div' value='D' id='mem_div_d' ".CompareReturnValue("D",$mem_div,"checked")."><label for='mem_div_d'>기타</label>
						</td>
					</tr>
					<tr height=27>
						<td class='search_box_title' >이메일 발송여부 </td>
						<td class='search_box_item'  >
						<input type=radio name='mailsend_yn' value='A' id='mailsend_a'  ".CompareReturnValue("A",$mailsend_yn,"checked")." checked><label for='mailsend_a'>전체</label>
						<input type=radio name='mailsend_yn' value='1' id='mailsend_y'  ".CompareReturnValue("1",$mailsend_yn,"checked")."><label for='mailsend_y'>수신회원만</label><input type=radio name='mailsend_yn' value='0' id='mailsend_n' ".CompareReturnValue("0",$mailsend_yn,"checked")."><label for='mailsend_n'>수신거부회원</label>
						</td>
						<td class='search_box_title' >SMS 발송여부 </td>
						<td class='search_box_item'  >
							<input type=radio name='smssend_yn' value='A' id='smssend_a'  ".CompareReturnValue("A",$smssend_yn,"checked")." checked><label for='smssend_a'>전체</label>
							<input type=radio name='smssend_yn' value='1' id='smssend_y'  ".CompareReturnValue("1",$smssend_yn,"checked")."><label for='smssend_y'>수신회원만</label>
							<input type=radio name='smssend_yn' value='0' id='smssend_n' ".CompareReturnValue("0",$smssend_yn,"checked")."><label for='smssend_n'>수신거부회원</label>
						</td>
					</tr>";

	 $Contents .= "
					<tr height=27>
						<td class='search_box_title' ><label for='regdate'>가입일자</label><input type='checkbox' name='regdate' id='regdate' value='1' onclick='ChangeRegistDate(document.searchmember);' ".CompareReturnValue("1",$regdate,"checked")."></td>
						<td class='search_box_item'  colspan=3 >
							".search_date('cmd_sdate','cmd_edate',$cmd_sdate,$cmd_edate)."
						</td>
					</tr>
					<tr height=27>
						<td class='search_box_title' ><label for='visitdate'>최근방문일</label><input type='checkbox' name='visitdate' id='visitdate' value='1' onclick='ChangeVisitDate(document.searchmember);' ".CompareReturnValue("1",$visitdate,"checked")."></td>
						<td class='search_box_item'  colspan=3  >
							".search_date('slast','elast',$slast,$elast)."
						</td>
					</tr>
					<tr height=27>
						<td class='search_box_title' >마일리지(M) 보유</td>
						<td class='search_box_item' colspan='3' >
							<input type=radio name='mileage' value='' id='reserve_'  ".CompareReturnValue("",$mileage,"checked")." checked><label for='reserve_'>전체</label>
							<input type=radio name='mileage' value='1' id='reserve_y'  ".CompareReturnValue("1",$mileage,"checked")."><label for='reserve_y'>보유</label>
							<input type=radio name='mileage' value='2' id='reserve_n' ".CompareReturnValue("2",$mileage,"checked")."><label for='reserve_n'>미보유</label>
						</td>
						<!--
						<td class='search_box_title' >포인트(P) 보유 </td>
						<td class='search_box_item'  >
							<input type=radio name='point' value='' id='point_'  ".CompareReturnValue("",$point,"checked")." checked><label for='point_'>전체</label>
							<input type=radio name='point' value='1' id='point_y'  ".CompareReturnValue("1",$point,"checked")."><label for='point_y'>보유</label>
							<input type=radio name='point' value='2' id='point_n' ".CompareReturnValue("2",$point,"checked")."><label for='point_n'>미보유</label>
						</td>
						-->
					</tr>
					<tr height=27>
						<td class='search_box_title' >가입경로</td>
						<td class='search_box_item'  colspan=3>
							<input type=radio name='agent_type' value='' id='agent_type_'  ".CompareReturnValue("",$agent_type,"checked")." checked><label for='agent_type_'>전체</label>
							<input type=radio name='agent_type' value='W' id='agent_type_W'  ".CompareReturnValue("W",$agent_type,"checked")."><label for='agent_type_W'>PC(web)</label>
							<input type=radio name='agent_type' value='M' id='agent_type_M' ".CompareReturnValue("M",$agent_type,"checked")."><label for='agent_type_M'>모바일</label>
						</td>
						 
					</tr>
				</table>
			</td>
			<th class='box_06'></th>
		</tr>
		<tr>
			<th class='box_07'></th>
			<td class='box_08'></td>
			<th class='box_09'></th>
		</tr>
	</table>
	</td>
</tr>
<tr height=50>
	<td style='padding:10px 20px 0 20px' colspan=4 align=center><input type=image src='../images/".$admininfo["language"]."/bt_search.gif' align=absmiddle  ></td>
</tr>
</table><br></form>

<form name='list_frm'>
<input type='hidden' name='code[]' id='code'>
<table width='100%' cellpadding=0 cellspacing=0 border=0>
<col width=15%>
<col width=47%>
<col width=18%>
<col width=9%>
<tr>
	<td>전체 회원수 : ".number_format($total)." 명</td>
	<td align=left height=30>
	</td>
	<td align=right>";

if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E")){
	$Contents .= "<span class='helpcloud' help_height='30' help_html='엑셀 다운로드 형식을 설정하실 수 있습니다.'>
					<a href='excel_config.php?".$QUERY_STRING."&info_type=member&excel_type=member_list_excel' rel='facebox' >
					<img src='../images/".$admininfo["language"]."/btn_excel_set.gif'></a></span>";
}else{
	$Contents .= "<a href=\"".$auth_excel_msg."\"><img src='../images/".$admininfo["language"]."/btn_excel_set.gif'></a>";
}
	$Contents .= "&nbsp;";
if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E")){
	//$Contents .= "<a href='member.php?".$_SERVER["QUERY_STRING"]."&mode=excel'><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";
	$Contents .= "<a href='javascript:ig_excel_dn_chk(\"member.php?".$_SERVER["QUERY_STRING"]."&mode=excel\");'><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";


}else{
	$Contents .= "<a href=\"".$auth_excel_msg."\"><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";
}

$Contents .= "
	</td>
	<td align=right>
	목록수 : <select name='max' id='max'>
				<option value='5' ".($_COOKIE[member_max_limit] == '5'?'selected':'').">5</option>
				<option value='10' ".($_COOKIE[member_max_limit] == '10'?'selected':'').">10</option>
				<option value='20' ".($_COOKIE[member_max_limit] == '20'?'selected':'').">20</option>
				<option value='30' ".($_COOKIE[member_max_limit] == '30'?'selected':'').">30</option>
				<option value='50' ".($_COOKIE[member_max_limit] == '50'?'selected':'').">50</option>
				<option value='100' ".($_COOKIE[member_max_limit] == '100'?'selected':'').">100</option>
				<option value='500' ".($_COOKIE[member_max_limit] == '500'?'selected':'').">500</option>
			</select>
	</td>
</tr>
</table>

<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' class='list_table_box'>
<tr height='34' bgcolor='#ffffff'>
	<td width='2%' align='center' class=s_td><input type=checkbox name='all_fix' id='all_fix' onclick='fixAll(document.list_frm)'></td>
	<td width='3%' align='center' class='m_td'><font color='#000000'><b>순번</b></font></td>
	<td width='5%' align='center' class='m_td'><font color='#000000'><b>그룹</b></font></td>
	<td width='5%' align='center' class='m_td small' nowrap><font color='#000000'><b>국내<br>해외</b></font></td>
	<td width='6%' align='center' class='m_td' nowrap><font color='#000000'><b>회원구분</b></font></td>
	 <td width='6%' align='center' class='m_td' nowrap><font color='#000000'><b>회원타입</b></font></td>
	<!--<td width='6%' align='center' class=m_td nowrap><font color='#000000'><b>승인여부</b></font></td>-->
	<td width='7%' align='center' class=m_td><font color='#000000'><b>이름</b></font></td>
	<td width='9%' align='center' class=m_td><font color='#000000'><b>아이디</b></font></td>
	<td width='17%' align='center' class=m_td><font color='#000000'><b>이메일</b></font></td>
	<td width='9%' align='center' class=m_td><font color='#000000'><b>최근방문일</b></font></td>
	<td width='6%' align='center' class=m_td><font color='#000000'><b>로긴수</b></font></td>";
	if($admininfo[mall_type] != "H"){
	$Contents .= "
	<td width='6%' align='center' class=m_td><font color='#000000'><b>마일리지</b></font></td>
	<!--<td width='6%' align='center' class=m_td><font color='#000000'><b>포인트</b></font></td>-->";
	}
	$Contents .= "
	<td width='20%' align='center' class=e_td><font color='#000000'><b>관리</b></font></td>
</tr>";

	for ($i = 0; $i < $db->total; $i++){

		$db->fetch($i);
		$no = $total - ($page - 1) * $max - $i;

	/*
		if ($db->dt[mem_level] == "E")	{ $perm = "탈퇴회원"; }
		if ($db->dt[mem_level] == "M")	{ $perm = "일반회원"; }
		if ($db->dt[mem_level] == "B")	{ $perm = "입점업체"; }
		if ($db->dt[mem_level] == "C")	{ $perm = "특별회원"; }
	*/


/*		// 회원 마일리지 포인트 값은 common_user 에 mileage , point 에서 가져오면 됩니다. 새로운 구조로 변경  2013-06-20 이학봉
		if($db->dbms_type == "oracle"){
			$mdb->query("SELECT sum(reserve) as reserve_sum FROM ".TBL_SHOP_RESERVE_INFO." WHERE uid_ = '".$db->dt[code]."' and state in ('1','2','5','6','7')");
		}else{
			$sql = "SELECT IFNULL(sum(reserve),'0') as reserve_sum FROM ".TBL_SHOP_RESERVE_INFO." WHERE uid = '".$db->dt[code]."' and state in ('1','2','5','6','7')";
			//echo $sql;
			$mdb->query($sql);
		}
		$mdb->fetch(0);
		$reserve_sum = number_format($mdb->dt[reserve_sum]);
*/

		if($db->dt[is_id_auth] != "Y"){
			$is_id_auth = "미인증";
		}else{
			$is_id_auth = "";
		}

		switch($db->dt[authorized]){
			case "Y":
				$authorized = "승인";
				break;
			case "N":
				$authorized = "승인대기";
				break;
			case "X":
				$authorized = "승인거부";
				break;
			default:
				$authorized = "알수없음";
				break;
		}

		switch($db->dt[mem_type]){
            case "M":
                $mem_type = "일반회원";
                break;
            case "F":
                $mem_type = "글로벌회원";
                break;
			case "C":
				$mem_type = "기업<br>".($db->dt[com_name] != "" ? "(".$db->dt[com_name].")":"");
				break;
			case "A":
				$mem_type = "직원(관리자)";
				break;
		}

		switch($db->dt[mem_div]){
			case "MD":
			$mem_div = "MD담당자";
			break;
			case "S":
			$mem_div = "셀러";
			break;
			case "D":
			$mem_div = "기타";
			break;
		}

		/*
		switch($db->dt[nationality]){
			case "I":
			$nationality = "국내";
			break;
			case "O":
			$nationality = "해외";
			break;
			case "D":
			$nationality = "기타";
			break;
		}
		*/
        $nationality = GetDisplayDivision($db->dt['mall_ix'], "text");

if($_SESSION["admininfo"]["charger_id"] == "forbiz"){
		switch($db->dt[sex_div]){
			case "W":
			$sex_div = "<span style='padding-left:2px' class='helpcloud' help_width='45' help_height='20' help_html='여성'><img src='../images/".$admininfo["language"]."/Female.png' style='cursor:pointer;'></span>";
			break;
			case "M":
			$sex_div = "<span style='padding-left:2px' class='helpcloud' help_width='45' help_height='20' help_html='남성'><img src='../images/".$admininfo["language"]."/Male.png' style='cursor:pointer;'></span>";
			break;
			case "D":
			default:
			$sex_div = "";
			break;
		}
}

		$Contents = $Contents."
		<tr height='32' onMouseOver=\"this.style.backgroundColor='#E8ECF1'; \" onMouseOut=\"this.style.backgroundColor=''\">
			<td class='list_box_td'><input type=checkbox name=code[] id='code' value='".$db->dt[code]."'></td>
			<td class='list_box_td' nowrap>".$no."</td>
			<td class='list_box_td' style='padding:0px 5px;' nowrap><span title='".$db->dt[organization_name]."'>".$db->dt[gp_name]."</span></td>
			<td class='list_box_td' nowrap>".$nationality."(".($db->dt[agent_type] == "M" ? "모바일":"웹").")</td>
			<td class='list_box_td small' style='line-height:150%;' nowrap>".$mem_type."</td>
			<td class='list_box_td' nowrap>".$mem_div."</td>
			<!--<td class='list_box_td' >".$authorized."</td>-->
			<td class=' point' nowrap align='left'>
				<table border='0' width='100%'>
				<tr>
					<td width='17'>".$sex_div."</td>
					<td align='left'>";
					if($update_auth){
						$Contents .= "<a href=\"javascript:PopSWindow2('member_info.php?mmode=pop&code=".$db->dt[code]."&mmode=pop',1280,800,'member_view')\" style='cursor:pointer' >";
					}else{
						$Contents .= "<a href=\"".$auth_update_msg."\">";
					}
					if($admininfo["language"] == 'korean') {
						$Contents .="<!--<a href=\"javascript:PopSWindow('member_view.php?code=".$db->dt[code]."',985,600,'member_info')\" style='cursor:pointer' >-->".wel_masking_seLen(Black_list_check($db->dt[code],$db->dt[name]), 1, 1);
                    }else{
                        $Contents .="<!--<a href=\"javascript:PopSWindow('member_view.php?code=".$db->dt[code]."',985,600,'member_info')\" style='cursor:pointer' >-->".wel_masking_seLen(Black_list_check($db->dt[code],$db->dt[first_name]." ".$db->dt[last_name]), 1, 1);
                    }

			$Contents .= " 
					</td>
				</tr>
				</table>
			</td>
			<td class='list_box_td' ><a href=\"javascript:PopSWindow2('member_cti.php?mmode=pop&code=".$db->dt[code]."&mmode=pop',1280,800,'member_view')\" style='cursor:pointer' >".$db->dt[id]."</a></td>
			<td class='list_box_td' >".wel_masking("E", $db->dt[mail])."<font color=red> ".$is_id_auth."</font></td>
			<td class='list_box_td' >".$db->dt[last]."</td>
			<td class='list_box_td' >".$db->dt[visit]."</td>";
		if($admininfo[mall_type] != "H"){
			$Contents .= "
			<td class='list_box_td ctr point' ><a href=\"javascript:PoPWindow('mileage.pop.php?code=".$db->dt[code]."',700,700,'mileage_pop')\">".$db->dt[mileage]."</a></td>
			<!--<td class='list_box_td ctr point' ><a href=\"javascript:PoPWindow('point.pop.php?code=".$db->dt[code]."',700,700,'reserve_pop')\">".$db->dt[point]."</a></td>-->";
		}
			$Contents .= "
			<td class='list_box_td ctr'  style='padding:5px;' nowrap>";
			if($update_auth){
				$Contents .= "<img src='../images/".$admininfo["language"]."/btn_crm.gif' border=0 align=absmiddle onClick=\"PopSWindow2('member_cti.php?mmode=pop&code=".$db->dt[code]."&mmode=pop',1280,800,'member_view')\" style='cursor:pointer;' alt='고객상담' title='고객상담'/> ";
			}else{
				$Contents .= "<a href=\"".$auth_update_msg."\"><img src='../images/".$admininfo["language"]."/btn_crm.gif' border=0 align=absmiddle alt='고객상담' title='고객상담' ></a> ";
			}

			if($update_auth){
				$Contents .= "<img src='../images/".$admininfo["language"]."/bts_modify.gif' border=0 align=absmiddle onClick=\"PopSWindow('member_info.php?mmode=pop&code=".$db->dt[code]."&mmode=pop',900,710,'member_info')\" style='cursor:pointer;' alt='수정' title='수정'/> ";
			}else{
				$Contents .= "<a href=\"".$auth_update_msg."\"><img src='../images/".$admininfo["language"]."/bts_modify.gif' border=0 align=absmiddle alt='수정' title='수정' ></a> ";
			}

			//$mString .= "<img  src='../image/btn_view_source.gif'  border=0 align=absmiddle>";
			if($delete_auth){
				$Contents .= "<img src='../images/".$admininfo["language"]."/btn_del.gif' border=0 align=absmiddle onClick=\"deleteMemberInfo('delete','".$db->dt[code]."')\" style='cursor:pointer;' alt='삭제' title='삭제'/> ";
			}else{
				//$Contents .= "<a href=\"".$auth_delete_msg."\"><img src='../image/btc_del.gif' border=0 align=absmiddle ></a> ";
			}
			if($create_auth){
				 $Contents .= "
				 <img src='../images/".$admininfo["language"]."/btn_sms.gif' align=absmiddle onclick=\"PoPWindow('../sms.pop.php?code=".$db->dt[code]."',500,380,'sendsms')\" style='cursor:pointer;' alt='문자발송' title='문자발송'>
				 <img src='../images/".$admininfo["language"]."/btn_email.gif' align=absmiddle onclick=\"PoPWindow('../mail.pop.php?code=".$db->dt[code]."',550,535,'sendmail')\" style='cursor:pointer;' alt='이메일발송' title='이메일발송'>
				 ";
			}else{
				$Contents .= "
				 <a href=\"".$auth_write_msg."\"><img src='../images/".$admininfo["language"]."/btn_sms.gif' align=absmiddle alt='문자발송' title='문자발송'></a>
				 <a href=\"".$auth_write_msg."\"><img src='../images/".$admininfo["language"]."/btn_email.gif' align=absmiddle alt='이메일발송' title='이메일발송'></a>
				 ";
			}
			$Contents .= "
	</td>
</tr>";

}

if (!$db->total){

$Contents .= "
<tr height=50>
	<td colspan='15' align='center'>";
		if($mode == "search"){
			$Contents .= "검색결과에 맞는 회원 데이타가 없습니다.";
		}else{
			$Contents .= "조회하시고자 하는 검색조건을 선택후 검색해주세요";
		}
		$Contents .= "
	</td>
</tr>";
}

$Contents .= "
</table>
</form>

<table width=100%>
	<tr height='40'>
		<td align='left'>";

		if($create_auth){
			$Contents .= "
			<a href='javascript:listAction(document.list_frm);'><img src='../images/".$admininfo["language"]."/btn_selected_sms.gif' align=absmiddle  ></a>";
		}else{
			$Contents .= "
			<a href=\"".$auth_write_msg."\"><img src='../images/".$admininfo["language"]."/btn_selected_sms.gif' align=absmiddle ></a>";
		}
$Contents .= "
		</td>
		<td align='right'>".$str_page_bar."</td>
	</td>
</tr>
</table>";

/*
$help_text = "
<table cellpadding=0 cellspacing=0 class='small' >
	<col width=8>
	<col width=*>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >회원에게 SMS 또는 메일을 보내실려면 보내고자 하는 회원을 선택하신후 '선택회원 SMS 보내기' 버튼을 클릭하신후 메일을 보내실수 있습니다</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >회원정보를 백업하기 위해서는 회원정보 검색후 엑셀로 저장 버튼을 클릭하시면 됩니다</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >검색기능을 통해서 조건에 맞는 회원을 빠르게 검색하실수 있습니다</td></tr>
</table>
";*/

$help_text = getTransDiscription(md5($_SERVER["PHP_SELF"]),'A');

$Contents .= HelpBox("회원관리", $help_text,'70');


$Contents .= "
<form name='lyrstat'>
	<input type='hidden' name='opend' value=''>
</form>";


$P = new LayOut();
$P->addScript = "<script language='javascript' src='../include/DateSelect.js'></script>\n".$Script;
$P->OnloadFunction = "";	//init();
$P->strLeftMenu = member_menu();
$P->Navigation = "회원관리 > 전체회원";
$P->title = "전체회원";
$P->strContents = $Contents;
echo $P->PrintLayOut();


//	웰숲 우클릭 방지
include_once("../order/wel_drag.php");
?>

<script type="text/javascript">
	//	wel_ 새벽시간(23시~07시)이나 휴무일 등 업무시간 외 다운로드시 검수
	function ig_excel_dn_chk(s_val_Data) {
		//console.log(s_val_Data);
		var ig_now = new Date();   //현재시간
		var ig_hour = ig_now.getHours();   //현재 시간 중 시간.




			//	새벽시간(23시~07시), 휴무일(일, 토)
		//if(Number(ig_hour) >= "23" || Number(ig_hour) <= "7" || Number(ig_now.getDay()) == "0" || Number(ig_now.getDay()) == "6") {
			var ig_inputString = prompt('사유를 간략하게 입력하세요.\r\n(20자 이내(띄어쓰기포함), 특수문자 제외)');

			if(ig_inputString != null && ig_inputString.trim() != "") {
				//	엑셀다운로드 진행

					var str_length = ig_inputString.length;		// 전체길이

					if(str_length > "20") {
						alert("사유가 20자 이상 입니다.");
						return false;
					} else {
						var ig_inputString_PW = prompt('파일 비밀번호를 지정해 주세요.\r\n(15자 이하, 영문/숫자만 사용, 공백사용금지)');

							if(ig_inputString_PW != null && ig_inputString_PW.trim() != "") {

								var str_PW_length = ig_inputString_PW.length;		// 전체길이

								if(str_PW_length > "15") {
									alert("비밀번호를 15자 이하로 해주세요.");
									return false;
								} else {
									location.href = s_val_Data+"&irs="+ig_inputString+"&ipw="+ig_inputString_PW;
								}

							} else {
								alert("비밀번호를 입력해 주세요.");
								return false;
							}
					}


			} else {
				alert("사유를 입력하세요");
				return false;
			}
		/*} else {
			//	일반 업무때 다운로드
			var ig_inputString_PW = prompt('파일 비밀번호를 지정해 주세요.\r\n(15자 이하, 영문/숫자만 사용, 공백사용금지)');

				if(ig_inputString_PW != null && ig_inputString_PW.trim() != "") {

					var str_PW_length = ig_inputString_PW.length;		// 전체길이

					if(str_PW_length > "15") {
						alert("비밀번호를 15자 이하로 해주세요.");
						return false;
					} else {
						location.href = s_val_Data+"&ipw="+ig_inputString_PW;
					}

				} else {
					alert("비밀번호를 입력해 주세요.");
					return false;
				}
		}*/



	}
</script>