<?php
/**
 * Created by PhpStorm.
 * User: moon
 * Date: 2020-01-10
 * Time: 오후 1:41
 */
include("../class/layout.class");


$db = new Database;

$max = 20; //페이지당 갯수

if ($page == '')
{
    $start = 0;
    $page  = 1;
}
else
{
    $start = ($page - 1) * $max;
}

if(!empty($sdate) && !empty($edate)){
    $startDate = $sdate;
    $endDate = $edate;
}else{
    $before2years = date("Y-m-d");
    $before1years = date("Y-m-d",strtotime("1 month"));
    $startDate = $before2years;
    $endDate = $before1years;

    $sdate = $startDate;
    $edate = $endDate;
}

$where = "where am.am_ix <> '' ";
if($startDate != "" && $endDate != ""){
    $where .= " and am.extinction_date between  '".$startDate."' and '".$endDate."' ";
}

if($mall_ix!=""){
    $where .= " and cu.mall_ix = '".$mall_ix."' ";
}

if($gp_ix != ""){
    $where .= " and cmd.gp_ix = '".$gp_ix."' ";
}


if($mode == 'search') {

    $sql = "select 
          sum(available_mileage) as sum_available_mileage,
          sum(extinction_mileage) as sum_extinction_mileage 
        from (
                select 
                  sum(cu.mileage) as available_mileage,
                  sum((am.am_mileage - ifnull((select sum(rm_mileage) from shop_remove_mileage where am_ix = am.am_ix and rm_state = 1 group by am_ix) ,0))) extinction_mileage
                  
                from 
                  shop_add_mileage am
                left join 
                  common_user cu on am.uid = cu.code
                left join
                  common_member_detail cmd on am.uid = cmd.code
                left join 
                  shop_groupinfo sg on cmd.gp_ix = sg.gp_ix
                
                $where       
                and cu.code is not null
                group by am.uid
                HAVING extinction_mileage > 0
        ) a ";
    $db->query($sql);
    $db->fetch();

    $sum_available_mileage = $db->dt['sum_available_mileage'];
    $sum_extinction_mileage = $db->dt['sum_extinction_mileage'];
    $sum_total_mileage = $sum_available_mileage - $sum_extinction_mileage;

    $sql = "select 
          am.uid,
          sum((am.am_mileage - ifnull((select sum(rm_mileage) from shop_remove_mileage where am_ix = am.am_ix and rm_state = 1 group by am_ix) ,0))) extinction_mileage
        from 
          shop_add_mileage am
        left join 
          common_user cu on am.uid = cu.code
        left join
          common_member_detail cmd on am.uid = cmd.code
        left join 
          shop_groupinfo sg on cmd.gp_ix = sg.gp_ix
        
        $where       
        and cu.code is not null
        group by am.uid 
        HAVING extinction_mileage > 0 ";
    $db->query($sql);
    $total = $db->total;


    $sql = "select 
          am.uid,
          cu.id,
          sg.gp_name,
          cu.mileage,
          sum((am.am_mileage - ifnull((select sum(rm_mileage) from shop_remove_mileage where am_ix = am.am_ix and rm_state = 1 group by am_ix) ,0))) extinction_mileage
        from 
          shop_add_mileage am
        left join 
          common_user cu on am.uid = cu.code
        left join
          common_member_detail cmd on am.uid = cmd.code
        left join 
          shop_groupinfo sg on cmd.gp_ix = sg.gp_ix 
        $where       
        and cu.code is not null
        group by am.uid 
        HAVING extinction_mileage > 0 ";

    if($mmode != 'excel'){
        $sql .= " limit $start,$max";
    }

    $db->query($sql);
    $extinction_data = $db->fetchall();

}

if($mmode == 'excel'){

    set_time_limit(9999999999);
    ini_set('memory_limit',-1);

    include("../class/layout.class");
    include '../include/phpexcel/Classes/PHPExcel.php';

    //error_reporting(E_ALL);
    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    $memberXL = new PHPExcel();

    // 속성 정의
    $memberXL->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("Mallstory.com")
        ->setTitle("Reserve List")
        ->setSubject("Reserve List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("mallstory")
        ->setCategory("Reserve List");

    // 데이터 등록
    $memberXL->getActiveSheet(0)->setCellValue('A' . 1, "아이디");
    $memberXL->getActiveSheet(0)->setCellValue('B' . 1, "회원등급");
    $memberXL->getActiveSheet(0)->setCellValue('C' . 1, "사용가능 마일리지");
    $memberXL->getActiveSheet(0)->setCellValue('D' . 1, "소멸대상 마일리지");
    $memberXL->getActiveSheet(0)->setCellValue('E' . 1, "소멸 후 사용가능 마일리지");

    if(is_array($extinction_data) && count($extinction_data) > 0){
        $i = 0;
        foreach($extinction_data as $key=>$val){

            $sum_mileage = $val['mileage'] - $val['extinction_mileage'];
            $memberXL->getActiveSheet()->setCellValue('A' . ($i + 2), $val['id']);
            $memberXL->getActiveSheet()->setCellValue('B' . ($i + 2), $val['gp_name']);
            $memberXL->getActiveSheet()->setCellValue('C' . ($i + 2), $val['mileage']);
            $memberXL->getActiveSheet()->setCellValue('D' . ($i + 2), $val['extinction_mileage']);
            $memberXL->getActiveSheet()->setCellValue('E' . ($i + 2), $sum_mileage);

            $i++;
        }
    }


    // 시트이름등록
    $memberXL->getActiveSheet()->setTitle('적립금 내역');

    // 첫번째 시트 선택
    $memberXL->setActiveSheetIndex(0);
    $memberXL->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);


    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="mileage_extinction_list.xls"');
    header('Cache-Control: max-age=0');


    $objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
    $objWriter->save('php://output');

    exit;
}

if($_SERVER["QUERY_STRING"] == "nset=$nset&page=$page"){
    $query_string = str_replace("nset=$nset&page=$page","",$_SERVER["QUERY_STRING"]) ;
}else{
    $query_string = str_replace("nset=$nset&page=$page&","","&".$_SERVER["QUERY_STRING"]) ;
}
$str_page_bar = page_bar($total, $page, $max, $query_string,"");

if(is_array($extinction_data) && count($extinction_data) > 0){
    foreach($extinction_data as $key=>$val){
        $sum_mileage = $val['mileage'] - $val['extinction_mileage'];
        $extinction_list .= "
        <tr height=28 align=center>       
            <td class='list_box_td' bgcolor='#ffffff'>".$val['id']."</td>
            <td class='list_box_td' bgcolor='#ffffff'>".$val['gp_name']."</td>
            <td class='list_box_td' bgcolor='#ffffff'>".number_format($val['mileage'],2)."</td>
            <td class='list_box_td' bgcolor='#ffffff'>".number_format($val['extinction_mileage'],2)."</td>
            <td class='list_box_td' bgcolor='#ffffff'>".number_format($sum_mileage,2)." </td>
        </tr> 
        ";
    }
}else{
    $extinction_list .= "
        <tr height=28 align=center>       
            <td class='list_box_td' bgcolor='#ffffff' colspan='5'>
                검색 내용이 존재하지 않습니다.
            </td>
        </tr> 
        ";
}



$Contents01 .= "
	<table width='100%' cellpadding=0 cellspacing=0 border='0' align='left'>
	  <tr >
		<td align='left' colspan=6> ".GetTitleNavigation("소멸 마일리지 조회", "회원관리 > 소멸 마일리지 조회 ")."</td>
	  </tr>
	  <tr>
			<td>
				<form name='searchmember' style='display:inline;'>
				<input type='hidden' name='mode' value='search'>
				<input type='hidden' name='mem_ix' value='$mem_ix'>
				<input type='hidden' name='info_type' value='$info_type'>
				 
						<table border='0' cellpadding='0' cellspacing='0' width='100%'> 
							<tr>
								<td align='left' colspan=2  width='100%' valign=top style='padding-top:0px;'>
									 

									<table cellpadding=0 cellspacing=0 width='100%' class='search_table_box'>
										<col width='18%' />
										<col width='32%' />
										<col width='18%' />
										<col width='32%' />";
if($_SESSION["admin_config"][front_multiview] == "Y"){
    $Contents01 .= "
					<tr>
						<td class='search_box_title' > 글로벌 회원 구분</td>
						<td class='search_box_item' colspan=3>".GetDisplayDivision($mall_ix, "select")." </td>
					</tr>";
}

if($mmode != "personalization"){
    $Contents01 .= "
										<tr height=27>
											<td class='search_box_title' >회원그룹 </td>
											<td class='search_box_item' colspan='3'>".makeGroupSelectBox($mdb,"gp_ix",$gp_ix)."</td>";
    $Contents01 .= "
										</tr>";
    $Contents01 .= "
										";
}

$Contents01 .= "				
										<tr height=27>
											<td class='search_box_title' bgcolor='#efefef' align=center><b>소멸일자</b></td>
											<td class='search_box_item' align=left  colspan='3'>
											".search_date('sdate','edate',$sdate,$edate,'','N')."
											</td>
										</tr>																						
									</table>
											 
								</td>
							</tr>
							<tr >
								<td colspan=3 align=center style='padding:10px 0;'>
									<input type='image' src='../images/".$admininfo["language"]."/bt_search.gif' border=0>
								</td>
							</tr>
						</table> 
				</form>
			</td>
		</tr>";

$Contents01 .= "
	  </table>";

$Contents01 .= "
<table width='100%' cellpadding=0 cellspacing=0 border='0' align='left' style='table-layout:fixed;margin-top:30px;' >
	<tr>
		<td align='left' colspan='' style='padding:3px 0px;'>".colorCirCleBox("#efefef","100%","<div style='padding:5px;padding-left:10px;'> <img src='../image/title_head.gif' align=absmiddle> <b class='blk'>소멸대상 마일리지 통계</b></div>")."</td>
	</tr>
</table>
<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' class='list_table_box'>	
	<tr height='28' bgcolor='#ffffff'>
		<td width='14%' align='center' class=s_td><font color='#000000'><b>마일리지 소멸대상 회원수</b></font></td>
		<td width='14%' align='center' class='m_td'><font color='#000000'><b>사용가능 마일리지 합계</b></font></td>
		<td width='14%' align='center' class='m_td'><font color='#000000'><b>소멸대상 마일리지 합계</b></font></td>
		<td width='14%' align='center' class='m_td'><font color='#000000'><b>소멸 후 사용가능 마일리지 </b></font></td>
	
	</tr>
	<tr height='28'>
		<td class='list_box_td' >".number_format($total)."</td>
		<td class='list_box_td'>".number_format($sum_available_mileage,2)."</td>
		<td class='list_box_td'>".number_format($sum_extinction_mileage,2)."</td>
		<td class='list_box_td'>".number_format($sum_total_mileage,2)."</td>
	</tr>
</table>
<br><br>";

$Contents02 = "
<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' >
  <tr height=30 >
	<td>
		<b>전체 : ".$total." 개</b> 
	</td>
  	<td colspan=5 align=right>";
if($mmode != "personalization"){
    if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E")){
        $Contents02 .= "<a href='?mmode=excel&".$QUERY_STRING."'><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";
    }else{
        $Contents02 .= "<a href=\"".$auth_excel_msg."\"><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";
    }
}
$Contents02 .= "
	</td>
  </tr>
</table>
<table width='100%' cellpadding=3 cellspacing=0 border='0' align='left' class='list_table_box'>
    <col width='20%' />
    <col width='20%' />
    <col width='20%' />
    <col width='20%' />
    <col width='20%' />
    
    <tr bgcolor=#efefef style='font-weight:bold' align=center height=28>        
        <td class='s_td' >아이디</td>
        <td class='m_td' >회원등급 </td>
        <td class='m_td' >사용가능 마일리지 </td>
        <td class='m_td' >소멸대상 마일리지 </td>
        <td class='e_td' >소멸 후 사용가능 마일리지 </td>
    </tr>
    ".$extinction_list."
</table>
<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' >
<col width='10%'>
<col width='*'>
<tr height=40>
	<td align=right>".$str_page_bar."</td>
</tr>
</table>
";



$Contents = "<table width='100%' border=0>";
$Contents = $Contents."<tr><td>$Contents01<br></td></tr>";
$Contents = $Contents."<tr><td>".$Contents02."<br></td></tr>";
$Contents = $Contents."<tr height=30><td></td></tr>";
$Contents = $Contents."</table >";


$help_text = getTransDiscription(md5($_SERVER["PHP_SELF"]),'A');

$Contents .= HelpBox("소멸 마일리지 조회", $help_text);

$P = new LayOut();
$P->addScript = "<script language='javascript' src='../include/DateSelect.js'></script>\n".$Script;
$P->OnloadFunction = "";	//init();
$P->strLeftMenu = member_menu();
$P->Navigation = "회원관리 > 소멸 마일리지 조회";
$P->title = "소멸 마일리지 조회";
$P->strContents = $Contents;
echo $P->PrintLayOut();