<?php

include("../class/layout.class");
include '../include/phpexcel/Classes/PHPExcel.php';
include_once("service.lib.php");

//error_reporting(E_ALL);
PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

date_default_timezone_set('Asia/Seoul');


if ($vFromYY != ""){

	$sDate = $vFromYY."/".$vFromMM."/".$vFromDD;
	$eDate = $vToYY."/".$vToMM."/".$vToDD;
	$startDate = $vFromYY.$vFromMM.$vFromDD;
	$endDate = $vToYY.$vToMM.$vToDD;
}

$db = new MySQL;
$odb = new MySQL;
$ddb = new MySQL;


$max = 15; //페이지당 갯수

if ($page == ''){
	$start = 0;
	$page  = 1;
}else{
	$start = ($page - 1) * $max;
}

// 검색 조건 설정 부분
if($admininfo[admin_level] == 9){
	$where = "WHERE si.si_status <> 'SR' AND si.si_status!='' ";
} else if($admininfo[admin_level] == 8){
	$where = "WHERE si.si_status <> 'SR' AND si.si_status!='' AND s_type='".$admininfo["company_id"]."' ";
}


if ($bname != "")	$where .= "and si.name = '$bname' ";
if ($pname != "")	$where .= "and si.pname = '$pname' ";
if($date_type){
	if ($vFromYY != "")	$where .= "and date_format(".$date_type.",'%Y%m%d') between $startDate and $endDate ";
}

if($search_type && $search_text){
		if($search_type == "combi_name"){
			$where .= "and (si.name LIKE '%".trim($search_text)."%'  or si.pname LIKE '%".trim($search_text)."%') ";
		}else{
			$where .= "and $search_type LIKE '%".trim($search_text)."%' ";
		}
	}
//print_r($type);
/*if(is_array($type)){
	for($i=0;$i < count($type);$i++){
		if($type[$i]){
			if($type_str == ""){
				$type_str .= "'".$type[$i]."'";
			}else{
				$type_str .= ", '".$type[$i]."' ";
			}
		}
	}

	if($type_str != ""){
		$where .= "and si.si_status in ($type_str) ";
	}
}else{
	if($type){
		$where .= "and si.si_status = '$type' ";
	}
}*/
switch($type) {
	case("SI") : $where.=" and si.si_status = '$type' AND UNIX_TIMESTAMP(si.end_date) >= '".time()."' ";
	break;
	case("SS") : $where.=" and si.si_status = 'SI' AND UNIX_TIMESTAMP(si.end_date) < '".time()."' ";
	break;
	case("CC") : $where.=" and si.si_status = '$type' ";
	break;
}

if($admininfo[admin_level] == 9){
	/*if($admininfo[mem_type] == "MD"){
		$addWhere = " and od.company_id in (".getMySellerList($admininfo[charger_ix]).") ";
	}*/
	$sql = "SELECT si.*, UNIX_TIMESTAMP(si.end_date) AS unix_end_date 
				FROM service_info si LEFT JOIN ".TBL_COMMON_USER." c ON si.code=c.code 
				LEFT JOIN ".TBL_COMMON_MEMBER_DETAIL." cmd ON c.code=cmd.code
			$where ORDER BY si.regdate DESC ";
	//echo $sql;
/*서브쿼리 삭제 아무것도 없을때 에러남 서브쿼리 부분에서 */
//,			(select delivery_price from shop_order_delivery where o.oid = oid and od.company_id = company_id) as delivery_totalprice,
//				(select company_total from shop_order_delivery where o.oid = oid and od.company_id = company_id) as company_total

}else if($admininfo[admin_level] == 8){
	$sql = "SELECT si.*, UNIX_TIMESTAMP(si.end_date) AS unix_end_date 
				FROM service_info si 
				LEFT JOIN ".TBL_COMMON_USER." c ON si.code=c.code 
				LEFT JOIN ".TBL_COMMON_MEMBER_DETAIL." cmd ON c.code=cmd.code
				$where ORDER BY si.regdate DESC ";

//,(select delivery_price from shop_order_delivery where o.oid = oid and od.company_id = company_id) as delivery_totalprice,(select company_total from shop_order_delivery where o.oid = oid and od.company_id = company_id) as company_total
}
$db->query($sql);


$memberXL = new PHPExcel();

	// 속성 정의
$memberXL->getProperties()->setCreator("아이소다")
							 ->setLastModifiedBy("isoda.co.kr")
							 ->setTitle("Service Usage List")
							 ->setSubject("Service Usage List")
							 ->setDescription("generated by isoda")
							 ->setKeywords("isoda")
							 ->setCategory("Service Usage List");

// 데이터 등록
$memberXL->getActiveSheet(0)->setCellValue('A' . 1, "사용자명");
$memberXL->getActiveSheet(0)->setCellValue('B' . 1, "서비스종류");
$memberXL->getActiveSheet(0)->setCellValue('C' . 1, "패키지명");
$memberXL->getActiveSheet(0)->setCellValue('D' . 1, "시작일");
$memberXL->getActiveSheet(0)->setCellValue('E' . 1, "만료일");
$memberXL->getActiveSheet(0)->setCellValue('F' . 1, "서비스상태");

for($i=0;$i<$db->total;$i++){
	$db->fetch($i);

	switch($db->dt[si_status]) {
		case "SI" : $si_status="사용중";
		break;
		case "CC" : $si_status="사용취소";
		break;
	}

	$now_time=time();
	if($now_time>$db->dt["unix_end_date"]) {
		$si_status="사용만료";
	}
	
	$memberXL->getActiveSheet()->setCellValue('A' . ($i + 2), $db->dt[name]);
	$memberXL->getActiveSheet()->setCellValue('B' . ($i + 2), print_service_code_name($db->dt[s_kind]));
	$memberXL->getActiveSheet()->setCellValue('C' . ($i + 2), $db->dt[pname]);
	$memberXL->getActiveSheet()->setCellValue('D' . ($i + 2), substr($db->dt[start_date],0,10));
	$memberXL->getActiveSheet()->setCellValue('E' . ($i + 2), substr($db->dt[end_date],0,10));
	$memberXL->getActiveSheet()->setCellValue('F' . ($i + 2), $si_status);
}

// 시트이름등록
$memberXL->getActiveSheet()->setTitle('서비스이용');

// 첫번째 시트 선택
$memberXL->setActiveSheetIndex(0);
$memberXL->getActiveSheet()->getColumnDimension('A')->setWidth(15);
$memberXL->getActiveSheet()->getColumnDimension('B')->setWidth(25);
$memberXL->getActiveSheet()->getColumnDimension('C')->setWidth(25);
$memberXL->getActiveSheet()->getColumnDimension('D')->setWidth(15);
$memberXL->getActiveSheet()->getColumnDimension('E')->setWidth(15);
$memberXL->getActiveSheet()->getColumnDimension('F')->setWidth(15);
//$memberXL->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="service_usage.xls"');
header('Cache-Control: max-age=0');


$objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
$objWriter->save('php://output');

exit;

?>