<?php

	include($_SERVER["DOCUMENT_ROOT"]."/admin/class/layout.class");
	include("../lib/imageResize.lib.php");
	include '../include/phpexcel/Classes/PHPExcel.php';

	include("./translation_excel_input.lib.php");


	unset($goods_mandatory_info); //DB에서 불러오기에 기존 데이타 삭제 2014-04-01 이학봉
	ini_set('memory_limit','300M');

	$removestring = array("\n", "\t");

	
	$db = new MySQL;
	//$db2 = new MySQL;
	$image_db = new MySQL;
 


 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 샘플 엑셀 다운로드
/// 작성 : 신훈식 ( 2013.04.29 )
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if($_POST["act"] == "sample_excel_down"){


	//$selected_mandatory_info = $goods_mandatory_info[$_POST["mandatory_type_1"]][$_POST["mandatory_type_2"]][$_POST["mandatory_type_3"]];
	//$selected_mandatory_info = $goods_mandatory_info[$mandatory_type_1][$mandatory_type_2][$mandatory_type_3];
	$selected_mandatory_info = $goods_mandatory_info[$mandatory_type_1][$mandatory_type_2];	//DB저장후 2차배열까지만 사용 2014-04-01 이학봉

	$tmp_sample_excel_info = array_merge($goods_basic_sample,$selected_mandatory_info);

	$sample_excel_info = array_merge($tmp_sample_excel_info,$goods_options_sample);

	//echo "aaa".intval($_POST["mandatory_type_1"]);
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$sample_excel = new PHPExcel();

	// 속성 정의
	$sample_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("accounts plan price List")
								 ->setSubject("accounts plan price List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("accounts plan price List");
	$col = 'A';

	foreach($sample_excel_info as $key => $value){

		if($value[validation]=='true'){
			$sample_excel->getActiveSheet(0)->getStyle($col . "1")->getFont()->getColor()->setARGB("FFFF0000");
		}

		if($value[code]=="mandatory_type"){
			//$mandatory_type = $_POST["mandatory_type_1"].$mandatory_type_2.$mandatory_type_3;
			$mandatory_type = $_POST["mandatory_type_1"].$mandatory_type_2;	//2차배열까지만 2014-04-01 이학봉
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", " ".$mandatory_type);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}elseif($value[code]=="category"){
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $value[sample]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getStyle($col . "2")->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}elseif($value[code]=="admin"){
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $admininfo[company_id]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}elseif($value[code]=="product_type"){
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $product_type);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}else{
			$sample_excel->getActiveSheet(0)->setCellValue($col . "1", $value[title]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "2", $value[sample]);
			$sample_excel->getActiveSheet(0)->setCellValue($col . "3", $value[comment]);
			$sample_excel->getActiveSheet(0)->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}
	}

	$sample_excel->getActiveSheet(0)->getStyle('A' . "4")->getFont()->getColor()->setARGB("FFFF0000");
	$sample_excel->getActiveSheet(0)->setCellValue('A' . "4",'빨간색 글씨로 되어있는 항목은 필수 입니다. !!');


	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="sample_excel.xls"');
	header('Cache-Control: max-age=0');

	$objWriter = PHPExcel_IOFactory::createWriter($sample_excel, 'Excel5');
	$objWriter->save('php://output');
	exit;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 상품등록
/// 작성 : 신훈식 ( 2013.04.29 )
/// 내용 : 엑셀 업로드된 데이타를 shared memory 에 저장후 한개씩 처리해서 결과를 반영해 나가는 구조로 바꾼다.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if($act == "new_excel_input"){

	//include("../include/lib/pclzip.lib.php");
//exit;
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

		if ($excel_file_size > 0){
			copy($excel_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);
		}

		$objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"]."".$_SESSION["admin_config"][mall_data_root]."/images/upfile/".$excel_file_name);

		$shift_num = 0;

		// 데이터는 3줄부터 시작, 1, 2줄은 제목+코드명

		$rownum = 2;


		//$columnVar = $objPHPExcel->setActiveSheetIndex(0)->getCell('A' . ($rownum))->getValue();

		include("../logstory/class/sharedmemory.class");
		$shmop = new Shared("translation_upload_excel_data");
		$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$_SESSION["admin_config"][mall_data_root]."/_shared/";
		//echo $shmop->filepath;
		$shmop->SetFilePath();
		$translation_upload_excel_data = $shmop->getObjectForKey("translation_upload_excel_data");
		
		$translation_upload_excel_data="";
		
		$translation_upload_excel_data[session_id()][0]["language"] = "언어";
		$translation_upload_excel_data[session_id()][0]["trans_key"] = "번역키";		
		$translation_upload_excel_data[session_id()][0]["trans_div"] = "번역구분";
		$translation_upload_excel_data[session_id()][0]["file_path"] = "파일경로";
		$translation_upload_excel_data[session_id()][0]["file_name"] = "파일";
		$translation_upload_excel_data[session_id()][0]["korea"] = "기준문구";
		$translation_upload_excel_data[session_id()][0]["trans_text"] = "번역문구";

		$z=0;
		
	 

		while (($objPHPExcel->getActiveSheet()->getCell('E' . $rownum)->getValue() != "") && ($i < 10)) {
			//$pcode = $objPHPExcel->getActiveSheet()->getCell('A' . $rownum)->getValue();
			//$col = 'A';
			//foreach($sample_excel_info as $key => $value){

			if (is_object($objPHPExcel->getActiveSheet()->getCell("A" . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell("A" . $rownum));
				$a_value = $objRichText->getPlainText();
			}else{
				$a_value = $objPHPExcel->getActiveSheet()->getCell("A" . $rownum)->getValue();
			}

			if (is_object($objPHPExcel->getActiveSheet()->getCell("B" . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell("B" . $rownum));
				$b_value = $objRichText->getPlainText();
			}else{
				$b_value = $objPHPExcel->getActiveSheet()->getCell("B" . $rownum)->getValue();
			}

			if (is_object($objPHPExcel->getActiveSheet()->getCell("C" . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell("C" . $rownum));
				$c_value = $objRichText->getPlainText();
			}else{
				$c_value = $objPHPExcel->getActiveSheet()->getCell("C" . $rownum)->getValue();
			}

			if (is_object($objPHPExcel->getActiveSheet()->getCell("D" . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell("D" . $rownum));
				$d_value = $objRichText->getPlainText();
			}else{
				$d_value = $objPHPExcel->getActiveSheet()->getCell("D" . $rownum)->getValue();
			}

			if (is_object($objPHPExcel->getActiveSheet()->getCell("E" . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell("E" . $rownum));
				$e_value = $objRichText->getPlainText();
			}else{
				$e_value = $objPHPExcel->getActiveSheet()->getCell("E" . $rownum)->getValue();
			}

			if (is_object($objPHPExcel->getActiveSheet()->getCell("F" . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell("F" . $rownum));
				$f_value = $objRichText->getPlainText();
			}else{
				$f_value = $objPHPExcel->getActiveSheet()->getCell("F" . $rownum)->getValue();
			}



			$translation_upload_excel_data[session_id()][$rownum-1]["language"] = $trans_type;//"korea";
			$translation_upload_excel_data[session_id()][$rownum-1]["trans_key"] = $d_value;
			$translation_upload_excel_data[session_id()][$rownum-1]["trans_div"] = $a_value;
			$translation_upload_excel_data[session_id()][$rownum-1]["file_path"] = $b_value;
			$translation_upload_excel_data[session_id()][$rownum-1]["file_name"] = $c_value;
			$translation_upload_excel_data[session_id()][$rownum-1]["korea"] = $e_value;
			$translation_upload_excel_data[session_id()][$rownum-1]["trans_text"] = $f_value;
	//echo "aaa";
		//print_r($translation_upload_excel_data);
		//exit;
		 
			$z++;
			$rownum++;
		}
		try{
		//	echo "aaa";
		//print_r($translation_upload_excel_data);
		//exit;
		}catch(Exception $e){
			echo $e->getMessage();
			exit;
		}
		$shmop->setObjectForKey($translation_upload_excel_data, "translation_upload_excel_data") ;
		echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./translation_excel_input.php?up_mode=new_upload'</script>";
}


if($act == "single_data_reg"){

	include("../logstory/class/sharedmemory.class");
	//auth(8);
	$shmop = new Shared("translation_upload_excel_data");
	//	$shmop->clear();
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$_SESSION["admininfo"]["mall_data_root"]."/_shared/";
	$shmop->SetFilePath();
	$translation_upload_excel_data = $shmop->getObjectForKey("translation_upload_excel_data");

	//$db->query("SELECT * FROM ".TBL_SHOP_PRODUCT." where pcode = '".$pcode."' ");
	

	$select_excel_goods_infos = filter_by_value($translation_upload_excel_data[session_id()], 'trans_key', $trans_key);

	foreach($select_excel_goods_infos as $key => $value){

		$insert_yn=true;

		//$result_massage = count($select_excel_goods_infos);
		$trans_type = $value[language];
		$trans_key = $value[trans_key];
		$trans_div = $value[trans_div];
		$file_path = $value[file_path];
		$file_name = $value[file_name];
		$text_name = $value[korea];
		$text_korea = $value[korea];
		$trans_text = $value[trans_text];
		$trans_text = str_replace("''","",$trans_text);
		$trans_text = str_replace("'","&#39;",$trans_text);
		$trans_text = str_replace('"',"&quot;",$trans_text);

		if(trim($trans_text)){

				$sql="select trans_ix from global_translation where trans_key='".$trans_key."' ";
				$db->query($sql);
                if($db->total) {
                    $db->fetch();
                    $trans_ix = $db->dt[trans_ix];
                } else {
                    $sql = "insert into global_translation
						(trans_key, text_name, text_korea, regdate) 
						values
						('$trans_key','$text_name','$text_korea',NOW())";
                    $db->query($sql);
                    $trans_ix = $db->insert_id();
                }

				$sql="select trans_ix from global_translation_detail where trans_type='".$trans_type."' and trans_ix='".$trans_ix."' ";
				$db->query($sql);
				if($db->total){
					$db->fetch();
					$trans_ix = $db->dt[trans_ix];
					$sql = "update global_translation_detail set 
								trans_text = '$trans_text'
							where 
								trans_ix='".$trans_ix."' and trans_type = '".$trans_type."' ";
					echo "<span class=''>수정완료</span>";
				}else{
					$sql = "insert into global_translation_detail
						(trans_ix,trans_key, trans_type, trans_text,regdate) 
						values
						('$trans_ix','$trans_key','$trans_type','$trans_text',NOW())";

					echo "<span class='blue'>등록완료</span>";
				}

				$db->query($sql);
				$result_massage = $sql;
		}
		//echo $result_massage;
		/*
		if(trim($text_name)){

			$sql="select trans_ix from global_translation where trans_type='".$trans_type."' and trans_key='".$trans_key."' ";
			$db->query($sql);
			if($db->total){
				$db->fetch();
				$trans_ix = $db->dt[trans_ix];
				$sql = " update global_translation set
							file_path = '$file_path',
							file_name = '$file_name',
							trans_text = '$trans_text'
						where 
							trans_ix='".$trans_ix."' ";
				echo "<span class=''>수정완료</span>";
			}else{
				$sql = " insert into global_translation
					(trans_ix,trans_key, trans_div,trans_type,file_path, file_name, text_name,text_korea,trans_text,disp,regdate) 
					values
					('','$trans_key','$trans_div','$trans_type','$file_path','$file_name','$text_name','$text_korea','$trans_text','1',NOW())";

				echo "<span class='blue'>등록완료</span>";
			}

			$db->query($sql);
			$result_massage = $sql;
		}
		//echo $result_massage;
		*/

	$translation_upload_excel_data[session_id()][$key][status] = "C";
	$translation_upload_excel_data[session_id()][$key][status_message] = "등록완료";
	$shmop->setObjectForKey($translation_upload_excel_data, "translation_upload_excel_data") ;

	}

}

 
 if($act == "make_language_file"){

     $sql = "select count(*) as total from shop_mall_config where mall_ix = 'template_compile_cron' and config_name like '%_".$trans_type."' and config_value = 'ing' ";
     $db->query($sql);
     $db->fetch();
     if($db->dt['total'] > 0){
         echo("<script>alert('※compile 작업이 완료가 안되었습니다. 잠시후 다시 시도해 주세요.※');</script>");
         exit;
     }

     //$trans_type = "korea";
	$sql = "select t.trans_ix, t.trans_key, trans_div, td.trans_type, file_path, file_name, text_name, text_korea, is_check, disp, td.regdate, td.trans_text  
				from global_translation t join global_translation_detail td on t.trans_ix = td.trans_ix 
				where td.trans_type = '".$trans_type."' and t.disp='1' ";
	$db->query($sql);
	$trans_datas = $db->fetchall("object");
	
	$trans_write .= "<?php\nreturn [\n";
	$trans_js_write="var _LANGUAGE = {\n";
	for($i=0;$i < count($trans_datas);$i++){
	    if($i!=0){
            $trans_write .= ",";
            $trans_js_write .= ",";
        }
		$trans_write .= "'".trim($trans_datas[$i][trans_key])."' => '".str_replace(array("'","\n"),array("\\'",""),html_entity_decode($trans_datas[$i][trans_text]))."' /*".$trans_datas[$i][text_korea]."*/\n";
		$trans_js_write .= "'".trim($trans_datas[$i][trans_key])."' : '".str_replace(array("'","\n"),array("\\'",""),html_entity_decode($trans_datas[$i][trans_text]))."' /*".$trans_datas[$i][text_korea]."*/\n";
	}
	$trans_write .= "];";
    $trans_js_write .= "};";

	$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root] ."/_language/";
	
	if (! is_dir ( $path )) {
		mkdir ( $path, 0777 );
		chmod ( $path, 0777 );
	} else {
		// chmod($path,0777);
	}

	/*
	$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root] ."/_language/".$trans_type;
	if (! is_dir ( $path )) {
		mkdir ( $path, 0777 );
		chmod ( $path, 0777 );
	}
	*/
	
	unlink ( $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root]."/_language/$trans_type.php");
	$fp = fopen ( $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root]."/_language/$trans_type.php", "a+" );
	chmod ( $path."/common.php", 0777 );
	fwrite ( $fp, $trans_write );
	fclose ( $fp );

	unlink ( $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root]."/_language/$trans_type.js");
	$fp1 = fopen ( $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root]."/_language/$trans_type.js", "a+" );
	chmod ( $path."/language.js", 0777 );
	fwrite ( $fp1, $trans_js_write );
	fclose ( $fp1 );

     $sql = "update shop_mall_config set config_value = 'ready' where mall_ix = 'template_compile_cron' and config_name like '%_".$trans_type."' and config_value = 'complete'";
     $db->query($sql);
     $db->fetch();

	echo("<script language='javascript' src='../js/message.js.php'></script><script>show_alert2('언어가 정상적으로 생성 되었습니다.');</script>");
	echo("<script>parent.document.location.reload();</script>");

 }

 if($act == "changetempletlanguage_global"){
	
	$sql = "select * from global_translation where trans_type = '".$trans_type."' and disp='1' group by text_korea order by CHAR_LENGTH(text_korea)  desc ";
	$db->query($sql);
	$trans_datas = $db->fetchall("object");
	
	//$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root]."/templet/hong/";
	//$exec = "find ".$path."  ! \( -type d -path './data' -prune \) -name '*.php' |xargs grep 'layout_config' |grep 'mall_cc_interval' > /home/dev/layout_config.txt";


	//일반 템플릿
	$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/templet/".$_SESSION["admin_config"]['selected_templete']."/";

	for($i=0;$i < count($trans_datas);$i++){
		$change_text = '{=__LANGUAGE["'.$trans_datas[$i][trans_key].'"]}';
		$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/".$trans_datas[$i][text_korea]."/".$change_text."/g' {} \;";
		shell_exec($exec)."<br/>";
	}

	$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/<!--{=__LANGUAGE/<!-- {=__LANGUAGE/g' {} \;";
	shell_exec($exec)."<br/>";
	
	//모바일 템플릿
	$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/mobile_templet/".$_SESSION["admin_config"]['mall_use_mobile_templete']."/";
	
	for($i=0;$i < count($trans_datas);$i++){
		$change_text = '{=__LANGUAGE["'.$trans_datas[$i][trans_key].'"]}';
		$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/".$trans_datas[$i][text_korea]."/".$change_text."/g' {} \;";
		shell_exec($exec)."<br/>";
	}

	$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/<!--{=__LANGUAGE/<!-- {=__LANGUAGE/g' {} \;";
	shell_exec($exec)."<br/>";

	//게시판 템플릿
	//$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/bbs_templet/";
	$path = $_SERVER ["DOCUMENT_ROOT"] ."/bbs_templet/";
	
	for($i=0;$i < count($trans_datas);$i++){
		$change_text = '{=__LANGUAGE["'.$trans_datas[$i][trans_key].'"]}';
		$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/".$trans_datas[$i][text_korea]."/".$change_text."/g' {} \;";
		shell_exec($exec)."<br/>";
	}

	$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/<!--{=__LANGUAGE/<!-- {=__LANGUAGE/g' {} \;";
	shell_exec($exec)."<br/>";

	echo("<script language='javascript' src='../js/message.js.php'></script><script>show_alert2('정상적으로 실행이 되었습니다.');</script>");
 }




 if($act == "changetempletlanguage"){

	set_time_limit(9999999999);
	ini_set('memory_limit',-1);

	$sql = "select * from global_translation where trans_type = '".$trans_type."' and disp='1' group by text_korea order by CHAR_LENGTH(text_korea)  desc";
	//and CHAR_LENGTH(text_korea) > 1 and trans_key = '1f48f1407f65e20cd922bf5bb9a87954' 
	$db->query($sql);
	$trans_datas = $db->fetchall("object");

	//and length(text_korea) > 3 
	
	//$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"][mall_data_root]."/templet/hong/";
	//$exec = "find ".$path."  ! \( -type d -path './data' -prune \) -name '*.php' |xargs grep 'layout_config' |grep 'mall_cc_interval' > /home/dev/layout_config.txt";

//exit;
	//$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/<!--{=__LANGUAGE/<!-- {=__LANGUAGE/g' {} \;";
	//shell_exec($exec)."<br/>";

		//모바일 템플릿
		$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/mobile_templet/".$_SESSION["admin_config"]['mall_use_mobile_templete']."/";//".$_SESSION["admin_config"]['mall_use_mobile_templete']."
		
		for($i=0;$i < count($trans_datas);$i++){
			$change_text = '{=__LANGUAGE["'.$trans_datas[$i][trans_key].'"]\/\/'.implode(".",str_split_unicode($trans_datas[$i][text_korea],1)).'}';
			$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/".$trans_datas[$i][text_korea]."/".$change_text."/g' {} \;";
			echo $trans_datas[$i][text_korea].' -- '.$trans_datas[$i][trans_key]."<br>";
			shell_exec($exec)."<br/>";
		}


	if(false){

		//일반 템플릿
		$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/templet/".$_SESSION["admin_config"]['mall_use_templete']."/";//".$_SESSION["admin_config"]['selected_templete']."
		//layout/header/

	 
		for($i=0;$i < count($trans_datas);$i++){
			$change_text = '{=__LANGUAGE["'.$trans_datas[$i][trans_key].'"]\/\/'.$trans_datas[$i][trans_key].'}';
			$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/".str_replace("+","\\+",str_replace(" ","\s",trim($trans_datas[$i][text_korea])))."/".$change_text."/g' {} \;";
			echo $exec."<br>";
			$output = shell_exec($exec)."<br/>";
			//echo $output."<br>";
		}

		for($i=0;$i < count($trans_datas);$i++){
			$change_text = ''.implode(".",str_split_unicode($trans_datas[$i][text_korea],1)).'';
			$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/\/\/".$trans_datas[$i][trans_key]."/\/\/".$change_text."/g' {} \;";
			//echo $exec."---1212<br>";
			$output = shell_exec($exec)."<br/>";
			//echo $output."<br>";
		}

		//모바일 템플릿
		$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/mobile_templet/".$_SESSION["admin_config"]['mall_use_mobile_templete']."/";//".$_SESSION["admin_config"]['mall_use_mobile_templete']."
		
		for($i=0;$i < count($trans_datas);$i++){
			$change_text = '{=__LANGUAGE["'.$trans_datas[$i][trans_key].'"]\/\/'.implode(".",str_split_unicode($trans_datas[$i][text_korea],1)).'}';
			$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/".$trans_datas[$i][text_korea]."/".$change_text."/g' {} \;";
			shell_exec($exec)."<br/>";
		}

		$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/<!--{=__LANGUAGE/<!-- {=__LANGUAGE/g' {} \;";
		shell_exec($exec)."<br/>";


		//게시판 템플릿
		//$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/bbs_templet/";
		$path = $_SERVER ["DOCUMENT_ROOT"] ."/bbs_templet/";
		
		for($i=0;$i < count($trans_datas);$i++){
			$change_text = '{=__LANGUAGE["'.$trans_datas[$i][trans_key].'"]//'.implode(".",str_split_unicode($trans_datas[$i][text_korea],1)).'}';
			$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/".$trans_datas[$i][text_korea]."/".$change_text."/g' {} \;";
			shell_exec($exec)."<br/>";
		}

		$exec = "find ".$path." -name '*.htm' -exec perl -pi -e 's/<!--{=__LANGUAGE/<!-- {=__LANGUAGE/g' {} \;";
		shell_exec($exec)."<br/>";

			
	}

	echo("<script language='javascript' src='../js/message.js.php'></script><script>show_alert2('정상적으로 실행이 되었습니다.');</script>");
 }


 if($act == "abstract_korea_text"){
	//$subject = '한글입니다.<div >옆은</div>일본어日本最大級일본최대급?!@#!asdf91237  ad한글%#@$하하하^%&({}as23寒한문';
	if($templet_type == "web"){
		$templet = $_POST[$templet_type."_templet"];
	}else if($templet_type == "mobile"){
		$templet = $_POST[$templet_type."_templet"];
	}else if($templet_type == "minishop"){
		$templet = $_POST[$templet_type."_templet"];
	}else{
		exit;
	}
	
	$path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/templet/".$templet."/";//header_top.htm
	$this_path = $_SERVER ["DOCUMENT_ROOT"] .$_SESSION["admin_config"]['mall_data_root']."/templet/".$templet."/service_goods/s_goods/";

	//echo $path."<br>";	

	$all_files = read_all_files($path);

	//print_r($all_files);
	//exit;
	 if(is_array($all_files[files])){
		   foreach($all_files[files] as $key => $single_file){
			  //print_r($single_file);
			   if(substr_count($single_file[file_name],".htm") ){//|| substr_count($single_file,".js")
					//echo $single_file[path]."<br>";

					$html = load_template($single_file[path]);
 					
					preg_match_all("|alert\(['\"](.*)['\"]\)|U",$html, $outputs, PREG_PATTERN_ORDER);
					$html = str_replace(array("\r","\n"),"", $html);
					//exit;
					//print_r($outputs);
					foreach($outputs[1] as $key => $out){
						//echo "1<br>";
						//print_r($out)."<br>";
						//echo "2<br>";
						$strip_out = strip_tags($out);
						if($strip_out){
							
							$text_korea = onlyHanAlpha($strip_out);
							if($text_korea){
								
								$trans_div = str_replace($path,"",$single_file[path]);
								$file_structure = explode("/",$trans_div);
								$file_name = $single_file[file_name];
								$trans_key = md5($text_korea);//$trans_div."-".
								if(count($file_structure) > 2){
									$file_path = $file_structure[0]."/".$file_structure[1];
								}else{
									$file_path = $file_structure[0];
								}

								$input[trans_div]= $trans_div;
								$input[file_structure]= $file_structure;
								$input[file_name]= $file_name;
								$input[trans_key]= $trans_key;
								$input[file_path]= $file_path;
								$input[text_korea]= $text_korea;
								
								manage_translation_word($db, $input);
							}
						}
					}
					 
					preg_match_all("|alt=['\"](.*)['\"]|U",$html, $outputs, PREG_PATTERN_ORDER);
					//exit;

					foreach($outputs[1] as $key => $out){
						//print_r($out);
						//print_r($out)."<br>";
						$strip_out = strip_tags($out);
						if($strip_out){
							
							$text_korea = onlyHanAlpha($strip_out);
							if($text_korea){
								
								$trans_div = str_replace($path,"",$single_file[path]);
								$file_structure = explode("/",$trans_div);
								$file_name = $single_file[file_name];
								$trans_key = md5($text_korea);//$trans_div."-".
								if(count($file_structure) > 2){
									$file_path = $file_structure[0]."/".$file_structure[1];
								}else{
									$file_path = $file_structure[0];
								}
								
								$input[trans_div]= $trans_div;
								$input[file_structure]= $file_structure;
								$input[file_name]= $file_name;
								$input[trans_key]= $trans_key;
								$input[file_path]= $file_path;
								$input[text_korea]= $text_korea;
								
								manage_translation_word($db, $input);
							}
						}
					}
					
					preg_match_all("|<[^>]+>(.*)</[^>]+>|U",$html, $outputs, PREG_PATTERN_ORDER);
					//print_r($outputs);
					foreach($outputs[1] as $key => $out){
						//print_r($out);
						$strip_out = strip_tags($out);
						if($strip_out){
							
							$text_korea = onlyHanAlpha($strip_out);
							if($text_korea){
								
								$trans_div = str_replace($path,"",$single_file[path]);
								$file_structure = explode("/",$trans_div);
								$file_name = $single_file[file_name];
								$trans_key = md5($text_korea);//$trans_div."-".
								if(count($file_structure) > 2){
									$file_path = $file_structure[0]."/".$file_structure[1];
								}else{
									$file_path = $file_structure[0];
								}
								
								$input[trans_div]= $trans_div;
								$input[file_structure]= $file_structure;
								$input[file_name]= $file_name;
								$input[trans_key]= $trans_key;
								$input[file_path]= $file_path;
								$input[text_korea]= $text_korea;
								
								manage_translation_word($db, $input);
							}
						}
					}

				
			   }
		   }
	   }
	 
		echo("<script language='javascript' src='../js/message.js.php'></script><script>show_alert2('정상적으로 미번역 데이타가 추출 되었습니다.');</script>");
 }

function manage_translation_word($db, $params){
	$debug = false;
	$trans_div = $params[trans_div];
	$file_structure = $params[file_structure];
	$file_name = $params[file_name];
	$trans_key = $params[trans_key];
	$file_path = $params[file_path];
	$text_korea = trim($params[text_korea]);
	$trans_type = "korean";
	$trans_text = str_replace(array('......','.....','....','...','..'),'',$text_korea);
								 
	if(str_replace(array('.',' ',',','+'),'',$text_korea) != ""){ //$text_korea != "." && $text_korea != ".." && $text_korea != "..." && $text_korea != "...." && $text_korea != "....." && 
			$sql = "select * from global_translation where text_korea = '".$text_korea."' and trans_type = 'korean' ";
			$db->query($sql);
			echo $text_korea."<br>";
			if(!$db->total){
				$sql = "insert into global_translation
							(trans_ix,trans_key,trans_div,trans_type,file_path, file_name, text_name, text_korea,trans_text,is_check,disp,regdate) 
							values
							('','$trans_key','".$file_structure[0]."','korean','$file_path','$file_name','$text_korea','$text_korea','$text_korea','1','1',NOW())";
				//		echo nl2br($sql)."<br><br>";
				//$db->sequences = "global_translation_SEQ";
				if(!$debug){
					$db->query($sql);
					$db->query("SELECT trans_ix FROM global_translation WHERE trans_ix=LAST_INSERT_ID()");
					$db->fetch();
					$trans_ix = $db->dt[trans_ix];
					$sql = "insert into global_translation_detail(trans_ix,trans_key,trans_type,trans_text,regdate) values('$trans_ix','$trans_key','$trans_type','$trans_text',NOW())";
					$db->query($sql);
				}
				//echo "<b>".$trans_div."</div>==>".$file_name."==".$path."<br>";
				//echo "\n";
			}else{
				$db->fetch();
				$trans_ix = $db->dt[trans_ix];
				$sql = "update global_translation set
							is_check = '1'
							where trans_ix = '".$trans_ix."' ";
				//echo $text_korea."<br>";
				//echo nl2br($sql)."<br><br>";
				if(!$debug){
					$db->query($sql);

					$db->query("SELECT trans_ix FROM global_translation_detail WHERE trans_ix='$trans_ix' ");
					if(!$db->total){ 
						$sql = "insert into global_translation_detail(trans_ix,trans_key,trans_type,trans_text,regdate) values('$trans_ix','$trans_key','$trans_type','$trans_text',NOW())";
						$db->query($sql);
					}
				}

			}
	}
}
 
function read_all_files($root = '.'){ 
  $files  = array('files'=>array(), 'dirs'=>array()); 
  $directories  = array(); 
  $last_letter  = $root[strlen($root)-1]; 
  $root  = ($last_letter == '\\' || $last_letter == '/') ? $root : $root.DIRECTORY_SEPARATOR; 
  
  $directories[]  = $root; 
  $i=0;
  while (sizeof($directories)) { 
    $dir  = array_pop($directories); 
    if ($handle = opendir($dir)) { 
      while (false !== ($file = readdir($handle))) { 
        if ($file == '.' || $file == '..') { 
          continue; 
        } 
		$file_name = $file;
        $file  = $dir.$file; 
        if (is_dir($file)) { 
          $directory_path = $file.DIRECTORY_SEPARATOR; 
          array_push($directories, $directory_path); 
          $files['dirs'][]  = $directory_path; 
        } elseif (is_file($file)) { 
          $files['files'][$i][path]  = $file; 
		  $files['files'][$i][file_name]  = $file_name; 
		  $i++;
        } 
      } 
      closedir($handle); 
    } 
  } 
  
  return $files; 
}


function getFileList ( $path , $select_file="", $maxdepth = -1 , $mode = "FULL" , $d = 0 ){
	
   if ( substr ( $path , strlen ( $path ) - 1 ) != '/' ) { $path .= '/' ; }
   $dirlist = array () ;
  
   if ( $handle = @opendir ( $path ) )
   {
//echo "<b style='color:red;'>".$path."</b><br>";
       while ( false !== ( $__file = readdir ( $handle ) ) )
       {
           if ( $__file != '.' && $__file != '..' )
           {
               $only_file = $__file;
               $__file = $path . $__file ;
			   //echo "<b style='color:red;'>".$__file."</b><br>";
               if ( ! is_dir ( $__file )){
               		
               		$_files[] = $__file;
               		
               }else{
					$_dir_file_obj = getFileList;
			   }
           }
       }
       closedir ( $handle ) ;
   }
   if ( $d == 0 ) { natcasesort ( $dirlist ) ; }
   return ( $_files ) ;
}


function autoLink($contents)
{
	$pattern = '/(http|https|ftp|mms):\/\/[0-9a-z-]+(\.[_0-9a-z-]+)+(:[0-9]{2,4})?\/?';
	$pattern .= '([\.~_0-9a-z-]+\/?)*';
	$pattern .= '(\S+\.[_0-9a-z]+)?';
	$pattern .= '(\?[_0-9a-z#%&=\-\+]+)*/i';
	$replacement = '<a href="\\0" target="_blank">\\0</a>';
	
	return preg_replace($pattern, $replacement, $contents, -1);
}

 


function onlyHanAlpha($subject) {

	$pattern = '/([\xEA-\xED][\x80-\xBF]{2}|[\s])+/';//|[a-zA-Z]|[a-zA-Z] +\.\,
	//$pattern = '/([\xEA-\xED][\x80-\xBF]{2}|[a-zA-Z])+/';
	preg_match_all($pattern, $subject, $match);
	return implode('', $match[0]);
}


function str_split_unicode($str, $l = 0) {
    if ($l > 0) {
        $ret = array();
        $len = mb_strlen($str, "UTF-8");
        for ($i = 0; $i < $len; $i += $l) {
            $ret[] = mb_substr($str, $i, $l, "UTF-8");
        }
        return $ret;
    }
    return preg_split("//u", $str, -1, PREG_SPLIT_NO_EMPTY);
}

//print_r($admin_config);


?>