<?
//include($_SERVER["DOCUMENT_ROOT"]."/admin/class/admin.page.class");
include($_SERVER["DOCUMENT_ROOT"]."/admin/product/category.lib.php");
include("../class/layout.class");
include("inventory.lib.php");
//auth(8);
if ($vToYY == ""){
	$before10day = mktime(0, 0, 0, date("m")  , date("d")-20, date("Y"));
	$vdate = date("Ymd", time());
	$today = date("Ymd", time());

//	$sDate = date("Y/m/d");
	$sDate = date("Y/m/d", time()-84600*(date("d")-1));
	$eDate = date("Y/m/d", time());

	$startDate = date("Ymd", time()-84600*(date("d")-1));
	$endDate = date("Ymd", time());
}else{
	$vdate = date("Ymd", time());
	$today = date("Ymd", time());

	if($view_type == "summary"){
		$sDate = date("Y/m/d", time()-84600*(date("d")-1));
		$eDate = date("Y/m/d", time());
		$startDate = date("Ymd", time()-84600*(date("d")-1));
		$endDate = date("Ymd", time());
	}else{
		$sDate = $vFromYY."/".$vFromMM."/".$vFromDD;
		$eDate = $vToYY."/".$vToMM."/".$vToDD;
		$startDate = $vFromYY.$vFromMM.$vFromDD;
		$endDate = $vToYY.$vToMM.$vToDD;
	}
}

if($max == ""){
	$max = 10; //페이지당 갯수
}

if ($page == ''){
	$start = 0;
	$page  = 1;
}else{
	$start = ($page - 1) * $max;
}


$db = new Database;
$db2 = new Database;
$cdb = new Database;

$where = "where iohd_ix is not null  ";

if($search_text != ""){
	$where .= "and ".$search_type." LIKE '%".$search_text."%' ";
}
if ($vFromYY != "")	$where .= " and date_format(iohd.regdate, '%Y%m%d') between $startDate and $endDate ";

if($ci_ix != ""){
	$where .= "and iohd.ci_ix = '".$ci_ix."' ";
}

if($pi_ix != ""){
	$where .= "and iohd.pi_ix = '".$pi_ix."' ";
}
/*	
	$sql = "select count(*) as total
						from inventory_customer_info ici ,
						common_member_detail cmd ,
						inventory_output_history_detail iohd  
						left join inventory_place_info ipi on ipi.pi_ix = iohd.pi_ix						
						$where  ";
*/
$sql = "select count(*) as total
				from inventory_output_history_detail iohd  
				left join inventory_place_info ipi on ipi.pi_ix = iohd.pi_ix				
				left join inventory_customer_info ici on ici.ci_ix = iohd.ci_ix and ici.customer_type = 'E'
				left join common_member_detail cmd on iohd.charger_ix = cmd.code
				$where  $orderbyString 
				LIMIT $start, $max";

//echo nl2br($sql);
	$db2->query($sql);
	$db2->fetch();
	$total = $db2->dt[total];

//echo $total;

if($view_type == "summary"){
	$page_title = "출고현황";
}else{
	$page_title = "출고리스트";
}


$sql = "select iohd.*,  iohd.charger_ix, ipi.place_name, ici.customer_name, AES_DECRYPT(UNHEX(cmd.name),'".$db->ase_encrypt_key."') as name
				from inventory_output_history_detail iohd  
				left join inventory_place_info ipi on ipi.pi_ix = iohd.pi_ix				
				left join inventory_customer_info ici on ici.ci_ix = iohd.ci_ix and ici.customer_type = 'D'
				left join common_member_detail cmd on iohd.charger_ix = cmd.code
				$where  $orderbyString 
				";
$db->query($sql);
$goods_infos = $db->fetchall();	
if($mode == "excel"){
	include '../include/phpexcel/Classes/PHPExcel.php';
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);
	
	date_default_timezone_set('Asia/Seoul');
	
	$accounts_plan_priceXL = new PHPExcel();
	
	// 속성 정의
	$accounts_plan_priceXL->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("accounts plan price List")
								 ->setSubject("accounts plan price List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("accounts plan price List");
	
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('A' . 1, "번호");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('B' . 1, "상품코드");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('C' . 1, "상품명");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('D' . 1, "옵션명");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('E' . 1, "보관장소");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('F' . 1, "출고내용");	
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('G' . 1, "출고처");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('H' . 1, "출고수량");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('I' . 1, "출고가격");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('J' . 1, "총액");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('K' . 1, "작성자");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('L' . 1, "출고일");

	$before_pid = "";
	
	for ($i = 0; $i < count($goods_infos); $i++)
	{
		/*if(file_exists(PrintImage($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product", $goods_infos[$i][id], "m"))){
			$img_str = PrintImage($admin_config[mall_data_root]."/images/product", $goods_infos[$i][id], "m");
		}else{
			$img_str = "../image/no_img.gif";
		}*/
		$total_delivery_price = ($goods_infos[$i][delivery_cnt])*($goods_infos[$i][delivery_price]);
		$profit = ($goods_infos[$i][delivery_price]-$goods_infos[$i][cast_price]);
		$profit_price = ($profit*$goods_infos[$i][delivery_cnt]);
		if ($profit_price > 0){
			$profit_margin = round(($profit_price/$total_delivery_price)*100, 1);
		}
		
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('A' . ($i + 2), ($i + 1));
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('B' . ($i + 2), $goods_infos[$i][id]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('C' . ($i + 2), $goods_infos[$i][pname]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('D' . ($i + 2), $goods_infos[$i][option_div]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('E' . ($i + 2), $goods_infos[$i][place_name]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('F' . ($i + 2), $goods_infos[$i][delivery_msg]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('G' . ($i + 2), $goods_infos[$i][customer_name]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('H' . ($i + 2), number_format($goods_infos[$i][delivery_cnt])) ;
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('I' . ($i + 2), number_format($goods_infos[$i][delivery_price]));
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('J' . ($i + 2), number_format($goods_infos[$i][delivery_cnt] * $goods_infos[$i][delivery_price]));
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('K' . ($i + 2), $goods_infos[$i][charger]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('L' . ($i + 2), $goods_infos[$i][regdate]);


		
		/*
		
			$profit_price = ($profit*$db->dt[delivery_cnt]);
		if ($profit_price > 0){
		$profit_margin = round(($profit_price/$total_delivery_price)*100, 1);
		}
		
				
			<td class='list_box_td'>".$db->dt[delivery_cnt]."</td>
					<td class='list_box_td list_bg_gray'>".number_format($db->dt[delivery_price])."</td>
					<td class='list_box_td' style='padding:0px 5px;' nowrap>".number_format($total_delivery_price)."</td>
					<td class='list_box_td list_bg_gray'>".number_format($db->dt[cast_price])."</td>
					<td class='list_box_td'>".number_format($total_cast_price)."</td>
					<td class='list_box_td list_bg_gray'>".number_format($profit)."</td>
					<td class='list_box_td '>".number_format($profit_price)."</td>
					<td class='list_box_td list_bg_gray'>".$profit_margin."%</td>
		*/
		
		//$accounts_plan_priceXL->getActiveSheet()->setCellValue('M' . ($i + 2), ($goods_infos[$i][disp] == 1 ? "노출함":"노출안함"));

		
		
	//	$place_name = $goods_infos[$i][place_name];

		

	}

	// 첫번째 시트 선택
	$accounts_plan_priceXL->setActiveSheetIndex(0);
	
	// 너비조정
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('A')->setWidth(5);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('B')->setWidth(15);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('C')->setWidth(15);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('J')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('K')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('L')->setAutoSize(true);
	
	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="stock_output.list.xls"');
	header('Cache-Control: max-age=0');
	
	$objWriter = PHPExcel_IOFactory::createWriter($accounts_plan_priceXL, 'Excel5');
	$objWriter->save('php://output');

	exit;
}

if($mode == "search"){
	//$str_page_bar = page_bar_search($total, $page, $max);
	$str_page_bar = page_bar($total, $page,$max, "&view=innerview&max=$max&mode=$mode&search_type=$search_type&search_text=$search_text&orderby=$orderby&ordertype=$ordertype&vFromYY=$vFromYY&vFromMM=$vFromMM&vFromDD=$vFromDD&vToYY=$vToYY&vToMM=$vToMM&vToDD=$vToDD","");
}else{
	$str_page_bar = page_bar($total, $page,$max, "&view=innerview&max=$max&orderby=$orderby&ordertype=$ordertype","");
	//echo $total.":::".$page."::::".$max."<br>";
}

$Contents =	"<table cellpadding=0 cellspacing=0 width='100%'>
			 <tr>
			    <td align='left' colspan=4 style='padding-bottom:10px;'> ".GetTitleNavigation("$page_title", "재고관리 > $page_title")."</td>
			</tr>

			 <form name='search_frm' method='get' action='".$HTTP_URL."' onsubmit='return CheckFormValue(this);' ><!--target='act'><input type='hidden' name='view' value='innerview'-->
			 <input type='hidden' name='mode' value='search'>
			 <input type='hidden' name='cid' value='$cid'>
			 <input type='hidden' name='depth' value='$depth'>
				<td colspan=2>
					<table class='box_shadow' style='width:100%;height:20px' cellpadding='0' cellspacing='0'><!---mbox04-->
						<tr>
							<th class='box_01'></th>
							<td class='box_02'></td>
							<th class='box_03'></th>
						</tr>
						<tr>
							<th class='box_04'></th>
							<td class='box_05 align=center' style='padding:10'>
								<table cellpadding=0 cellspacing=0 border=0 width=100% class='input_table_box' >";


$Contents .=	"				<col width=20%>
									<col width=30%>
									<col width=20%>
									<col width=30%>
									<tr>
										<td class='input_box_title'> <label for='regdate'>출고일자 </label><input type='checkbox' name='regdate' id='regdate' value='1' onclick='ChangeIncomeDate(document.search_frm);' ".CompareReturnValue("1",$regdate,"checked")."> </td>
										<td class='input_box_item' colspan=3>
											<table border=0 cellpadding=0 cellspacing=0>
												<TD nowrap>
												<SELECT onchange=javascript:onChangeDate(this.form.vFromYY,this.form.vFromMM,this.form.vFromDD) name=vFromYY></SELECT> 년
												<SELECT onchange=javascript:onChangeDate(this.form.vFromYY,this.form.vFromMM,this.form.vFromDD) name=vFromMM></SELECT> 월 <SELECT name=vFromDD></SELECT> 일 </TD>
												<TD width=10 align=center> ~ </TD>
												<TD nowrap>
												<SELECT onchange=javascript:onChangeDate(this.form.vToYY,this.form.vToMM,this.form.vToDD) name=vToYY></SELECT> 년
												<SELECT onchange=javascript:onChangeDate(this.form.vToYY,this.form.vToMM,this.form.vToDD) name=vToMM></SELECT> 월
												<SELECT name=vToDD></SELECT> 일</TD>
											</table>
										</td>
									</tr>
									<tr>
										<td class='input_box_title'> 출고처</td>
										<td class='input_box_item'>
										".SelectBoxSellCustomer("ci_ix", $ci_ix, "false")."

										</td>
										<td class='input_box_title'> 목록갯수</td>
										<td class='input_box_item'>
										<select name=max style=\"font-size:12px;height: 20px; width: 50px;\" align=absmiddle><!-- onchange=\"document.frames['act'].location.href='".$HTTP_URL."?cid=$cid&depth=$depth&view=innerview&max='+this.value\"-->
										<option value='5' ".CompareReturnValue(5,$max).">5</option>
										<option value='10' ".CompareReturnValue(10,$max).">10</option>
										<option value='15' ".CompareReturnValue(15,$max).">15</option>
										<option value='20' ".CompareReturnValue(20,$max).">20</option>
										<option value='50' ".CompareReturnValue(50,$max).">50</option>
										<option value='100' ".CompareReturnValue(100,$max).">100</option>
										</select> <span class='small'>한페이지에 보여질 갯수를 선택해주세요</span>
										</td>
									</tr>
									<tr>
										<td class='input_box_title'> 보관장소</td>
										<td class='input_box_item'>
										 ".makeSelectBoxTargetPlace($pi_ix, 'pi_ix',"","false")."
										</td>
										<td class='input_box_title'> </td>
										<td class='input_box_item'>
										
										</td>
										
									</tr>
									<tr>
										<td class='input_box_title'> 검색어  </td>
										<td class='input_box_item'  colspan=3 align=left  style='padding-right:5px;padding-top:2px;'>
											<table cellpadding=0 cellspacing=0>
											<tr>
												<td><select name='search_type' id='search_type'  style=\"font-size:12px;height:22px;\"><option value='pname'>상품명</option><option value='pcode'>상품코드</option></select></td>
												<td style='padding-left:3px;'>
												<INPUT id=search_texts onkeyup='findNames();' class='textbox' value='' onclick='findNames();'  clickbool='false' style=' FONT-SIZE: 12px; WIDTH: 260px; COLOR: #736357; BACKGROUND-COLOR: #ffffff' name=search_text autocomplete='off' validation=false  title='검색어'><!--onFocusOut='clearNames()'--><br>

												<DIV id=popup style='display: none; width: 268px; POSITION: absolute; height: 150px; backgorund-color: #fffafa' ><!--onmouseover=focusOutBool=false;  onmouseout=focusOutBool=true;-->
												<table cellSpacing=0 cellPadding=0 border=0 width=100% height=100% bgColor=#efefef style='width: 268px;'>
													<tr height=24>
														<td width=100%  style='padding:0 0 0 5px'>
														<table width=100% cellpadding=0 cellspacing=0 border=0>
														<tr>
															<td class='p11 ls1'>검색어 자동완성</td>
															<td class='p11 ls1' onclick='focusOutBool=false;clearNames()' style='cursor:hand;padding:0 10px 0 0' align=right>닫기</td>
														</tr>
														</table>
														</td>
													</tr>
													<tr height=100% >
														<td valign=top bgColor=#efefef style='' colspan=2>
															<table cellpadding=0 cellspacing=0 width=100% height=100% style='margin:0 0px 5px 0px;height: 120px;' bgcolor=#ffffff>
																<tr>
																	<td valign=top >
																	<div style='POSITION: absolute; overflow-y:auto;height: 120px;' id='search_data_area'>
																		<TABLE id=search_table style='table-layout:fixed;width:100%;' cellSpacing=0 cellPadding=0 bgColor=#ffffff border=0>
																		<TBODY id=search_table_body></TBODY>
																		</TABLE>
																	<div>
																	</td>
																</tr>
															</table>

														</td>
													</tr>
												</table>
												</DIV>
												</td>
												<td colspan=2 style='padding-left:5px;'><span class='p11 ls1'>* 상품명의 일부를 입력하시면 자동검색됩니다. 2자 이상 입력해주세요</span></td>
											</tr>
											</table>
										</td>
									</tr>
									<!--tr hegiht=1><td colspan=4  class='td_underline'></td></tr-->

								</table>
							</td>
							<th class='box_06'></th>
						</tr>
						<tr>
							<th class='box_07'></th>
							<td class='box_08'></td>
							<th class='box_09'></th>
						</tr>
					</table>

				</td>
			</tr>
			<tr ><td  colspan=2 align=center style='padding-top:20px;'><input type=image src='../images/".$admininfo["language"]."/bt_search.gif' border=0 align=absmiddle> <!--btn_inquiry.gif--></td></td>
			</form>
			<tr>
			<td valign=top >";

$Contents .=	"
			</td>
			<td valign=top style='padding:0px;padding-top:0px;' id=product_list>
			<!--form ><input type=hidden name='mode' value='search'>

			<table width='100%'>
				<tr height=25 align=center>
					<td>상품코드</td>
					<td>제품명</td>
					<td>가격</td>
					<td>검색</td>
				</tr>
				<tr height=25 align=center>
					<td><input type=text name=pid value='$pid' size=8></td>
					<td><input type=text name=pname value='$pname' size=30></td>
					<td nowrap><input type=text name=from_price value='$from_price' size=10> ~ <input type=text name=to_price value='$to_price' size=10></td>
					<td><input type=submit value='search'></td>
					<td><input type=button value='전체보기' onclick=\"document.location.href='/admin/product_list.php'\"></td>
				</tr>
			</table>";

$Contents .=	"
			</form-->";
$innerview = "
			<table width='100%' cellpadding=0 cellspacing=0 border=0>
			<tr height=30>
				<td align=left>
				<b>상품명</b>
				<a href='?cid=$cid&depth=0&orderby=pname&ordertype=asc'><img src='../image/orderby_desc.gif' border=0 align=top alt='가나다순' title='가나다순'></a>
				<a href='?cid=$cid&depth=0&orderby=pname&ordertype=desc'><img src='../image/orderby_asc.gif' border=0 align=top alt='가나다역순' title='가나다역순'></a>
				<b>출고날짜</b>
				<a href='?cid=$cid&depth=0&orderby=date&ordertype=desc'><img src='../image/orderby_desc.gif' border=0 align=top alt='최근등록순' title='최근등록순'></a>
				<a href='?cid=$cid&depth=0&orderby=date&ordertype=asc'><img src='../image/orderby_asc.gif' border=0 align=top alt='등록순' title='등록순'></a>

				</td>
				<td align=right>
				".($view_type == "list" ? "<a href='stock_output.list.php?".str_replace("view_type=list", "mode=excel",$_SERVER["QUERY_STRING"])."'><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>" : "")."
					
				</td>
				<!--td align=right>".$str_page_bar."</td--></tr></table>
			<table cellpadding=2 cellspacing=0 bgcolor=gray border=0 width=100% class='list_table_box'>
			<tr bgcolor='#cccccc' height=30 align=center>
				<td width='5%' class=s_td>번호</td>
				<td class=m_td >상품명</td>
				<td width='10%' class='m_td'>옵션명(규격)</td>
				<td width='10%' class=m_td>보관장소</td>
				<td width='13%' class=m_td>출고내용</td>
				<td width='10%' class=m_td>출고처</td>
				<td width='10%' class=m_td>출고수량</td>
				<td width='10%' class=m_td>출고가격</td>
				<td width='10%' class=m_td>작성자</td>
				<td width='15%' class=e_td>출고일</td>

			</tr>";



if($orderby != "" && $ordertype != ""){
	$orderbyString = " order by $orderby $ordertype ";
}else{
	$orderbyString = " order by regdate desc ";
}
/*
$where = "where   iohd.charger_ix = cmd.code  and ici.ci_ix = iohd.ci_ix ";


if($search_text != ""){
	$where .= "and ".$search_type." LIKE '%".$search_text."%' ";
}
if ($startDate != "")	$where .= " and date_format(iohd.regdate, '%Y%m%d') between $startDate and $endDate ";
*/	


	/*	
$sql = "select iohd.*,  iohd.charger_ix, ipi.place_name, ici.customer_name, AES_DECRYPT(UNHEX(cmd.name),'".$db->ase_encrypt_key."') as name
			from inventory_customer_info left join common_member_detail cmd ,
			inventory_output_history_detail iohd  
			left join inventory_place_info ipi on ipi.pi_ix = iohd.pi_ix						
			$where $orderbyString 
			LIMIT $start, $max";
*/
	$sql = "select iohd.*,  iohd.charger_ix, ipi.place_name, ici.customer_name, AES_DECRYPT(UNHEX(cmd.name),'".$db->ase_encrypt_key."') as name
				from inventory_output_history_detail iohd  
				left join inventory_place_info ipi on ipi.pi_ix = iohd.pi_ix				
				left join inventory_customer_info ici on ici.ci_ix = iohd.ci_ix and ici.customer_type = 'D'
				left join common_member_detail cmd on iohd.charger_ix = cmd.code
				$where  $orderbyString 
				LIMIT $start, $max
				";
//echo nl2br($sql);
$db->query($sql);

//echo $sql;

if($db->total == 0){
	$innerview .= "<tr bgcolor=#ffffff height=50><td colspan=10 align=center> 출고된 내역이 없습니다.</td></tr>";
}else{
	for ($i = 0; $i < $db->total; $i++)
	{
		$db->fetch($i);
		$no = $total - ($page - 1) * $max - $i;

		if($db->dt[option_text] == ""){
			$option_text = "FREE";
		}else{
			$option_text = $db->dt[option_text];
		}
		if($db->dt[output_type] == "1"){
			$output_text = "일반판매";
		}else if($db->dt[output_type] == "2"){
			$output_text = "직원판매";
		}else if($db->dt[output_type] == "3"){
			$output_text = "기타판매";
		}else if($db->dt[output_type] == "9"){
			$output_text = "손/방실";
		}
		/*if(file_exists($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product/c_".$db->dt[pid].".gif")){
			$img_str = $admin_config[mall_data_root]."/images/product/c_".$db->dt[pid].".gif";
		}else{
			$img_str = "../image/no_img.gif";
		}*/
		if(file_exists(PrintImage($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/product", $db->dt[pid], "s"))){
			$img_str = PrintImage($admin_config[mall_data_root]."/images/product", $db->dt[pid], "s");
		}else{
			$img_str = "../image/no_img.gif";
		}

		$sum_delivery_cnt += $db->dt[delivery_cnt];

	$innerview .= "<tr height=70>
					<td class='list_box_td list_bg_gray'>".$no."</td>
					<td class='list_box_td point' style='padding:5px 5px;' nowrap>
					<table>
						<tr>
							<td width='50' align=center style='padding:0px 10px;'><img src='".$img_str."' width=50 height=50 style='border:1px solid #eaeaea' align=absmiddle></td>
							<td  class='list_box_td'style='text-align:left; padding-left:10px;line-height:150%;'>
							<span class='small'>".getCategoryPathByAdmin($db->dt[cid], 4)."</span><br>
							<!--a href=\"javascript:PoPWindow3('stock_output_detail.php?idx=".$db->dt[o_ix]."&pid=".$db->dt[pid]."&company_code=".$db->dt[pi_ix]."',820,800,'input_detail_pop')\"--><b>".$db->dt[pname]."</b><!--/a-->
							</td>
						</tr>
					</table>
					</td>
					<td class='list_box_td list_bg_gray'> ".$db->dt[option_div]."</td>
					<td class='list_box_td'>".$db->dt[place_name]."</td>
					<td class='list_box_td list_bg_gray'>".$db->dt[delivery_msg]."</td>
					<td class='list_box_td' style='padding:0px 5px;' nowrap>".$db->dt[customer_name]."</td>
					<td class='list_box_td list_bg_gray'>".$db->dt[delivery_cnt]."</td>
					<td class='list_box_td'>".$db->dt[delivery_price]."</td>
					<td class='list_box_td list_bg_gray'>".$db->dt[name]."</td>
					
					<td class='list_box_td'>".$db->dt[regdate]."</td>
";

	}

	if($view_type == "summary"){
	$innerview .= "<tr height=30>
					<td class='list_box_td list_bg_gray' colspan=6><b>합계</b></td>					
					<td class='list_box_td ' >".$sum_delivery_cnt."</td>
					<td class='list_box_td ' colspan=3></td>
					</tr>
					";
	}

}
	$innerview .= "</table>
				<table width='100%'><tr height=30><td align=right>".$str_page_bar."</td></tr></table>

				";

$Contents = $Contents.$innerview ."
			</td>
			</tr>
		</table>
		<iframe name='act' src='' width=0 height=0></iframe>
			";

$help_text = "
<table cellpadding=0 cellspacing=0 class='small' >
	<col width=8>
	<col width=*>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >리스트에서 기본적인 정보를 수정하실수 있습니다</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >개별정보를 수정후 <img src='../image/btc_modify.gif' align=absmiddle> 버튼를 클릭하시면 해당 제품만을 수정하실수 있습니다</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >리스트의 여러제품을 수정후 <img src='../image/bt_all_modify.gif' align=absmiddle> 버튼를 클릭하시면 해당 리스트에 보여지는 전체 제품을 수정하실수 있습니다</td></tr>
</table>
";

//$Contents .= HelpBox("상품 리스트", $help_text);


$category_str ="<div class=box id=img3  style='width:155px;height:250px;overflow:auto;'>".Category()."</div>";


	$Script = "<Script Language='JavaScript' src='/js/ajax2.js'></Script>\n
	<script Language='JavaScript' src='../include/zoom.js'></script>
	<!-- 스크립트 에러 발생으로 주석처리함 kbk -->
	<script src='stock_output.list.js' type='text/javascript'></script>
	<script type='text/javascript'>	
function onLoad(FromDate, ToDate) {
	var frm = document.search_frm;
	
	
	LoadValues(frm.vFromYY, frm.vFromMM, frm.vFromDD, FromDate);
	LoadValues(frm.vToYY, frm.vToMM, frm.vToDD, ToDate);";
	

if($regdate != "1"){
$Script .= "
	frm.vFromYY.disabled = true;
	frm.vFromMM.disabled = true;
	frm.vFromDD.disabled = true;
	frm.vToYY.disabled = true;
	frm.vToMM.disabled = true;
	frm.vToDD.disabled = true;	";
}
$Script .= "	
	init_date(FromDate,ToDate);
	
}
</script>
";
	$P = new LayOut();
	$P->strLeftMenu = inventory_menu();
	$P->addScript = $Script;
	$P->Navigation = "재고관리 > 입출고관리 > $page_title";
	$P->title = "$page_title";
	$P->strContents = $Contents;
	$P->OnloadFunction = "onLoad('$sDate','$eDate');";//"ChangeOrderDate(document.search_frm);";
	$P->addScript = "<script language='javascript' src='../include/DateSelect.js'></script>\n$Script";
	$P->PrintLayOut();





?>

