<?php
/**
 * Created by PhpStorm.
 * User: moon
 * Date: 2017-07-27
 * Time: 오후 4:54
 */
include $_SERVER['DOCUMENT_ROOT']."/admin/class/layout.class";

$db = new Database;
$Contents01 .= "
    
	<form name='searchmember' style='display:inline;'>
	<input type='hidden' name='mode' value='search'>
	<input type='hidden' name='co_ix' value='".$_GET['co_ix']."'>
	<table border='0' cellpadding='0' cellspacing='0' width='100%'>	
	<tr>
		<td align='left' colspan=2  width='100%' valign=top style='padding-top:0px;'>
			<table border='0' cellpadding='0' cellspacing='0' width='100%'>
			<tr>
				<td class='box_05' valign=top style='padding:0px;'>
					<table cellpadding=0 cellspacing=0 width='100%' class='search_table_box'>
				
					<col width=15%>
					<col width=*>
					<tr height=27>
						<td class='search_box_title' >검색조건 </td>
						<td class='search_box_item' >
							<select name='search_type' id='search_type'  style=\"font-size:12px;\">
                                <option value='user_name' ".CompareReturnValue("user_name",$search_type).">이름</option>
                                <option value='user_id' ".CompareReturnValue("user_id",$search_type).">ID</option>
                                <option value='question' ".CompareReturnValue("question",$search_type).">내용</option>
                            </select>
                            <input id=search_texts class='textbox' value='".$search_text."' autocomplete='off'  name=search_text  title='검색어'>
						</td>
					</tr>					
					</table>
				</td>
			</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan=3 align=center style='padding:10px 0;'>
			<input type='image' src='../images/".$admininfo["language"]."/bt_search.gif' border=0>
		</td>
	</tr>
	</table>
	</form>";

$max = 15; //페이지당 갯수

if ($page == ''){
    $start = 0;
    $page  = 1;
}else{
    $start = ($page - 1) * $max;
}

$where = "where co_ix = '".$_GET['co_ix']."' ";
if($mode == 'search'){
    if($_GET['search_type'] && $_GET['search_text']){
        $where .= " and ".$_GET['search_type']." LIKE '%".$_GET['search_text']."%' ";
    }
}

$sql = "select count(*) cnt from bienview_whos_next_question $where ";
$db->query($sql);
$db->fetch();
$total = $db->dt['cnt'];

$sql = "select * from bienview_whos_next_question  $where order by qu_ix desc  ";
if($mmode != 'excel'){
    $sql .= " Limit $start,$max ";
}

$db->query($sql);
$question_data = $db->fetchall();


if($mmode == 'excel'){
    include("../include/phpexcel/Classes/PHPExcel.php");
    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    $QuestionListXL = new PHPExcel();

    // 속성 정의
    $QuestionListXL->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("Mallstory.com")
        ->setTitle("orders List")
        ->setSubject("orders List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("mallstory")
        ->setCategory("question List");



    // 데이터 등록
    $QuestionListXL->getActiveSheet(0)->setCellValue('A' . 1, "질문자명");
    $QuestionListXL->getActiveSheet(0)->setCellValue('B' . 1, "ID");
    $QuestionListXL->getActiveSheet(0)->setCellValue('C' . 1, "내용");

    if(is_array($question_data) && $total > 0) {
        $i = 0;
        foreach ($question_data as $val) {
            $QuestionListXL->getActiveSheet()->setCellValue('A' . ($i + 2), $val['user_name']);
            $QuestionListXL->getActiveSheet()->setCellValue('B' . ($i + 2), $val['user_id']);
            $QuestionListXL->getActiveSheet()->setCellValue('C' . ($i + 2), $val['question']);
            $i++;
        }
    }


    // 시트이름등록
    $QuestionListXL->getActiveSheet()->setTitle('질문목록');

    // 첫번째 시트 선택
    $QuestionListXL->setActiveSheetIndex(0);
    $QuestionListXL->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
    $QuestionListXL->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
    $QuestionListXL->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);


    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="question_whos_next.xls"');
    header('Cache-Control: max-age=0');


    $objWriter = PHPExcel_IOFactory::createWriter($QuestionListXL, 'Excel5');
    $objWriter->save('php://output');

    exit;
}



$Contents01 .= "
	<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' >
	<tr height=30 >
		<td>
			<b>전체 : ".$total." 개</b> 
		</td>
		<td  align=right>
		    <a href='?".$_SERVER["QUERY_STRING"]."&mmode=excel'><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' style='vertical-align:middle;' border=0></a>
		    목록 수 :
            <select name=max style=\"font-size:12px;height: 20px; width: 50px;\" align=absmiddle>
                <option value='5' ".CompareReturnValue(5,$max).">5</option>
                <option value='10' ".CompareReturnValue(10,$max).">10</option>
                <option value='20' ".CompareReturnValue(20,$max).">20</option>
                <option value='40' ".CompareReturnValue(40,$max).">40</option>
                <option value='50' ".CompareReturnValue(50,$max).">50</option>
                <option value='100' ".CompareReturnValue(100,$max).">100</option>
            </select> 
		</td>
	</tr>
	</table>
	<table width='100%' cellpadding=3 cellspacing=0 border='0' align='left' class='list_table_box'>
	<col width=10%>
	<col width=20%>
	<col width=*>
	<tr bgcolor=#efefef style='font-weight:bold' align=center height=28>		
		<td class='s_td'>번호</td>
		<td class='m_td'>질문자 명/ID</td>
		<td class='e_td'>내용</td>
	</tr>";
if(is_array($question_data) && $total > 0){
    $i=0;
    foreach($question_data as $val){
        $no = $total - ($page - 1) * $max - $i;
        $Contents01 .= "        
        <tr height=28 align=center>        
            <td class='list_box_td' bgcolor='#ffffff'>".$no."</td>			
            <td class='list_box_td list_bg_gray'>".$val['user_name']."/".$val['user_id']."</td>
            <td class='list_box_td '>".$val['question']." </td>
        </tr>
        ";
        $i++;
    }
}else{
    $Contents01 .= "
    <tr height=28 align=center>        
        <td class='list_box_td' colspan='3'>
            <span>질문 내역이 없습니다.</span>            
        </td>
    </tr> ";
}
$Contents01 .= "
    </table>
	";
$Contents01 .= "
    <table width='100%' border='0' cellpadding='3' cellspacing='0' align='center' >
        <tr height=40>
         <td colspan='13' align='right'>&nbsp;".page_bar($total, $page, $max,$query_string."#list_top","")."&nbsp;</td>
        </tr>
    </table>";



$Contents = $Contents01;


$P = new LayOut();
$P->addScript = "".$Script;//<script language='javascript' src='../include/DateSelect.js'></script>\n
$P->OnloadFunction = "";
$P->strLeftMenu = bienview_menu();
$P->Navigation = "BIENVIEW관리 > 콘텐츠 관리 > 질문목록 ";
$P->title = "질문목록";
$P->strContents = $Contents;
echo $P->PrintLayOut();