<?php

	include("../class/layout.class");
	include '../include/phpexcel/Classes/PHPExcel.php';

	//error_reporting(E_ALL);
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');




	$db = new Database;
	$mdb = new Database;


	if ($admininfo[mall_type] == "O"){
		if($db->dbms_type == "oracle"){
			$where = " where cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F','S') ";
		}else{
			$where = " where cu.code != '' and cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F','S') ";
		}
	}else{
		if($db->dbms_type == "oracle"){
			$where = " where cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F') ";
		}else{
			$where = " where cu.code != '' and cu.code = cmd.code and cmd.gp_ix = mg.gp_ix and gp_level != 0 and cu.mem_type in ('M','C','F') ";
		}
	}
	if($region != ""){
		$where .= " and addr1 LIKE  '%".$region."%' ";
	}

	if($gp_level != ""){
		$where .= " and mg.gp_level = '".$gp_level."' ";
	}

	if($gp_ix != ""){
		$where .= " and mg.gp_ix = '".$gp_ix."' ";
	}


	$birthday = $birYY.$birMM.$birDD;
	$birthday2 = substr($birYY,2,2).$birMM.$birDD;


	if($sex == "M" || $sex == "W"){
		$where .= " and sex_div =  '$sex' ";
	}

	if($mailsend_yn != "A" && $mailsend_yn != ""){
		$where .= " and info =  '$mailsend_yn' ";
	}

	if($smssend_yn != "A" && $smssend_yn != ""){
		$where .= " and sms =  '$smssend_yn' ";
	}


	if($db->dbms_type == "oracle"){
		if($search_type != "" && $search_text != ""){
			if($search_type == "name" || $search_type == "mail" || $search_type == "pcs" || $search_type == "tel" ){
				$where .= " and AES_DECRYPT($search_type,'".$db->ase_encrypt_key."') LIKE  '%$search_text%' ";
			}else{
				$where .= " and $search_type LIKE  '%$search_text%' ";
			}
		}
	}else{
		if($search_type != "" && $search_text != ""){
			if($search_type == "name" || $search_type == "mail" || $search_type == "pcs" || $search_type == "tel" ){
				$where .= " and AES_DECRYPT(UNHEX($search_type),'".$db->ase_encrypt_key."') LIKE  '%$search_text%' ";
			}else{
				$where .= " and $search_type LIKE  '%$search_text%' ";
			}
		}
	}

	$startDate = $FromYY.$FromMM.$FromDD;
	$endDate = $ToYY.$ToMM.$ToDD;

	if($startDate != "" && $endDate != ""){
		$where .= " and  MID(replace(cu.date,'-',''),1,8) between  $startDate and $endDate ";
	}

	$vstartDate = $vFromYY.$vFromMM.$vFromDD;
	$vendDate = $vToYY.$vToMM.$vToDD;

	if($vstartDate != "" && $vendDate != ""){
		$where .= " and  MID(replace(cu.last,'-',''),1,8) between  $vstartDate and $vendDate ";
	}

	if($db->dbms_type == "oracle"){
		$sql = "select cmd.code, cu.id, AES_DECRYPT(cmd.name,'".$db->ase_encrypt_key."') as name, AES_DECRYPT(cmd.mail,'".$db->ase_encrypt_key."') as mail,
			cu.visit, date_format(cmd.date_,'%Y.%m.%d') as regdate, mg.gp_name,  last, AES_DECRYPT(cmd.pcs,'".$db->ase_encrypt_key."') as pcs
			from common_user cu, common_member_detail cmd , ".TBL_SHOP_GROUPINFO." mg $where  ORDER BY cmd.date_ DESC "; //kbk
	}else{
		$sql = "select cmd.code, cu.id, AES_DECRYPT(UNHEX(cmd.name),'".$db->ase_encrypt_key."') as name, AES_DECRYPT(UNHEX(cmd.mail),'".$db->ase_encrypt_key."') as mail,
			cu.visit, date_format(cmd.date,'%Y.%m.%d') as regdate, mg.gp_name,  UNIX_TIMESTAMP(last) AS last, AES_DECRYPT(UNHEX(cmd.pcs),'".$db->ase_encrypt_key."') as pcs
			from common_user cu, common_member_detail cmd , ".TBL_SHOP_GROUPINFO." mg $where  ORDER BY cmd.date DESC "; //kbk
	}
	//echo $sql;
	$db->query($sql);





	$memberXL = new PHPExcel();

		// �Ӽ� ����
	$memberXL->getProperties()->setCreator("������ �ڸ���")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("Member List")
								 ->setSubject("Member List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("Member List");

	// ������ ���
	$memberXL->getActiveSheet(0)->setCellValue('A' . 1, "��ȣ");
	$memberXL->getActiveSheet(0)->setCellValue('B' . 1, "�׷�");
	$memberXL->getActiveSheet(0)->setCellValue('C' . 1, "�̸�");
	$memberXL->getActiveSheet(0)->setCellValue('D' . 1, "���̵�");
	$memberXL->getActiveSheet(0)->setCellValue('E' . 1, "�̸���");
	$memberXL->getActiveSheet(0)->setCellValue('F' . 1, "�����");
	$memberXL->getActiveSheet(0)->setCellValue('G' . 1, "�α��");
	$memberXL->getActiveSheet(0)->setCellValue('H' . 1, "������");
	$memberXL->getActiveSheet(0)->setCellValue('I' . 1, "�ڵ���");


	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);

		if($db->dbms_type == "oracle"){
			$mdb->query("SELECT sum(reserve) as reserve_sum FROM ".TBL_SHOP_RESERVE_INFO." WHERE uid_ = '".$db->dt[code]."' and state in (1,2,5,6,7)");
		}else{
			$mdb->query("SELECT sum(reserve) as reserve_sum FROM ".TBL_SHOP_RESERVE_INFO." WHERE uid = '".$db->dt[code]."' and state in (1,2,5,6,7)");
		}
		$mdb->fetch(0);

		$memberXL->getActiveSheet()->setCellValue('A' . ($i + 2), ($i + 1));
		$memberXL->getActiveSheet()->setCellValue('B' . ($i + 2), $db->dt[gp_name]);
		$memberXL->getActiveSheet()->setCellValue('C' . ($i + 2), $db->dt[name]);
		$memberXL->getActiveSheet()->setCellValue('D' . ($i + 2), $db->dt[id]);
		$memberXL->getActiveSheet()->setCellValue('E' . ($i + 2), $db->dt[mail]);
		$memberXL->getActiveSheet()->setCellValue('F' . ($i + 2), $db->dt[regdate]);
		$memberXL->getActiveSheet()->setCellValue('G' . ($i + 2), $db->dt[visit]);
		$memberXL->getActiveSheet()->setCellValue('H' . ($i + 2), ($mdb->dt[reserve_sum] == "" ? "-":$mdb->dt[reserve_sum]));
		$memberXL->getActiveSheet()->setCellValue('I' . ($i + 2), $db->dt[pcs]);
	}

	// ��Ʈ�̸����
	$memberXL->getActiveSheet()->setTitle('ȸ��');

	// ù��° ��Ʈ ����
	$memberXL->setActiveSheetIndex(0);
	$memberXL->getActiveSheet()->getColumnDimension('A')->setWidth(5);
	$memberXL->getActiveSheet()->getColumnDimension('B')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('C')->setWidth(15);
	$memberXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('G')->setWidth(10);
	$memberXL->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="members.xls"');
	header('Cache-Control: max-age=0');


	$objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
	$objWriter->save('php://output');

	exit;