<?
include("../class/layout.class");
include("./company.lib.php");
$db = new Database;

if(!$max){
	$max = 15; //페이지당 갯수
}

if ($page == '')
{
	$start = 0;
	$page  = 1;
}
else
{
	$start = ($page - 1) * $max;
}


$info_type = "company_list";

$search_str = "";

if($search_type == "company"){
	if($search_text){
		$sql = "select
				ccr.relation_code 
				from
					common_company_detail as ccd
					inner join common_company_relation as ccr on (ccd.company_id = ccr.company_id)
				where
					ccd.com_name like '%".$search_text."%'";

		$db->query($sql);
		$db->fetch();

		if($db->dt[relation_code]){
		$search_code = $db->dt[relation_code];
		}else{
		$search_code = "a";
		}
	}
	$search_str .= " and ccr.relation_code like '".$search_code."%' ";
}else if ($search_type == "ccd.com_name"){
	
	if($search_text){

		if($search_type == "ccd.com_name"){
			$search_str .= " and ccd.com_name LIKE  '%".$search_text."%' ";
		}else{
			$search_str .= " and ".$search_type." = '".$search_text."' ";
		}

		//$search_str .= " and ccr.relation_code like '".$search_code."%' ";
	}
}

if($nationality != ""){
	$search_str .= " and csd.nationality = '".$nationality."' ";
}

if($com_div != ""){
	$search_str .= " and ccd.com_div = '".$com_div."' ";
}

if($cid2){
	
	$search_str_9 .= " and cr.relation_code = '".$cid2."' ";
}

if(is_array($seller_type)){
	if($seller_type[0] !="a"){
		$search_str .= " and (";
		foreach($seller_type as $key =>$value){
			if($value){
				$search_str .= "ccd.seller_type like'%".$value."%'";
				if(($key == 0 and count($seller_type) != 1) or $key != count($seller_type)-1){
					$search_str .= " or ";
				}
			}
		}
		$search_str .=")";
	}
}


if($_REQUEST['regdate'] == '1'){
	if($sdate != "" && $edate != ""){
		if($db->dbms_type == "oracle"){
			$search_str .= " and  to_char(ccd.regdate_ , 'YYYY-MM-DD') between  '".$sdate."' and '".$edate."' ";
		}else{
			$search_str .= " and date_format(ccd.regdate,'%Y-%m-%d') between  '".$sdate."' and '".$edate."' ";
		}
	}
}

if($admininfo[admin_level] == '8'){	//셀러업체일경우 추가
	$search_str .= " and ccd.company_id = '".$admininfo[company_id]."'";
}

$sql = "SELECT 
			COUNT(*) as total
		FROM 
			common_company_detail ccd
			left join common_seller_detail as csd on (ccd.company_id = csd.company_id)
			inner join ".TBL_COMMON_COMPANY_RELATION." as cr on (ccd.company_id = cr.company_id)
		where 
			com_type in ('BR','A','BP','BO') 
			$search_str 
			$search_str_9";
$db->query($sql);
$db->fetch();
$total = $db->dt[total];

if($db->dbms_type == "oracle"){
	$sql = "SELECT ccd.*,
			cr.relation_code
		FROM 
			".TBL_COMMON_COMPANY_DETAIL." ccd
			left join common_seller_detail as csd on (ccd.company_id = csd.company_id)
			inner join ".TBL_COMMON_COMPANY_RELATION." as cr on (ccd.company_id = cr.company_id)
		where
			ccd.com_type in ('BR','A','BP','BO' )
			$search_str
			$search_str_9
			order by cr.relation_code, ccd.regdate asc 
			LIMIT $start,$max";
}else{
	$sql = "SELECT ccd.*,
			cr.relation_code
		FROM 
			".TBL_COMMON_COMPANY_DETAIL." ccd
			left join common_seller_detail as csd on (ccd.company_id = csd.company_id)
			inner join ".TBL_COMMON_COMPANY_RELATION." as cr on (ccd.company_id = cr.company_id)
		where  
			ccd.com_type in ('BR','A','BP','BO' )
			$search_str
			$search_str_9
			order by cr.relation_code, ccd.regdate asc 
			LIMIT $start,$max";
}

$db->query($sql);


if($mode == "excel"){

	$goods_infos = $db->fetchall();
	$info_type = "company_list";

	include("excel_out_columsinfo.php");
	$sql = "select conf_val from inventory_config where charger_ix='".$admininfo[charger_ix]."' and conf_name='basic_excel_".$info_type."' ";
	$db->query($sql);
	$db->fetch();
	$stock_report_excel = $db->dt[conf_val];

	$sql = "select conf_val from inventory_config where charger_ix='".$admininfo[charger_ix]."' and conf_name='basic_excel_checked_".$info_type."' ";
	$db->query($sql);
	$db->fetch();
	$stock_report_excel_checked = $db->dt[conf_val];

	$check_colums = unserialize(stripslashes($stock_report_excel_checked));

	$columsinfo = $colums;

	include '../include/phpexcel/Classes/PHPExcel.php';
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$inventory_excel = new PHPExcel();

	// 속성 정의
	$inventory_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("accounts plan price List")
								 ->setSubject("accounts plan price List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("accounts plan price List");
	$col = 'A';
	if(is_array($check_colums) && count($check_colums) > 0 ) {

        foreach ($check_colums as $key => $value) {
            $inventory_excel->getActiveSheet(0)->setCellValue($col . "1", $columsinfo[$value][title]);
            $col++;
        }

        $before_pid = "";

        for ($i = 0; $i < count($goods_infos); $i++) {
            $j = "A";
            foreach ($check_colums as $key => $value) {

                if ($key == "seller_auth") {

                    switch ($goods_infos[$i][seller_auth]) {
                        case "Y":
                            $value_str = "승인";
                            break;
                        case "N":
                            $value_str = "승인대기";
                            break;
                        case "X":
                            $value_str = "승인거부";
                            break;
                        default:
                            $value_str = "알수없음";
                            break;
                    }


                } else if ($key == "com_type") {
                    switch ($goods_infos[$i][com_type]) {
                        case "A":
                            $value_str = "본사";
                            break;
                        case "BR":
                            $value_str = "지사";
                            break;
                        case "BP":
                            $value_str = "사업소";
                            break;
                        case "BO":
                            $value_str = "영업소";
                            break;
                        case "G":
                            $value_str = "거래처";
                            break;
                        default:
                            $value_str = "알수없음";
                            break;
                    }
                } else if ($key == "com_div") {
                    switch ($goods_infos[$i][com_div]) {
                        case "P":
                            $value_str = "개인(일반과세자)";
                            break;
                        case "S":
                            $value_str = "개인(간이과세자)";
                            break;
                        case "R":
                            $value_str = "법인사업자";
                            break;
                        case "E":
                            $value_str = "면세사업자";
                            break;
                        default:
                            $value_str = "알수없음";
                            break;
                    }
                } else if ($key == "nationality") {
                    switch ($goods_infos[$i][nationality]) {
                        case "I":
                            $value_str = "국내";
                            break;
                        case "O":
                            $value_str = "해외";
                            break;
                    }
                } else if ($key == "member_count") {
                    $value_str = getmembercount($goods_infos[$i][company_id]);
                } else {
                    $value_str = $goods_infos[$i][$value];//$db1->dt[$value];
                }

                $inventory_excel->getActiveSheet()->setCellValue($j . ($z + 2), $value_str);
                $j++;

                unset($history_text);
            }
            $z++;
        }
        // 첫번째 시트 선택
        $inventory_excel->setActiveSheetIndex(0);

        // 너비조정
        $col = 'A';
        foreach ($check_colums as $key => $value) {
            $inventory_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
            $col++;
        }
    }else{
        $inventory_excel->getActiveSheet(0)->setCellValue($col . "1", "엑셀 다운로드 형식 설정이 안되어 있습니다. 엑셀 설정하기를 클릭하여 저장 후 다시 엑셀 저장 시도해주세요.");
        $inventory_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
    }

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="company_'.$info_type.'.xls"');
	header('Cache-Control: max-age=0');

	$objWriter = PHPExcel_IOFactory::createWriter($inventory_excel, 'Excel5');
	$objWriter->save('php://output');

	exit;
}

if($search_text != ""){
	$str_page_bar = page_bar($total, $page,$max, "&view=innerview&max=$max&search_type=$search_type&search_text=$search_text&orderby=$orderby&ordertype=$ordertype&list_type=$list_type","view");
}else{
	$str_page_bar = page_bar($total, $page,$max, "&view=innerview&max=$max&orderby=$orderby&ordertype=$ordertype&list_type=$list_type","view");
}

if( $admininfo[mall_use_multishop] && $admininfo[mall_div]){
	if($admininfo[admin_level] == 9){
		$menu_name = "회사조직도";
	}else{
		$menu_name = "회사조직도";
	}
}else{
	$menu_name = "거래처관리";
}

$mstring .= "
<table class='box_shadow' style='width:100%;' cellpadding='0' cellspacing='0' border='0'>
	<tr>
		<td >
 		<table width='100%' border='0' cellspacing='0' cellpadding='0' height='25' class='search_table_box'>
		<form name=search_seller method='get'><!--SubmitX(this);'-->
		<input type='hidden' name='cid2' value='$cid2'>
		<input type='hidden' name='depth' value='$depth'>
		<input type='hidden' name=mc_ix value='".$mc_ix." '>
		<col width='15%'>
		<col width='85%'>
		<tr>
			<td class='input_box_title'> <b>사업장 검색</b></td>
			<td class='input_box_item' colspan='3'>
				<table border=0 cellpadding=0 cellspacing=0>
					<tr>
						<td style='padding-right:5px;'>
						".getCompanyList("본사", "cid0_1", "onChange=\"loadCategory('cid0_1','cid1_1','company')\" title='선택' ", '5', $cid2,'company')."</td>
						<td style='padding-right:5px;'>
						".getCompanyList("선택", "cid1_1", "onChange=\"loadCategory('cid1_1','cid2_1','company')\" title='선택'", '15', $cid2,'company')."</td>
						<td style='padding-right:5px;'>
						".getCompanyList("선택", "cid2_1", "onChange=\"loadCategory('cid2_1','cid3_1','company')\" title='선택'", '25', $cid2,'company')."</td>
						<td>".getCompanyList("선택", "cid3_1", "onChange=\"loadCategory('cid3_1','','company')\" title='선택'", '35', $cid2,'company')."</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr height=27>
			<td class='search_box_title' >거래유형 </td>
			<td class='search_box_item' colspan=3>
			<input type=checkbox name='seller_type[]' value='a' id='seller_type_'  ".CompareReturnValue("a",$seller_type,"checked")."><label for='seller_type_'> 전체</label>&nbsp;&nbsp;
			<input type=checkbox name='seller_type[]' value='1' id='seller_type_1'  ".CompareReturnValue("1",$seller_type,"checked")."><label for='seller_type_1'> 국내 매출</label>&nbsp;&nbsp;
			<input type=checkbox name='seller_type[]' value='2' id='seller_type_2'  ".CompareReturnValue("2",$seller_type,"checked")."><label for='seller_type_2'> 국내 매입</label>&nbsp;&nbsp;
			<input type=checkbox name='seller_type[]' value='3' id='seller_type_3'  ".CompareReturnValue("3",$seller_type,"checked")."><label for='seller_type_3'> 해외 수출</label>&nbsp;&nbsp;
			<input type=checkbox name='seller_type[]' value='4' id='seller_type_4'  ".CompareReturnValue("4",$seller_type,"checked")."><label for='seller_type_4'> 해외 수입</label>&nbsp;&nbsp;
			<input type=checkbox name='seller_type[]' value='5' id='seller_type_5'  ".CompareReturnValue("4",$seller_type,"checked")."><label for='seller_type_5'> 외주 물류창고</label>&nbsp;&nbsp;
			</td>
		</tr>
		<tr height=27>
			<td class='search_box_title' >국내외 구분 </td>
			<td class='search_box_item'  colspan='3'>
			<input type=radio name='nationality' value='' id='nationality_'  ".CompareReturnValue("",$nationality,"checked")."><label for='nationality_'> 전체</label>&nbsp;&nbsp;
			<input type=radio name='nationality' value='I' id='nationality_I'  ".CompareReturnValue("I",$nationality,"checked")."><label for='nationality_I'> 국내</label>&nbsp;&nbsp;
			<input type=radio name='nationality' value='O' id='nationality_O'  ".CompareReturnValue("O",$nationality,"checked")."><label for='nationality_O'> 해외</label>&nbsp;&nbsp;
			<input type=radio name='nationality' value='D' id='nationality_D'  ".CompareReturnValue("D",$nationality,"checked")."><label for='nationality_D'> 기타</label>&nbsp;&nbsp;
			</td>
		</tr>
		<tr>
			<td class='search_box_title'>사업자 유형</td>
			<td class='search_box_item'  colspan='3'>
				<input type=radio name='com_div' value='' id='com_div_'  ".CompareReturnValue("",$com_div,"checked")."><label for='com_div_'> 전체 </label>&nbsp;&nbsp;
				<input type=radio name='com_div' value='R' id='com_div_1'  ".CompareReturnValue("R",$com_div,"checked")."><label for='com_div_1'> 법인사업자 </label>&nbsp;&nbsp;
				<input type=radio name='com_div' value='P' id='com_div_2'  ".CompareReturnValue("P",$com_div,"checked")."><label for='com_div_2'> 개인사업자 </label>&nbsp;&nbsp;
				<input type=radio name='com_div' value='S' id='com_div_3' ".CompareReturnValue("S",$com_div,"checked")."><label for='com_div_3'> 간이사업자 </label>&nbsp;&nbsp;
				<input type=radio name='com_div' value='E' id='com_div_4' ".CompareReturnValue("E",$com_div,"checked")."><label for='com_div_4'> 면세 </label>&nbsp;&nbsp;
				<input type=radio name='com_div' value='I' id='com_div_5' ".CompareReturnValue("I",$com_div,"checked")."><label for='com_div_5'> 수출입업체 </label>&nbsp;&nbsp;
			</td>
		</tr>
		
		<tr height=27>
			<td class='search_box_title' ><label for='regdate'>회사등록일</label><input type='checkbox' name='regdate' id='regdate' value='1' onclick='ChangeRegistDate(document.search_seller);' ".CompareReturnValue("1",$regdate,"checked")."></td>
			<td class='search_box_item'  colspan=3 >
				".search_date('sdate','edate',$sdate,$edate)."
			</td>
		</tr>
		<tr height=27>
			<td class='search_box_title' >검색 </td>
			<td class='search_box_item' colspan=3>
				<table cellpadding=0 cellspacing=0 width=100%>
					<col width='80'>
					<col width='*'>
					<tr>
						<td>
							<select name=search_type>
								<option value='' ".CompareReturnValue("",$search_type,"selected")."> 선택 </option>
								<option value='ccd.com_ceo' ".CompareReturnValue("ccd.com_ceo",$search_type,"selected")."> 대표자명 </option>
								<option value='ccd.com_name' ".CompareReturnValue("ccd.com_name",$search_type,"selected")."> 사업장명 </option>
							</select>
						</td>
						<td>
							<input type=text name='search_text' class='textbox' value='".$search_text."' style='width:20%;font-size:12px;padding:1px;' >
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	</td>
</tr>
</table>
<table class='box_shadow' style='width:100%;' cellpadding='0' cellspacing='0' border='0'>
		<tr >
			<td colspan=3 align=center  style='padding:30px 0 10px 0'>
				<input type='image' src='../images/".$admininfo["language"]."/bt_search.gif' border=0>
			</td>
		</tr>
</table>
<br>
</form>
";

//info_type = company_list
$mstring .= "

		<table width='100%' border='0' cellspacing='0' cellpadding='0' height='25'>
			<col width=70%>
			<col width=10%>
			<col width=6%>
			<col width=7%>
		<tr height=30 >
			<td align=left><b class=blk>전체 : $total 개</b><div style='display:inline-block; padding:0px 0px 0px 20px'></div></td>
			<td align='right' colspan=3 style='padding:5px 0 5px 0;display:none;'>
			";
			if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E")){
				$mstring .= "<span class='helpcloud' help_height='30' help_html='엑셀 다운로드 형식을 설정하실 수 있습니다.'>
				<a href='excel_config.php?".$QUERY_STRING."&info_type=".$info_type."&excel_type=company_list' rel='facebox' ><img src='../images/".$admininfo["language"]."/btn_excel_set.gif'></a></span>";
			}else{
				$mstring .= "
				<a href=\"".$auth_excel_msg."\"><img src='../images/".$admininfo["language"]."/btn_excel_set.gif'></a>";
			}

			if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E")){
				$mstring .= " <a href='company.list.php?mode=excel&".str_replace($mode, "excel",$_SERVER["QUERY_STRING"])."'><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";
			}else{
				$mstring .= " <a href=\"".$auth_excel_msg."\"><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";
			}

			$mstring .= "
			</td>
		  </tr>
		</table>
		<table width='100%' cellpadding=0 cellspacing=0 border='0' >
		<tr>
			<td colspan=8>
				<table border='0' cellpadding='0' cellspacing='0' width='100%'>
				<!--tr>
					<td align='left' colspan=4 style='padding-bottom:5px;'> ".colorCirCleBox("#efefef","100%","<div style='padding:5px 5px 5px 15px;'><img src='../image/title_head.gif' ><b> 회사 리스트</b> ".($company_id != "" ? "[ ".$db->dt[com_name]." : ".$company_id." ]" : "")." </div>")."</td>
				  </tr-->
				</table>
			</td>
		</tr>
		</table>
		<table width='100%' border='0' cellpadding='0' cellspacing='0' align='center' class='list_table_box'>
			<col width=3%>
			<col width=10%>
			<col width=10%>
			<col width=12%>
			<col width=12%>
			<col width=10%>
			<col width=10%>
			<col width=9%>
			<col width='7%'>
			<col width='7%'>
		<tr bgcolor=#efefef align=center height=27>
			<td class='s_td'>순번</td>
			<td class='m_td'>등록일</td>
			<td class='m_td'>회사코드</td>
			<td class='m_td'>사업자유형</td>
			<td class='m_td'>사업자명/사업소명</td>
			<td class='m_td'>사원수</td>
			<td class='m_td'>대표연락처</td>
			<td class='m_td'>팩스</td>
			<td class='m_td'>사용승인상태</td>
			<td class='e_td'>관리</td>
		</tr>
		";

if($db->total){
	$company_infos = $db->fetchall();

	for($i=0;$i<count($company_infos);$i++){

		$no = $total - ($page - 1) * $max - $i;
		$phone = explode("-",$company_infos[$i][com_phone]);
		$fax = explode("-",$company_infos[$i][com_fax]);

		if($company_infos[$i][seller_auth] == "Y"){
			$auth_str = "승인";
		}else if($company_infos[$i][seller_auth] == "N"){
			$auth_str = "승인대기";
		}else if($company_infos[$i][seller_auth] == "X"){
			$auth_str = "승인거부";
		}
		
		if($company_infos[$i][com_type] == "A"){
			$com_type_name = "본사";
		}else if($company_infos[$i][com_type] == "BR"){
			$com_type_name = "지사";
		}else if($company_infos[$i][com_type] == "BP"){
			$com_type_name = "사업소";
		}else if($company_infos[$i][com_type] == "BO"){
			$com_type_name = "영업소";
		}else if($company_infos[$i][com_type] == "G"){
			$com_type_name = "거래처";
		}

		if($company_infos[$i][com_name]){
			$common_name = $company_infos[$i][com_name];
		}else{
			$common_name = $company_infos[$i][com_name];
		}

		$mstring .="
				<tr height=32 align=center>
					<td class='list_box_td '>".$no."</td>
					<td class='list_box_td '>".$company_infos[$i][regdate]."</td>
					<td align='left'><span style='padding-left:10px;'>".$company_infos[$i][relation_code]."</span></td>
					<td class='list_box_td'>".$com_type_name."</td>
					<td class='list_box_td '><a href='company.add.php?company_id=".$company_infos[$i][company_id]."'>".$company_infos[$i][com_name]."</a></td>
					<td class='list_box_td'>".getmembercount($company_infos[$i][company_id])." 명 </td>
					<td class='list_box_td '>".$company_infos[$i][com_phone]."</td>
					<td class='list_box_td '>".$company_infos[$i][com_fax]."</td>
					<td class='list_box_td '>".$auth_str."</td>
					<td class='list_box_td' align=center style='padding:0px 5px' nowrap>";
	
            if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"U")){
				$type = array('BR','BP','BO');
				if(in_array($company_infos[$i][com_type],$type)){
				$mstring .="
						<a href='customer.add.php?company_id=".$company_infos[$i][company_id]."&info_type=basic'><img src='../images/".$admininfo["language"]."/bts_modify.gif' border=0 align='absmiddle'></a>";
				}else if($company_infos[$i][com_type] == "G"){
					$mstring .="
						<a href='seller.add.php?company_id=".$company_infos[$i][company_id]."&info_type=basic'><img src='../images/".$admininfo["language"]."/bts_modify.gif' border=0 align='absmiddle'></a>";
				}else{
				$mstring .="
						<a href='company.add.php?company_id=".$company_infos[$i][company_id]."&info_type=basic'><img src='../images/".$admininfo["language"]."/bts_modify.gif' border=0 align='absmiddle'></a>";
				}
			}else{
				$mstring .="
					<a href=\"".$auth_update_msg."\"><img src='../images/".$admininfo["language"]."/btc_modify.gif' border=0 align='absmiddle'></a>
					";
			}
	
			if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"D")){
					if($company_infos[$i][com_type] !="A"){
				$mstring .="
					<a href=\"JavaScript:DeleteCompany('".$company_infos[$i][company_id]."')\"><img src='../images/".$admininfo["language"]."/btn_del.gif' border=0 align='absmiddle' title='삭제'></a> ";
					}
			}else{  
				
				$mstring .="
					<a href=\"".$auth_delete_msg."\"><img src='../images/".$admininfo["language"]."/btn_del.gif' border=0 align='absmiddle'  title='삭제'></a> ";
			}
			$mstring .="
					</td>
				</tr>";
	}
}else{
	$mstring .= "<tr height=50><td colspan=10 align=center style='padding-top:10px;'>등록된 입점업체가 없습니다.</td></tr>";
}

$mstring .="</table><br>";

$mstring .="<table width='100%' cellpadding=0 cellspacing=0 border='0' >";
	if( $admininfo[mall_use_multishop] && $admininfo[admin_level] == 9){
		$mstring .= "<tr hegiht=30><td colspan=8 align=right style='padding:10px 0px;'>".$str_page_bar."</td></tr>";
		
		if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"C")){
			if($admininfo["mall_type"] == "B" || $admininfo["mall_type"] == "F" || $admininfo["mall_type"] == "R"   || $admininfo["mall_type"] == "BW" ){
					$mstring .= "<tr hegiht=30><td colspan=8 align=right style='padding-top:10px;'><a href='company.add.php'><img src='../images/".$admininfo["language"]."/btn_basic_company.gif' border=0></a></td></tr>";
			}else{
				$mstring .= "<tr hegiht=30><td colspan=8 align=right style='padding-top:10px;'><a href='customer.add.php'><img src='../images/".$admininfo["language"]."/btn_basic_company.gif' border=0></a></td></tr>";
			}
		}
	}else{
	//	$mstring .= "<tr hegiht=40><td colspan=8 align=right style='padding-top:10px;'><a href='company.add.php'><img src='../image/b_companyadd.gif' border=0></a></td></tr>";
		$mstring .= "<tr hegiht=30><td colspan=8 align=right style='padding-top:10px 0px;'>".$str_page_bar."</td></tr>";
	}

$mstring .="</table><br>";

$Contents = $mstring;

$Script .= "
<script language='javascript' src='../include/DateSelect.js'></script>\n
<script language='javascript' src='../basic/company.add.js'></script>";
$Script .= "
<script language='javascript'>

function clearAll(frm){
	for(i=0;i < frm.code.length;i++){
			frm.code[i].checked = false;
	}
}

function checkAll(frm){
	for(i=0;i < frm.code.length;i++){
			frm.code[i].checked = true;
	}
}

function fixAll(frm){
	if (!frm.all_fix.checked){
		clearAll(frm);
		frm.all_fix.checked = false;
			
	}else{
		checkAll(frm);
		frm.all_fix.checked = true;
	}
	//input_check_num();
}

function ChangeRegistDate(frm){
	if(frm.regdate.checked){
		frm.sdate.disabled = false;
		frm.edate.disabled = false;
	}else{
		frm.sdate.disabled = true;
		frm.edate.disabled = true;
	}
}

function init(){
//alert(1);
	var frm = document.search_seller;
//	onLoad('$sDate','$eDate');";

if($regdate != "1"){ 
	$Script .= "
	frm.sdate.disabled = true;
	frm.edate.disabled = true;";
}

$Script .= "
}

";

$Script .= "
function deleteMemberInfo(act, code){
	if(confirm('해당회원 정보를 정말로 삭제하시겠습니까? \\n 삭제시 관련된 모든 정보가 삭제됩니다.')){
		window.frames['iframe_act'].location.href= 'member.act.php?act='+act+'&code='+code;
	}
}
</script>";

$P = new LayOut;
$P->addScript = "$Script";
$P->OnloadFunction = "";
$P->strLeftMenu = basic_menu();
$P->Navigation = "기초정보관리 > 본사관리 > $menu_name";
$P->title = "$menu_name";
$P->strContents = $Contents;
$P->PrintLayOut();


?>