<?
//include($_SERVER["DOCUMENT_ROOT"]."/admin/class/admin.page.class");
include("../class/layout.class");
//auth(8);

if(!$_GET["max"]){
	$max = 20; //페이지당 갯수
}else{
	$max = $_GET["max"];
	$_SESSION["max"];
}

	if ($page == '')
	{
		$start = 0;
		$page  = 1;
	}
	else
	{
		$start = ($page - 1) * $max;
	}


if($_GET["cid2"]){
    $_SESSION["product_order"]["cid2"] = $_GET["cid2"];
    $_SESSION["product_order"]["depth"] = $_GET["depth"];
    $cid2 = $_GET["cid2"];
    $depth = $_GET["depth"];
    if(empty($mode)){
        $mode = "search";
    }

}else{
    $cid2 = $_SESSION["product_order"]["cid"];
    $depth = $_SESSION["product_order"]["depth"];
}

if($_GET['mode'] =='search' &&  empty($cid2)){
    echo "<script>alert('카테고리를 선택해 주세요'); location.href='./product_order.php';</script>";
    exit;
}else if($_GET['mode'] =='search' && $_GET['depth'] < 0 ){

    echo "<script>alert('카테고리를 선택해 주세요');location.href='./product_order.php'</script>";
    exit;
}

$sortDepth = 'sortdepth' . $depth;
//$orderby = $sortDepth . ' asc, regdate';
$now_date = date('Y-m-d H:i:s');
$orderby = 'case 
                when p.disp != 1 then 100000 
                when p.state not in (1,4) then 100000
                when p.is_sell_date = 1 and ("'.$now_date.'" < sell_priod_sdate or "'.$now_date.'" > sell_priod_edate) then 100000
                when (CASE WHEN  p.state in ("1","4") THEN '
                    . '(CASE WHEN p.stock_use_yn IN ("Q","Y") THEN '
                    . "(SELECT IFNULL(sum(if((pod.option_stock < pod.option_sell_ing_cnt),0,(pod.option_stock - pod.option_sell_ing_cnt))),0)"
                    . " FROM " . TBL_SHOP_PRODUCT_OPTIONS . " as po, " . TBL_SHOP_PRODUCT_OPTIONS_DETAIL . " as pod WHERE po.opn_ix = pod.opn_ix AND po.option_use='1' AND pod.option_soldout!='1' AND po.pid=p.id"
                    . " AND (po.option_kind != 's2' OR (po.option_kind='s2' AND pod.set_group_seq!=0 )) )"
                    . ' ELSE 99999 END)'
                    . ' ELSE 0 END) < 1 then 100000 
            else '.$sortDepth . ' end asc, regdate';
$ordertype = "desc";


$notRelationBasic = true;

include("../product/product_query.php");


if($mode == 'excel'){

//error_reporting(E_ALL);
    include '../include/phpexcel/Classes/PHPExcel.php';
    PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

    date_default_timezone_set('Asia/Seoul');

    $memberXL = new PHPExcel();

    // 속성 정의
    $memberXL->getProperties()->setCreator("포비즈 코리아")
        ->setLastModifiedBy("hanmipost.com")
        ->setTitle("Application List")
        ->setSubject("Application List")
        ->setDescription("generated by forbiz korea")
        ->setKeywords("hanmipost")
        ->setCategory("hanmipost");

    // 데이터 등록
    $memberXL->getActiveSheet(0)->setCellValue('A' . 1, "번호");
    $memberXL->getActiveSheet(0)->setCellValue('B' . 1, "전시구분");
    $memberXL->getActiveSheet(0)->setCellValue('C' . 1, "상품시스템코드");
    $memberXL->getActiveSheet(0)->setCellValue('D' . 1, "상품명");
    $memberXL->getActiveSheet(0)->setCellValue('E' . 1, "색상");
    $memberXL->getActiveSheet(0)->setCellValue('F' . 1, "카테고리");
    $memberXL->getActiveSheet(0)->setCellValue('G' . 1, "기본카테고리여부");
    $memberXL->getActiveSheet(0)->setCellValue('H' . 1, "상품상태");
    $memberXL->getActiveSheet(0)->setCellValue('I' . 1, "재고상태");
    $memberXL->getActiveSheet(0)->setCellValue('J' . 1, "판매가");
    $memberXL->getActiveSheet(0)->setCellValue('K' . 1, "재고수");
    $memberXL->getActiveSheet(0)->setCellValue('L' . 1, "주문수");
    $memberXL->getActiveSheet(0)->setCellValue('M' . 1, "노출순서");
	$memberXL->getActiveSheet(0)->setCellValue('N' . 1, "Sno");
	$memberXL->getActiveSheet(0)->setCellValue('O' . 1, "Depth");


    //------ row 1 data ------
    for($i=0, $j=0;$i < $slave_db->total;$i++,$j++){
        $excel_datas = $slave_db->fetch($i);


        if($excel_datas[state] == 1){
            $state_str = "판매중";
        }else if($excel_datas[state] == 2){
            $state_str = "판매중지";
        }else if($excel_datas[state] == 4){
            $state_str = "판매예정";
        }else if($excel_datas[state] == 6){
            $state_str = "등록신청중";
        }else if($excel_datas[state] == 7){
            $state_str = "수정신청중";
        }else if($excel_datas[state] == 0){
            $state_str = "일시품절중";
        }else if($excel_datas[state] == 5){
            $state_str = "판매종료";
        }

        if($excel_datas['basic'] == '1'){
            $is_basic = "(기본)";
        }else{
            $is_basic = "";
        }

        $is_stock = "";
        if($excel_datas[disp] != '1' ) {
            $is_stock = "[미노출]";
        }
        if($excel_datas[state] != '1'){
            $is_stock = "[미판매]";
        }
        if(($excel_datas[stock] - $excel_datas[sell_ing_cnt]) < 1){
            $is_stock = "[품절]";
        }

        if($excel_datas['is_sell_date'] == '1'){
            if($now_date < $excel_datas['sell_priod_sdate'] || $now_date > $excel_datas['sell_priod_edate']){
                $is_stock = "[판매기간만료]";
            }
        }

        $sql = "SELECT
                    IF (
                        SUM(IFNULL(pod.option_stock, 0)) > SUM(
                            IFNULL(pod.option_sell_ing_cnt, 0)
                        ),
                        SUM(IFNULL(pod.option_stock, 0)) - SUM(
                            IFNULL(pod.option_sell_ing_cnt, 0)
                        ),
                        0
                    ) as stock_ckeck
                    FROM
                        shop_product_options AS po,
                        shop_product_options_detail AS pod
                    WHERE
                        po.opn_ix = pod.opn_ix
                    AND po.option_use = '1'
                    AND pod.option_soldout != '1'
                    AND po.pid = '".$excel_datas['id']."'
                    AND (
                        po.option_kind != 's2'
                        OR (
                            po.option_kind = 's2'
                            AND pod.set_group_seq != 0
                        )
                    )
        ";
        $db->query($sql);
        $db->fetch();
        $stock_ckeck = $db->dt['stock_ckeck'];
        if($stock_ckeck < 1){
            $is_stock = "[옵션품절]";
        }

        $display_area = "".GetDisplayDivision($excel_datas['mall_ix'], "text")."";

        $vieworder = $excel_datas[$sortDepth];



        $memberXL->getActiveSheet(0)->setCellValue('A' .($i + 2), ($i+1));
        $memberXL->getActiveSheet(0)->setCellValue('B' .($i + 2), $display_area);
        $memberXL->getActiveSheet(0)->setCellValue('C' .($i + 2), $excel_datas['id']);
        $memberXL->getActiveSheet(0)->setCellValue('D' .($i + 2), $excel_datas['pname']);
        $memberXL->getActiveSheet(0)->setCellValue('E' .($i + 2), $excel_datas['add_info']);
        $memberXL->getActiveSheet(0)->setCellValue('F' .($i + 2), getCategoryPathByAdmin($excel_datas[cid], 4));
        $memberXL->getActiveSheet(0)->setCellValue('G' .($i + 2), $is_basic);
        $memberXL->getActiveSheet(0)->setCellValue('H' .($i + 2), $state_str);
        $memberXL->getActiveSheet(0)->setCellValue('I' .($i + 2), $is_stock);
        $memberXL->getActiveSheet(0)->setCellValue('J' .($i + 2), $excel_datas['sellprice']);
        $memberXL->getActiveSheet(0)->setCellValue('K' .($i + 2), $excel_datas['stock']);
        $memberXL->getActiveSheet(0)->setCellValue('L' .($i + 2), $excel_datas['order_cnt']);
        $memberXL->getActiveSheet(0)->setCellValue('M' .($i + 2), $vieworder);
		$memberXL->getActiveSheet(0)->setCellValue('N' .($i + 2), $excel_datas['rid']);
		$memberXL->getActiveSheet(0)->setCellValue('O' .($i + 2), $sortDepth);


    }


    // 시트이름등록
    $memberXL->getActiveSheet()->setTitle('분류별목록');

    // 첫번째 시트 선택
    $memberXL->setActiveSheetIndex(0);
    $memberXL->getActiveSheet()->getColumnDimension('A')->setWidth(5);
    $memberXL->getActiveSheet()->getColumnDimension('B')->setWidth(15);
    $memberXL->getActiveSheet()->getColumnDimension('C')->setWidth(15);
    $memberXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('G')->setWidth(10);
    $memberXL->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
    $memberXL->getActiveSheet()->getColumnDimension('J')->setWidth(5);
    $memberXL->getActiveSheet()->getColumnDimension('K')->setWidth(15);
    $memberXL->getActiveSheet()->getColumnDimension('L')->setWidth(15);
    $memberXL->getActiveSheet()->getColumnDimension('M')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('N')->setAutoSize(true);
	$memberXL->getActiveSheet()->getColumnDimension('O')->setWidth(5);

    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="product_order"'.date('Ymd').'".xls"');
    header('Cache-Control: max-age=0');


    $objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
    $objWriter->save('php://output');

    exit;

}

if($_SERVER["QUERY_STRING"] == "nset=$nset&page=$page"){
    $query_string = str_replace("nset=$nset&page=$page","",$_SERVER["QUERY_STRING"]) ;
}else{
    $query_string = str_replace("nset=$nset&page=$page&","","&".$_SERVER["QUERY_STRING"]) ;
}
//echo $query_string;
$str_page_bar = page_bar($total, $page, $max, str_replace('&view=innerview','',$query_string),"");
//$str_page_bar = page_bar($ptotal, $page, $max, "&cid2=$cid2&&depth=$depth&company_id=$company_id&max=$max");


$Contents =	"
			<table cellpadding=0 cellspacing=0 width='100%'>
			<tr>
			<td valign=top style='padding-top:33px;' >";

$Contents .=	"
			</td>
			<td valign=top style='padding:0px;padding-top:0px;' id='product_orderarea'>";

$innerview =	"
			<form id='search_form' name='search_form' method='get' >
			<input type='hidden' name='mode' value='search'>
			<input type='hidden' name='cid2' value='$cid2'>
			<input type='hidden' name='depth' value='$depth'>
			<input type='hidden' name='max' value='$max'>
			<table cellpadding=0 cellspacing=0 border=0 width=100%>
			<tr>
				<td colspan=2>
					<table cellpadding=0 cellspacing=0 border=0 width=100% align='center' class='input_table_box'>
						<col width='20%' />
						<col width='30%' />
						<col width='20%' />
						<col width='30%' />";
					if($_SESSION["admin_config"][front_multiview] == "Y"){
					$innerview .= "
						<tr>
							<td class='search_box_title' > 프론트 전시 구분</td>
							<td class='search_box_item' colspan=3>".GetDisplayDivision($mall_ix, "select")." </td>
						</tr>";
					}
					$innerview .= "
						<tr>
							<td class='search_box_title' >판매상태</td>
							<td class='search_box_item' colspan='3'>
								<table cellpadding=0 cellspacing=0 border='0'  align='left'>";

	$innerview .=	"
								<col width=70>
								<col width=80>
								<col width=90>";

	$innerview .=	"		<col width=80> 
								<col width=90>
								<col width=110>
								
								
								<tr>";

	$innerview .=	"
									<td>
									<input type='checkbox' name='state[]' id='search_state_1' value='1' title='판매중' ".(is_array($state)?in_array('1',$state)?'checked':'':'')."/>
									<label for='search_state_1'> 판매중 </label> 
									</td>
									<td>
									<input type='checkbox' name='state[]' id='search_state_0' value='0' title='일시품절' ".(is_array($state)?in_array('0',$state)?'checked':'':'')."/>
									<label for='search_state_0'> 일시품절 </label> 
									</td>
									<td>
									<input type='checkbox' name='state[]' id='search_state_2' value='2' title='판매중지' ".(is_array($state)?in_array('2',$state)?'checked':'':'')."/>
									<label for='search_state_2'> 판매중지</label>
									</td>
									<td>
									<input type='checkbox' name='state[]' id='search_state_8' value='8' title='승인거부' ".(is_array($state)?in_array('8',$state)?'checked':'':'')."/> 
									<label for='search_state_8'> 승인거부 </label>
									</td>";

		if($admininfo[admin_level] == '9'){


	$innerview .=	"			<td>
									<input type='checkbox' name='state[]' id='search_state_6' value='6' title='승인대기' ".(is_array($state)?in_array('6',$state)?'checked':'':'')."/> 
									<label for='search_state_6'> 승인대기 </label>
									</td>

									<td>
									<input type='checkbox' name='state[]' id='search_state_7' value='7' title='수정대기상품' ".(is_array($state)?in_array('7',$state)?'checked':'':'')."/> 
									<label for='search_state_7'> 수정대기상품 </label>
									</td>";


	$innerview .=	"	
									
									";

	$innerview .=	"	
									<td>
									<input type='checkbox' name='state[]' id='search_state_9' value='9' title='판매금지' ".(is_array($state)?in_array('9',$state)?'checked':'':'')."/> 
									<label for='search_state_9'> 판매금지 </label>
									</td>
									";

		}
	$innerview .=	"
								</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td class='search_box_title'>노출여부</td>
							<td class='search_box_item'>
								<table cellpadding=0 cellspacing=0 border='0'  align='left'>
								<col width=60>
								<col width=100>
								<tr>
									<td>
										<input type='checkbox' name='disp[]' id='disp_1' value='1' title='노출' ".(is_array($disp)?in_array('1',$disp)?'checked':'':'')."/><label for='disp_1'> 노출 </label> 
									</td>
									<td>
										<input type='checkbox' name='disp[]' id='disp_0' value='0' title='미노출' ".(is_array($disp)?in_array('0',$disp)?'checked':'':'')."/><label for='disp_0'> 미노출 </label> 
									</td>
									<td></td>
								</tr>
								</table>
							</td>
							<td class='search_box_title'>브랜드</td>
							<td class='search_box_item'>
							".BrandListSelect($b_ix, $cid)."
							</td>
						</tr>
						</table>
				</td>
			</tr>
			<tr>
				<td colspan=2 align=center style='padding:20px 0px;'><input type=image src='../images/".$admininfo["language"]."/bt_search.gif' border=0 align=absmiddle><!--btn_inquiry.gif--></td>
			</tr>
			</table>
			</form>
			
			
			";


$innerview .= "
			<table width='100%' cellpadding=0 cellspacing=0 border=0>
			<col width=10%>
			<col width=60%>
			<col width=15%>
			<col width=15%>
			<tr>
			    <td align='left' colspan=4 > ".GetTitleNavigation("분류별 상품배열", "프로모션/전시 > 분류별 상품배열")."</td>
			</tr>
			<tr>
			    <td align='left' colspan=4 id='array_info'> </td>
			</tr>
			<tr>
			    <td align='left' colspan=4 id='array_info2'> </td>
			</tr>";

/* 임시 주석처리 20131001
$innerview .= "
			<tr><td colspan=4 align=left style='padding-bottom:5px;'>".colorCirCleBox("#efefef","100%","<div style='padding:5px 5px 5px 15px;'><b> 분류별 전시설정</b></div>")."</td></tr>
			<tr>
			    <td align='left' colspan=4>
					<table border='0' cellpadding=0 cellspacing=0 width='100%' class='search_table_box' style='margin-bottom:10px;'>
					  <col width='20%'>
					  <col width='30%'>
					  <col width='20%'>
					  <col width='30%'>
					 <tr >
						  <td class='input_box_title'> <b>기본정렬 방식</b></td>
						  <td class='input_box_item' style='padding:5px 10px;' colspan=3 >
						  <input type='radio' class='textbox' name='order_type' id='order_type' value='regdate' style='border:0px;' ".($gdb->dt[order_type] == "regdate" ? "checked":"")."><label for='order_type_regdate'>최근 등록순</label>
						  <input type='radio' class='textbox' name='order_type' id='order_type' value='order_cnt' style='border:0px;' ".($gdb->dt[order_type] == "order_cnt" ? "checked":"")."><label for='order_type_order_cnt'>구매수순</label>
						  <input type='radio' class='textbox' name='order_type' id='order_type' value='view_cnt' style='border:0px;' ".($gdb->dt[order_type] == "view_cnt" ? "checked":"")."><label for='order_type_order_cnt'>클릭수순</label>
						  <input type='radio' class='textbox' name='order_type' id='order_type' value='sellprice' style='border:0px;' ".($gdb->dt[order_type] == "sellprice" ? "checked":"")."><label for='order_type_order_cnt'>최저가순</label>
						  <input type='radio' class='textbox' name='order_type' id='order_type' value='favorite_cnt' style='border:0px;' ".($gdb->dt[order_type] == "favorite_cnt" ? "checked":"")."><label for='order_type_order_cnt'>관심상품순</label>
						  </td>
						</tr>
					 <tr >
						  <td class='input_box_title'> <b>전시타입</b></td>
						  <td class='input_box_item' style='padding:5px 10px;' colspan=3>
						  <div style='float:left;text-align:center;width:130px;padding-top:10px;'>
							<img src='../images/".$admininfo["language"]."/g_5.gif' align=center onclick=\"document.getElementById('display_type_".($i+1)."_0').checked = true;\"><br>
							<input type='radio' class='textbox' name='display_type[".($i+1)."]' id='display_type_".($i+1)."_0' value='0' style='border:0px;' ".($gdb->dt[display_type] == "0" ? "checked":"")."><label for='display_type_".($i+1)."_0'>기본형(5EA 배열)</label>
						  </div>
						  <div style='float:left;text-align:center;width:130px;padding-top:10px;'>
							<img src='../images/".$admininfo["language"]."/g_4.gif' align=center onclick=\"document.getElementById('display_type_".($i+1)."_1').checked = true;\"><br>
							<input type='radio' class='textbox' name='display_type[".($i+1)."]' id='display_type_".($i+1)."_1' value='1' style='border:0px;' ".($gdb->dt[display_type] == "1" ? "checked":"")."><label for='display_type_".($i+1)."_1'>기본형(4EA 배열)</label>
						  </div>
						  <div style='float:left;text-align:center;width:130px;padding-top:10px;'>
							<img src='../images/".$admininfo["language"]."/g_3.gif' align=center onclick=\"document.getElementById('display_type_".($i+1)."_2').checked = true;\"><br>
							<input type='radio' class='textbox' name='display_type[".($i+1)."]' id='display_type_".($i+1)."_2' value='2' style='border:0px;' ".($gdb->dt[display_type] == "2" ? "checked":"")."><label for='display_type_".($i+1)."_2'>기본형2(3EA 배열)</label>
						  </div>
						  <div style='float:left;text-align:center;width:150px;padding-top:10px;'>
							<img src='../images/".$admininfo["language"]."/slide_4.gif' align=center onclick=\"document.getElementById('display_type_".($i+1)."_3').checked = true;\"><br>
							<input type='radio' class='textbox' name='display_type[".($i+1)."]' id='display_type_".($i+1)."_3' value='3' style='border:0px;' ".($gdb->dt[display_type] == "3" ? "checked":"")."><label for='display_type_".($i+1)."_3' class='small' nowrap>슬라이드형(4EA 배열)</label>
						  </div>
						  <div style='float:left;text-align:center;width:135px;padding-top:10px;'>
							<img src='../images/".$admininfo["language"]."/g_16.gif' align=center onclick=\"document.getElementById('display_type_".($i+1)."_4').checked = true;\"><br>
							<input type='radio' class='textbox' name='display_type[".($i+1)."]' id='display_type_".($i+1)."_4' value='4' style='border:0px;' ".($gdb->dt[display_type] == "4" ? "checked":"")."><label for='display_type_".($i+1)."_4'>기본형4(1/*EA 배열)</label>
						  </div>
						  <div style='float:left;text-align:center;width:135px;padding-top:10px;'>
							<img src='../images/".$admininfo["language"]."/g_17.gif' align=center onclick=\"document.getElementById('display_type_".($i+1)."_5').checked = true;\"><br>
						  <input type='radio' class='textbox' name='display_type[".($i+1)."]' id='display_type_".($i+1)."_5' value='5' style='border:0px;' ".($gdb->dt[display_type] == "5" ? "checked":"")."><label for='display_type_".($i+1)."_5'>기본형(4EA 배열)</label>
						  </div>
						  <div style='float:left;text-align:center;width:135px;padding-top:10px;'>
						  <img src='../images/".$admininfo["language"]."/g_24.gif' align=center onclick=\"document.getElementById('display_type_".($i+1)."_6').checked = true;\"><br>
						  <input type='radio' class='textbox' name='display_type[".($i+1)."]' id='display_type_".($i+1)."_6' value='6' style='border:0px;' ".($gdb->dt[display_type] == "6" ? "checked":"")."><label for='display_type_".($i+1)."_6'>기본형(2/4EA 배열)</label>
						  </div>
						  ";

//$Contents .= SelectFileList2($DOCUMENT_ROOT.$admin_config[mall_data_root]."/module/main_templet/")."

$innerview .= "
						  </td>
						</tr>
					  <tr height=28>
						<td class='search_box_title' nowrap> <b>분류 메인 전시 제목</b></td>
						<td class='search_box_item' colspan=3><input class='textbox' type='text' name='cmg_title' value='".$slave_db->dt[cmg_title]."' validation=true title='전시 제목' maxlength='50' style='width:98%'></td>
					  </tr>
					 
						<tr height=27>
							<td class='search_box_title' nowrap> <b>상품목록갯수</b></td>
							<td class='search_box_item' colspan=3>
							한페이지에 <input class='textbox number' type='text' name='goods_max' size=5 value='".$slave_db->dt[goods_max]."' maxlength='50' > 개의 상품을 노출합니다
							<div class=small style='display:inline;'>입력되지 않으면 기본 상품 노출갯수 15개로 노출됩니다.</div>
							</td>
						</tr>
						<tr height=27>
							<td class='search_box_title' nowrap> <b>상품이미지 사이즈</b></td>
							<td class='search_box_item' colspan=3 style='padding:5px;'>
								가로 : <input class='textbox number' type='text' name='image_width' size=5 value='".$image_width."' maxlength='50' >
								세로 : <input class='textbox number' type='text' name='image_height' size=5 value='".$image_height."' maxlength='50' ><br>
								<div class=small style='padding:4px 0px '>
								정보가 입력되지 않으면 기본 이미지 사이즈가 노출됩니다. <br>
								한쪽 사이즈만 입력되면 입력되지 않은 부분은 비율적으로 표시되게 됩니다.<br>


								</div>
								</td>
						</tr>
					</table>
				</td>
			</tr>";
*/

//if(strpos($_SESSION['admininfo']['admin_id'],'forbiz') !== false ) {
    $innerview .= "
            <tr>
				<td colspan='2' align='left'> 
					<form name='excelForm' id='excelForm' method='post' action='/admin/product/order.act.php' enctype='multipart/form-data' target='act'>
						<input type='hidden' name='mode' value='excelUpd'>
						<input type='hidden' name='cname' value='".$cname."' />
						<input type='hidden' name='cid' value='".$cid2."' />
						<input type='hidden' name='depth' value='".$depth."' />
						<input type='hidden' name='pid' value='".$pid."' />
						<input type='hidden' name='company_id' value='".$company_id."' />
						<input type='hidden' name='max' value='".$max."' />
						<input type='file' name='product_file' id='product_file' size=70 class='textbox' style='width:300px'>
					</form>
						&nbsp;<img src='../images/".$admininfo["language"]."/bts_modify.gif' border=0 align=absmiddle style='cursor:pointer' onclick='fileUpd();'>
				</td>
				<td colspan='2' align='right'> 
			        <a href='?mode=excel&".str_replace($mode, "excel",$_SERVER["QUERY_STRING"])."'><img src='../images/" . $admininfo["language"] . "/btn_excel_save.gif' border=0></a>
			    </td>
			</tr>";
//}
$innerview .= "
			<tr><td colspan=4 align=left style='padding-bottom:5px;'>".colorCirCleBox("#efefef","100%","<div style='padding:5px 5px 5px 15px;'><b> 선택된 카테고리</b> :&nbsp;&nbsp;&nbsp;<b id='select_category_path1'>".($cid2 == "" ? "전체":getCategoryPathByAdmin($cid2, $depth))."</b></div>")."</td></tr>			
			<tr height=30>
				<td colspan=1>
					<table cellpadding=0 cellspacing=0>
						<tr>";
						if($admininfo[mall_type] == "B"){
$innerview .= "<td style='padding-right:3px;'>".CompanyList($company_id, "","max",$max)."</td>";
						}

/*
	$type_param="";
	if(is_array($state)){
		foreach($state as $val){
			$type_param .= "&state%5B%5D=".$val;
		}
	}else{
		if(!empty($state)){
			$type_param .= "&state%5B%5D=".$state;
		}
	}
	
	if(is_array($disp)){
		foreach($disp as $val){
			$type_param .= "&disp%5B%5D=".$val;
		}
	}else{
		if(!empty($disp)){
			$type_param .= "&disp%5B%5D=".$disp;
		}
	}
*/
//document.location.href='".$HTTP_URL."?cid2=$cid2&depth=$depth&company_id=$company_id&b_ix=$b_ix&mall_ix=$mall_ix".$type_param."&max='+this.value
$innerview .= "<td ><select name=max style=\"font-size:12px;height: 20px; width: 80px;\" align=absmiddle onchange=\"document.search_form.max.value=this.value;document.search_form.submit();\"><!--view=innerview& behavior: url('../js/selectbox.htc'); -->
							<option value='10' ".CompareReturnValue(10,$max).">10</option>
							<option value='20' ".CompareReturnValue(20,$max).">20</option>
							<option value='30' ".CompareReturnValue(30,$max).">30</option>
							<option value='40' ".CompareReturnValue(40,$max).">40</option>
							<option value='50' ".CompareReturnValue(50,$max).">50</option>
							<option value='100' ".CompareReturnValue(100,$max).">100</option>
							<option value='200' ".CompareReturnValue(200,$max).">200</option>
							<option value='300' ".CompareReturnValue(300,$max).">300</option>
							<option value='400' ".CompareReturnValue(400,$max).">400</option>
							<option value='500' ".CompareReturnValue(500,$max).">500</option>
							<option value='600' ".CompareReturnValue(600,$max).">600</option>
							<option value='1000' ".CompareReturnValue(1000,$max).">1000</option>
							</select></td>
						<td nowrap> &nbsp;씩 보기</td>
						</tr>
					</table>
				</td>
				<td width=150></td>
				<td colspan=2 align=right nowrap>".$str_page_bar."</td>
             
			</tr>
			</table>
			<form name=vieworderform method=post action='/admin/product/order.act.php' target='act'>
			
			<input type='hidden' name='cname' value='".$cname."' />
			<input type='hidden' name='cid' value='".$cid2."' />
			<input type='hidden' name='depth' value='".$depth."' />
			<input type='hidden' name='pid' value='".$pid."' />
			<input type='hidden' name='company_id' value='".$company_id."' />
			<input type='hidden' name='max' value='".$max."' />
			<table width='100%' cellpadding=2 cellspacing=0 border=0 class='list_table_box'><!--onselectstart='return false;' ondragstart='return false;'-->
			<col width=5%>
			<col width=*>
			<col width=10%>
			<col width=10%>
			<col width=10%>
			<col width=7%>
			<col width=10%>
			<tr height=25 align=center>
				<td  class=s_td>이미지</td>
				<td class=m_td>제품명</td>
				<td  class=m_td>상태</td>
				<td  class=m_td>판매가</td>
				<td  class=m_td>재고수</td>
				<td  class=m_td>주문수</td>
				<td  class=e_td>노출순서</td>
			</tr>
			</table>

			<table cellpadding=2 cellspacing=0 width=100% onselectstart='return false;' ondragstart='return false;' id='product_order_table' class='list_table_box'><!--frame=hsides rules=rows-->
			<col width=5%>
			<col width=*>
			<col width=10%>
			<col width=10%>
			<col width=10%>
			<col width=7%>
			<col width=10%>
			<tbody>
			";


if($slave_db->total == 0){
	$innerview = $innerview."<tr bgcolor=#ffffff height=50><td colspan=8 align=center> 등록된 제품이 없습니다.</td></tr>";
}else{
	$total = $slave_db->total;
	for ($i = 0; $i < $slave_db->total; $i++)
	{

		$slave_db->fetch($i);

		if($slave_db->dt[state] == 1){
			$state_str = "판매중";
		}else if($slave_db->dt[state] == 2){
            $state_str = "판매중지";
        }else if($slave_db->dt[state] == 4){
            $state_str = "판매예정";
        }else if($slave_db->dt[state] == 6){
            $state_str = "등록신청중";
        }else if($slave_db->dt[state] == 7){
			$state_str = "수정신청중";
		}else if($slave_db->dt[state] == 0){
			$state_str = "일시품절중";
		}else if($slave_db->dt[state] == 5){
            $state_str = "판매종료";
        }

        if($slave_db->dt['basic'] == '1'){
		    $is_basic = "(기본)";
        }else{
            $is_basic = "";
        }

        $is_stock = "";
        $soldOutBool = false;
        if($slave_db->dt[disp] != '1' ) {
            $is_stock = "[미노출]";
            $soldOutBool = true;
        }
        if($slave_db->dt[state] != '1' && $slave_db->dt[state] != '4'){
            $is_stock = "[미판매]".$slave_db->dt[state];
            $soldOutBool = true;
        }
        if(($slave_db->dt[stock] - $slave_db->dt[sell_ing_cnt]) < 1){
            $is_stock = "[품절]";
            $soldOutBool = true;
        }

        if($slave_db->dt['is_sell_date'] == '1'){
            if($now_date < $slave_db->dt['sell_priod_sdate'] || $now_date > $slave_db->dt['sell_priod_edate']){
                $is_stock = "[판매기간만료]";
                $soldOutBool = true;
            }
        }

        $sql = "SELECT
                    IF (
                        SUM(IFNULL(pod.option_stock, 0)) > SUM(
                            IFNULL(pod.option_sell_ing_cnt, 0)
                        ),
                        SUM(IFNULL(pod.option_stock, 0)) - SUM(
                            IFNULL(pod.option_sell_ing_cnt, 0)
                        ),
                        0
                    ) as stock_ckeck
                    FROM
                        shop_product_options AS po,
                        shop_product_options_detail AS pod
                    WHERE
                        po.opn_ix = pod.opn_ix
                    AND po.option_use = '1'
                    AND pod.option_soldout != '1'
                    AND po.pid = '".$slave_db->dt['id']."'
                    AND (
                        po.option_kind != 's2'
                        OR (
                            po.option_kind = 's2'
                            AND pod.set_group_seq != 0
                        )
                    )
        ";
        $db->query($sql);
        $db->fetch();
        $stock_ckeck = $db->dt['stock_ckeck'];
        if($stock_ckeck < 1){
            $is_stock = "[옵션품절]";
            $soldOutBool = true;
        }

        $display_area = "(".GetDisplayDivision($slave_db->dt['mall_ix'], "text").")";

        $border_line = "";
        if (($i+1)%4 == 0 ){
            $border_line = " border-bottom: 1px solid red";
        }

        $addQaDir = "";
        if($admin_config['mall_domain'] == "0925admintest.barrelmade.co.kr"){
            $addQaDir = "/QA";
        }

		/*
		if(file_exists($_SERVER["DOCUMENT_ROOT"]."".PrintImage($admin_config[mall_data_root]."/images/product", $slave_db->dt[id], "s", $slave_db->dt)) || $image_hosting_type=='ftp') {
			$img_str = PrintImage($admin_config[mall_data_root]."/images/product", $slave_db->dt[id], "s", $slave_db->dt);
		}else{
			$img_str = "../image/no_img.gif";
		}
		*/

		//$img_str = PrintImage($admin_config[mall_data_root]."/images/product", $slave_db->dt[id], "s", $slave_db->dt);
        $img_str = PrintImage($admin_config[mall_data_root]."/images/addimgNew".$addQaDir, $slave_db->dt[id], "slist", $slave_db->dt);

        $vieworder = $slave_db->dt[$sortDepth];

        if($soldOutBool === true ){
            $vieworder = 99999;
            if($vieworder < 99999) {
                $sql = "update shop_product_relation set $sortDepth = '99999' where rid = '" . $slave_db->dt['rid'] . "' ";
                $db->query($sql);
            }
        }

        $add_info = "";
        if($slave_db->dt['add_info']){
            $add_info = "[".$slave_db->dt['add_info']."]";
        }

	$innerview .= "<tr height=40 align=center style='cursor:pointer;' onclick=\"spoit(this)\" id='".$slave_db->dt[id]."'>
					<td class='list_box_td list_bg_gray' style='".$border_line."'><img src='".$img_str."' width=30 height=30 align=absmiddle style='border:1px solid #efefef'></td>
					<td class='list_box_td point' style='padding:5px;line-height:130%;text-align:left;".$border_line."' align=left>
					<b style='color:gray' class=small>".$is_basic."".getCategoryPathByAdmin($slave_db->dt[cid], 4)."</b>
					".($slave_db->dt["new"] == 1 ? "<img src='/icon/icon_new.gif' border=0 align=absmiddle>":"")."
					".($slave_db->dt["hot"] == 1 ? "<img src='/icon/icon_hot.gif' border=0 align=absmiddle>":"")."
					".($slave_db->dt["event"] == 1 ? "<img src='/icon/icon_event.gif' border=0 align=absmiddle>":"")."<br>
					<b>".$display_area."".$is_stock."[".$slave_db->dt[id]."] ".$slave_db->dt[pname]."</b> ".$add_info."<br>
					</td>
					<td class='list_box_td list_bg_gray' style='".$border_line."'>
					".$state_str."
					</td>
					<td class='list_box_td' style='".$border_line."'>".$currency_display[$admin_config["currency_unit"]]["front"]." ".number_format($slave_db->dt[sellprice],0)." ".$currency_display[$admin_config["currency_unit"]]["back"]."</td>
					<td class='list_box_td list_bg_gray' align=center style='padding-right:5px;".$border_line."'>".number_format($slave_db->dt[stock],0)." </td>
					<td class='list_box_td' style='".$border_line."'>".number_format($slave_db->dt[order_cnt],0)." </td>
					<td class='list_box_td list_bg_gray' style='line-height:130%;".$border_line."' class=small nowrap><!--".$slave_db->dt[vieworder]."--><!--".$slave_db->dt[regdate]."<br>".$slave_db->dt[company_name]."-->
					<input type=hidden name=sno[] size=2 value='".$slave_db->dt['rid']."'>
					<input type=text class-'textbox' name=sort[".$i."] size=8 style='text-align:center;' value='".$vieworder."'>
					</td>
				</tr>";

	}
}
	$innerview .= "
				</tbody>
				</table>
				<table width='100%'>";
                if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"U")){
                $innerview .= "
					<tr height=50 bgcolor=#ffffff><td colspan=8 align=center><input type=image src='../images/".$admininfo["language"]."/b_save.gif' border=0 align=absmiddle></td></tr>
                    ";
                }
				$innerview .= "	
                    <tr height=30><td></td><td align=right nowrap>".$str_page_bar."</td></tr>
				</table></form>
				<!--form name=vieworderform method=post action='./order.act.php' target='act'>
				<input type='hidden' name='vieworder'>
				<input type='hidden' name='_vieworder'>
				<input type='hidden' name='pid'>
				<input type='hidden' name='cid2' value='$cid2'>
				<input type='hidden' name='depth' value='$depth'>
				<input type='hidden' name='max' value='$max'>
				<input type='hidden' name='page' value='$page'>
				<input type='hidden' name='nset' value='$nset'>
				</form-->
				";

$Contents = $Contents.$innerview ."


			</td>
			</tr>

		</table>";
/*
$help_text = "
	<table>
		<tr>
			<td style='line-height:150%' class=small>
			<img src='../image/icon_list.gif' align=absmiddle>먼저 상품배열을 변경하시고자 하는 카테고리를 선택해주세요<br>
			<img src='../image/icon_list.gif' align=absmiddle>상품배열을 변경하시고자 하는 제품을 클릭한후 <b>↑ ↓ 방향키</b>를 눌러서 이동하시후 <b>저장</b>버튼을 누르시면 저장됩니다<br>
			</td>
		</tr>
	</table>
	";*/
	$help_text = getTransDiscription(md5($_SERVER["PHP_SELF"]),'A');
	/*
$help_text = "
<table cellpadding=0 cellspacing=0 class='small' >
	<col width=8>
	<col width=*>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >먼저 상품배열을 변경하시고자 하는 카테고리를 선택해주세요</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >상품배열을 변경하시고자 하는 제품을 선택 합니다. ctrl 키를 누른후 선택하시면 복수개의 상품을 선택하여 한꺼번에 변경이 가능합니다. 연속된 복수개의 상품의 순서 변경을 원하실 경우 시작 상품 선택후 shift 키와 같이 선택하시면 복수개의 상품을 선택 하실수 있습니다.</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >선택된 상품들의 순서를 변경하기 위해서는  <b>↑ ↓ 방향키</b>를 눌르거나 아래(↓) | 위(↑) | 아래로5칸 | 위로5칸 | 아래로10칸 | 위로10칸 | 페이지 마지막 | 페이지 맨위  버튼을 클릭해서 순서를 변경 합니다. </td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >변경된 상품의 노출 순서를 저장하기 위해서는 아래 <b>저장</b>버튼을 누르시면 저장됩니다</td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td class='small' >한페이지에 더 많은 상품을 보기 위해서는 상단에 셀렉트 박스의 숫자를 증가 시키면 많은 상품을 보실수 있습니다</td></tr>
</table>
";*/
$help_text = getTransDiscription(md5($_SERVER["PHP_SELF"]),'B');


$Contents .= HelpBox("분류별 상품배열", $help_text, 171);

$category_str ="<div class=box id=img3  style='width:195px;height:350px;overflow:auto;'>".Category()."</div>";


if($view == "innerview"){
	echo "<html><meta http-equiv='Content-Type' content='text/html; charset=euc-kr'><body>$innerview</body></html>";
	$inner_category_path = getCategoryPathByAdmin($cid2, $depth);
	echo "
	<Script>
	parent.document.getElementById('product_orderarea').innerHTML = document.body.innerHTML;
	//parent.document.vieworderform.max.value='$max';
	parent.document.getElementById('select_category_path1').innerHTML='".$inner_category_path."';
	parent.unblockLoadingBox();
	</Script>";
}else{
	$P = new LayOut();

	if($page_type=="seller"){
		$P->strLeftMenu = seller_menu("/admin",$category_str);
		$P->Navigation = "셀러관리 > 프로모션관리 > 상품전시관리(미니샵)";
		$P->title = "상품전시관리(미니샵)";
	}else{
		$P->strLeftMenu = display_menu("/admin",$category_str);
		$P->Navigation = "프로모션/전시 > 분류 전시관리 > 분류별 상품배열";
		$P->title = "분류별 상품배열";
	}

	$P->addScript = "<script Language='JavaScript' src='../include/zoom.js'></script><script Language='JavaScript' src='../display/product_order.js'></script>";
	$P->strContents = $Contents;
	if ($category_load == "yes"){
		$P->OnLoadFunction = "zoomBox(event,this,200,400,0,90,img3)";
	}
	$P->BodyFunctionAdd = "ondragstart='return false' onselectstart='return false'";
	$P->PrintLayOut();
}



function Category()
{
	$mdb = new Database;

	global $id,$company_id,$max;

$m_string = "
<script language='JavaScript' src='../include/manager.js'></script>
<script language='JavaScript' src='../include/Tree.js'></script>
<script>

/*	 Create Tree		*/
	var tree = new Tree();
	tree.color = 'black';
	tree.bgColor = 'white';
	tree.borderWidth = 0;

	function fileUpd(){
		if(!$('#product_file').val()){
			alert('첨부파일이 없습니다.');
			return false;
		}

		if(confirm('노출순서를 변경하시겠습니까?')){
			 $('#excelForm').submit();
		}
	}
/*	Create Root node	*/
	var rootnode = new TreeNode('상품카테고리', '../resources/ServerMag_Etc_Root.gif','../resources/ServerMag_Etc_Root.gif');
	rootnode.action = \"setCategory('product category','000000000000000',-1,'".$id."','".$company_id."','".$max."')\";
	rootnode.expanded = true;";

$mdb->query("SELECT * FROM ".TBL_SHOP_CATEGORY_INFO." WHERE depth is not null order by vlevel1, vlevel2, vlevel3, vlevel4, vlevel5");

$total = $mdb->total;
for ($i = 0; $i < $mdb->total; $i++)
{

	$mdb->fetch($i);

	if ($mdb->dt["depth"] == 0){
		$m_string = $m_string.PrintNode($mdb->dt["cname"],$mdb->dt["cid"],$mdb->dt["depth"]);
	}else if($mdb->dt["depth"] == 1){
		$m_string = $m_string.PrintGroupNode($mdb->dt["cname"],$mdb->dt["cid"],$mdb->dt["depth"]);
	}else if($mdb->dt["depth"] == 2){
		$m_string = $m_string.PrintGroupNode($mdb->dt["cname"],$mdb->dt["cid"],$mdb->dt["depth"]);
	}else if($mdb->dt["depth"] == 3){
		$m_string = $m_string.PrintGroupNode($mdb->dt["cname"],$mdb->dt["cid"],$mdb->dt["depth"]);
	}else if($mdb->dt["depth"] == 4){
		$m_string = $m_string.PrintGroupNode($mdb->dt["cname"],$mdb->dt["cid"],$mdb->dt["depth"]);
	}
}

	$m_string = $m_string."tree.addNode(rootnode);";

$m_string = $m_string."
</script>
<form>
<div id=TREE_BAR style='margin:5px;'>
<script>
tree.draw();
tree.nodes[0].select();
</script>
</div>
</form>";

return $m_string;
}




function PrintRootNode($cname){

	$cname = str_replace("\"","&quot;",$cname);
	$cname = str_replace("'","&#39;",$cname);

	$vPrintRootNode = "var rootnode = new TreeNode('$cname', '../resources/ServerMag_Etc_Root.gif','../resources/ServerMag_Etc_Root.gif');/n
			rootnode.expanded = true;\n\n";

	return $vPrintRootNode;
}

function PrintNode($cname,$cid,$depth)
{
	global $id,$company_id,$max;
	$cid1 = substr($cid,0,3);
	$cid2 = substr($cid,3,3);
	$cid3 = substr($cid,6,3);
	$cid4 = substr($cid,9,3);
	$cid5 = substr($cid,12,3);

	$cname = str_replace("\"","&quot;",$cname);
	$cname = str_replace("'","&#39;",$cname);

	return "	var node$cid = new TreeNode('$cname', '../resources/Common_TreeNode_CodeManage.gif', '../resources/Common_TreeNode_CodeManage.gif');
	node$cid.expanded = true;
	node$cid.action = \"setCategory('$cname','$cid',$depth,'$id','".$company_id."','".$max."')\";
	rootnode.addNode(node$cid);\n\n";
}

function PrintGroupNode($cname,$mcid,$depth)
{
	global $id,$cid,$company_id,$max;
	$cid1 = substr($mcid,0,3);
	$cid2 = substr($mcid,3,3);
	$cid3 = substr($mcid,6,3);
	$cid4 = substr($mcid,9,3);
	$cid5 = substr($mcid,12,3);

	$Parentdepth = $depth - 1;

	if ($depth+1 == 1){
		$cid1 = "000";
	}else if($depth+1 == 2){
		$cid2 = "000";
	}else if($depth+1 == 3){
		$cid3 = "000";
	}else if($depth+1 == 4){
		$cid4 = "000";
	}else if($depth+1 == 5){
		$cid5 = "000";
	}

	$parent_cid = "$cid1$cid2$cid3$cid4$cid5";

	if ($depth ==1){
		$ParentNodeCode = "node$parent_cid";
	}else if($depth ==2){
		$ParentNodeCode = "groupnode$parent_cid";
	}else if($depth ==3){
		$ParentNodeCode = "groupnode$parent_cid";
	}else if($depth ==4){
		$ParentNodeCode = "groupnode$parent_cid";
	}else if($depth ==5){
		$ParentNodeCode = "groupnode$parent_cid";
	}

	if ($cid == $mcid){
		$expandstring = "true";
	}else{
		$expandstring = "false";
	}

	$cname = str_replace("\"","&quot;",$cname);
	$cname = str_replace("'","&#39;",$cname);

	return "		var groupnode$mcid = new TreeNode('$cname',TREE_FOLDER_CLOSED_IMG,TREE_FOLDER_OPEN_IMG);
		groupnode$mcid.tooltip = '$cname';
		groupnode$mcid.id ='nodeid$mcid';
		groupnode$mcid.expanded = $expandstring;
		groupnode$mcid.action = \"setCategory('$cname','$mcid',$depth,'$id','".$company_id."','".$max."')\";
		$ParentNodeCode.addNode(groupnode$mcid);\n\n";
}

?>