<?php
include($_SERVER["DOCUMENT_ROOT"]."/admin/class/layout.class");
include("../lib/imageResize.lib.php");
include '../include/phpexcel/Classes/PHPExcel.php';
include('../inventory/goods_mandatory_info.lib.php');

//Excel upload Memory Limit
set_time_limit(9999999999);
ini_set('memory_limit',-1);
//

	$removestring = array("\n", "\t");

	$db = new Database;
	$image_db = new Database;



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 카테고리 브랜드 코드 엑셀 다운로드
/// 작성 : 홍진영 ( 2013.05.03 )
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if($_GET["act"] == "ect_code_down"){

	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$etc_excel = new PHPExcel();

	// 속성 정의
	$etc_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("etc code List")
								 ->setSubject("etc code List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("etc code List");

	$etc_excel->setActiveSheetIndex(0);
	$etc_excel->getActiveSheet()->setTitle('카테고리');

	$ct_excel_info = array ("대분류","중분류","소분류","세분류","카테고리코드");
	$col = 'A';
	foreach($ct_excel_info as $ci){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $ci);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}

	$tb = $_SESSION['admin_config']["mall_inventory_category_div"]=="P"	?	TBL_SHOP_CATEGORY_INFO:"inventory_category_info";
	$sql = "SELECT * FROM ".$tb." order by cid";
	$db->query($sql);
	$db->fetch();

	$z = 2;

	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		//$ct_name=explode('>',$db->dt[ct_name]);
		$ct_name=explode('>',getIventoryCategoryPathByAdmin($db->dt[cid], 4));
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $ct_name[0]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $ct_name[1]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $ct_name[2]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $ct_name[3]);
		$col++;
		$etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT );
		$etc_excel->getActiveSheet()->setCellValue($col . $z , " ".$db->dt[cid]);
		$z++;
	}

	//주매입처 시작 
	$etc_excel->createSheet();
	$etc_excel->setActiveSheetIndex(1);
	$etc_excel->getActiveSheet()->setTitle('주매입처');
	
	$md_excel_info = array ("거래처코드","거래처명","등록일");
	$col = 'A';

	foreach($md_excel_info as $md){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $md);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}

	$sql = "select
				ccd.company_id,
				ccd.company_id as company_id,
				ccd.com_name as com_name,
				ccd.regdate
			from
				common_company_detail as ccd
			where
				ccd.seller_type like ('%2%')
				";
	$db->query($sql);

	$z = 2;
	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[company_id]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[com_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[regdate]);
		$z++;
	}


	//브랜드 시작
	$etc_excel->createSheet();
	$etc_excel->setActiveSheetIndex(2);
	$etc_excel->getActiveSheet()->setTitle('브랜드');

	$b_excel_info = array ("브랜드명","브랜드코드");
	$col = 'A';

	foreach($b_excel_info as $bi){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $bi);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}
	$sql = "select b_ix,brand_name from shop_brand where disp='1' order by brand_name";
	$db->query($sql);
	$db->fetch();

	$z = 2;
	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[brand_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[b_ix]);
		$z++;
	}

	//제조사 시작
	$etc_excel->createSheet();
	$etc_excel->setActiveSheetIndex(3);
	$etc_excel->getActiveSheet()->setTitle('제조사');

	$c_excel_info = array ("제조사명","제조사코드");
	$col = 'A';

	foreach($c_excel_info as $c){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $c);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}
	$sql = "select c_ix,company_name from shop_company where disp='1' order by company_name";
	$db->query($sql);
	$db->fetch();

	$z = 2;
	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[company_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[c_ix]);
		$z++;
	}
	
	//원산지 시작
	$etc_excel->createSheet();
	$etc_excel->setActiveSheetIndex(4);
	$etc_excel->getActiveSheet()->setTitle('원산지');

	$o_excel_info = array ("원산지명","원산지코드");
	$col = 'A';

	foreach($o_excel_info as $oi){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $oi);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}
	$sql = "select og_ix,origin_name from common_origin where disp='1' ";
	$db->query($sql);
	$db->fetch();

	$z = 2;
	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[origin_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[og_ix]);
		$z++;
	}

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename=inventory_etc_code_v1.xls');
	header('Cache-Control: max-age=0');

	$etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
	$etc_excel->save('php://output');

}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 상품등록
/// 작성 : 신훈식 ( 2013.04.29 )
/// 내용 : 엑셀 업로드된 데이타를 shared memory 에 저장후 한개씩 처리해서 결과를 반영해 나가는 구조로 바꾼다.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

if($act == "new_excel_input"){	//대량상품등록 엑셀정보 저장 

	include("../include/lib/pclzip.lib.php");

	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	if ($excel_file_size > 0){
		copy($excel_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);
	}

	if ($goods_img_file_size > 0){
		copy($goods_img_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".$goods_img_file_name);

		//PclZip 객체를 생성합니다.
		//$객체 = new PclZip("생성할 압축파일 이름");
		$zipfile = new PclZip($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".$goods_img_file_name);

		$extract = $zipfile->extract(PCLZIP_OPT_PATH, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".str_replace(".zip","",$goods_img_file_name)); 

	}

	$objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);

	$shift_num = 0;

	// 데이터는 5줄부터 시작
	$rownum = 5;

	//$columnVar = $objPHPExcel->setActiveSheetIndex(0)->getCell('A' . ($rownum))->getValue();

	include("../logstory/class/sharedmemory.class");
	$shmop = new Shared("upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/_shared/";
	//echo $shmop->filepath;
	$shmop->SetFilePath();
	$upload_excel_data = $shmop->getObjectForKey("upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	
	$upload_excel_data="";

	$col = 'A';
	for($i=0;$i < count($goods_basic_sample)-1;$i++){
		$col++;
	}

	$col = 'A';
	
	foreach($goods_basic_sample as $key => $value){
		$upload_excel_data[session_id()][$rownum-5][$value[code]] = $value[title];//$objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
		$col++;
	}

	$z=0;
	while (($objPHPExcel->getActiveSheet()->getCell('E' . $rownum)->getValue() != "") && ($rownum < 5000)) {
		//$pcode = $objPHPExcel->getActiveSheet()->getCell('A' . $rownum)->getValue();
		$col = 'A';
		foreach($goods_basic_sample as $key => $value){

			// PHPExcel_RichText
			if (is_object($objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell($col . $rownum));
				$upload_excel_data[session_id()][$rownum-4][$value[code]] = $objRichText->getPlainText();
			}else{
				$upload_excel_data[session_id()][$rownum-4][$value[code]] = $objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
			}
			$col++;
		}

		$upload_excel_data[session_id()][$rownum-4][p_no] = $z;

		if($page_type == 'input'){
			$upload_excel_data[session_id()][$rownum-4][company_id] = $company_id;
			$upload_excel_data[session_id()][$rownum-4][goods_img_file] = $goods_img_file_name;
		}
		//###
		else
		{
			$upload_excel_data[session_id()][$rownum-4][goods_img_file] = $goods_img_file_name;
		}
		//###

		$z++;
		$rownum++;
	}

	$shmop->setObjectForKey($upload_excel_data, "upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]) ;

	if($page_type == 'input'){
		echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./inventory_goods_input_excel.php?up_mode=new_upload'</script>";
	}else{
		echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./inventory_goods_update_excel.php?up_mode=new_upload'</script>";
	}

}



if($act == "single_goods_reg" && strlen($p_no)>0){		//메모리에 저장된 대량상품등록 정보로 상품추가 부분 2014-06-18 이학봉 

	include("../logstory/class/sharedmemory.class");
	//auth(8);
	$shmop = new Shared("upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	//	$shmop->clear();
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$_SESSION["admininfo"]["mall_data_root"]."/_shared/";
	$shmop->SetFilePath();
	$upload_excel_data = $shmop->getObjectForKey("upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);

	$select_excel_goods_infos = filter_by_value($upload_excel_data[session_id()], 'p_no', $p_no);

	foreach($select_excel_goods_infos as $key => $value){
		/*
		if($key < 4){	//5번짜 라인부터 상품등록 하게끔 설정 2014-06-24 이학봉
			continue;
		}
		*/

		$insert_yn=true;
		$result_massage="";

		foreach($value as $_key => $_value){
			$$_key = trim(str_replace("'","&#39;",$_value));
			
			//필수값 체크!!!
			foreach($goods_basic_sample as $basic_sample){
				if($basic_sample[code]==$_key){
					if($basic_sample[validation]=="true" && $_value =="" && $_key!="product_type" ){
						$insert_yn=false;
						$result_massage .= "<span class='red'>".$basic_sample[title]." ".$_value." 이(가) 없습니다.</span><br/>";
					}
				}
			}
		}

		//단위정보
		if($unit != ""){
			$unit_array = explode("|",$unit);
			$change_amount_array = explode("|",$change_amount);
			$buying_price_array = explode("|",$buying_price);
			$wholesale_price_array = explode("|",$wholesale_price);
			$sellprice_array = explode("|",$sellprice);
			$weight_array = explode("|",$weight);
			$length_info_array = explode("^",$length_info);
		
			for($i=0;$i<count($unit_array);$i++){

				$lenth_detail = explode("|",trim($length_info_array[$i]));

				$goods_unit[$i][unit] = $unit_array[$i];
				$goods_unit[$i][change_amount] = $change_amount_array[$i];
				$goods_unit[$i][buying_price] = $buying_price_array[$i];
				$goods_unit[$i][wholesale_price] = $wholesale_price_array[$i];
				$goods_unit[$i][sellprice] = $sellprice_array[$i];
				$goods_unit[$i][weight] = $weight_array[$i];
				$goods_unit[$i][width_length] = $lenth_detail[0];
				$goods_unit[$i][depth_length] = $lenth_detail[1];
				$goods_unit[$i][height_length] = $lenth_detail[2];
			}
		
		}


		if($page_type == 'input'){
			if($standard_gid != ""){
				$sql="select count(*) as total from inventory_goods where gid='".$standard_gid."' ";
				$db->query($sql);
				$db->fetch();
				$total = $db->dt[total];
				if($total){
					$insert_yn=false;
					$result_massage .= "<span class='red'>품목코드 ".$standard_gid." 가 이미 존재합니다.</span><br/>";
				}

				$standard[0][standard] = $standard_name;
				$standard[0][gid] = $standard_gid;
				//$standard[0][gid] = rand();	//테스트용 2014-06-21 이학봉
				if($standard_barcode != ""){
					$standard_barcode_array = explode("|",$standard_barcode);
					for($i=0;$i<count($standard_barcode_array);$i++){
						$standard[0][barcode][$i] = $standard_barcode_array[$i];
					}
				}
				
				$standard[0][etc] = $standard_etc;
			}
		}else{

			if($standard_gid != ""){
				$standard_gid_array = explode("|",$standard_gid);
				$standard_name_array = explode("|",$standard_name);

				$standard_barcode_array = explode("^",$standard_barcode);

				$standard_etc_array = explode("|",$standard_etc);
				$unit_array = explode("|",$unit);

				for($i=0;$i<count($standard_gid_array);$i++){
				
					$standard[$i][standard] = trim($standard_name_array[$i]);
					$standard[$i][gid] = trim($standard_gid_array[$i]);
					
					
					$standard_barcode_array_once = explode("|",$standard_barcode_array[$i]);
					for($j=0;$j<count($unit_array);$j++){
						$standard[$i][barcode][$unit_array[$j]]= trim($standard_barcode_array_once[$j]);
					}

					$standard[$i][etc] = trim($standard_etc_array[$i]);
				}
			
			}
		
		}



		//카테고리	
		$cid1_1	 = $selected_cid;
		
		//원산지명
		if($og_ix != ""){
			$db->query("select origin_name from common_origin where og_ix = '".$og_ix."'");
			$db->fetch();
			$origin = $db->dt[origin_name];
		}

		//제조사명
		if($c_ix !=""){
			$db->query("SELECT company_name FROM shop_company where c_ix = '".$c_ix."' ");
			$db->fetch();
			$company=$db->dt[company_name];
		}

		//브랜드명
		if($b_ix !=""){
			$db->query("SELECT brand_name FROM shop_brand where b_ix = '".$b_ix."' ");
			$db->fetch();
			$brand=$db->dt[brand_name];
		}

		//$img_url_copy = '1';
		if($page_type == 'input'){
			$bs_act = '1';
			$act = "insert";
			$img_url_copy='1';
			$order_basic_unit = $basic_unit;
		}else if($page_type == 'update'){
			$act = "update";
		}
		///////DEFAULT///////

		if($insert_yn){
			if($upload_excel_data[session_id()][$key][status] !='C'){

				if($page_type == 'input'){
					include "./inventory_goods_input.act.php";
				}else{
					include "./inventory_goods_update_excel.act.php";
				}
				/////////////////////////////////	품목일괄등록 이미지 업로드
				if($allimg != ""){
					Batch_Images_Processing($allimg, $gid,$goods_img_file);
				}
			
				$upload_excel_data[session_id()][$key][status] = "C";
				$upload_excel_data[session_id()][$key][status_message] = "등록완료";
				echo "<span class='blue'>등록완료</span>";
			}else{
				echo "<span class='blue'>PASS</span>";
			}
		}else{
			echo $result_massage;
		}
	}

	$shmop->setObjectForKey($upload_excel_data, "upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]) ;
}

if($act == "bad_goods_info_excel"){

	include("../logstory/class/sharedmemory.class");
	$shmop = new Shared("upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/_shared/";
	//echo $shmop->filepath;
	$shmop->SetFilePath();
	$upload_excel_data = $shmop->getObjectForKey("upload_goods_excel_data_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);

	$title_info=array();
	$bad_info_excel_data=array();

	foreach($upload_excel_data[session_id()] as $key => $val){
		if($key==0){
			$title_info=$val;
		}elseif($val[status]!="C"){
			array_push($bad_info_excel_data,$val);
		}
	}

	if(count($bad_info_excel_data) > 0){

		PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

		date_default_timezone_set('Asia/Seoul');

		$etc_excel = new PHPExcel();

		// 속성 정의
		$etc_excel->getProperties()->setCreator("포비즈 코리아")
									 ->setLastModifiedBy("Mallstory.com")
									 ->setTitle("etc code List")
									 ->setSubject("etc code List")
									 ->setDescription("generated by forbiz korea")
									 ->setKeywords("mallstory")
									 ->setCategory("etc code List");

		$etc_excel->setActiveSheetIndex(0);
		$etc_excel->getActiveSheet()->setTitle('등록실패품목');

		$col = 'A';
		foreach($title_info as $key => $val){
			$etc_excel->getActiveSheet()->mergeCells($col . "1:". $col. "4");
			$etc_excel->getActiveSheet()->setCellValue($col . "1", $val);
			//$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}
		

		for($i=0,$z=5;$i<count($bad_info_excel_data);$i++,$z++){
			$col = 'A';
			
			foreach($title_info as $key => $val){
				if($key == "category"){
					$etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT);
					$etc_excel->getActiveSheet()->setCellValue($col . $z , " ".$bad_info_excel_data[$i][$key]);
				}else{
					$etc_excel->getActiveSheet()->setCellValue($col . $z , $bad_info_excel_data[$i][$key]);
				}

				$col++;
			}
		}

		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename=bad_goods_info_excel.xls');
		header('Cache-Control: max-age=0');

		$etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
		$etc_excel->save('php://output');
	}else{

		if($page_type == 'input'){
			echo "<script type='text/javascript'>
			<!--
				location.href='./inventory_goods_input_excel.php?up_mode=new_upload';
				alert('등록 실패한 품목이 없습니다.');
			//-->
			</script>";
		}else{
			echo "<script type='text/javascript'>
			<!--
				location.href='./inventory_goods_update_excel.php?up_mode=new_upload';
				alert('등록 실패한 품목이 없습니다.');
			//-->
			</script>";
		}
	}
	exit;
}


function Batch_Images_Processing($xlImageFileName, $bpid,$goods_img_file)
{

	$bpid = str_replace("/","_",$bpid);
	$bpid = str_replace(":","_",$bpid);
	$bpid = str_replace(" ","_",$bpid);

	global $admin_config;
	$uploadDirectory = UploadDirText($_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/images/inventory", $bpid, 'Y');
	$sourceDirectory = $_SERVER["DOCUMENT_ROOT"] . $admin_config[mall_data_root] . "/BatchUploadImages/";
	
	if($goods_img_file != ""){
		$goods_img_file_array = explode(".",$goods_img_file);
		$zip_directory = $goods_img_file_array[0]."/";
	}

	$sourceImageFileFullPath = $sourceDirectory.$zip_directory. $xlImageFileName;
	ExcelImageCopy($sourceImageFileFullPath, $bpid);


}

function ExcelImageCopy($image_path, $pid){

	global $admin_config, $DOCUMENT_ROOT,$image_db;

	$basedir = $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/inventory/";
	$targetDirectory = $basedir . UploadDirText($basedir, $pid, 'Y') . '/';


	if(!file_exists($image_path)) {
		return ;
	}
	
	$image_info = getimagesize ($image_path);
	$image_type = substr($image_info['mime'],-3);
	$image_db->query("select width,height from shop_image_resizeinfo order by idx");//kbk 11/12/15
	$image_info2 = $image_db->fetchall();
	$basic_img_src = $targetDirectory . "/basic_".$pid.".gif";

	copy($image_path, $basic_img_src);

	switch ($image_type){
		case "gif":
		case "GIF":
			MirrorGif($basic_img_src, $targetDirectory . "/b_".$pid.".gif", MIRROR_NONE);
			resize_gif($targetDirectory . "/b_".$pid.".gif",$image_info2[0][0],$image_info2[0][1]);

			MirrorGif($basic_img_src, $targetDirectory . "/c_".$pid.".gif", MIRROR_NONE);
			resize_gif($targetDirectory . "/c_".$pid.".gif",$image_info2[4][0],$image_info2[4][1]);
			break;
		default:
			Mirror($basic_img_src, $targetDirectory . "/b_".$pid.".gif", MIRROR_NONE);
			resize_jpg($targetDirectory . "/b_".$pid.".gif",$image_info2[0][0],$image_info2[0][1]);

			Mirror($basic_img_src, $targetDirectory . "/c_".$pid.".gif", MIRROR_NONE);
			resize_jpg($targetDirectory . "/c_".$pid.".gif",$image_info2[4][0],$image_info2[4][1]);
			break;
	}

	if (is_file($image_path)) {
	//###	@unlink($image_path);
	}

	//syslog(LOG_INFO, 'END\r\n');
}


?>