<?
include("../class/layout.class");
include($_SERVER["DOCUMENT_ROOT"]."/admin/product/category.lib.php");
include("./inventory.lib.php");


if($max == ""){
$max = 20; //페이지당 갯수
}

if ($page == ''){
	$start = 0;
	$page  = 1;
}else{
	$start = ($page - 1) * $max;
}


$db = new Database;


$where=" where ips.gid=gu.gid and ips.unit=gu.unit ";
$_where = " where inven.gid=g.gid ";

if($admininfo[admin_level] == 9){
	
	if($admininfo[mem_type] == "MD"){
		$_where .= " and g.admin in (".getMySellerList($admininfo[charger_ix]).") ";
	}

}else{
	$_where = " and g.admin ='".$admininfo[company_id]."' ";
}

if($company_id != ""){
	$where .= "and ips.company_id = '".$company_id."' ";
}

if($pi_ix != ""){
	$where .= "and ips.pi_ix = '".$pi_ix."' ";
}

if($ps_ix != ""){
	$where .= "and ips.ps_ix = '".$ps_ix."' ";
}


if($search_text != ""){
	if($search_type == "gname_gid"){
		$_where .= "and (g.gname LIKE '%".$search_text."%' or g.gid LIKE '%".$search_text."%') ";
	}else{
		$_where .= "and g.".$search_type." LIKE '%".$search_text."%' ";
	}
}

if($admin_type != ""){
	$_where .= "and g.admin_type = '".$admin_type."' ";
}


switch ($depth){
	case 0:
		$cut_num = 3;
		break;
	case 1:
		$cut_num = 6;
		break;
	case 2:
		$cut_num = 9;
		break;
	case 3:
		$cut_num = 12;
		break;
	case 4:
		$cut_num = 15;
		break;
}

if ($cid2){
	$_where .= " and g.cid LIKE '".substr($cid2,0,$cut_num)."%' ";
}

if(empty($startDate)){
	$startDate = date("Y-m-d", strtotime($today."-3day"));
}

if(empty($endDate)){
	$endDate = date("Y-m-d");
}


if($startDate !="" && $endDate !=""){
	//$_where .= " and date_format(first_regdate,'%Y%m%d') between ".str_replace("-","",$startDate)." and ".str_replace("-","",$endDate)." ";
	$_where .= " and first_regdate between '".$startDate." 00:00:00' and '".$endDate." 23:59:59' ";
}

if($stand_by_day!=""){
	$_where .= " and inven.stand_by_day >= '".$stand_by_day."' ";
}

if($output_rate !=""){
	$_where .= " and out_stock_rate <= ".$output_rate." ";
}

$sql = "select count(*) as total
	from (
		select ips.gid,date_format(min(ips.regdate),'%Y-%m-%d') as first_regdate
		from inventory_product_stockinfo ips ,
		inventory_goods_unit gu
		$where 
		group by ips.gid
	) inven,
	inventory_goods g
	$_where
	";
$db->query($sql);
$db->fetch();
$total = $db->dt[total];


$orderbyString = "order by out_stock_rate asc ";

if($mode != "excel"){
	$limit_str=" LIMIT $start, $max ";
}

$sql = "select 
			inv.*,pi.place_name, ps.section_name, ips.unit, ips.stock,
			(select com_name as company_name from common_company_detail ccd where ccd.company_id = inv.company_id limit 1) as company_name,
			(select date_format(ih.regdate,'%Y-%m-%d') from inventory_history ih , inventory_history_detail ihd where ih.h_ix = ihd.h_ix and ihd.gid=inv.gid and ih.h_div='1' order by hd_ix desc limit 1) as last_input_date,
			ifnull((select date_format(ih.regdate,'%Y-%m-%d') from inventory_history ih , inventory_history_detail ihd where ih.h_ix = ihd.h_ix and ihd.gid=inv.gid and ih.h_div='2' order by hd_ix desc limit 1),'미출고') as last_output_date
		from 
		(
			select inven.*,g.cid, g.gname, g.gcode, g.standard
			from (
				select ips.gid,ips.company_id,
				count(*) as row_cnt,
				date_format(min(ips.regdate),'%Y-%m-%d') as first_regdate,
				sum(ips.total_in_stock) as total_in_stock,
				sum(ips.total_out_stock) as total_out_stock,
				ifnull(sum(ips.total_out_stock) / sum(ips.total_in_stock),0) as out_stock_rate,
				sum(ips.stock * gu.change_amount) as combine_stock,
				(select sum(ihd.remain_stock * DATEDIFF(NOW(),ihd.regdate))/sum(ihd.remain_stock) from inventory_history ih , inventory_history_detail ihd where ih.h_ix = ihd.h_ix and ihd.gid=ips.gid and ih.h_div='1' and ihd.remain_stock > 0) as stand_by_day
				from inventory_product_stockinfo ips ,
				inventory_goods_unit gu
				$where 
				group by ips.gid
			) inven,
			inventory_goods g
			$_where
			$orderbyString
			$limit_str
		) inv
		left join inventory_product_stockinfo ips on (ips.gid = inv.gid)
		left join inventory_place_info pi on (pi.pi_ix = ips.pi_ix)
		left join inventory_place_section ps on (ps.ps_ix = ips.ps_ix)
	 ";

//echo nl2br($sql);
//exit;
$db->query($sql);

$goods_infos = $db->fetchall();

if($mode == "excel"){
	include '../include/phpexcel/Classes/PHPExcel.php';
	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$accounts_plan_priceXL = new PHPExcel();

	// 속성 정의
	$accounts_plan_priceXL->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("accounts plan price List")
								 ->setSubject("accounts plan price List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("accounts plan price List");

	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('A' . 1, "번호");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('B' . 1, "대표코드");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('C' . 1, "품목코드");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('D' . 1, "품목명");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('E' . 1, "품목규격");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('F' . 1, "최초입고일");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('G' . 1, "최근입고일");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('H' . 1, "최근출고일");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('I' . 1, "미출고일");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('J' . 1, "총입고갯수");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('K' . 1, "총출고수량");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('L' . 1, "출고율");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('M' . 1, "개당평균대기일");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('N' . 1, "통합재고(EA)");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('O' . 1, "사업장");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('P' . 1, "창고");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('Q' . 1, "보관장소");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('R' . 1, "단위");
	$accounts_plan_priceXL->getActiveSheet(0)->setCellValue('S' . 1, "재고현황");


	$before_pid = "";

	for ($i = 0; $i < count($goods_infos); $i++)
	{

		$last_day = (strtotime($goods_infos[$i][last_output_date]) - strtotime($goods_infos[$i][last_input_date]))/86400;

		$accounts_plan_priceXL->getActiveSheet()->setCellValue('A' . ($i + 2), ($i + 1));
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('B' . ($i + 2), $goods_infos[$i][gcode]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('C' . ($i + 2), $goods_infos[$i][gid]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('D' . ($i + 2), $goods_infos[$i][gname]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('E' . ($i + 2), $goods_infos[$i][standard]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('F' . ($i + 2), $goods_infos[$i][first_regdate]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('G' . ($i + 2), $goods_infos[$i][last_input_date]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('H' . ($i + 2), $goods_infos[$i][last_output_date]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('I' . ($i + 2),  ($last_day > 0 ? round($last_day) : "0")."일");
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('J' . ($i + 2), $goods_infos[$i][total_in_stock]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('K' . ($i + 2), $goods_infos[$i][total_out_stock]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('L' . ($i + 2), round($goods_infos[$i][out_stock_rate])."%");
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('M' . ($i + 2), round($goods_infos[$i][stand_by_day])."일");
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('N' . ($i + 2), $goods_infos[$i][combine_stock]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('O' . ($i + 2), $goods_infos[$i][company_name]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('P' . ($i + 2), $goods_infos[$i][place_name]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('Q' . ($i + 2), $goods_infos[$i][section_name]);
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('R' . ($i + 2), getUnit($goods_infos[$i][unit], "basic_unit","","text"));
		$accounts_plan_priceXL->getActiveSheet()->setCellValue('S' . ($i + 2), $goods_infos[$i][stock]);
	}

	// 첫번째 시트 선택
	$accounts_plan_priceXL->setActiveSheetIndex(0);

	// 너비조정
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('A')->setWidth(10);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('J')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('K')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('L')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('M')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('N')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('O')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('P')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('Q')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('R')->setAutoSize(true);
	$accounts_plan_priceXL->getActiveSheet()->getColumnDimension('S')->setAutoSize(true);

	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="first_stocked.xls"');
	header('Cache-Control: max-age=0');

	//$objWriter = PHPExcel_IOFactory::createWriter($accounts_plan_priceXL, 'Excel5');
	$objWriter = PHPExcel_IOFactory::createWriter($accounts_plan_priceXL, 'CSV');
	$objWriter->setUseBOM(true);
	$objWriter->save('php://output');

	exit;
}

//print_r($_SERVER);
if($mode == "search"){
	//$str_page_bar = page_bar_search($total, $page, $max);
	if($_SERVER["QUERY_STRING"] == "nset=$nset&page=$page"){
		$query_string = str_replace("nset=$nset&page=$page","",$_SERVER["QUERY_STRING"]) ;
	}else{
		$query_string = str_replace("nset=$nset&page=$page&","","&".$_SERVER["QUERY_STRING"]) ;
	}
	$str_page_bar = page_bar($total, $page, $max, $query_string,"");
}else{
	$str_page_bar = page_bar($total, $page, $max, "&max=$max","");
}


$Contents =	"
		<script  id='dynamic'></script>
		<table cellpadding=0 cellspacing=0 width='100%'>
			<tr>
			    <td align='left' colspan=4 > ".GetTitleNavigation("재고현황", "재고관리 > 재고현황")."</td>
			</tr>
			<tr height=150>
				<td colspan=2>
					<form name='search_form' method='get' action='".$HTTP_URL."' onsubmit='return CheckFormValue(this);' >
					<input type='hidden' name='mode' value='search'>
					<input type='hidden' name='cid2' value='$cid2'>
					<input type='hidden' name='depth' value='$depth'>
					<table class='box_shadow' style='width:100%;height:20px' cellpadding='0' cellspacing='0' border='0'><!---mbox04-->
						<tr>
							<th class='box_01'></th>
							<td class='box_02'></td>
							<th class='box_03'></th>
						</tr>
						<tr>
							<th class='box_04'></th>
							<td class='box_05 align=center' style='padding:0px'>
								<table cellpadding=0 cellspacing=1 border=0 width=100% align='center' class='input_table_box'>
									<col width='15%' >
									<col width='35%' >
									<col width='15%' >
									<col width='*' >
									<tr>
										<td class='input_box_title'>  <b>선택된 카테고리</b>  </td>
										<td class='input_box_item' colspan=3><b id='select_category_path1'>".($search_text == "" ? getIventoryCategoryPathByAdmin($cid2, $depth)."(".$total."개)":"<b style='color:red'>'$search_text'</b> 로 검색된 결과 입니다.")."</b></div></td>
									</tr>
									<tr>
										<td class='input_box_title'><b>카테고리선택</b></td>
										<td class='input_box_item' colspan=3>
											<table border=0 cellpadding=0 cellspacing=0>
												<tr>
													<td style='padding-right:5px;'>".getInventoryCategoryList("대분류", "cid0_1", "onChange=\"loadCategory(this,'cid1_1',2)\" title='대분류' ", 0, $cid2)."</td>
													<td style='padding-right:5px;'>".getInventoryCategoryList("중분류", "cid1_1", "onChange=\"loadCategory(this,'cid2_1',2)\" title='중분류'", 1, $cid2)."</td>
													<td style='padding-right:5px;'>".getInventoryCategoryList("소분류", "cid2_1", "onChange=\"loadCategory(this,'cid3_1',2)\" title='소분류'", 2, $cid2)."</td>
													<td>".getInventoryCategoryList("세분류", "cid3_1", "onChange=\"loadCategory(this,'cid2',2)\" title='세분류'", 3, $cid2)."</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td class='input_box_title'>사업장/창고</td>
										<td class='input_box_item' colspan='3'>
											".SelectEstablishment($company_id,"company_id","select","false","onChange=\"loadPlace(this,'pi_ix')\" ")."
											".SelectInventoryInfo($company_id, $pi_ix,'pi_ix','select','false', "onChange=\"loadPlaceSection(this,'ps_ix')\" ")."
											".SelectSectionInfo($pi_ix,$ps_ix,'ps_ix',"select","false" )." 
										</td>
									</tr>
									<tr>
										<td class='input_box_title'><b>최초 입고일</b></td>
										<td class='input_box_item' colspan='3'>
											".search_date('startDate','endDate',$startDate,$endDate)."
										</td>
									</tr>
									<tr>
										<td class='input_box_title'><b>출고율</b></td>
										<td class='input_box_item' >
											<input class='textbox number'  size='3' name='output_rate' value='".$output_rate."' validation='false'  title='출고율'> % 이하 <span class='small'>* 전체입고/출고 수량을 산출한 %</span>
										</td>
										<td class='input_box_title'><b>개당평균대기일</b></td>
										<td class='input_box_item' >
											<input class='textbox number'  size='3' name='stand_by_day' value='".$stand_by_day."' validation='false'  title='개당평균대기일'> 일 이상 <span class='small'>* 1개당 평균 창고 대기일을 산출한 일(소수점 2차리)</span>
										</td>
									</tr>
									<tr>
										<td class='input_box_title'>  <b>검색어</b>  </td>
										<td class='input_box_item'>
											<table cellpadding=0 cellspacing=0>
												<tr>
													<td>
														<select name='search_type'  style=\"font-size:12px;height:22px;\">
															<option value='gname_gid' ".CompareReturnValue("gname_gid",$search_type).">품목명+품목코드</option>
															<option value='gid' ".CompareReturnValue("gid",$search_type).">품목코드</option>
															<!--option value='gcode'>대표코드</option-->
															<option value='gname' ".CompareReturnValue("gname",$search_type).">품목명</option>
														</select> 
													</td>
													<td>
														<input class='textbox' value='".$search_text."' style='width:160px;' name='search_text' validation='false'  title='검색어'>
													</td>
												</tr>
											</table>
										</td>
										<td class='input_box_title'>품목구분</td>
										<td class='input_box_item' >
											<input type=radio name='admin_type' class=nonborder value='' id='admin_type_' validation=false ".($admin_type == "" ? "checked":"")."><label for='admin_type_'>전체</label>
											<input type=radio name='admin_type' class=nonborder value='A' id='admin_type_A' validation=false ".($admin_type == "A" ? "checked":"")."><label for='admin_type_A'>본사품목</label>
											<input type=radio name='admin_type' class=nonborder value='S' id='admin_type_S' validation=false ".($admin_type == "S" ? "checked":"")."><label for='admin_type_S'>위탁품목</label>
										</td>
									</tr>
								</table>
							</td>
							<th class='box_06'></th>
						</tr>
						<tr>
							<th class='box_07'></th>
							<td class='box_08'></td>
							<th class='box_09'></th>
						</tr>
					</table>
					</form>
				</td>
			</tr>
			<tr >
				<td colspan=2 align=center style='padding:10px 0px;'><img src='../images/".$admininfo["language"]."/bt_search.gif' border=0 style='cursor:pointer;' onclick=\"$('form[name=search_form]').submit();\" align=absmiddle></td>
			</tr>
			<tr>
				<td>
				</td>
			    <td align='right'  style='padding:5px 0 5px 0;'>";

if(checkMenuAuth(md5($_SERVER["PHP_SELF"]),"E")){
	$Contents .= "<a href='long_not_output.php?".$_SERVER["QUERY_STRING"]."&mode=excel'><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0 align='absmiddle'></a>";
}else{
	$Contents .= "<a href=\"".$auth_excel_msg."\"><img src='../images/".$admininfo["language"]."/btn_excel_save.gif' border=0></a>";
}


$Contents .= "
				</td>
			</tr>
			<tr>";
$Contents .=	"
			<td valign=top colspan='2' style='padding:0px;padding-top:0px;' id=product_stock>
			";

	$innerview = "<div style='overflow-x:hidden;width:100%;'>
			<table cellpadding=0 cellspacing=0  width='100%' class='list_table_box' style='min-width:1100px;'>
			<col width='3%'>
			<col width='7%'>
			<col width='*%'>
			<col width='7%'>
			<col width='7%'>
			<col width='6%'>
			<col width='6%'>
			<col width='5%'>
			<col width='7%'>
			<col width='7%'>
			<col width='7%'>
			<col width='5%'>
			<col width='5%'>
			<tr align=center height=30>
				<td class=s_td rowspan=2>순</td>
				<td class=m_td rowspan=2>대표코드<br/>품목코드</td>
				<td class=s_td rowspan=2>품목명/규격</td>
				<td class=m_td rowspan=2>최초입고일<br/>/최근입고일</td>
				<td class=m_td rowspan=2>최근출고일<br/>/미출고일</td>
				<td class=m_td rowspan=2>입고/출고<br/>/출고율</td>
				<td class=e_td rowspan=2>개당<br/>평균대기일</td>
				<td class=m_td rowspan=2>통합재고(EA)</td>
				<td class=m_td colspan=3 nwrap>보관장소</td>
				<td class=m_td rowspan=2>단위</td>
				<td class=m_td rowspan=2 nwrap>재고현황</td>
			</tr>
			<tr align=center height=30>
				<td class=m_td >사업장</td>
				<td class=m_td >창고</td>
				<td class=m_td >보관장소</td>
			</tr>
			";

if(count($goods_infos) == 0){
	$innerview .= "<tr bgcolor=#ffffff height=50><td colspan=13 align=center> 해당되는  품목이 없습니다.</td></tr>";
}else{

	$before_pid = "";

	for ($i = 0,$no=1; $i < count($goods_infos); $i++)
	{
		//$no = $total - ($page - 1) * $max - $i;
		
		if(file_exists($_SERVER["DOCUMENT_ROOT"]."".InventoryPrintImage($admin_config[mall_data_root]."/images/inventory", $goods_infos[$i][gid], "c"))){
			$img_str = InventoryPrintImage($admin_config[mall_data_root]."/images/inventory", $goods_infos[$i][gid], "c");
		}else{
			$img_str = "../image/no_img.gif";
		}

	$innerview .= "<tr height=35 align=center>";
				if($goods_infos[$i][gid]!=$b_gid){
					$innerview .= "
					<td bgcolor=#ffffff rowspan='".$goods_infos[$i][row_cnt]."'>".($no)."</td>
					<td bgcolor=#ffffff rowspan='".$goods_infos[$i][row_cnt]."'>".$goods_infos[$i][gcode]."<br/>".$goods_infos[$i][gid]."</td>
					<td class='list_box_td point' style='padding:2px 2px;' nowrap rowspan='".$goods_infos[$i][row_cnt]."'>
						<table cellpadding=0 cellspacing=0>
							<tr>
								";
		if(file_exists($_SERVER["DOCUMENT_ROOT"]."".InventoryPrintImage($admin_config[mall_data_root]."/images/inventory", $goods_infos[$i][gid], "c"))){
			$innerview .= "<td width='40' rowpan='2' align=center style='padding:0px 2px;'><img src='".$img_str."' width=30 height=30 style='border:1px solid #eaeaea' align=absmiddle></td>";
		}
		$innerview .= "		<td  class='list_box_td'style='text-align:left; padding-right:10px;line-height:150%;'>
									<a href=\"javascript:PoPWindow3('../inventory/inventory_goods_input.php?mmode=pop&gid=".$goods_infos[$i][gid]."',970,800,'inventory_goods_info')\"><b>".$goods_infos[$i][gname]."</b></a>
								</td>
							</tr>
							<tr>
								<td  class='list_box_td'style='text-align:left; padding-right:10px;line-height:150%;'>
									<b>".$goods_infos[$i][standard]."</b>
								</td>
							</tr>
						</table>
					</td>
					<td bgcolor=#ffffff rowspan='".$goods_infos[$i][row_cnt]."'>".$goods_infos[$i][first_regdate]."<br/>".$goods_infos[$i][last_input_date]."</td>";

					$last_day = (strtotime($goods_infos[$i][last_output_date]) - strtotime($goods_infos[$i][last_input_date]))/86400;

					$innerview .= "
					<td bgcolor=#ffffff rowspan='".$goods_infos[$i][row_cnt]."'>".$goods_infos[$i][last_output_date]."<br/>".($last_day > 0 ? number_format($last_day) : "0")."일</td>
					<td bgcolor=#ffffff rowspan='".$goods_infos[$i][row_cnt]."'>".$goods_infos[$i][total_in_stock]."개<br>".$goods_infos[$i][total_out_stock]."개<br/>".number_format($goods_infos[$i][out_stock_rate])."%</td>
					<td bgcolor=#ffffff nowrap rowspan='".$goods_infos[$i][row_cnt]."'>".number_format($goods_infos[$i][stand_by_day])."일</td>
					<td bgcolor=#ffffff nowrap rowspan='".$goods_infos[$i][row_cnt]."'>".$goods_infos[$i][combine_stock]."</td>";

					$no++;
				}
					$innerview .= "
					<td bgcolor=#ffffff nowrap>".$goods_infos[$i][company_name]."</td>
					<td bgcolor=#ffffff>".$goods_infos[$i][place_name]."</td>
					<td bgcolor=#ffffff>".$goods_infos[$i][section_name]."</td>
					<td bgcolor=#ffffff>".getUnit($goods_infos[$i][unit], "basic_unit","","text")."</td>
					<td bgcolor=#ffffff>".$goods_infos[$i][stock]."</td>
				</tr>
				";

		$b_gid = $goods_infos[$i][gid];
	}

}
	$innerview .= "</table>
				</div>
				<table width='100%' cellpadding=0 cellspacing=0>
					<tr height=40><td></td>
					<td align=right nowrap>".$str_page_bar."</td></tr>

				</table>";

$Contents = $Contents.$innerview ."
			</td>
			</tr>
		</table>
			";


/*
$help_text = "
<table cellpadding=2 cellspacing=0 class='small' >
	<col width=8>
	<col width=*>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td   > 각 품목별 및 규격(옵션)별로 재고현황을 보실 수 있습니다
</td></tr>
	<!--tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td > 매입가나 , 기본 도소매가가 다른 경우는 별도의 품목으로 등록합니다 </td></tr>
	<tr><td valign=top><img src='/admin/image/icon_list.gif' ></td><td > 바코드가 다른 품목은 별도의 품목으로 등록한다. </td></tr-->
</table>
";
*/

$Contents .= HelpBox("장기미출고재고", $help_text);

//$category_str ="<div class=box id=img3  style='width:155px;height:250px;overflow:auto;'>".Category()."</div>";


if($view == "innerview"){
	echo "<html><meta http-equiv='Content-Type' content='text/html; charset=euc-kr'><body>$innerview</body></html>";
	$inner_category_path = getCategoryPathByAdmin($cid, $depth);
	echo "
	<Script>
	parent.document.getElementById('product_stock').innerHTML = document.body.innerHTML;
	parent.document.getElementById('select_category_path1').innerHTML='".$inner_category_path."';
	</Script>";
}else{
	$Script = "<script Language='JavaScript' type='text/javascript' src='placesection.js'></script>
	<script Language='JavaScript' type='text/javascript'>
	function loadCategory(sel,target) {
		//alert(target);
		var trigger = sel.options[sel.selectedIndex].value;
		var form = sel.form.name;
		var depth = sel.getAttribute('depth');

		//빈값일 경우에는 카테고리 정보 불러오는 파일에서 처리함 kbk 13/08/08
		//if(sel.selectedIndex!=0) {
			window.frames['act'].location.href = 'inventory_category.load2.php?form=' + form + '&trigger=' + trigger + '&depth='+depth+'&target=' + target;
		//}

	}

	
	</script>";

	$P = new LayOut();
	$P->strLeftMenu = inventory_menu();
	$P->addScript = $Script;
	$P->Navigation = "재고관리 > 장기미출고재고";
	$P->title = "장기미출고재고";
	$P->strContents = $Contents;



	$P->PrintLayOut();
}

?>