<?php

include("../class/layout.class");
include("../inventory/inventory.lib.php");
include '../include/phpexcel/Classes/PHPExcel.php';

//error_reporting(E_ALL);
PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

date_default_timezone_set('Asia/Seoul');
ini_set('memory_limit', '-1');

$where = " WHERE t1.pi_ix > 0 ";

if(!empty($search_type) && !empty($search_text))
{
	$where .= " AND " . $search_type . " LIKE '%" . $search_text . "%'";
}

if(!empty($cnt))
{
	if($cnt == "P")
	{
		$where .= " AND t1.pcnt > 0 ";
	}
	else
	{
		$where .= " AND t1.bcnt > 0 ";
	}
}

if (!empty($cid2)){
	switch ($depth){
		case 0: $cut_num = 3; break;
		case 1: $cut_num = 6; break;
		case 2: $cut_num = 9; break;
		case 3: $cut_num = 12; break;
		case 4: $cut_num = 15; break;
	}
	$where .= " and t1.cid LIKE '".substr($cid2,0,$cut_num)."%' ";
}

$db = new MySQL;

$sql = "SELECT t1.*
		FROM
			(SELECT
				psi.psi_ix,
				pi.pi_ix,
				pi.place_name,
				g.gid,
				g.cid,
				g.gcode,
				g.gname,
				g.item_account,
				gu.gu_ix,
				gu.unit,
				SUM(gu.sellprice) as sellprice,
					(SELECT com_name
					FROM common_company_detail ccd
					WHERE ccd.company_id = pi.company_id
					LIMIT 1) AS company_name,
					(SELECT SUM(stock)
					FROM inventory_product_stockinfo ips2
					INNER JOIN inventory_place_section ps2
					ON ips2.ps_ix = ps2.ps_ix
					WHERE ips2.pi_ix = pi.pi_ix
					AND ips2.unit = gu.unit
					AND ips2.gid = g.gid
					AND ps2.section_type = 'P'
					LIMIT 1) AS pcnt,
					(SELECT SUM(stock)
					FROM inventory_product_stockinfo ips2
					INNER JOIN inventory_place_section ps2
					ON ips2.ps_ix = ps2.ps_ix
					WHERE ips2.pi_ix = pi.pi_ix
					AND ips2.unit = gu.unit
					AND ips2.gid = g.gid
					AND ps2.section_type = 'B'
					LIMIT 1) AS bcnt
			FROM inventory_place_info pi
			INNER JOIN inventory_product_stockinfo psi
			ON pi.pi_ix = psi.pi_ix
			LEFT JOIN inventory_goods_unit gu
			ON psi.gid = gu.gid AND psi.unit = gu.unit
			LEFT JOIN inventory_goods g
			ON gu.gid = g.gid
			GROUP BY gu.gu_ix, pi.pi_ix) t1
		".$where."
";
$db->query($sql);

$memberXL = new PHPExcel();

// 속성 정의
$memberXL->getProperties()->setCreator("포비즈 코리아")
							 ->setLastModifiedBy("Mallstory.com")
							 ->setTitle("Member List")
							 ->setSubject("Member List")
							 ->setDescription("generated by forbiz korea")
							 ->setKeywords("mallstory")
							 ->setCategory("Member List");

// 셀 병합
$memberXL->getActiveSheet()->mergeCells('A1:A2');
$memberXL->getActiveSheet()->mergeCells('B1:B2');
$memberXL->getActiveSheet()->mergeCells('C1:C2');
$memberXL->getActiveSheet()->mergeCells('D1:D2');
$memberXL->getActiveSheet()->mergeCells('E1:E2');
$memberXL->getActiveSheet()->mergeCells('F1:F2');
$memberXL->getActiveSheet()->mergeCells('G1:G2');
$memberXL->getActiveSheet()->mergeCells('J1:J2');

$memberXL->getActiveSheet()->mergeCells('H1:I1');

// 데이터 등록
$memberXL->getActiveSheet(0)->setCellValue('A' . 1, "대표코드/품목코드");
$memberXL->getActiveSheet(0)->setCellValue('B' . 1, "품목 단위코드");
$memberXL->getActiveSheet(0)->setCellValue('C' . 1, "이미지/품목명");
$memberXL->getActiveSheet(0)->setCellValue('D' . 1, "품목계정");
$memberXL->getActiveSheet(0)->setCellValue('E' . 1, "단위");
$memberXL->getActiveSheet(0)->setCellValue('F' . 1, "사업장");
$memberXL->getActiveSheet(0)->setCellValue('G' . 1, "창고");
$memberXL->getActiveSheet(0)->setCellValue('H' . 1, "재고현황");
$memberXL->getActiveSheet(0)->setCellValue('J' . 1, "재고자산");

$memberXL->getActiveSheet(0)->setCellValue('H' . 2, "양호");
$memberXL->getActiveSheet(0)->setCellValue('I' . 2, "불량");

$colNum = 3;

for($i=0;$i<$db->total;$i++){
	$db->fetch($i);
	$memberXL->getActiveSheet()->setCellValue('A' . ($i + $colNum), $db->dt[gcode]."/".$db->dt[gid]);
	$memberXL->getActiveSheet()->setCellValue('B' . ($i + $colNum), $db->dt[gu_ix]);
	$memberXL->getActiveSheet()->setCellValue('C' . ($i + $colNum), $db->dt[gname]);
	$memberXL->getActiveSheet()->setCellValue('D' . ($i + $colNum), $ITEM_ACCOUNT[$db->dt[item_account]]);
	$memberXL->getActiveSheet()->setCellValue('E' . ($i + $colNum), getUnit($db->dt[unit], "basic_unit", "", "text"));
	$memberXL->getActiveSheet()->setCellValue('F' . ($i + $colNum), $db->dt[company_name]);
	$memberXL->getActiveSheet()->setCellValue('G' . ($i + $colNum), $db->dt[place_name]);
	$memberXL->getActiveSheet()->setCellValue('H' . ($i + $colNum), $db->dt[pcnt]);
	$memberXL->getActiveSheet()->setCellValue('I' . ($i + $colNum), $db->dt[bcnt]);
	$memberXL->getActiveSheet()->setCellValue('J' . ($i + $colNum), $db->dt[sellprice]);
}

// 시트이름등록
$memberXL->getActiveSheet()->setTitle('대리점');

// 첫번째 시트 선택
$memberXL->setActiveSheetIndex(0);
$memberXL->getActiveSheet()->getColumnDimension('A')->setWidth(20);
$memberXL->getActiveSheet()->getColumnDimension('B')->setWidth(15);
$memberXL->getActiveSheet()->getColumnDimension('C')->setWidth(30);
$memberXL->getActiveSheet()->getColumnDimension('D')->setWidth(20);
$memberXL->getActiveSheet()->getColumnDimension('E')->setWidth(10);
$memberXL->getActiveSheet()->getColumnDimension('F')->setWidth(20);
$memberXL->getActiveSheet()->getColumnDimension('G')->setWidth(20);
$memberXL->getActiveSheet()->getColumnDimension('H')->setWidth(10);
$memberXL->getActiveSheet()->getColumnDimension('I')->setWidth(10);
$memberXL->getActiveSheet()->getColumnDimension('J')->setWidth(20);

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="members.xls"');
header('Cache-Control: max-age=0');


$objWriter = PHPExcel_IOFactory::createWriter($memberXL, 'Excel5');
$objWriter->save('php://output');