<?php
include($_SERVER["DOCUMENT_ROOT"]."/admin/class/layout.class");
include("../lib/imageResize.lib.php");
include '../include/phpexcel/Classes/PHPExcel.php';
include('../inventory/stock_adjustment_info.lib.php');

	$removestring = array("\n", "\t");

	$db = new Database;
	$image_db = new Database;


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 카테고리 브랜드 코드 엑셀 다운로드
/// 작성 : 홍진영 ( 2013.05.03 )
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if($_GET["act"] == "ect_code_down"){

	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	$etc_excel = new PHPExcel();

	// 속성 정의
	$etc_excel->getProperties()->setCreator("포비즈 코리아")
								 ->setLastModifiedBy("Mallstory.com")
								 ->setTitle("etc code List")
								 ->setSubject("etc code List")
								 ->setDescription("generated by forbiz korea")
								 ->setKeywords("mallstory")
								 ->setCategory("etc code List");

	$etc_excel->setActiveSheetIndex(0);
	$etc_excel->getActiveSheet()->setTitle('조정창고(사업장)');

	//조정창고 - 사업장
	$company_excel_info = array ("사업장명","사업장키");
	$col = 'A';
	foreach($company_excel_info as $ci){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $ci);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}

	$tb = $_SESSION['admin_config']["mall_inventory_category_div"]=="P"	?	TBL_SHOP_CATEGORY_INFO:"inventory_category_info";
	$sql = "SELECT 
				distinct(ccd.company_id),
				ccd.*,
				cr.relation_code
			FROM 
				common_company_detail ccd
				inner join common_company_relation as cr on (ccd.company_id = cr.company_id)
				inner join inventory_place_info as ipi on (ccd.company_id = ipi.company_id)
			where 
				ccd.com_type in ('BR','HO','BP','BO','G','A','S' ) 
				and ccd.is_wharehouse =1
				order by cr.relation_code ASC";
	$db->query($sql);
	$db->fetch();

	$z = 2;

	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[com_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[company_id]);
		$z++;
	}

	//조정창고 - 창고
	$etc_excel->createSheet();
	$etc_excel->setActiveSheetIndex(1);
	$etc_excel->getActiveSheet()->setTitle('조정창고(창고)');
	
	$place_excel_info = array ("창고명","창고키");
	$col = 'A';

	foreach($place_excel_info as $md){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $md);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}

	$sql = "select * from inventory_place_info where disp = 'Y'";
	$db->query($sql);

	$z = 2;
	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[place_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[pi_ix]);
		$z++;
	}


	//조정창고 - 출고보관장소
	$etc_excel->createSheet();
	$etc_excel->setActiveSheetIndex(2);
	$etc_excel->getActiveSheet()->setTitle('출고보관장소');

	$b_excel_info = array ("출고보관장소명","출고보관장소키");
	$col = 'A';

	foreach($b_excel_info as $bi){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $bi);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}
	$sql = "select * from inventory_place_section where section_type = 'D'";
	$db->query($sql);
	$db->fetch();

	$z = 2;
	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[section_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[ps_ix]);
		$z++;
	}

	//매입처
	$etc_excel->createSheet();
	$etc_excel->setActiveSheetIndex(3);
	$etc_excel->getActiveSheet()->setTitle('매입처');

	$c_excel_info = array ("매입처명","매입처키");
	$col = 'A';

	foreach($c_excel_info as $c){
		$etc_excel->getActiveSheet()->setCellValue($col . "1", $c);
		$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
		$col++;
	}
	//$sql = "select c_ix,company_name from shop_company where disp='1' order by company_name";
	$sql = "select
				distinct ccd.company_id,
				ccd.company_id as company_id,
				ccd.com_name as com_name,
				ccd.com_ceo,
				ccd.regdate
			from
				common_company_detail as ccd
				inner join common_company_relation as ccr on (ccd.company_id = ccr.company_id)
			where
				ccr.relation_code like 'C0001%'
				and ccd.seller_auth = 'Y'
				and ( ccd.seller_type like '%2%' or ccd.seller_type like '%4%') order by ccr.relation_code asc
			";
	$db->query($sql);
	$db->fetch();

	$z = 2;
	for($i=0;$i<$db->total;$i++){
		$db->fetch($i);
		$col = 'A';
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[com_name]);
		$col++;
		$etc_excel->getActiveSheet()->setCellValue($col . $z , $db->dt[company_id]);
		$z++;
	}
	
	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename=stock_adjustment_etc_code_v1.xls');
	header('Cache-Control: max-age=0');

	$etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
	$etc_excel->save('php://output');

}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// 제목 : 상품고시분류별 상품등록
/// 작성 : 신훈식 ( 2013.04.29 )
/// 내용 : 엑셀 업로드된 데이타를 shared memory 에 저장후 한개씩 처리해서 결과를 반영해 나가는 구조로 바꾼다.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

if($act == "new_excel_input"){	//대량상품등록 엑셀정보 저장 

	include("../include/lib/pclzip.lib.php");

	PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

	date_default_timezone_set('Asia/Seoul');

	if ($excel_file_size > 0){
		copy($excel_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);
	}

	if ($goods_img_file_size > 0){
		copy($goods_img_file, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".$goods_img_file_name);

		//PclZip 객체를 생성합니다.
		//$객체 = new PclZip("생성할 압축파일 이름");
		$zipfile = new PclZip($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".$goods_img_file_name);

		$extract = $zipfile->extract(PCLZIP_OPT_PATH, $_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/BatchUploadImages/".str_replace(".zip","",$goods_img_file_name)); 

	}

	$objPHPExcel = PHPExcel_IOFactory::load($_SERVER["DOCUMENT_ROOT"]."".$admin_config[mall_data_root]."/images/upfile/".$excel_file_name);

	$shift_num = 0;

	// 데이터는 5줄부터 시작
	$rownum = 5;

	//$columnVar = $objPHPExcel->setActiveSheetIndex(0)->getCell('A' . ($rownum))->getValue();

	include("../logstory/class/sharedmemory.class");
	$shmop = new Shared("stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/_shared/";
	//echo $shmop->filepath;
	$shmop->SetFilePath();
	$upload_excel_data = $shmop->getObjectForKey("stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	
	$upload_excel_data="";

	$col = 'A';
	for($i=0;$i < count($goods_basic_sample)-1;$i++){
		$col++;
	}

	$col = 'A';
	
	foreach($goods_basic_sample as $key => $value){
		$upload_excel_data[session_id()][$rownum-5][$value[code]] = $value[title];//$objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
		$col++;
	}

	$z=0;
	while (($objPHPExcel->getActiveSheet()->getCell('E' . $rownum)->getValue() != "") && ($rownum < 5000)) {
		//$pcode = $objPHPExcel->getActiveSheet()->getCell('A' . $rownum)->getValue();
		$col = 'A';
		foreach($goods_basic_sample as $key => $value){

			// PHPExcel_RichText
			if (is_object($objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue())) {
				$objRichText = new PHPExcel_RichText($objPHPExcel->getActiveSheet()->getCell($col . $rownum));
				$upload_excel_data[session_id()][$rownum-4][$value[code]] = $objRichText->getPlainText();
			}else{
				$upload_excel_data[session_id()][$rownum-4][$value[code]] = $objPHPExcel->getActiveSheet()->getCell($col . $rownum)->getValue();
			}
			$col++;
		}

		$upload_excel_data[session_id()][$rownum-4][p_no] = $z;

		if($page_type == 'input'){
			//$upload_excel_data[session_id()][$rownum-4][company_id] = $company_id;
			//$upload_excel_data[session_id()][$rownum-4][goods_img_file] = $goods_img_file_name;
		}

		$z++;
		$rownum++;
	}

	$shmop->setObjectForKey($upload_excel_data, "stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]) ;

	if($page_type == 'input'){
		echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./stock_adjustment_input_excel.php?up_mode=new_upload'</script>";
	}else{
		echo "<script language='javascript' src='../js/message.js.php'></script><script>top.location.href='./stock_adjustment_input_excel.php?up_mode=new_upload'</script>";
	}

}


if($act == "single_goods_reg" && strlen($p_no)>0){		//메모리에 저장된 대량상품등록 정보로 상품추가 부분 2014-06-18 이학봉 

	include("../logstory/class/sharedmemory.class");
	//auth(8);
	$shmop = new Shared("stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	//	$shmop->clear();
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$_SESSION["admininfo"]["mall_data_root"]."/_shared/";
	$shmop->SetFilePath();
	$upload_excel_data = $shmop->getObjectForKey("stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);

	$select_excel_goods_infos = filter_by_value($upload_excel_data[session_id()], 'p_no', $p_no);

	foreach($select_excel_goods_infos as $key => $value){
		/*
		if($key < 4){	//5번짜 라인부터 상품등록 하게끔 설정 2014-06-24 이학봉
			continue;
		}
		*/

		$insert_yn=true;
		$result_massage="";

		foreach($value as $_key => $_value){
			$$_key = trim(str_replace("'","&#39;",$_value));
			
			//필수값 체크!!!
			foreach($goods_basic_sample as $basic_sample){
				if($basic_sample[code]==$_key){
					if($basic_sample[validation]=="true" && $_value =="" && $_key!="product_type" ){
						$insert_yn=false;
						$result_massage .= "<span class='red'>".$basic_sample[title]." ".$_value." 이(가) 없습니다.</span><br/>";
					}
				}
			}
		}

		//2. 품목계정
		$item_account_array = array('1','2','3','4','5','6','7');
		if(!in_array($item_account,$item_account_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>품목게정 값이 정상적이지 않습니다.</span><br/>";
		}

		//3. 매입단위
		$unit_array = array('1','2','3','4','5','6','7','8');
		if(!in_array($unit,$unit_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>매입단위 값이 정상적이지 않습니다.</span><br/>";
		}

		//4. 부가세 적용
		$surtax_div_array = array('1','2','3','4','5');
		if(!in_array($surtax_div,$surtax_div_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>부가세 값이 정상적이지 않습니다.</span><br/>";
		}

		//5. 입고창고(창고)
		$regist_pi_ix_array = array('1','2','3');
		if(!in_array($regist_pi_ix,$regist_pi_ix_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>입고창고 키값이 정상적이지 않습니다.</span><br/>";
		}

		//6. 조정유형
	
		$h_type_array = array('01','09','FC');
		if(!in_array($h_type,$h_type_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>조정유형 키값이 정상적이지 않습니다.</span><br/>";
		}

		//7. 재고조정타입별 입출고 유형 매칭값 확인
		$stock_type_array = array('1','2','3');
		if(!in_array($stock_type,$stock_type_array)){
			$insert_yn=false;
			$result_massage .= "<span class='red'>입고창고 키값이 정상적이지 않습니다.</span><br/>";
		}else{
			if($stock_type == '1'){
				if($h_type != '01'){
					$insert_yn=false;
					$result_massage .= "<span class='red'>재고조정 타입별 조정유형 키값이 정상적이지 않습니다.</span><br/>";
				}
			}else if($stock_type == '2'){
				if($h_type != '09'){
					$insert_yn=false;
					$result_massage .= "<span class='red'>재고조정 타입별 조정유형 키값이 정상적이지 않습니다.</span><br/>";
				}
			}else if($stock_type == '3'){
				if($h_type != 'FC'){
					$insert_yn=false;
					$result_massage .= "<span class='red'>재고조정 타입별 조정유형 키값이 정상적이지 않습니다.</span><br/>";
				}
			}
		}

		//8. 출고 재고조정일경우 보관장소키값은 필수값임.
		if($stock_type == '2'){
			if($regist_ps_ix == '' || $regist_ps_ix == '0'){
			$insert_yn=false;
			$result_massage .= "<span class='red'>출고조종시 보관장소 키값이 빈값입니다.</span><br/>";
			}else{
				$sql = "select ps_ix from inventory_place_section where ps_ix = '".$regist_ps_ix."'";
				$db->query($sql);
				
				if($db->total > 0){
					
				}else{
					$insert_yn=false;
					$result_massage .= "<span class='red'>유효하지 않은 보관장소 키입니다.</span><br/>";
				}
			}
		}



		//////////////////////////////////////데이타값 마추기 시작 ////////////////////////////////////
		//당당자 아이디 
		if($charger_id != ""){
			$db->query("select code from common_user where id = '".$charger_id."'");
			$db->fetch();
			$charger_ix = $db->dt[code];
		}

		//매입처명
		if($ci_ix !=""){
			$db->query("SELECT com_name FROM common_company_detail where company_id = '".$ci_ix."' ");
			$db->fetch();
			$ci_name=$db->dt[com_name];
		}

		//h_div
		if($stock_type == '1'){	//입고조정
			$h_div = '1';	//입고일경우 1
		}else if($stock_type == '2'){				//출고조정
			$h_div = '2';	//입고일경우 1
		}else if($stock_type == '3'){				//기초조정
			$h_div = '1';	//입고일경우 1
		}
		$item_infos[0][gid] = $gid;	
		$item_infos[0][standard] = $standard;
		$item_infos[0][item_account] = $item_account;
		$item_infos[0][unit] = $unit;
		$item_infos[0][surtax_div] = $surtax_div;
		$item_infos[0][expiry_date] = $expiry_date;
		$item_infos[0][amount] = $amount;
		$item_infos[0][price] = $price;
		
		if($page_type == 'input'){
			$act = "insert";
		}else if($page_type == 'update'){
			$act = "update";
		}
		///////DEFAULT///////

		if($insert_yn){
			if($upload_excel_data[session_id()][$key][status] !='C'){

				if($page_type == 'input'){
					include "./register.act.php";
				}else{
					//include "./inventory_goods_update_excel.act.php";
				}

				$upload_excel_data[session_id()][$key][status] = "C";
				$upload_excel_data[session_id()][$key][status_message] = "재고조정완료";
				echo "<span class='blue'>재고조정완료</span>";
			}else{
				echo "<span class='blue'>PASS</span>";
			}
		}else{
			echo $result_massage;
		}
	}

	$shmop->setObjectForKey($upload_excel_data, "stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]) ;
}

if($act == "bad_goods_info_excel"){

	include("../logstory/class/sharedmemory.class");
	$shmop = new Shared("stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);
	$shmop->filepath = $_SERVER["DOCUMENT_ROOT"].$admin_config[mall_data_root]."/_shared/";
	//echo $shmop->filepath;
	$shmop->SetFilePath();
	$upload_excel_data = $shmop->getObjectForKey("stock_adjustment_input_excel_".$page_type."_".$_SESSION["admininfo"]["charger_ix"]);

	$title_info=array();
	$bad_info_excel_data=array();

	foreach($upload_excel_data[session_id()] as $key => $val){
		if($key==0){
			$title_info=$val;
		}elseif($val[status]!="C"){
			array_push($bad_info_excel_data,$val);
		}
	}

	if(count($bad_info_excel_data) > 0){

		PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);

		date_default_timezone_set('Asia/Seoul');

		$etc_excel = new PHPExcel();

		// 속성 정의
		$etc_excel->getProperties()->setCreator("포비즈 코리아")
									 ->setLastModifiedBy("Mallstory.com")
									 ->setTitle("etc code List")
									 ->setSubject("etc code List")
									 ->setDescription("generated by forbiz korea")
									 ->setKeywords("mallstory")
									 ->setCategory("etc code List");

		$etc_excel->setActiveSheetIndex(0);
		$etc_excel->getActiveSheet()->setTitle('등록실패품목');

		$col = 'A';
		foreach($title_info as $key => $val){
			$etc_excel->getActiveSheet()->mergeCells($col . "1:". $col. "4");
			$etc_excel->getActiveSheet()->setCellValue($col . "1", $val);
			//$etc_excel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
			$col++;
		}
		

		for($i=0,$z=5;$i<count($bad_info_excel_data);$i++,$z++){
			$col = 'A';
			
			foreach($title_info as $key => $val){
				if($key == "category"){
					$etc_excel->getActiveSheet()->getStyle($col . $z)->getNumberFormat()->setFormatCode( PHPExcel_Style_NumberFormat::FORMAT_TEXT);
					$etc_excel->getActiveSheet()->setCellValue($col . $z , " ".$bad_info_excel_data[$i][$key]);
				}else{
					$etc_excel->getActiveSheet()->setCellValue($col . $z , $bad_info_excel_data[$i][$key]);
				}

				$col++;
			}
		}

		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename=bad_stock_adjustment_info_excel.xls');
		header('Cache-Control: max-age=0');

		$etc_excel = PHPExcel_IOFactory::createWriter($etc_excel, 'Excel5');
		$etc_excel->save('php://output');
	}else{

		if($page_type == 'input'){
			echo "<script type='text/javascript'>
			<!--
				location.href='./stock_adjustment_input_excel.php?up_mode=new_upload';
				alert('등록 실패한 품목이 없습니다.');
			//-->
			</script>";
		}else{
			echo "<script type='text/javascript'>
			<!--
				location.href='./stock_adjustment_input_excel.php?up_mode=new_upload';
				alert('등록 실패한 품목이 없습니다.');
			//-->
			</script>";
		}
	}
	exit;
}

?>